### ISSUE TITLE
Request change API for remove_torrent ( int -> enum )

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#1183]
- void remove_torrent(torrent_handle const& h, int options) override;
- void remove_torrent(torrent_handle const& h, options_t options) override;
  ...
      // flags to be passed in to remove_torrent().
      enum options_t
      {
                      // default
                      delete_none = 0,
          // delete the files belonging to the torrent from disk.
          // including the part-file, if there is one
          delete_files = 1,
  
  ```
      // delete just the part-file associated with this torrent
      delete_partfile = 2
  };
  ```

**Comment by arvidn** [comment]
yes, this is a good idea. however, the ``enum`` should be an ``enum class``, probably backed by ``std::uint8_t``. Since this actually alters the API, the existing function and enum must be left, but under the ``TORRENT_NO_DEPRECATE`` macro, and the new ``enum class`` should probably not be a member of ``torrent_handle``.

**Comment by arvidn** [comment]
pull requests are welcome! :)

**Comment by arvidn** [comment]
this has been implemented with `remove_flags_t`
