### ISSUE TITLE
Runtime warning, then importing python libtorrent module (RC_1_1)

### ISSUE THREAD

**Issue by barmalej2** [arvidn/libtorrent#1217]
libtorrent version (or branch):RC_1_1 git branch
boost version: 1.61.0
python version: 2.7.12
platform/architecture: armv5tel GNU/Linux, kernel 2.6.31.8
compiler and compiler version: gcc 4.9.2, 
Step to reproduce case. Import python libtorrent:
`python -c "import libtorrent; print libtorrent.version"`
Expected output is only libtorrent version.
Actual output is:

> -c:1: RuntimeWarning: to-Python converter for boost::shared_ptrlibtorrent::alert already registered; second conversion method ignored.
> 1.1.1.0

**Comment by cas--** [comment]
A little research turned up this project encountering the [same issue](https://github.com/BVLC/caffe/pull/4069/files) and seems to due to boost version differences.

**Comment by arvidn** [comment]
iirc, the underlying problem is that different version of boost.python or perhaps when building against different versions of python (2 vs. 3) has different behavior here. A while ago I spent quite some time trying to resolve this. as far as I know, at least I got it to work everywhere.

However, the long term solution is to get rid of the ``shared_ptr<>`` as part of the API, which puts all of this to reset once and for all. This is already the case in master and will be the fix in the next major release. I am open to patches that fixes this warning in the 1.1 branch, but I'm not sure I'm prepared to put much more work into it myself.

**Comment by Falcosc** [comment]
@barmalej2 What did you think about it? I don't like the idea of changing the RC_1_1 api to solve this issue. And it would may be take more effort than switching your python scripts to libtorrent 1.2.

**Comment by cas--** [comment]
The problem here is why is this occuring only in certain Linux configurations... I.e. I don't see this on my Ubuntu systems but iirc it's seen on Arch

**Comment by Falcosc** [comment]
I would guess because on the seen Arch system there was a boost version difference. But I don't know.

**Comment by arvidn** [comment]
would it make sense to remove the problematic alert-binding for the upcoming RC_1_1 release? That way at least some other deprecated functions could be preserved

**Comment by cas--** [comment]
It seems this is occurring with boost >=1.61 as I can replicate this on Ubuntu Yaketty.

@arvidn did you see this workaround that `caffe` used: https://github.com/BVLC/caffe/pull/3866/files

**Comment by barmalej2** [comment]
Thank you guys for your efforts and time spending tp resolve this.  Tested with latest libtorrent-1.1.2_git3b359ab (RC_1_1). No more runtime warnings. Closing this issue.
