### ISSUE TITLE
Assert triggered when removing magnet immediately after metadata was received.

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#1283]
The assert is described in this comment: https://github.com/arvidn/libtorrent/issues/1177#issuecomment-256052959

I'll explain the workflow of qbittorrent without qbittorrent-related stuff.
1. User adds magnet and an info dialog is presented to him.
2. Magnet is added to the session in the background with the flag `flag_upload_mode` set. This is done to preload the metadata and present info to the user while the dialog is open.
3. When metadata is received we pass around the torrent_info object and remove the magnet from the session.
4. If user accepts dialog we add it via the torrent_info object we hold, otherwise we discard it.

Apparently the assert triggers when we remove the magnet and it tries to write something to disk.
In any case due to the `flag_upload_mode` flag it shouldn't try to write something anyway.

PS: I wasn't the one that triggered. I was just asked to open a new issue about it.

**Comment by arvidn** [comment]
I'll try to replicate this in a test. Do you sometimes re-add the torrent with the ``torrent_info`` object programatically? i.e. immediately after removing the magnet link? The reason I ask is because the info-hash would be the same, and that's used as a key for the torrent. If the magnet link hasn't been fully removed yet by the time it's re-added, it's possible they get mixed up.

**Comment by arvidn** [comment]
This is in RC_1_1 is it?

**Comment by sledgehammer999** [comment]
>Do you sometimes re-add the torrent with the torrent_info object programatically? i.e. immediately after removing the magnet link?

It depends how quickly the user accepts the dialog...

>This is in RC_1_1 is it?

The particular report yes. @najjara did you get that assert with 1.0.10 too?

**Comment by arvidn** [comment]
@sledgehammer999 as a separate note, you probably want to use the ``stop_when_ready`` flag in ``add_torrent_params`` instead.

**Comment by arvidn** [comment]
I'm pretty sure I understand what's going on now. I added that assert while looking for another issue. Basically, it just keeps a queue of the last n torrents that have been deleted, and it expects to not see any activity on any of them. However, in this case, you add a torrent, delete it (and delete the files I believe) which adds it to this list. Then you add back that same torrent, and it starts downloading. The assert triggers because it's still in the list of deleted torrents.

I will remove this assert.

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/1286

**Comment by najjara** [comment]
> The particular report yes. @najjara did you get that assert with 1.0.10 too?

@sledgehammer999 I didn't get it with 1.0.10. Should I compile again?
Or should this issue be gone per @arvidn's [comment](https://github.com/arvidn/libtorrent/issues/1283#issuecomment-258053242)

**Comment by sledgehammer999** [comment]
@najjara no don't bother.
@arvidn ok I'll use the new flag for 1.1.x and the other one for 1.0.x.
