### ISSUE TITLE
Using "get_peers" as "ping" consumes more traffic.

### ISSUE THREAD

**Issue by thomas-yuan** [arvidn/libtorrent#129]
I think [Read-only DHT Nodes] (http://bittorrent.org/beps/bep_0043.html) is trying to save traffic for mobile device. But if we using "get_peers" as "ping", then we consumed more traffic unnecessarily.

Based on wireshark, a get_peers is usually 153 bytes, and a response is 359 bytes. I guess a "ping" should be 80~90 bytes around (based on error response is 8X bytes), and same as the response of "ping". so we can save 60%~70% traffic.

Any thoughts? If you agree with this idea, I can work on it.

**Comment by arvidn** [comment]
you have to take into account the additional traffic needed to maintain the routing table too. Right now, the pinging and maintenance of the routing table is combined. And I think overall, it consumes less bandwidth. Partly because you should also take into account the ethernet, IP and UDP overhead. If you can do the maintenance in few large packets, that's better than many small ones. Especially pinging has a, proportionally, very large overhead. It also doesn't have all that much utility, it just knows if one node is still responsive.

I wrote some about it here: http://blog.libtorrent.org/2014/11/dht-routing-table-maintenance/

I haven't actually measured the bandwidth usage, so that might be an interesting thing to do. One possible strict improvement would be to use pings once our routing table is full, and we would just throw away any new nodes we would learn about anyway. This is the case when the replacement bucket is full

**Comment by thomas-yuan** [comment]
Read your blog and that paper.

one question, does the touting table can be full? I think almost means 159 * 8 nodes (or 128 + 64 + 32 + 16 + 155 * 8 for extended_routing_table), is that possible?  From your blog, the routing table size is around 600 nodes. Also I saw some comments like this, not sure why tables can't deeper than 26 or 27, also don't know why it must <= 50. ( 128 + 64 + 32 + 16 + 46 * 8 = 608, very close to the routing table size in your blog)

```c++
		// if this assert triggers a lot in the wild, we should probably
		// harden our resistence towards this attack. Perhaps by never
		// splitting a bucket (and discard nodes) if the two buckets above it
		// are empty or close to empty
//		TORRENT_ASSERT(m_buckets.size() <= 50);
		if (m_buckets.size() > 50)
		{
			// this is a sanity check. In the wild, we shouldn't see routing
			// tables deeper than 26 or 27. If we get this deep, there might
			// be a bug in the bucket splitting logic, or there may be someone
			// playing a prank on us, spoofing node IDs.
```

**Comment by arvidn** [comment]
for every new bucket you open up, the total size of the DHT network must double. It just so happens that the BitTorrent DHT network is about 10 million nodes or so. Let's first consider the original specification, where every bucket fits 8 nodes. To fill the first bucket, you need 16 nodes (8 of which fall into the other half of the address space from you). To fill the second bucket you need twice as many. Since we assume uniform distribution, you need enough nodes to fill up everyone's second bucket. To fill the 3rd bucket, you need twice as many nodes again. and so on. Assuming a uniform distribution you can estimate the size of the network by just looking at how close the closest nodes are to you. The closer they are, the larger the network must be. My anecdotal experience is that normally you find alive nodes reliably around 21 to 22 bits into the node ID. That means the number of nodes you end up having in your routing table, in practice, is limited by the total number of nodes in the network. But it does not scale linearly, every time the size of the network doubles, you get one more bucket (of 8 nodes).

If you have 21 buckets in your routing table, that adds up to 8 * 21 = 168 (but then you have as many replacement nodes too). And with the extended table, you'll have more nodes in the top buckets, it would add up to:

128 + 64 + 32 + 16 + 8*17 = 376

**Comment by thomas-yuan** [comment]
Not sure the logic is correct, when send_single_refresh, 
```c++
if (m_table.bucket_size(bucket) < m_table.bucket_limit(bucket))
{
    // send ping.
}
else
{
    // send get_peers.
}
```
Tested several times, this is the first one about how many nodes (routing table size) with different logic. (forget to collect send/receive message bytes, just for reference) . 

![Test Result](https://lh3.googleusercontent.com/voEc-QwgL_V_xCYeQJK6F2PvCPGhK-kFLx0Zx028KLDBp-hkbc8O-AQOtSYMCCUie3KDl__9Nd9ciCQ=w1332-h784)


I have another test result shows that using ping can save about 16% data usage. 

This is the third one.
 ![Test 3, routing table](https://lh4.googleusercontent.com/qnlad-q5c_X0LXYe7X9EyPUbZxoUL7qyTWLbxnTMrYtjnwFOXsJlsRQhDqYrQlYa5vamCxn5JSSOL7s=w1855-h805)

![Test 3, data usage](https://lh4.googleusercontent.com/linoR_NhQqgK2Hh8K1UppXbldp9EP8FDdVdEKIzTXBIMf3K4MbEKkj-v_DDeE7qlXL0JXvxvhG316oc=w1338-h646)

seems only saved 8% data usage in this case.

Actually I found every 10 minutes bootstrap maybe consumed most of data.  Based on 2nd diagram, there are 3 jump about messages number which is caused by bootstrap (100 message was sent), but the alive_node and replacement nodes is smooth, which from my point of view, maybe it's not necessary? 

So if no boot strap, seems we can save almost 50% data usage based on diagram 3. (just remove the jump from ping data usage, compare to the get_peers data usage)

**Comment by arvidn** [comment]
The top graph suggests that your patch does significantly worse, doesn't it? am I misreading it?

Is there an unconditional bootstrap every 10 minutes? That doesn't sound right. I would at least expect it to be conditioned on the routing table being in a particularly bad state or something. I looks like there's a bug there.

Also, your top graph reminds me, your condition should probably also require the replacement bucket to be full.

**Comment by thomas-yuan** [comment]
For the first graph, the yellow is for original alive-nodes, the green is for the patch alive-nodes. I generated it with a wrong order.

The 10 minutes bootstrap is in node::tick().

BTW, ping/pong need about 220 bytes, get_peers need about 500 bytes. 

The replacement need to be full sounds reasonable.

**Comment by thomas-yuan** [comment]
Actually I'm trying to reduce DHT bandwidth usage without too much performance lost. So it can be used on mobile device even user is using cellular. 

The original testing shows that it will use about 35m per day if the node is dire tall accessible from Internet. Using read_only can reduce it to 15M per day. But it's still too much from my point of view.

Right now the node::tick is 5 seconds , if we can remove the bootstrap and make the interval configurable, say 20 seconds (need test first), then I assume DHT itself should only consumes 2M per day which is acceptable for me.

**Comment by thomas-yuan** [comment]
More test results update.
https://public.chartblocks.com/c/55f8d260c9a61d7175a8f045?t=2d3096dbe5beeda
https://public.chartblocks.com/c/55f8d4a0c9a61dfa75a8f045?t=52e5d51c591ff5d
https://public.chartblocks.com/c/55f8d8b7c9a61df076a8f045?t=b8ca44d68f90e34

== Bandwidth
Original readonly node will use about 12M per day. 
If no bootstrap every 10 minutes, can save 50% bandwidth. 6M per day.
If no bootstrap every 10 minutes, and change routing table refresh to 30 seconds, 1.1M per day.(Not in chart)
If no bootstrap every 10 minutes, routing table refresh every 30 seconds, use ping if bucket is full, then 900K per day.

== Performance (get immutable item every 60 minutes, how long the first result returned, mill-seconds)
Almost same.

== Routing table size
Original readonly, about 370 live nodes.
If no bootstrap every 10 minutes, about 340 live nodes.
If no bootstrap and refresh 30 seconds, using ping,  about 260 live nodes.

**Comment by arvidn** [comment]
since your pull request to change get_peers to ping has been merged, I'll close this
