### ISSUE TITLE
Create a search only through the BitTorrent network.

### ISSUE THREAD

**Issue by korenevskiy** [arvidn/libtorrent#1311]
Creating a search without a server, search downloads through the hash.
For example: If the title(name) of any download calculate the hash, then you can search without trackers, you can look directly into the network by UDP.
How it works: Everyone who creates seed should input the naming of 3-5 titles, each of which will be determined by the hash. These hashes are to be assigned to the seed. Example hashes for the titles: "Terminator", "Terminator 2", "Терминатор", "Терминатор 2".
When searched, it must be performed to compare and contrast hashes seeds. Example: when searching display a list of all the names that have a only one certain desired hash, ie in the table are displayed when searching for a different distribution of the hash (which is defined by its name), each line is a separate distribution of torrents.
.
The result is a search engine that is not possible to block on any tracker. None of the copyright.
.
And of course it is obvious that this is a very complex function.
But the meaning of it is that if it is. It client will not be just the same as everyone. It client will be at 4 heads above all the clients together.
A very large popularity.
.
The creation of such a function is similar to the invention Bitcoins.

**Comment by MassaRoddel** [comment]
How is that different from searching the DHT network for announced names (info hash + name/title)?

**Comment by korenevskiy** [comment]
In any way, the problem is that developers do not use HASH for storing names and the search titles.
Developers are create programs that search in sites. This is because your library is not ready for the search functions of title names in DHT. And of course, should be one rule for many search names in DHT.
In the library  necessary create a few functions for creating hashes from title name and adding these in DHT and search these DHT.
Only in this case you can use the torrent without resorting to the use of the internet browsers to search for torrents and without searching on sites trackers.

**Comment by arvidn** [comment]
when you say "search", do you mean something like a hash-lookup or do you mean something like a google-search?

There's a pretty important distinction, the latter includes stemming, spell correction, case-insensitivity and substring matching and other ways to support misspelled or near hits.

I don't think you can expect a search engine where you take a search term and hash it will hit anything significant, because of the perfect match of the complete name-property.

Anyway, I have a hard time understanding exactly what you're proposing.

**Comment by korenevskiy** [comment]
I suggest searching the hash.
.
Example: The user(leech) inputs the word in the program field. The program calculates a hash of the word. Then the program searches for the hash in the torrent network.
Dear arvidn, you're right. Here it is necessary corresponds to the exact spelling of the word.
.
Poetmou do this: 1. The program will calculate the hash for search 1."as is" and 2."lowercase letters." 2.seeder will create a torrent, and placed in the DHT once under several hash.
To create a torrent will need to enter the name in the 5 fields. For each field will calculate the hash. And then the seeder to place all of the hashes in DHT.

**Comment by arvidn** [comment]
I'm sorry to say that you don't seem to demonstrate an understanding of this space. Clearly just turning names of torrents to lower case will have an insignificant effect on search hit rate. the main problems are punctuation characters, spaces and other tags that people may add to names.

can you think of any name of a torrent off-hand? (i.e. without looking) that actually is an exact match of an existing torrent? exact match means *exact*, every ascii character having the exact right value and no additional and no missing characters.

I assume it's obvious that you would need to do splitting of words, stemming and probably add some more fuzzing to get anything remotely useful for searching. what you end up with is not trivial to store in a DHT, since there are so many keys.

You may want to look at yacy, which is a peer to peer web search platform. That's an incredible challenge.

**Comment by dessalines** [comment]
I think [BTDigg](https://en.wikipedia.org/wiki/BTDigg) might do what @korenevskiy 's asking. It crawls the DHT and creates a searchable index from torrent attributes like name, size, list of files, etc. Although I'm not sure how frequently it updates, because I've been able to find some, but not all of my torrents through it.

**Comment by korenevskiy** [comment]
Maybe then the title on the split spaces and punctuation. Then create a hash for each word. Next, place a hash of words in NTDs.
leecher will look for hashes of different words, and where there is overlap at the all words different hashes. The search will be closest to the result.

**Comment by arvidn** [comment]
right.. then you discover that the nodes hosting torrent lists for the words "the", "a", "at", "are" [etc](http://www.ranks.nl/stopwords). will often go offline and have very high churn, as if they're getting too much DHT traffic.

You start hard coding a list of stopwords in the clients. You find that some names end up with mostly stopwords or other very common words and that perhaps classifying terms as either ignored (stopwords) or not, may not be reflective of the (presumed) [zipf](https://en.wikipedia.org/wiki/Zipf's_law) distribution, and you still end up with words that are so common that nodes can't hold the entire list of torrents containing those words.

at the same time you discover that the DHT traffic worldwide has exploded by an order of magnitude or more, because of all these words being announced to it, in addition to the existing peer lists maintained by the DHT.

I don't want to discourage you to try to solve these problems, just fast forward you closer to where the actual challenges are.

**Comment by korenevskiy** [comment]
dessalines write about [BTDigg](https://en.wikipedia.org/wiki/BTDigg) . 
Are BTDigg a library or algorithm or a web service?
In our country have blocked most trekkers. 
Many torrent run on phones and distribute content. I think  technology has the ability to create a search in a hash. We need to understand how to do it.
We stopped in the development of P2P magnet links?

**Comment by Chocobo1** [comment]
I think what @korenevskiy trying to say is a feature that is already implemented in [Kad network](https://en.wikipedia.org/wiki/Kad_network):
`Search for eD2k hashes based on keywords in the file name.`

Based on my experience using [emule client](http://www.emule-project.net), you can just initiate a search using `ubuntu iso` as keywords, then the client will search for files that (partially) matches it.

I've no idea if it's possible to have a similar function in bittorrent protocol.

**Comment by korenevskiy** [comment]
Maybe all the same, let us consider the idea. Building 5 hashes of different names for the same torrent. This option I suggest to first in this discussion.
What do you think how much hash of are available for the name of the movie Terminator 2?

**Comment by korenevskiy** [comment]
Maybe  can come up with something better?

**Comment by arvidn** [comment]
basically every hit here has more than 5 words in their names. If you limit the number of words to be announced to the DHT, you need some heuristic for picking the best/most descriptive 5 words.

https://thepiratebay.org/search/terminator%202/0/99/0

presumably you would treat every punctuation character as word-separator. This also highlights the problem with "2" presumably having to be a stopword.

**Comment by korenevskiy** [comment]
And if the title is separate, and the tags separately.
Those. torrent will have one name, and 5 to search for the hash tags.
By the way, this link I had locked country, I open it  a in VPN.
You are right to find all titles in Piratbey, all titles chaotic. But it's just a name. And we will hash tags. the ones that I have mentioned.

**Comment by korenevskiy** [comment]
Dear gurus.
It seems a great idea. Title and searches split.
Names only for reading. And 5 fields designed for the keywords search. These keywords will be calculated cache. And search DHT.
.
And also, when you create a torrent, the user will fill in the name alone, and keywords in separate fields separately.
.
No need to worry about the different spellings. https://thepiratebay.org/search/terminator%202/0/99/0 keywords will be the same for most of the same title torrent.

**Comment by korenevskiy** [comment]
Dear gurus.
It seems a great idea. Title and searches split.
Names only for reading. And 5 fields designed for the keywords search. These keywords will be calculated cache. And search DHT.
.
And also, when you create a torrent, the user will fill in the name alone, and keywords in separate fields separately.
.
No need to worry about the different spellings. https://thepiratebay.org/search/terminator%202/0/99/0 keywords will be the same for most of the same title torrent.

**Comment by korenevskiy** [comment]
Dear guru developers.
Let's try to implement the feature.  If it is bad then will removed in the next season. This functionality is not difficult. You just need to add a couple of methods.
.
Please add search  hashes . 5 hashes are computed from the 5 key words.
Each torrent will be created 1 title and 5 keywords hashes.
. As you can see I've changed a proposal for a method of searching.
I used to suggested to use search hashes only 5 titles.  But now I suggest to do differently. But I suggest to have only one name and 5 hashes keywords.
.
Dear guru developers.
Total to add a couple of methods:
1. Create a hash keyword. 
2. Register hashes. 
3. Find the hash keyword in DHT.

**Comment by korenevskiy** [comment]
10 to 15 years ago. Google search service and other services so  they do not distinguish between  the time word at that time. I remember myself as I picked up an exact match words (or words). I even make mistakes and get results 0.
All was good. All enjoyed this search. All people arranged. People have tried to do the right search.

**Comment by korenevskiy** [comment]
What's will wrong with BitTorrent, if he will also do a search?

**Comment by MassaRoddel** [comment]
I assume a client would have to announce these 5 hashs to the dht network with a new command (similar to announce_peer). But it would include a changeable list of torrent hashs to make the torrent hash - keyword hash relation. Or do you expect another dht command for each client to return all matching torrents for a keyword hash (similar to get_peers)?
I can predict a very long keyword hash list if I take all the languages into account...

**Comment by korenevskiy** [comment]
@MassaRoddel Probably similar to the get_peers(). Maybe later we will find a better way.
.
1. User enters text search program. The program splits the text into words, then the program removes punctuation, then the program makes a hash for each word.
2. The program find to the hash network. Then he shows the search result where the most simultaneous matches hashes. It shows at the top of the list of torrents whose hashes match 3-4 from  hashes words find text.
.
To understand search technology, I introduced this procedure user control.
.
Maybe  it's not the best way.
. Let's discuss.
.
You can add a hash search, which will be stored only type of data (music, movies, TV shows, software, news, TV, etc.).
You can add a hash search, in which only the date will be stored (2016-11, 2011-12, 2016)
You can add a hash search, in which only the language will be stored (en-GB, ru-RU, etc)
Here it is necessary to adopt rules of procedure for the type and time.
If this type of hashes will be difficult, let's postpone it for later.

**Comment by MassaRoddel** [comment]
Are you aware that this will very likely totally overload dht nodes which had announced the hashs for "movie", "mkv" etc.?

**Comment by korenevskiy** [comment]
Yes you are right. Power increase DHT nobody wants.
It can be done differently. Can program (library) itself will filter the list of torrents after receiving the replies, and then show this list?

**Comment by korenevskiy** [comment]
Clearly, Bittorrent never  be not better.

**Comment by Falcosc** [comment]
@korenevskiy if we don't want to overload dht nodes with additional hashes, what would you like to do with just the info hashes? You could only get a list of available info hashes but you would not know what is in there.

I guess there is no way to get a search without tracker if we don't want to overload dht nodes.

**Comment by korenevskiy** [comment]
@Falcosc 
Yes, that's right, DHT will pregruzhen.
But:
1. DHT will not be overloaded, and will only be heavily loaded.
2. DHT not menyaetsya sorosti and does not increase. But now is a creating powerful DHT for any.
3. Let's try a new function. If this fails, we will remove it.

**Comment by arvidn** [comment]
you dismiss these concerns without providing any evidence of any research. If you want to be convincing, please provide research backing your claims. You may be able to understand how such a network can be built by looking at yacy, http://yacy.net/en/index.html

you could also write a BEP outlining our proposal in more detail and ask people to review it. But keep in mind, you can't expect people to spend more time reviewing than what you spent researching and typing up a proposal.

**Comment by korenevskiy** [comment]
You right. I provide research.
