### ISSUE TITLE
Python session.listen_on RuntimeError: Address family not supported by protocol

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#137]
A few Raspbian users running lt 1.0.6 are seeing the following error (e.g. in #132) from the listen_on method:

    self.session.listen_on(listen_ports[0], listen_ports[1], str(self.config["listen_interface"]).strip())
    exceptions.RuntimeError: Address family not supported by protocol

The ports are valid integers and listen_interface is an empty string. I cannot replicate the error myself. However I suspect it is due to IPv6 being disabled on RPi Raspbian. I don't ever recall seeing this issue from users running 0.16.

**Comment by arvidn** [comment]
a workaround in the meantime would be to explicitly set the listen interface to the IP of the internet-facing interface.

Another workaround would be to build with IPv6 support disabled for raspian.

libtorrent detects whether IPv6 is supported by trying to convert a string to an address (inet_pton()), if it fails to convert "::1", it's not supported, otherwise it's assumed to be supported. This works for windows. I take it on linux this conversion works even though IPv6 is disabled. Do you know of a way to detect whether IPV6 is enabled on linux?

**Comment by cas--** [comment]
A user has reported that [raspbian enable](https://www.raspbian.org/RaspbianFAQ#How_do_I_enable_or_use_IPv6.3F) does work so that will have to be the workaround for now. 

Checking `/proc/net/if_inet6` seems to be the best route, it would be empty if IPv6 is disabled. Otherwise would return a result like this:

    fe800000000000000a0027fffec736d0 02 40 20 80     eth0
    00000000000000000000000000000001 01 80 10 80       lo

**Comment by arvidn** [comment]
Here's a patch that attempts to open an IPv6 socket.

https://github.com/arvidn/libtorrent/pull/138

**Comment by arvidn** [comment]
I merged this patch and I will assume it fixes the problem (until someone re-opens this ticket)
