### ISSUE TITLE
[Feature suggestion] Propagating webseeds (HTTP Sources)

### ISSUE THREAD

**Issue by ahtebe** [arvidn/libtorrent#1433]
The issue: magnet links offered in most torrent sites don't include the ws:"insert_webssed_link_here" parameter even if the .torrent uploaded there correctly defines a number of webseeds (HTTP Sources).
This means that despite webseeds being available, a user is not able to download from them, because he doesn't know their links.

What I propose is that users who know of the webseeds for a particular torrent share with connected peers who don't know them the links to the webseeds.

Maybe libtorrent could set a precedent for this and cause other bittorent implementations to recognize the sharing of webseeds. Maybe this could be a bittorrent protocol extension?

**Comment by Falcosc** [comment]
The protocol extension could be a little bit more complex than expected, because you want to have the option to not propagate some of these URLs because there are User Related Data could be part of the URL parameter definition.

And you should not want to share web seed urls because HTTP requests are a lot more expensive then bittorent requests. That mean you should create as less http requests as possible. If you want to include a web seed into the swarm, only one swarm member should connection via http and share the received data with the swarm as proxy.

Of course we could ignore that http is expensive for the server provider, but in long term server providers will limit range requests (206) by n-times per second or even worse they could turn off the handling of these requests if it does force to much load.
In my opinion we should not even suggest such a protocol extension.

**Comment by ahtebe** [comment]
Then what's the point of having webseeds if we almost nobody uses them, even if they are available?

As for the cost of webseeds, isn't it already common to only download from webseeds if there are no p2p seeds available? That way downloading trough http would be a last resort.

So the webseeds would be shared but not necessarily used. They'd just be available in case there isn't anyone seeding.

**Comment by Falcosc** [comment]
That is a great point. But currently no bittorent clients has implemented webseed as lowest priority.
It’s common to download from a HTTP server with just one GET request or if you create parallel connections it creates 4 requests, maybe 10. But Bittorent clients create more then 1000s requests and if you have a fast connection the request overhead puts more load on the server as it has network bandwidth.

Until not any bittorent client has a solution for that I would not like such a feature.
Even we didn't solve it at libtorrent. Recently we fix something to get requests for large ranges but this does only work if no other peers are connected. If other peers are connected we still create these stupid 1MiB small range requests.
There are already servers out there which are blocking such small range requests because the providers get annoyed by them. And even worse, some of them ban you for some time.

I don't want to have this kind of behavior as a common solution for http server providers. For example recently I joint to a partial available torrent,  5 other peers has missed multiple sequential ranges in file and a single one 1MiB piece gap. I did get every missing part from webseed to the swarm except for the smallest gap. I was not able to get this piece from webseed.
Even a restart of the whole download did not help because even in sequential pick mode piece picker selects only the one piece because the others were already available in swarm and webseed does not respond to this small range request. I did have to download the whole file with wget to fix it.

I don't want to vote down your idea, I just don't want that the situation gets worse as it already is.

And it's not the fault of the server providers. If they don't have a bittorent client on the http host then the normally don't want to be part of the swarm. For example because of the disk io, predictive read cache strategies does not work with bittorent.

### But to be more constructive, I have a solution for you:
Create a reseed feature for the torrent file host which put webseeds into the torrent file if somebody requests a reseed. With such kind of solution you could even implement webseed based on session id with limited availability time by requesting for an open http slot on client side with the ip of the  client who did request reseed. The bittorent protocol extension would not be able to handle it because you can't share session links of http download slots which are bound to a single ip address for a limited time.
What do you think about this solution? Recently I did implement a session based http slot request for torrents as workaround to prove that it’s more effective to share the files via bittorrent to all http mirrors instead of distributing files over ftp and http.

**Comment by ahtebe** [comment]
I like your solution but it kind of puts the ball on the torrent hosts side. That is to say, it doesn't promote decentralization of p2p file sharing. 
And the "masses" that use bittorrent aren't going to be able to use this feature as its something only private trackers would implement, with apparently the future of bittorrent being magnets rather than .torrents. 
Its a sort of "inflexible" solution if you get what I mean... If the host goes down, the webseeds might as well not exist.

It is better than nothing though and it does help mitigate the problem of content not being seeded/unavailable, which is in my opinion the point of webseeds.

Shame it can't be done in a decentralized manner.

**Comment by arvidn** [comment]
I think the privacy aspect is probably the main hurdle. at least some web seeds in use today put per-user arguments in the web seed URL. Sharing these would be problematic, so it cannot be done unconditionally.

The other main issue I cane see is the potential for abuse. If you join a popular swarm and tell everyone that there's a web seed at ``http://you.victim.here.com/foobar`` you may be able to instigate *a lot* of people to hit it. Once everyone realized it's bogus, you just move on to telling everyone about ``http://your.victim.here.com/foobar2`` and so on.

It seems to me a much better solution would be for people publishing magnet links to include the web seeds in there.

**Comment by ahtebe** [comment]
>It seems to me a much better solution would be for people publishing magnet links to include the web seeds in there.

Precisely because people (or most) don't do that is why I thought of writing this feature/suggestion.
Maybe someone will think up something feasible.
