### ISSUE TITLE
Move storage NOOP now causes data loss

### ISSUE THREAD

**Issue by anthonyryan1** [arvidn/libtorrent#1473]
When testing 1.1.1 I noticed a regression where triggering move_storage on a torrent and passing the same path relative to $HOME as it currently has actually deletes all of the data.

Reproduction steps:
1. Download a torrent placing it in $HOME/Downloads
2. "Move storage" on that torrent to "Downloads"
3. Observed that the torrent's data files are removed.

This seems to a a regression introduced in 1.1. In 1.0 and prior this would correctly do nothing printing a message like "storage move failed: File exists"

```
libtorrent: 1.1.1
platform: Linux
architecture: x86_64
compiler:: gcc 4.9.4
```

**Comment by Falcosc** [comment]
A fix should be consider the comments of this ticket too https://github.com/arvidn/libtorrent/issues/435

**Comment by arvidn** [comment]
This problem was most likely introduced because of a more sophisticated move-storage logic. @sledgehammer999 may have some thoughts. The new function supports moving files individually, into existing directories. The problem here is that the same location on disk may be aliased and it's not obvious that the destination is the same as the source. In your example you spell it both "Downloads" and "$HOME/Downloads", so a simple string comparison would not be sufficient.

on linux there are functions to canonicalize paths, but there are holes in them, and they're not portable. Does anyone have any suggestion on what do to about this case?

@ssiloti perhaps?

**Comment by ssiloti** [comment]
Determining if two paths refer to the same file can be done, although it may not be trivial on all platforms. For Linux you can find code to do it in coreutils by grepping for the string "are the same file". On Windows you can use GetFileInformationByHandle on each path and compare their VolumeSerialNumber and FileIndex.

**Comment by arvidn** [comment]
does this fix it? @anthonyryan1 
https://github.com/arvidn/libtorrent/pull/1487
