### ISSUE TITLE
Suggestion - New Encryption

### ISSUE THREAD

**Issue by Papanikles** [arvidn/libtorrent#1489]
As we know some ISPs apply speed limitations on P2P connections. Using conventional encryption (RC4 / Plain text) no longer results. They have discovered way to decipher the data.

What I suggest is that the libbtorrent support a new type of encryption (RC5, AES, etc.).

I believe that is a simple thing to modify on libttorrent library on encryption section. Basically we need to implement a new encryption on libtorrent and when client have encryption On libtorrent verify (compatibility reasons) peer-id of connection and if the peer is a libtorrent user apply the new encryption to the connection also uses the old encryption.

Something like this:
If (encryption == on AND peer-id == libtorrent)
encrypt = new;
else If (encryption == on AND peer-id != libtorrent)
encrypt = old;
else
encrypt = none;

I think this can be a great point that differentiation and can help a lot people that suffering by limitations of your ISP.

What you think about this?

Best Regards.

**Comment by arvidn** [comment]
if you send the peer-id in the clear, you're kind of defeating the purpose of the obfuscation.
btw, how confident are you that ISPs can and do decrypt the traffic?
It seems like it would be simpler to develop heuristics based on other traffic properties to apply rate limits to.

**Comment by Falcosc** [comment]
traffic properties like amount of requests with specific sizes. There are alot smal requests over the bittorent protocoll https://wiki.theory.org/BitTorrentSpecification#Messages. I guess it would be quite easy for ISPs to determine bittorent by the 1000's smal request.

**Comment by Papanikles** [comment]
I don't know how works now in RC4/plain text, but you need always send what type the encryption that you use, right (crypto_field)? The method that isps use to break RC4 is this: http://www.blackhat.com/presentations/bh-usa-09/BROOKS/BHUSA09-Brooks-BitTorrHacks-PAPER.pdf (they suggest to use AES instead RC4)

RC4 is broken and is easly for isps identify bittorrent traffic. Plain text only encrypt header and the rest is not encrypted so another easy way to identify the traffic.

Personally I think that a new encryption would be awesome if some bittorrent library can introduce.

**Comment by Falcosc** [comment]
Some users do already have CPU usage issues because they got to many incoming connections
https://github.com/arvidn/libtorrent/issues/1339
I guess having handshakes without hash operations could reduce this problem by accepting only TLS as incoming connection.

But in my opinion this would not help at ISP limitation problems, at least not for a lot of people. Because I can’t imagine that ISPs would hold such an enormous database because the requirements for such a system and constant internet crawling for database population are not worth it.
Would be nice to hear if somebody is confident enough about it.

At summary:
I would like the suggestion for reducing CPU usage but not for solving ISP throttling issues because I guess other methods without decryption are more easy to implement for the ISPs.

**Comment by arvidn** [comment]
@Papanikles that document you reference does not provide any evidence for what ISPs do. It mainly points out a few (somewhat obvious) properties of the bittorrent protocol and the weaknesses of RC4. But it's not at all obvious that an ISP would have to spend all that CPU to break RC4 to throttle bittorrent traffic. In fact, it seems unlikely to me.
I bet an ISP could get pretty far by just throttling all streams whose protocols it doesn't recognize.
