### ISSUE TITLE
[macOS] Pausing one torrent -- closing file handles -- may significantly affect download speed of other torrents

### ISSUE THREAD

**Issue by artemskikh** [arvidn/libtorrent#1508]
libtorrent version (or branch):  1.0.9.0 revision ca54dc0
platform/architecture: macOS Sierra (10.12)
compiler and compiler version: Apple LLVM version 8.0.0 (clang-800.0.38) 

No matter what the storage_mode is (storage_mode_allocate / storage_mode_sparse) , after randomly writing to parts of a big file in a torrent, pausing it (when libtorrent waits for file handles of a torrent to close) will significantly affect the download speed of remaining torrents.

Btw, the storage_mode_allocate mode doesn't seem to work on macOS (doesn't actually allocate space).

**Comment by arvidn** [comment]
since ``close()`` blocks on macOS, each call may cause a disk thread to stall, which means you'll effectively have fewer disk threads while waiting on them. On top of that, the kernel is writing zeros to those large files, which may also eat into your effective disk bandwidth, that's left over for libtorrent to use

**Comment by alervd** [comment]
arvidn, it's required to use separate disk i/o threads for the each torrent.
And separate threads for networks/files i/o also.
This should fix this issue.
