### ISSUE TITLE
How about adding a new peer_plugin function, on_read_complete() ?

### ISSUE THREAD

**Issue by mangokingTW** [arvidn/libtorrent#1572]
Hi all,

I hope there is a plugin function on_read_complete(disk_buffer_holder&)  at peer_connection::on_disk_read_complete(),
because which will make it possible to modify the disk_buffer_holder.
It is very useful to implement the data compression, which I am eager to do.
Is it reasonable?

Thanks.

**Comment by arvidn** [comment]
it's not quite that easy. the buffers being hung on the send queues aren't necessarily mutable. sometimes they point directly into the libtorrent disk cache, which may not be modified. It's a bit messy, but right now we copy these buffers *if* the connection is encrypted.

**Comment by ssiloti** [comment]
Variable size chunks would surely break assumptions all over the place in the disk I/O subsystem. The only sane way I can see of doing this currently is with a custom implementation of `storage_interface`.

**Comment by mangokingTW** [comment]
I have tried storage_interface. 
If I compress data there, it can not pass the hash check, 
and the size of buffer doesn't shrink (still the size of one piece).

**Comment by arvidn** [comment]
I would imagine the simplest way to implement this would be to write a plugin that adds two new extension messages, with basically the same semantics as REQUEST and PIECE. So, the plugin would issue the disk request and decide what to do with it when it comes back. It will then have the opportunity to compress it into a new buffer and hang that on the send buffer chain.

**Comment by mangokingTW** [comment]
It sounds great. I will give it a try.
Thank you for your advice.

**Comment by ssiloti** [comment]
Sorry, I thought you were talking about compressing stored data rather than compressing data over the network. You might be able to modify the `crypto_plugin` infrastructure to allow a plugin to perform compression instead of encryption. This would have the advantage of compressing protocol data as well as piece data. The crypto plugin can also work with blocks larger than a single piece which would improve the compression ratio.

**Comment by mangokingTW** [comment]
@ssiloti 
In fact, I want to compress data read out from the disk to reduce network traffic.
Maybe I am not very clear about crypto_plugin, but in my recognition crypto_plugin is impossible to decrease the size of buffer.
[See here](http://www.libtorrent.org/reference-Plugins.html#crypto_plugin)

**Comment by ssiloti** [comment]
Yes, that's the bit that needs to be modified to support compression. I haven't looked at how much work it would be, it might be trivial or nearly impossible, but it's something to look at.

**Comment by mangokingTW** [comment]
Sadly, there is a [limitation](https://github.com/arvidn/libtorrent/blob/master/src/peer_connection.cpp#L5440) at setup_send(), I could only encrypt(compress) 1 MB data.

**Comment by ssiloti** [comment]
Why is that a problem? A block size of 1MB seems pretty reasonable to me, it's certainly better than compressing individual 16KB chunks with a custom piece message.

**Comment by mangokingTW** [comment]
In my case, the size of one chunk is at least 16 MB.
So it is better for me to compress 16 MB data at one time.

**Comment by ssiloti** [comment]
Are you sure about that? I think libtorrent would need a lot of modifications to work with chunks larger than 16KB. Note that the chunk size is not the same as the piece size, chunks are generally always 16KB even if the piece size is bigger.

**Comment by mangokingTW** [comment]
Sorry, I just misunderstand your comment.

**Comment by mangokingTW** [comment]
I am confused with chunks.
Why is ``m_send_buffer`` related to chunk size but not piece size?
``on_request`` should send the receiver one whole piece, right?

**Comment by ssiloti** [comment]
No, each piece data request is for one chunk.

**Comment by arvidn** [comment]
there are good reasons to keep the block size (or chunk size) relatively small. Since both control messages and payload is sent over a single (TCP/uTP) channel, a payload block that's too large will delay control messages. When you say you want to compress larger blocks, I assume what you mean is you want to re-use a dictionary for 16 MiB, rather than sending a new one for each 16 kiB block (or perhaps more specifically, make the dynamically built dictionary resume at the next block you send). either way, the actual bittorrent messages with payload you send should probably still be smaller than 16 MiB.
