### ISSUE TITLE
Assert fail m_num_save_resume <= loaded_limit

### ISSUE THREAD

**Issue by Falcosc** [arvidn/libtorrent#1592]
I could reprduce an issue with non starting client UI because of to expensive methods.
Do you have an idea to check at which methods the process got stuck with 100% load?

If I use qbittorent client I don't get any output if I reach the code which cause the 100% stuck. I can't even trigger the exit method calls, it just log
```
Catching signal: SIGINT
Exiting cleanly
```
and is still stuck with 100% load for at least 5 minutes

This does happen with the debug compilation and would like to figure out which checks are to expensive for debugging.
This could be related to issues where users don't see ui with an debug build.

**Comment by arvidn** [comment]
I would suggest you attach a debugger and look at the call stack and the logic that's being executed, and the values controlling the loop (assuming it's stuck in a loop) or the amount of work queued up. It could be a logic error causing stalls but it could also be a scalability issue (where something too expensive is done per torrent or per peer, which is fine as long as you don't have too many of those).

To get a better sense of performance issues, I would suggest you use a sampling profiler. I take it you're on linux or OSX, since you mention SIGINT.

On linux there's a good profiler called "perf" and on osx "Instruments" (built into x code) is really good.

On linux you would attach with gdb. the key commands in gdb are: "bt" (back trace), "info locals" for local variables, "list" to list source code, "up"/"down" to move up and down the call stack, to inspect different frames, "step"/"next" to step execution forward. On OSX the main debugger is lldb, which has similar but slightly differently spelled commands.

In either case, you want to make sure your executable is built with debug symbols, and perhaps ``-fno-omit-frame-pointer``, to get better visibility into the program. for debugging logic (as opposed to performance issues), you probably want to build without optimizations as well.

**Comment by Falcosc** [comment]
Thanks, I will try it out.

**Comment by Falcosc** [comment]
Sorry, I have to reopen it because I can't find the hotspot

It does boot fine

[bootAndPending.txt](https://github.com/arvidn/libtorrent/files/788493/bootAndPending.txt)

until it's starting the webinterface, and then it does some actions which did not get done

[pendingOnly.txt](https://github.com/arvidn/libtorrent/files/788492/pendingOnly.txt)

webui is still not online which means we are still in the boot process

after 30 minutes in this 100% load state get this
> file: 'session_impl.cpp'
> line: 7124
> function: void libtorrent::aux::session_impl::check_invariant() const
> expression: m_num_save_resume <= loaded_limit

I does still have the both perf records. Would be nice if you could have a look.

**Comment by arvidn** [comment]
If you can't tell where the infinite loop is, do you have a reason to believe it's in libtorrent?

If you attach a debugger though, I would be surprised if the infinite loop is not obvious

**Comment by Falcosc** [comment]
Not infinit, It got just loaded with more actions then it could process. This goes on until 

> file: 'session_impl.cpp'
> line: 7124
> function: void libtorrent::aux::session_impl::check_invariant() const
> expression: m_num_save_resume <= loaded_limit

I just want to know which kind of invariant checks could be turned of to make it able to process the task faster then new task got into it.

**Comment by Falcosc** [comment]
m_num_save_resume limit violation is not related to a the problems with session start. I did get this assert error during a normaly running session.

Maybe to many files did reach the need save resume time. Currently I did disable the assert to be able to test other things.

**Comment by Falcosc** [comment]
I found the load issue.
The problem was that my perf report did had only stacks without invariant check calls for the most used calls `std::_Rb_tree_increment(std::_Rb_tree_node_base const*)`

After I did skip the checks which was marked with much less cpu time I get ridge of the expensive ones too.
I did just got more request then my sandybrige could process.
