### ISSUE TITLE
Settings_pack class for python bindings

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#1609]
I forgot to raise this before but there is no way currently to create/view the settings_pack without first initialising a session. It would be useful to have a `libtorrent.settings_pack` class in  `session_settings.cpp` to access the settings from python. 

Perhaps `session.make_settings_pack` could be utilised?

**Comment by Falcosc** [comment]
Settings are set as a python dict, at least at master. As far as I know Settings structure usage is only possible with deprecated functions. The new functions only rely on a dict which could be initialised before session, and the latest changes enable a revoke of session start if there are unsupportet parameter defined in the dict.

**Comment by cas--** [comment]
I am well aware how it works but that is not relevant here.

**Comment by Falcosc** [comment]
Would it sufficient for your requirement to get a dict with all available settings keys but empty values?

**Comment by cas--** [comment]
The default values are required

**Comment by Falcosc** [comment]
I'm not sure how much effort is needed to extract the default session values without initalising the session.

At least you would get only something which is near to the actual values. Because the values may change on initilisation.
Would it be enoght to just get the settings pack values which are used as default? They may not equal to the values which you get after initialising a session with default values. (for example a -1 on some of the settings get to max int during initalisiation.)

**Comment by cas--** [comment]
Please unless you have an actual solution can we just wait for arvid to reply. It is a distracting and unproductive discussion.

**Comment by Falcosc** [comment]
My solution would be a dict based on settings pack values (https://github.com/arvidn/libtorrent/blob/173951ec7fe52698f33e6a0a14abeef6e4aef006/src/settings_pack.cpp) and I just asking if this does match to your requirement before the implemenation could start. Because these values does may not match to the values you get after the session was initalised.

It would be way more work to call the initlisation methods instead of returning the values from settings_pack.cpp

**Comment by arvidn** [comment]
@cas-- I was under the impression that I had sufficiently abstracted settings pack into a dictionary in python. keep in mind that a ``settings_pack`` is like a delta-update. when you construct it, it's empty. you add updates to it and then apply those updates. i.e. you can't get to the default values by constructing one in C++ either.

my understanding is that all functions that take a settings_pack convert it to a dictionary at the python boundary and vice versa. What's the use case you have in mind for creating one?

would it be more convenient to have the same interface as C++ in python? i.e. where the settings pack is essentially a collection of dictionaries of int -> int, int -> string, int -> bool?

**Comment by cas--** [comment]
The documentatin has the defaults so I assumed it wouldn't be that hard... :) However how would you programmatically get the default values if you wanted reset something? The one example that comes to mind are setting `min_memory_usage()` or `high_performance_seed()` how would you return to default values?

In fact that actually raises a couple of other issues. There is no way to get `min_memory_usage()` or `high_performance_seed()` as a `settings_pack` in python bindings. There is an `lt.min_memory_usage()` but it returns `session_settings` object.
Also the documentation of the code for these settings_pack methods is incorrect as they return void.

> would it be more convenient to have the same interface as C++ in python? i.e. where the settings pack is essentially a collection of dictionaries of int -> int, int -> string, int -> bool?

I am not sure, I did see that and thought in a python env that would be odd. It's a bit late here so will have a think tomorrow.

**Comment by arvidn** [comment]
added those functions here: https://github.com/arvidn/libtorrent/pull/1614

**Comment by cas--** [comment]
Could this be another method like min_memory that populates with default values? Would that not be useful for c++ lib too?

**Comment by arvidn** [comment]
you mean a function that creates a ``settings_pack`` filled with the default values?
that would seem reasonable.

**Comment by cas--** [comment]
Yes perhaps that got lost along the way but that was my original intention of the ticket

**Comment by arvidn** [comment]
something like this? https://github.com/arvidn/libtorrent/pull/1663
