### ISSUE TITLE
DHT crawler

### ISSUE THREAD

**Issue by dessalines** [arvidn/libtorrent#1672]
I see examples of crawling the DHT and downloading metadata with some low level examples like this: 

https://github.com/dontcontactme/simDHT/blob/master/simDHT.py

How would this be done with libtorrent?

**Comment by ssiloti** [comment]
It's not clear to me how that code is supposed to work, but currently collecting infohashes from the DHT is not trivial. It requires having access to a large number of IP addresses in order to be able to monitor the DHT for announces. There is BEP 51 which defines a new DHT message to support crawling the DHT with a single node, but it is very new and is not supported by any clients yet. See #1652.

**Comment by MassaRoddel** [comment]
I don't think that you can do the DHT part with libtorrent's DHT without changing the code to get access to announce and get peers queries (you take info hashs from the get_peers too to speed up the process). But once you have peers from DHT you can use the normal functionality from libtorrent to get the metadata.
From my experience -  a single node can collect peers for about 10000 info hashs per day with a ~30% success rate to get the metadata (on ipv4, much less info hashs on ipv6 but higher success rate). Limiting factor are actually libtorrents encryption and Win7's NLA service (which starts eating cpu, memory and leaves a memory leak in the client).
Btw, with such an approach you will end up with a large amount of incoming connection requests (for no longer existing torrents in the session).
