### ISSUE TITLE
Sevral things

### ISSUE THREAD

**Issue by Col-blimp** [arvidn/libtorrent#1684]
1)
```
udp://tracker.opentrackr.org:1337/announce
udp://tracker.opentrackr.org:1337/announce/
```

Both the same tracker but LibTorrent `add_tracker() ` allows both instances, can be avoided with client filtering but docs say dupes are managed.

2)

`rename_file()` on Windows is allowing disallowed characters such as `?`, again can be avoided by client filtering but `file_error_alert` in such cases gets posted but does not pause the torrent.

3) 

`peer_error_alert` how to get the ip from the alert?

4)

```
assertion failed. Please file a bugreport at https://github.com/arvidn/libtorrent/issues
Please include the following information:

version: 1.2.0.0-62cdec8

#: 1
file: 'include\libtorrent/stack_allocator.hpp'
line: 141
function: libtorrent::aux::stack_allocator::ptr
expression: idx.val() < int(m_storage.size())

stack:
 0: 00007FF62A8A6C47 print_backtrace +375 
```

**Comment by arvidn** [comment]
1. does this apply to RC_1_1 too?
2. the filename validation is primarily concerned about those in .torrent files, which are considered non-trusted. If you try to rename a file to an invalid name, what happens? I would expect there to be a ``file_rename_failed_alert`` posted. Is that not the case? I suppose that would only happen if there's actually a file on disk that needs renaming. Otherwise you would get a ``file_error_alert`` once libtorrent tries to create the file. The reason the torrent isn't paused is to resume downloading of other files, and resuming seeding data. It's considered a feature to not interrupt that.

3. ``peer_error_alert`` derives from ``peer_alert`` which has an ``endpoint``- as well as a ``pid`` member. pid being the peer ID.

4. please file a separate ticket for this issue, including the stack trace and a description of how to reproduce it

**Comment by arvidn** [comment]
It's not obvious to me that it makes sense for libtorrent to detect those two URLs as identical. your example (of an empty path) is really the only example where the '/' is redundant, right?

**Comment by arvidn** [comment]
would this make sense to you? https://github.com/arvidn/libtorrent/pull/1688

**Comment by Col-blimp** [comment]
I does make sense, it's what I ended up doing in the client before passing the url to `add_tracker()`.

Regarding `rename_file()` if I rename `text.txt` to `?.txt ` when the torrent has downloaded a part of the file then the operation fails and `file_rename_failed_alert` is not posted and in this case you would expect the failure but would expect the failed alert.

 If I rename `text.txt` to `?.txt ` before any part of the file has downloaded the operation succeeds with `file_renamed_alert` and LibTorrent internally stores the file name as `?.txt ` then at some point later when it's that files turn to be written to disk for the first time `file_error_alert` is posted or if the torrent is unloaded then reloaded with resume data you get `torrent_error_alert` followed by `file_error_alert` and in this case having been alerted to the problem when trying to rename the file back to a valid name the operation fails with no alert so your left with a dud torrent, obviously proper filtering on client side prevents all of the above.

**Comment by arvidn** [comment]
As for trailing / in URLs, I'm not sure about that patch. technically, ``http://example.com/a`` is different from ``http://example.com/a/``, right? One refers to a directory and one refers to a file.

Do you know if there's a function on windows to validate a filename? I would prefer not not attempt to fully implement the rules of which filenames are OK.

**Comment by Col-blimp** [comment]
Not that I could find, boost::filesystem::windows_name() : http://www.boost.org/doc/libs/1_63_0/libs/filesystem/doc/portability_guide.htm other than that it seems your validating the name yourself or calling _splitpath() or similar to get an error code.

I'm not sure how the url's work I just know that:

```
udp://tracker.opentrackr.org:1337/announce
udp://tracker.opentrackr.org:1337/announce/
```
are both allowed and are both doing and reporting the same thing so to me its a duplicate.
