### ISSUE TITLE
[crash] libtorrent::utp_socket_impl::consume_incoming_data

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#1701]
https://drdump.com/DumpGroup.aspx?DumpGroupID=719885&Login=guest

![default](https://cloud.githubusercontent.com/assets/920705/22864126/a7679764-f15c-11e6-939c-4139de49b218.png)

![default](https://cloud.githubusercontent.com/assets/920705/22864144/ed455974-f15c-11e6-862b-d73d4274fd62.png)

**Comment by pavel-pimenov** [comment]
![default](https://cloud.githubusercontent.com/assets/920705/22864326/6253aaa6-f160-11e6-9228-013e807f14f1.png)

**Comment by arvidn** [comment]
yeah, I didn't feel great when I made this change. The other accesses to ``p`` must be done in a previous statement, before the ``std::move()``

**Comment by aldenml** [comment]
@arvidn could you elaborate a little more?

**Comment by arvidn** [comment]
the fact that ``p`` is moved-from *and* accessed (read from) in the same statement is a bug. The order of evaluation of those subexpressions is not defined. If ``p`` is moved from first, the other accesses will dereference a null pointer. The fix is to access the counters first, store them in a local variable and use that in the function call.

**Comment by aldenml** [comment]
I suspected that that was the issue (in java is well defined :), do you have plans for an imminent PR?

**Comment by aldenml** [comment]
See https://github.com/arvidn/libtorrent/pull/1704
