### ISSUE TITLE
python bindings for storage_interface?

### ISSUE THREAD

**Issue by mayli** [arvidn/libtorrent#1749]
libtorrent version (or branch):
python-libtorrent (0.16.13-1ubuntu2.1)

Is it possible to provide storage_interface via python? It seems the relevant data structure are not available via the python binding.

**Comment by arvidn** [comment]
it is not possible. In fact, it's not possible to provide any plugins from python. The fundamental reason is that libtorrent runs in a separate thread (or in the case of storage, multiple different threads).

It's not possible (or at least quite complicated) to call into python from other threads because of the GIL. As far as I know, boost.python does not expose an easy way to do this at least, and if it did, there would still be the synchronization problem that libtorrent's internal threads would have to wait for the main python thread to get the GIL.

This was a source of subtle memory corruption a few years ago, at which point I decided to disable support for writing extensions in python (and to only expose the default, existing, extensions to be added from python).

In addition to this, the current ``storage_interface`` customization point will be phased out over the next few major releases, in favor of a customization point covering all disk I/O, for all torrents.

**Comment by mayli** [comment]
Thanks for the comment. Waiting for the new "customization point".
