### ISSUE TITLE
Not leaving checking_resume_data state when creating a session using the twisted reactor thread

### ISSUE THREAD

**Issue by vandenheuvel** [arvidn/libtorrent#1786]
`libtorrent-rasterbar9 1.1.0-3 amd64`
`python-libtorrent 1.1.0-3 amd64`
`python3-libtorrent 1.1.0-3 amd64`
`python-twisted 16.4.1-1 all`
`python-twisted-bin 16.4.1-1 amd64`
`python-twisted-core 16.4.1-1 all`
`python3-twisted 16.4.1-1 all`
`python3-twisted-bin 16.4.1-1 amd64`
packages from the yakkety repository. Ubuntu 16.10. This problem applies to both python2 and python3.

When encountering this bug we made [this](https://stackoverflow.com/questions/42351473/using-libtorrent-session-with-twisted-stuck-on-checking-resume-data) Stack Overflow post and [this](https://twistedmatrix.com/trac/ticket/9044) Twisted ticket.

This [seeder](https://github.com/vandenheuvel/libtorrent-latency-benchmark/blob/2bfaf173952187956ae436494f95939a1e7fbbeb/seeder.py) and [leecher](https://github.com/vandenheuvel/libtorrent-latency-benchmark/blob/2bfaf173952187956ae436494f95939a1e7fbbeb/leecher.py) script demonstrate the problem.
These scripts either fail to leave the `checking_resume_data` state or the reporting of the state is faulty. This can be fixed by [this](https://github.com/vandenheuvel/libtorrent-latency-benchmark/commit/9b094e4bb8596da391b46bdd1a85a400e98584e8) workaround: calling `session.pop_alerts()` every time before calling `torrent_handle.status()`. 

Note that this problem doesn't arise when calling the main method outside the reactor thread. There is also no problem using the reactor thread to call `torrent_handle.status()` if the libtorrent session was created by the python main (non-reactor) thread.

**Comment by arvidn** [comment]
Is twisted relevant, or does this happen when called from *any* thread, other than the main one?
the part of the code that deals with synchronizing calls to torrent_handle and session_handle is in include/libtorrent/aux_/session_call.hpp and src/session_call.cpp. If the call to ``torrent_handle::status()`` returns early, before the torrent_status object has been populated, it might look like the torrent is stuck. The relevant code is here:
   https://github.com/arvidn/libtorrent/blob/RC_1_1/src/session_call.cpp#L82

Note the loop around ``ses.cond.wait()``, this ensures that ``done`` must be set before returning, even with spurious wake-ups and cross-traffic (since all threads communicating with the session thread use the same mutex and condition variable).

**Comment by vandenheuvel** [comment]
It seems that Twisted is essential, other threads work properly. Only starting the libtorrent session via Twisted results in the problem (and the need to use `session.pop_alerts()`.

**Comment by arvidn** [comment]
the symptom you see, is it a ``torrent_status`` object that has been *filled in* with invalid data, or is it *uninitialized* (or default initialized)?

I suppose maybe that distinction is hard to make from python
