### ISSUE TITLE
Question about "session stats header" log alert

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#1788]
libtorrent version (or branch): master
With the latest change
```cpp
if (m_alerts.should_post<log_alert>()
	|| m_alerts.should_post<session_stats_alert>())
```
now a `log_alert` is coming even if we don't expect one. I know this is a kind of especial log, but I find this printing of the header very fragile.

Is it posible to remove this "header construction" from `session_impl` and moving it to the tool that prints the stats? Where is that?

**Comment by arvidn** [comment]
yeah, this is a bit of a hack. the tool parses this header to know what values to expect in the columns. It would be fragile to not tie this mapping to the values in the same log.

The fundamental problem is that this should only be logged when ``session_stats_alert``s are enabled, but it has to be logged as a ``log_alert``, since it's text.

I imagine it would be possible to only log it when session_stats_alerts are enabled, regardless of whether logs are enabled or not

**Comment by aldenml** [comment]
Why not remove the code from `session_impl`? If that's possible, where to put it?

**Comment by arvidn** [comment]
I consider it important that the name-mapping of the stats counters (i.e. this alert) is part of the same alert-stream, or log file, as the stats itself. If that's accepted, it needs to be logged somewhere, on session startup seems reasonable. I suppose the code to build the string, and maybe even create and post the alert could be factored out into the session_stats code

**Comment by aldenml** [comment]
What do you think of having a method `session_stats_alert::headers_message()` that whatever tool is logging the alerts can use (at will)?

**Comment by aldenml** [comment]
That would not requires any space in the "stack allocator"
