### ISSUE TITLE
port libtorrent as a react native module

### ISSUE THREAD

**Issue by dpxcc** [arvidn/libtorrent#1791]
I'm interested in porting libtorrent as a react native module.

I'm wondering how I build libtorrent for both ios and android. I'm not familiar with boost. Please advice. Thanks!

**Comment by arvidn** [comment]
This describes how to cross compile for arm-linux, which I believe should be fairly similar to cross compiling for ios and android.

http://blog.libtorrent.org/2017/02/building-libtorrent-for-c-h-i-p/

**Comment by dpxcc** [comment]
Thanks, it is quite helpful!

It seems that openssl is disabled by default. Should I enable it? If so, how can I build openssl with boost build?

**Comment by arvidn** [comment]
It's probably a good idea to enable openssl. The only reason I have disabled it by default is because many systems (windows and macOS) don't come with it nor have a simple way of installing it (especially windows).

There's no Jamfile to build openssl, you have to build that with openssl's own build tools. Last time I did that it involved assembly, so it may not be quite as straight-forward.

openssl, or libcrypto really, will likely provide a more efficient implementation of SHA-1 for instance.
