### ISSUE TITLE
Queue not working in version 1.0.6

### ISSUE THREAD

**Issue by johanlundberg** [arvidn/libtorrent#180]
Since upgrading to Deluge 1.3.12 (it comes with libtorrent 1.0.6) the queue no longer works as expected.

After a restart of the client the right amount of torrents are active (Total Active in Deluge) but after 20-30 seconds more and more torrents goes from queued to seeding until all torrents are in the seeding state.

According to the Deluge forum I should raise this issue here. Any more information I can supply?

Edit: Deluge forum thread, http://forum.deluge-torrent.org/viewtopic.php?f=7&t=52565&p=217997#p217997

**Comment by johanlundberg** [comment]
I have now tried with libtorrent 1.0.5 and 1.0.4, both shows the same behaviour. Using 0.16.19 the queue works as expected again.

**Comment by arvidn** [comment]
did you enabled "dont_count_slow_torrents" by any chance?

**Comment by johanlundberg** [comment]
Sadly not, "dont_count_slow_torrents" is confirmed (both ui and config file) to be set to false.

**Comment by cas--** [comment]
I did a quick test and what I have seen is having `active_limit` and `active_seeds` set to the same value seems to cause an issue.

**Comment by arvidn** [comment]
any chance you could give this a try? (it appears to fix it for me)
https://github.com/arvidn/libtorrent/pull/186

**Comment by cas--** [comment]
Yep that does fix it here, I should have said it was almost as if `dont_count_slow_torrents` was enabled ;)

**Comment by cas--** [comment]
I think there might still be an issue here with this, I am seeing with latest 1.0RC code torrents starting out queued and then slowly (every 30-60s) one-by-one switching to seeding and it looks like dont_count_slow_torrents is the culprit again.

**Comment by arvidn** [comment]
I cannot reproduce this in RC_1_0. I create 100 random torrents and add them to client_test, and I make sure dont_count_slow_torrents is disabled. I wait 15 minutes, and still only a single torrent is started (and the other 99 are queued).

could you provide more details about the configuration you see this in? do the torrents have to be seeding? do you have incoming_starts_queued_torrents enabled by any chance?

**Comment by cas--** [comment]
I don't understand it either it tested fine on my dev machine but on my own server as soon as I swapped 0.16 for 1.0 all the queued seeding torrents started seeding. The problem is that it kills my router having too many torrents trying to open connections so testing this is not trivial.

I thought it might only be a seeding torrent issue so I ran a test by adding a torrent to download (active_downloads set to 1) which force an existing slow downloading torrent into the queue but after a few minutes it also switched back to downloading.

I can't think of anything notable with the configuration, incoming_starts_queued_torrents is defaulted to false.

I shall see if I can replicate on my dev machine.

**Comment by arvidn** [comment]
is there a chance you can get a log?

**Comment by cas--** [comment]
Ok I knew it would be something like this... the problems with logging meant I had to properly investigate what files were installed on my server and I found libtorrent libraries left over from a 1.0.6 package that were being used by the bindings. Weirdly the bindings were returning 1.0.7 as the library version so not sure what was going on there.

Anyway the upshot is that this issue is fixed (oh and logging works)

**Comment by arvidn** [comment]
ah, actually, there's no function call to ask libtorrent what version it is (on the library itself). There are just defines in headers. This means that the version of libtorrent the python bindings are *built* against is the version that's reported, not the version of the actual libtorrent library that gets loaded. I should probably fix that.
