### ISSUE TITLE
Negative distributed_copies in torrent_status from torrent_handle.status()

### ISSUE THREAD

**Issue by LiMinggang** [arvidn/libtorrent#1835]
libtorrent version (or branch):1.1.2
platform/architecture:Windows 7 X64
compiler and compiler version:VS2015

Called
if( torrenthandle.is_valid())
torrentstatus = torrenthandle.status(lt::torrent_handle::query_distributed_copies);

ret = wxString::Format( _T( "%.02f" ), torrentstatus.distributed_copies );

Got -1.0

**Comment by LiMinggang** [comment]
FPU should not be an issue. So, I guess m_picker might be the root cause.
 
((flags & torrent_handle::query_distributed_copies) && m_picker.get()) does not stand.

In my case, the torrent had finished downloading.

Not sure if it was wrong.

**Comment by arvidn** [comment]
ah. In order to save memory, the piece picker is destructed once downloading completes. this takes with it the piece-rarity state that's used to calculate distributed copies.

I believe there may be some options to leave the piece picker around for this purpose. for instance, in super seeding mode I believe it will be left around

**Comment by LiMinggang** [comment]
Good to know this.
