### ISSUE TITLE
Unhandled error with LT 1.1.2

### ISSUE THREAD

**Issue by wo0lly** [arvidn/libtorrent#1863]
libtorrent version (or branch): 1.1.2 `(RC1_1)`

platform/architecture: Ubuntu 16.04 64-bit

compiler and compiler version: g++

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Running Deluge 1.3-stable and Libtorrent 1.1.2 (RC1_1), whenever deluge is restarted and it ends up this error

`Unhandled Error`
`Traceback (most recent call last):`
`  File "/usr/lib/python2.7/dist-packages/deluge-1.3.14.dev0-py2.7.egg/deluge/main.py", line 241, in start_daemon`
`    Daemon(options, args)`
`  File "/usr/lib/python2.7/dist-packages/deluge-1.3.14.dev0-py2.7.egg/deluge/core/daemon.py", line 180, in __init__`
`    reactor.run()`
`  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1243, in run`
`    self.mainLoop()`
`  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1252, in mainLoop`
`    self.runUntilCurrent()`
`--- <exception caught here> ---`
 ` File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 878, in runUntilCurrent
    call.func(*call.args, **call.kw)`
`  File "/usr/lib/python2.7/dist-packages/deluge-1.3.14.dev0-py2.7.egg/deluge/core/rpcserver.py", line 324, in dispatch`
`    self.sendData((RPC_RESPONSE, request_id, ret))`
`  File "/usr/lib/python2.7/dist-packages/deluge-1.3.14.dev0-py2.7.egg/deluge/core/rpcserver.py", line 199, in sendData`
`    self.transport.write(zlib.compress(rencode.dumps(data)))`
`  File "/usr/lib/python2.7/dist-packages/deluge-1.3.14.dev0-py2.7.egg/deluge/rencode.py", line 391, in dumps`
`    encode_func[type(x)](x, r)`
`  File "/usr/lib/python2.7/dist-packages/deluge-1.3.14.dev0-py2.7.egg/deluge/rencode.py", line 338, in encode_list`
`    encode_func[type(i)](i, r)`
`  File "/usr/lib/python2.7/dist-packages/deluge-1.3.14.dev0-py2.7.egg/deluge/rencode.py", line 355, in encode_dict`
`    encode_func[type(v)](v, r)`
`  File "/usr/lib/python2.7/dist-packages/deluge-1.3.14.dev0-py2.7.egg/deluge/rencode.py", line 355, in encode_dict`
`    encode_func[type(v)](v, r)`
`  File "/usr/lib/python2.7/dist-packages/deluge-1.3.14.dev0-py2.7.egg/deluge/rencode.py", line 338, in encode_list`
`    encode_func[type(i)](i, r)`
`  File "/usr/lib/python2.7/dist-packages/deluge-1.3.14.dev0-py2.7.egg/deluge/rencode.py", line 350, in encode_dict`
`    encode_func[type(v)](v, r)`
`exceptions.KeyError: <type 'datetime.datetime'>`

Any insight into this would be appreciated.

**Comment by cas--** [comment]
You should really use the code tags for error output. 

This has just been fixed in RC_1_1: 852fada77266903998dd

However once you have trackers in Deluge containing `datetime` objects you will also need to apply this Deluge fix: [dd08cb29](http://git.deluge-torrent.org/deluge/commit/?h=1.3-stable&id=dd08cb29e531d6bbb5a1a0142f7d93d305ab64d3)

Relevant Deluge ticket: http://dev.deluge-torrent.org/ticket/3008

**Comment by arvidn** [comment]
@cas-- does ``set_trackers()`` require more fields now? or why do you need that patch to deluge?

**Comment by cas--** [comment]
When communicating with UIs the RPC protocol is rencoded and it will fail if any python objects are in the data. So if trackers from 1.1.2 are added containing objects and then been stored we need to remove them on next start of Deluge otherwise connecting with UIs will remain broken. I should also mention in Deluge 1.3 we have no need for that tracker info but will do for Deluge 2.0. 

This ticket can be closed as far as I'm concerned.
