### ISSUE TITLE
WinRT support

### ISSUE THREAD

**Issue by bbougot** [arvidn/libtorrent#188]
Is there any support for WinRT? I statically built libtorrent with Boost (which has itself been built using the arg: windows-api=store), but I wonder if there is another thing to do.
I built using : 
bjam msvc-14.0 link=static runtime-link=static boost=source variant=release
Compilation succeed, I've my lib.

**Comment by arvidn** [comment]
I haven't personally tried it on winRT (and I don't know of a way to do that on appveyor). @vktr may have some more experience

**Comment by bbougot** [comment]
@arvidn Ok thanks
Also, what is the pupose of BOOST_ASIO_WINDOWS_RUNTIME in socket_types.hpp ? From what I've understood, it should be defined when building for WinRT, but setting it in Jamfile make the build fail (S_addr undefined, which seems to be a conflict between winsock2.h and windows.h, although WIN32_LEAN_AND_MEAN is defined)...

**Comment by arvidn** [comment]
do you mean socket_type.hpp? (with no 's' at the end). I don't see any use of BOOST_ASIO_WINDOWS_RUNTIME anywhere in libtorrent. where are you looking?

**Comment by bbougot** [comment]
Sorry my bad, I was looking in Boost actually

**Comment by x128** [comment]
@bbougot I think you should subscribe to [Project Centennial news](https://devpreviewsignup.windows.com/). They promise some real WinAPI there.

**Comment by bbougot** [comment]
@x128 oh god! That's awesome thanks!

**Comment by joycepg** [comment]
as a FYI, I have been able to compile the libtorrent library for a Windows Store app, but I cannot link. The following link errors happen:

    1>libtorrent.lib(asio.obj) : error LNK2001: unresolved external symbol __imp__VerSetConditionMask@16
    1>libtorrent.lib(asio.obj) : error LNK2001: unresolved external symbol __imp__CreateFileA@28
    1>libtorrent.lib(asio.obj) : error LNK2001: unresolved external symbol __imp__SetWaitableTimer@24
    1>libtorrent.lib(asio.obj) : error LNK2001: unresolved external symbol __imp__CreateWaitableTimerW@12
    1>libtorrent.lib(asio.obj) : error LNK2001: unresolved external symbol __imp__TerminateThread@8
    1>libtorrent.lib(asio.obj) : error LNK2001: unresolved external symbol __imp__UnregisterWaitEx@8
    1>libtorrent.lib(asio.obj) : error LNK2001: unresolved external symbol __imp__GetModuleHandleA@4
    1>libtorrent.lib(asio.obj) : error LNK2001: unresolved external symbol __imp__GetCommState@8
    1>libtorrent.lib(asio.obj) : error LNK2001: unresolved external symbol __imp__SetCommState@8
    1>libtorrent.lib(asio.obj) : error LNK2001: unresolved external symbol __imp__SetCommTimeouts@8
    1>libtorrent.lib(asio.obj) : error LNK2001: unresolved external symbol __imp__RegisterWaitForSingleObject@24
    1>libtorrent.lib(asio.obj) : error LNK2001: unresolved external symbol __imp__VerifyVersionInfoW@16
    1>libtorrent.lib(storage.obj) : error LNK2001: unresolved external symbol __imp__GetDriveTypeW@4
    1>libtorrent.lib(session_impl.obj) : error LNK2001: unresolved external symbol __imp__GetVersionExW@4
    1>libtorrent.lib(file.obj) : error LNK2001: unresolved external symbol __imp__CreateFileW@28
    1>libtorrent.lib(file.obj) : error LNK2001: unresolved external symbol __imp__GetFileInformationByHandle@8
    1>libtorrent.lib(file.obj) : error LNK2001: unresolved external symbol __imp__ReadFileScatter@20
    1>libtorrent.lib(file.obj) : error LNK2001: unresolved external symbol __imp__WriteFileGather@20
    1>libtorrent.lib(file.obj) : error LNK2001: unresolved external symbol __imp__DeviceIoControl@32
    1>libtorrent.lib(file.obj) : error LNK2001: unresolved external symbol __imp__LoadLibraryA@4
    1>libtorrent.lib(file_pool.obj) : error LNK2001: unresolved external symbol __imp__LoadLibraryA@4
    1>libtorrent.lib(enum_net.obj) : error LNK2001: unresolved external symbol __imp__LoadLibraryA@4
    1>libtorrent.lib(file.obj) : error LNK2001: unresolved external symbol __imp__CopyFileW@12
    1>libtorrent.lib(disk_buffer_pool.obj) : error LNK2001: unresolved external symbol __imp__VirtualLock@8
    1>libtorrent.lib(disk_buffer_pool.obj) : error LNK2001: unresolved external symbol __imp__VirtualUnlock@8

This is because these APIs are not available to Windows Store Apps. Check the requirements section at the end of the manual page for the API, eg, [CreateFile](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363858(v=vs.85).aspx)
Some are reasonably easy to solve, eg, use CreateFile2 instead of CreateFile
Others are harder, eg, there is no simple alternative for LoadLibrary

**Comment by arvidn** [comment]
@joycepg that's great progress! I don't really know anything about the symbols originating from ``asio.obj``. Presumably boost.asio does not have WinRT as a target (or perhaps I'm failing to use it correctly). Last I checked, asio has a comprehensive compatibility layer, making it even support the old winsock API (iirc). My bet is that all of those functions already have alternatives the compiler could be directed to when building under WinRT.

The majority of the other link failures can most likely be fixed by teaching ``libtorrent/config.hpp`` about WinRT and disable certain feature macros. And possibly introduce some new ones to be able to disable other features.

``LoadLibrary()`` is mostly used to load ``iphlpapi.dll`` for certain functions, and sometimes ``kernel32.dll`` perhaps. In most (if not all) of those cases, there are alternative paths in case ``LoadLibrary()`` fails, which could be used for WinRT (most likely).
