### ISSUE TITLE
python bindings for dht_storage?

### ISSUE THREAD

**Issue by mayli** [arvidn/libtorrent#1970]
libtorrent version (or branch):
master
platform/architecture:
x86
compiler and compiler version:
gcc
please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I'd like to see the python bindings for dht_storage, it's missing from the current python bindings.

**Comment by arvidn** [comment]
so is the regular storage binding. the problem is that libtorrent cannot (or it's quite complicated) call back into python code, from its internal thread. This would require locking the GIL, and that could potentially stall libtorrent's thread, which is not designed to be stalled.

I think you may be better off implementing a custom dht storage in C++.
