### ISSUE TITLE
tracker announce loop

### ISSUE THREAD

**Issue by MassaRoddel** [arvidn/libtorrent#1992]
recent master branch

Looks like libtorrent starts looping with 100% cpu through the tracker announce functions (if an udp tracker name lookup fails.)

**Comment by ssiloti** [comment]
I haven't been able to reproduce this locally. Can you send me a torrent which triggers the hang?

**Comment by MassaRoddel** [comment]
Here is an example torrent (had to change the file extension). Maybe the problem is related to the listen sockets so that you wont be able to reproduce it  with a different setup.

[[HorribleSubs] Tsugumomo - 07 [480p].mkv.txt](https://github.com/arvidn/libtorrent/files/999657/HorribleSubs.Tsugumomo.-.07.480p.mkv.txt)

**Comment by ssiloti** [comment]
I don't get a hang with that torrent. Could you attach a debugger and get a stack trace?

**Comment by arvidn** [comment]
enabling verbose logging (and logging the alerts) may be useful too. The logic for picking which trackers to announce to is unfortunately quite complex, primarily because it originally was stateless (or at least without additional state). In addition, supporting both "announce to all tiers" and "announce to all trackers" makes it more complex. Perhaps this setting triggers the busy loop.

**Comment by MassaRoddel** [comment]
I will that.
Just in case that helps: the tracker name lookup fails with winsock error 11001 - Host not found.
Btw, it does not really hang just tries to announce at full cpu speed as if there are no time intervals.
It does not do that if there is just one working tracker.

**Comment by MassaRoddel** [comment]
Here is a few seconds log ...

**Comment by ssiloti** [comment]
Ah I see, when I saw "looping with 100% cpu" I thought it was a tight loop that prevented anything else from being processed. I can reproduce the failure now, I'm investigating the cause.
