### ISSUE TITLE
Peer leak bug with private torrent

### ISSUE THREAD

**Issue by xf1** [arvidn/libtorrent#2029]
> bep_0027:
MUST ONLY initiate connections to peers returned from the private tracker.

But libtorrent accept any incoming connections.
how to reproduce it:
1. Download a torrent from A tracker, get the peer list.
2. Announce the peer list to B tracker.
3. Change the torrent's announce url to B tracker.
4. Download  the new torrent from another IP

![result](https://cloud.githubusercontent.com/assets/6897578/26447855/13d9aea8-417d-11e7-9c3d-7392f7dcb013.jpg)

**Comment by arvidn** [comment]
accepting a connection is different from initiating one. The BEP does not put any restrictions on accepting connections. If you think about the consequences of such restrictions, you quickly realize that it would not work very well. It would require every peer to know about every other peer (including which port their NAT may assign them as they try to connect to you).

Trackers return a subset of the swarm, in the general case, peers do not know about every other peer in the swarm.

The private tracker flag in .torrent files is in fact not a particularly strong guarantee that outsiders can't get in to the swarm, since it relies on the peer list itself to be secret.

**Comment by arvidn** [comment]
My first impression is that your client may want to prevent users from (easily) changing the trackers for private torrents

**Comment by xf1** [comment]
Got it.
Private trackers usually have small swarm. It may be worth restricting IP without port(for peer behind NAT), and return entire swarm.
