### ISSUE TITLE
Crashes in DHT, possibly related to invalid reference to node in dht_tracker::connection_timeout

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#2128]
libtorrent version (or branch): `master`
platform/architecture: `all`

Hi, I'm getting a lot of crashes in the DHT like this
```
native: pc 0000000000393b5f  (libtorrent::dht::dht_tracker::send_packet(libtorrent::aux::session_listen_socket*, libtorrent::entry&, boost::asio::ip::basic_endpoint<boost::asio::ip::udp> const&)+271)
native: pc 00000000003b5fc6  (libtorrent::dht::rpc_manager::invoke(libtorrent::entry&, boost::asio::ip::basic_endpoint<boost::asio::ip::udp> const&, std::__ndk1::shared_ptr<libtorrent::dht::observer>)+1446)
native: pc 00000000003a678c  (libtorrent::dht::bootstrap::invoke(std::__ndk1::shared_ptr<libtorrent::dht::observer>)+668)
native: pc 00000000003b91a7  (libtorrent::dht::traversal_algorithm::add_requests()+567)
native: pc 00000000003b8de9  (libtorrent::dht::traversal_algorithm::start()+73)
native: pc 000000000043ecc7  (libtorrent::dht::find_data::start()+39)
native: pc 000000000039ffd0  (libtorrent::dht::node::tick()+192)
native: pc 000000000039100a  (libtorrent::dht::dht_tracker::refresh_timeout(boost::system::error_code const&)+74)
```
and
```
native: pc 00000000003dbbe0  (_ZN10libtorrent8ip_voter9cast_voteERKN5boost4asio2ip7addressEiS6_+160)
native: pc 00000000002b5094  (_ZN10libtorrent3aux12session_impl20set_external_addressERNS0_15listen_socket_tERKN5boost4asio2ip7addressEiS9_+244)
native: pc 00000000002b519d  (_ZThn4_N10libtorrent3aux12session_impl20set_external_addressEPNS0_21session_listen_socketERKN5boost4asio2ip7addressES9_+45)
native: pc 000000000039a0b0   (_ZN10libtorrent3dht4node8incomingERKNS0_3msgE+1008)
native: pc 0000000000393022 (_ZN10libtorrent3dht11dht_tracker15incoming_packetERKN5boost4asio2ip14basic_endpointINS4_3udpEEENS_4spanIKcEE+770)
native: pc 00000000002a5001 (_ZN10libtorrent3aux12session_impl13on_udp_packetENSt6__ndk18weak_ptrINS0_18session_udp_socketEEENS0_9transportERKN5boost6system10error_codeE+1841)
```
and
```
native: pc 00000000003b2068 (libtorrent::ip_voter::cast_vote(boost::asio::ip::address const&, int, boost::asio::ip::address const&)+200)
native: pc 00000000002c0d20  (libtorrent::hash_address(boost::asio::ip::address const&)+128)
```
and
```
native: pc 000000000037b520  (libtorrent::dht::node::connection_timeout()+92)
native: pc 000000000036d66c  (libtorrent::dht::dht_tracker::connection_timeout(libtorrent::dht::dht_tracker::tracker_node&, boost::system::error_code const&)+60)
```

-------
But I think they are all the same and/or related to the same problem. I have a theory that this code is the problem:
```cpp
void dht_tracker::delete_socket(aux::session_listen_socket* s)
{
...
	m_nodes.erase(s); <--- here
}
```
Because once the `tracker_node` is destroyed, the timer task (`connection_timeout`) could be already schedule for near immediate execution. The `cancel()` implicitly called by the timer destructor does not guarantee the task to be not executed, or executed with an error, from boost documentation:
```
   * @note If the timer has already expired when cancel() is called, then the
   * handlers for asynchronous wait operations will:
   *
   * @li have already been invoked; or
   *
   * @li have been queued for invocation in the near future.
   *
   * These handlers can no longer be cancelled, and therefore are passed an
   * error code that indicates the successful completion of the wait operation.
```

My questions are:
1- Is my theory correct?
2- If 1) is affirmative, how to solve it?

Thanks in advance

**Comment by ssiloti** [comment]
Your theory about nodes getting removed could explain the crash in `connection_timeout`. The fix for that would be to make `connection_timeout` take a `session_listen_socket*` as its first parameter instead of `tracker_node&`. It would then lookup the node in `m_nodes` or bail out if a match is not found.

It does not explain the other crashes because they do not involve code which stores a reference to `tracker_node` across multiple async events. It would help to have more details about the crashes that just a backtrace. What type of exceptions caused the crashes? Assuming it's a segmentation fault, which data structure was the code trying to access? Line numbers on the back traces (i.e. with debug symbols loaded) would also be nice.

**Comment by aldenml** [comment]
I need to revisit my logic the lead me to conclude this as the problem's root.

Unfortunately, this is one of those cases when the bug manifest itself in release, and with a fair amount of real users (with real use).

For now, the first crash is happening quite a lot, and maybe it's just the same fix for the refresh timer.

**Comment by aldenml** [comment]
About the first crash, yes, it's not the same, but related to the removal of `session_listen_socket` while still a task is scheduled by the refresh timer. Any suggestion to solve this one?

**Comment by arvidn** [comment]
an alternative way to fix it is to make ``aux::session_listen_socket`` be held in a ``shared_ptr`` and all handlers, as long as they are outstanding, keep the object alive. It would still be safe to erase it from the list, it would just be "orphaned", only kept alive by its outstanding async handlers.

**Comment by arvidn** [comment]
and I definitely think you're onto something here

**Comment by ssiloti** [comment]
The backtraces don't match up with places where `session_listen_socket*` is dereferenced, so I don't think making it a `shared_ptr` is going to do any good. As far as the DHT goes, it shouldn't be a problem because `session_listen_socket*` is stored in `dht:node` and we erase the node associated with a listen socket at the same time as the socket is removed. As long as we avoid accessing any zombie nodes, which is what my initial suggestion was about, we should never see a dangling `session_listen_socket*`.

**Comment by aldenml** [comment]
I think this issue was closed automatically by the comment of the PR

**Comment by arvidn** [comment]
should we reopen it until you can confirm the fixes?

**Comment by aldenml** [comment]
I would

**Comment by aldenml** [comment]
This crash seems to be solved, now moving on to new ones :)
