### ISSUE TITLE
error 665 file system limitation

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#2152]
libtorrent version (or branch): master
platform/architecture: windows x64
compiler and compiler version: VC++2017

Client code:
if (lt::alert_cast<lt::torrent_error_alert>(a))
{
LogManager::torrent_message("torrent_error_alert: " + a->message() + " info:" + std::string(a->what()));
}

End user log:

[2017-07-14 08:28:07] torrent_error_alert: Ice Age Collision Course 2016 UHD 4K 2160p HEVC10 Multi DTSHD 7.1 -Zeus ERROR: (**665 The requested operation could not be completed due to a file system limitation**) D:\ЯDownloads\Ice Age Collision Course 2016 UHD 4K 2160p HEVC10 Multi DTSHD 7.1 -Zeus\Ice Age Collision Course 2016 UHD 4K 2160p HEVC10 Multi DTSHD 7.1 -Zeus.mkv info:torrent_error_alert

Help?

**Comment by ajax16384** [comment]
d: is NTFS drive?

**Comment by pavel-pimenov** [comment]
NTFS + cluster size: 64K

**Comment by arvidn** [comment]
Do you also get a file_error_alert? It contains some more details. I wonder if this error means the file has too many extents. Is the file unusually large?

**Comment by pavel-pimenov** [comment]
1. add log file_error_alert.
2. torrent size: 34.41 GiB https://thepiratebay.org/torrent/17185930/Ice_Age_Collision_Course_2016_UHD_4K_2160p_HEVC10_Multi_DTSHD_7.

**Comment by arvidn** [comment]
regarding reproducing the problem; if it's caused by the file having too many extents, it would not happen consistently. In fact, if you download faster with more seeds you may be more likely to download in-order (reducing the likelihood of many extents).

One thing way to work-around it (if my theory is correct) would be to pre-allocate the files.
