### ISSUE TITLE
LT generates invalid resume data if the storage is missing

### ISSUE THREAD

**Issue by alervd** [arvidn/libtorrent#2168]
**Please provide the following information**

libtorrent version (or branch):

#define LIBTORRENT_VERSION "1.0.11.0"
#define LIBTORRENT_REVISION "bbb38a9"

platform/architecture:

Windows 10, x86

compiler and compiler version:

Microsoft Visual C++ 2015

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

1. Download a torrent to external drive (e.g. USB disk).
2. Unplug the drive from PC.
3. Call `torrent_handle::save_resume_data`. 
3. `save_resume_data_alert` will arrive with invalid resume data. This data will miss "file sizes" field or have sizes and timestamps set to 0. 

I expect LT to fill file sizes with known to it values w/o querying them from disk. It should know all of them in all the cases already, isn't? At a least case it could generate `save_resume_data_failed_alert` instead.

Now what case we have. User downloads a torrent to external drive and disconnects it from PC. 
Next time our app starts (with the drive plugged in) - progress of torrents is set to 0. However we have all the files downloaded completely...

**Comment by arvidn** [comment]
the reason files are ``stat()``ed from disk is because historically the modification times were recorded as well (and there's no way to accurately predict those). As compact mode has been removed from newer versions of libtorrent, even the file sizes are no longer necessary, so I believe the "file sizes" list is no longer being generated.

I would recommend upgrading to libtorrent 1.1.x.
