### ISSUE TITLE
ccache builds are broken for autotools based builds

### ISSUE THREAD

**Issue by johang** [arvidn/libtorrent#2176]
**Please provide the following information**

libtorrent version (or branch): **master**

platform/architecture: **Linux**

compiler and compiler version: **gcc 6.2, libc 2.24**

The build fails if I do this:

`CXX="ccache g++" ./configure && make`

It fails because "g++" finds its way into CXXFLAGS:

```
Compiler and linker flags:
  CPPFlags:             -I/usr/include 
  CFlags:               -pthread -g -O2 -fvisibility=hidden
  CXXFlags:             -ftemplate-depth=512 -Wno-format-zero-length g++  -fvisibility=hidden -fvisibility-inlines-hidden
  LDFlags:              -L/usr/lib/x86_64-linux-gnu  -fvisibility=hidden -fvisibility-inlines-hidden
  Libs:                 -lboost_system -lpthread
```

It's probably because of this line in configure.ac:

`CXXFLAGS="$CXXFLAGS $(echo "$CXX " | cut -d ' ' -f 2-)"`

**Comment by arvidn** [comment]
if you remove that line, does it work for you?
it looks like a hack that probably should be removed anyway

**Comment by johang** [comment]
Yes, it works if I remove that line.

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/2195

**Comment by arvidn** [comment]
Now I remember, the reason this was introduced was because the c++11 m4 script adds -std=c++11 to the ``CXX`` variable, rather than the ``CXXFLAGS`` one. In order to propagate this flag to the python binding (which uses distutils to build) it needs to be in ``CXXFLAGS``. That's why this patch causes a build failure. Do you have a better idea of how to propagate c++11 to the python binding build?

**Comment by johang** [comment]
Thanks for checking this. Sounds to me the c++11 m4 script is doing the wrong thing.

**Comment by arvidn** [comment]
merged
