### ISSUE TITLE
0 byte readonly file in torrent will fail hash check

### ISSUE THREAD

**Issue by bittaurus** [arvidn/libtorrent#2212]
**Please provide the following information**

libtorrent version (or branch):
deluged: 1.3.15
libtorrent: 1.1.3.0

platform/architecture:
Linux host.name 4.9.20-hardened-host-r1 #2 SMP Sun Apr 9 10:02:56 2017 x86_64 Intel(R) Pentium(R) CPU G850 @ 2.90GHz GenuineIntel GNU/Linux

compiler and compiler version:
irrelevant really

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

When doing a hash check on a torrent, if a 0 byte file is has no write permissions, the hash check will fail.

reproduce by:
create a torrent containing a 0 byte length file.
chmod 444 said.file.txt
try to do a hash check.

Apparently the hash check tries to open 0 byte files in readwrite mode, but any other files it's ok with being read only.

**Comment by kaazoo** [comment]
I had the same problem with Deluge 1.3.15 / libtorrent 1.0.9.0. 
It works if the file is owned by the user who runs Deluge (e.g. 'deluge' when using deluged service).
Just adding read permissions in the empty file is not enough.

**Comment by arvidn** [comment]
when starting a new torrent (and when running a force-recheck) libtorrent will try to create all empty files up-front (since there won't be any other event causing them to be created).

When trying to create a file that already exists, normally the error would be ``EEXIST``. I bet in this case, the error is ``EACCESS``, which is considered a fatal error.

I'm not sure that's unreasonable behavior. I guess if the file is owned by the correct user, but is read-only, it may also fail with ``EACCESS``. However, in order to distinguish this case from, say, the whole file system or parent directory being inaccessible is non-trivial.

Does anyone have any advise on *simple* ways to alter the logic to improve the situation?

**Comment by bittaurus** [comment]
Well, if the file exists, it reports as 0 bytes, it's supposed to be 0 bytes, why would you even need to waste cycles touching it?  We all know what it's contents are.

**Comment by bittaurus** [comment]
I discovered the problem while trying to seed torrents mounted on a rclone google drive mount, which API doesn't support simultaneous read and write access, you can random access either read or write, but not both at the same time.

So then I moved the files to a readwrite supported filesystem and it worked.
Then I set the 0 byte file -r--r--r-- and it failed again.

I'd imagine that if you were to mount any filesystem readonly (like from a DVD drive or what not), you'd end up failing as well.

**Comment by arvidn** [comment]
> Well, if the file exists, it reports as 0 bytes, it's supposed to be 0 bytes, why would you even need to waste cycles touching it? We all know what it's contents are.

You may as well ask: "why waste cycles on calling ``stat()`` on it, instead of just creating it?". It would introduce an extra system call. Presumably 0-sized files aren't all that common and probably won't matter.

It won't necessarily address the case of another user owning the file. Perhaps a more robust approach would be to always ignore errors from trying to create empty files. It's hard to think of a use case where failing that need to be fatal.

**Comment by bittaurus** [comment]
The hash check will just fail that block if the 0 byte file isn't present, and the block will never finish if downloading, correct?

**Comment by bittaurus** [comment]
As a workaround I have created a symlink structure pointing to the file locations for everything in the tree, then delete the link for the problematic file and copy it into the symlink tree, that way it can open that 0 byte file without issues and still have the majority of the files stored where i want them, then i seed from the symlink directory...

**Comment by arvidn** [comment]
The empty files do not participate in hash checking at all. Since they have nothing to hash. This is why they are a special case and created up-front. No block being downloaded will cause them to be created later.

**Comment by bittaurus** [comment]
Well, then I can't think of anything that would make ignoring errors a bad thing off the top of my head.

**Comment by arvidn** [comment]
please try this patch: https://github.com/arvidn/libtorrent/pull/2225

**Comment by bittaurus** [comment]
Thanks arvidn. Gitting the source as I type.

**Comment by arvidn** [comment]
merged
