### ISSUE TITLE
Help with DHT multi-home understanding and Questions

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#2306]
libtorrent version: `master`

Hello, I appreciate your help to understand with more details the mechanics of DHT in a multi-home environment. Allow me to describe the context of my situation first: I have an ATT UVERSE Gigapower (or ATT Fiber) vanilla setup, that means all my devices are connected to the Residential Gateway (RG) directly, my ISP is giving me IPv6 support, with 10/10 (all green) IPv6 tests. The RG _does not_ support UPnP or NAT-PMP, and I'm _not_ using manual port forwarding or DMZ with any device. No other `libtorrent` node is running in my network.

I'm trying to fetch `magnet:?xt=urn:btih:a83cc13bf4a07e85b938dcf06aa707955687ca7c` which is a fairly old and unpopular creative commons content torrent. I'm using `router.silotis.us:6881` as a bootstrap node in order to get IPv6 DHT nodes.

1)- First situation:
I only listening to `0.0.0.0:43567`, the port is irrelevant since no port mapping ever happens. The expected result is that I should not get any response, and that is what happens, eventually I get the log `DHT traversal: [0] not alive [ip]`.

2)- Second situation:
I only listening to `[::]:43567`. Now, to my good surprise with IPv6, I receive all UDP incoming packets (no portmap is necessary), all nodes I get are IPv6 and I get to finish the bootstrap, but during the magnet fetch, none of them have the torrent. Well, I'm getting the ones with port `:1` but unable to connect to them. So far, the expected result, since the IPv6 support is new and the torrent is old (and unpopular)

3)- Third situation:
Listening to `0.0.0.0:43567,[::]:43567`. The result is that I get IPv4 and IPv6 nodes and I'm able to fetch the magnet from IPv4 nodes. This is what I'm trying to understand.

Questions:

- Is the result in `3)` the expected one? or it is just a secondary effect of passing the incoming packet in `dht_tracker::incoming_packet` to all nodes (without discriminating protocol)? or it's that the intended behavior?

- If torrents can work with IPv4 nodes, why creating IPv6 only DHT's, like in `2)` does not allow to somehow "incorporate" IPv4 nodes in order to help with the actual transfer and info exchange?

- Is the only way to get "full performance" to open a socket in IPv4 for a "dummy" DHT?

Thanks (and sorry for the length)

**Comment by ssiloti** [comment]
I would expect bootstrapping the IPv4 DHT to work even without port mapping. Typically the router will establish a temporary mapping for outgoing UDP packets so that the response can be routed back to the same endpoint. Are you _only_ using `router.silotis.us` for bootstrapping? It only supports IPv6. You need to use another bootstrap server like `router.utorrent.com` to bootstrap IPv4.

Assuming you are only using `router.silotis.us` then these results make prefect sense. In the first scenario libtorrent can only talk IPv4 so it can't communicate with the bootstrap server at all and nothing happens. In the second scenario bootstrapping works but there are probably no IPv6 nodes in the swarm so the download fails. In the third scenario your client bootstraps over IPv6 then bootstraps IPv4 from dual stack nodes. Since you now have IPv4 connectivity the download succeeds.

**Comment by aldenml** [comment]
I'm only using one bootstrap node at a time, now, if I try `dht.libtorrent.org:25401` (the default one with no IPv6 support), I get nothing, but I just tried `router.utorrent.com` and it works with only IPv4 (case `1)`), so I suppose that means you are right about the temporary mapping for UDP (I wasn't aware of that feature) and that `dht.libtorrent.org` is down.

@ssiloti Thanks for the explanation, I can see now in the logs that the IPv4 nodes are from the traversal from the IPv6 communicating dual stack nodes.
