### ISSUE TITLE
High memory usage (or even memory leak) on a single torrent

### ISSUE THREAD

**Issue by alervd** [arvidn/libtorrent#2353]
**Please provide the following information**

libtorrent version (or branch):

#define LIBTORRENT_VERSION "1.1.4.0"
#define LIBTORRENT_REVISION "20c1407"

platform/architecture:

Windows 10 x64, libtorrent x86

compiler and compiler version:

Microsoft Visual C++ 2015

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

1. Add a single torrent and start downloading it
2. In a few minutes (or even faster) memory usage goes to 450MB or even more (e.g. 700+ MB). On a single download.

Memory will not be freed after removing the torrent.

1.0.11 version of LT was using memory no more than ~80MB...

The problem occurs for both normal torrents and magnets.

**Comment by Seeker2** [comment]
1.Which Windows version is this on?

2.And is both the OS and libtorrent 32 bit or 64 bit?

**Comment by alervd** [comment]
oops, forgot to mention it. Sorry. Edited the first post.

**Comment by alervd** [comment]
It seems that the problem occurs under Mac OS X too.

**Comment by arvidn** [comment]
@alervd I will see if I can reproduce this on OSX. In the meantime, can you run it under Instruments.app heap profiler?

**Comment by arvidn** [comment]
I can't find any obvious problem under a heap profiler on OSX. but then again, there are lots of things that can differ depending on settings, build config and which torrent one is downloading.

**Comment by alervd** [comment]
Torrent example:
magnet:?xt=urn:btih:73FC5131AEE0D2AB986D97FDEEE882E34442A322&tr=http%3A%2F%2Fbt4.t-ru.org%2Fann%3Fmagnet&dn=%D0%A1%D0%BE%D1%8E%D0%B7%D0%BD%D0%B8%D0%BA%D0%B8%20%2F%20Allied%20(%D0%A0%D0%BE%D0%B1%D0%B5%D1%80%D1%82%20%D0%97%D0%B5%D0%BC%D0%B5%D0%BA%D0%B8%D1%81%20%2F%20Robert%20Zemeckis)%20%5B2016%2C%20%D0%A1%D0%A8%D0%90%2C%20%D0%92%D0%B5%D0%BB%D0%B8%D0%BA%D0%BE%D0%B1%D1%80%D0%B8%D1%82%D0%B0%D0%BD%D0%B8%D1%8F%2C%20%D0%B1%D0%BE%D0%B5%D0%B2%D0%B8%D0%BA%2C%20%D1%82%D1%80%D0%B8%D0%BB%D0%BB%D0%B5%D1%80%2C%20%D0%B4%D1%80%D0%B0%D0%BC%D0%B0%2C%20%D0%BC%D0%B5%D0%BB%D0%BE%D0%B4%D1%80%D0%B0%D0%BC%D0%B0%2C%20%D0%B2%D0%BE%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9%2C%20BDRip%20720p%5D%20Dub%20%2B%20Sub%20Rus

**Comment by alervd** [comment]
Our build script (under Mac):

#!/bin/sh
set -e

OUTPUTDIR=macosx64
OUTPUTPATH=$PWD/$OUTPUTDIR
BOOSTBUILD=$PWD/../boost/$OUTPUTDIR/bin/b2

rm -rf $OUTPUTPATH

cd src

$BOOSTBUILD install --prefix=$OUTPUTPATH --without-python --toolset=clang \
    variant=release link=static runtime-link=shared logging=off \
    dht=on boost-link=static encryption=on \
    include="$PWD/../../openssl/$OUTPUTDIR/include" \
    library-path="$PWD/../../openssl/$OUTPUTDIR/lib" \
    include="$PWD/../../boost/$OUTPUTDIR/include" \
    library-path="$PWD/../../boost/$OUTPUTDIR/lib" \
    -sBOOST_ROOT="$PWD/../../boost/src" \
    architecture=x86 address-model=64 \
    cxxflags="-std=c++11 -stdlib=libc++ -mmacosx-version-min=10.7" \
    linkflags="-stdlib=libc++ -mmacosx-version-min=10.7" \
    -j2

cd ..

rm -rf src/bin

**Comment by alervd** [comment]
Session configure code:

auto s = m_session->settings();
    s.user_agent = userAgent.toStdString();
    s.apply_ip_filter_to_trackers = false;
    s.upnp_ignore_nonrouters = true;
    s.use_dht_as_fallback = false;
    s.ssl_listen = 0; // Disable support for SSL torrents for now
    s.lazy_bitfields = true; // To prevent ISPs from blocking seeding
    s.stop_tracker_timeout = 1; // Speed up exit
    s.auto_scrape_interval = 20*60;
    s.announce_to_all_trackers = true;
    s.announce_to_all_tiers = true;
    s.auto_scrape_min_interval = 15*60;
    s.cache_size = -1;
    decltype(s.disk_io_read_mode) mode;
#if !defined(Q_OS_MAC)
    s.cache_expiry = 60;
    mode = libtorrent::session_settings::enable_os_cache;
#else
    // Force flushing to disk more often; We are disabling OS cache later , but just in case...
    s.cache_expiry = 5;
    mode = libtorrent::session_settings::disable_os_cache;
#endif
    s.disk_io_read_mode = mode;
    s.disk_io_write_mode = mode;
    s.anonymous_mode = false;
    s.active_downloads = -1;
    s.active_seeds = -1;
    s.active_limit = -1;
    s.active_tracker_limit = -1;
    s.active_dht_limit = -1;
    s.active_lsd_limit = -1;
    s.ignore_limits_on_local_network = false;
    s.rate_limit_ip_overhead = false;
    s.strict_super_seeding = false;
    s.half_open_limit = 20;
    s.connections_limit = -1;
    s.unchoke_slots_limit = -1;
    s.connection_speed = 20;
    s.no_connect_privileged_ports = false;
    s.seed_choking_algorithm = libtorrent::session_settings::fastest_upload;
    s.ignore_resume_timestamps = true;
    m_session->set_settings(s);

    libtorrent::pe_settings pes;
    pes.out_enc_policy = libtorrent::pe_settings::enabled;
    pes.in_enc_policy = libtorrent::pe_settings::enabled;
    pes.allowed_enc_level = libtorrent::pe_settings::rc4;
    pes.prefer_rc4 = true;
    m_session->set_pe_settings(pes);

**Comment by alervd** [comment]
The higher is downloading speed, the higher is memory consumption. 
I test with the speed: 9MB/s

**Comment by alervd** [comment]
Yes, on low speeds (e.g. < 1MB/s) the problem seems to be not reproducible.

**Comment by alervd** [comment]
I've disabled all add_extension calls - nothing has changed.

**Comment by MassaRoddel** [comment]
Have you checked that the problem is not caused by another windows service like NLA (Network Location Awareness)? On my Windows 7 the service starts consuming more and more ram and cpu on high udp traffic caused by dht which also leads to more memory consumption in my client process.
I could not find any memory leaks in the client.
According to what I found with google so far is that where seems to be problems with exception handling on the socket layer.
Disabling the NLA service helped a lot on my system.
I thought they fixed that on Windows 10. (They tried to fix that on windows 7 and also blamed it on bad network card drivers)

**Comment by alervd** [comment]
1. problem happens on Mac too.
2. I've tested my app with old LT and the same my app version (same code) with new LT. App with old LT does not have the problem.

**Comment by arvidn** [comment]
can you catch it in Instruments.app? It will tell you exactly where the memory usage comes from.

**Comment by alervd** [comment]
Sorry, I'm not a MAC developer. I've launched it under Instruments | Allocations, but do not know what to do next. I see too many allocations.
I saved data from Instruments so you could load it on your machine (hopefully).
http://files2.freedownloadmanager.org/tmp/lt/mem.trace.7z

**Comment by arvidn** [comment]
thanks! All the memory is allocated for pieces to be stuck in the write-queue in the disk buffer. The number of disk buffers allowed to be allocated for this is controlled by the [max_queued_disk_bytes setting](http://libtorrent.org/reference-Settings.html#max_queued_disk_bytes).

<img width="1218" alt="instruments" src="https://user-images.githubusercontent.com/661450/30864637-0d0ae25a-a289-11e7-97c8-efef8999591f.png">

**Comment by alervd** [comment]
So, is this a bug or not?
I did not modify this setting, so it should be 1MB by default, am I right? But it uses 255MB...

**Comment by arvidn** [comment]
yeah, looking at this setting, it only seems to take effect once the cache is full. I guess your cache size is 255 MB, is that right?

**Comment by arvidn** [comment]
part of me thinks that maybe it's reasonable to use the full disk cache for the write queue, as long as it's not used for anything else. I would be worried about implicitly choking the download rate by restricting it earlier.

**Comment by MassaRoddel** [comment]
Does it make sense to have a write queue and a disk cache?

**Comment by alervd** [comment]
What cache do you mean? 255MB is not a maximum size it can use. In some cases it starts using 800+MB in a few minutes of downloading.

**Comment by arvidn** [comment]
the disk cache. What's your cache size limit? If it's higher, perhaps 255 MB is your steady state of flushing to disk at your download rate. You can get the cache size metrics for read buffers/write buffers etc. to understand what's going on in the cache.

**Comment by alervd** [comment]
Still do not understand... In my Windows system I have Crucial M500 SSD drive installed. It does not have a cache at all (as far as I know).
255MB - it was just a quick test on my Mac OS X virtual machine. I did not run it enough time and thus it did not "eat" as much memory as it could. 
Anyway, can I do something to fix this? Will this be fixed?

**Comment by arvidn** [comment]
The cache I'm referring to is the [libtorrent disk cache](http://libtorrent.org/reference-Settings.html#cache_size). If this setting is at least 16384 for you, then I'm tempted to declare this as "works as intended". However, the default cache size is 1024 blocks (~16 MiB). If you don't touch this setting, there's definitely an issue of the cache size not being honored.

Although, there is an edge case where each peer gets at least 2 blocks worth of disk cache (16 kiB each) unconditionally. So, if you have a very large number of peers, that would in theory be a loophole around the cache size enforcement. Still not unbounded though, since there's a limit on the number of peer connections.

For the case where your process uses more than 256 MiB of RAM, I would be interested in specifically which metric you used. Just process working set is normally not a useful metric, at least not when it includes the OS-level disk cache, outside of the process' control.

**Comment by alervd** [comment]
Thanks! :) 
The setting was set to `-1`. Setting it to 1024 fixed the issue.

**Comment by alervd** [comment]
However, I see no reason for it to use so much RAM even if the setting allows it. I would understand if my hard drive was slower than the network. But my download speed is just 10MB/s which is not a problem at all for my SSD drive...

**Comment by arvidn** [comment]
The disk thread is essentially doing its best to act as a buffer between the network thread and the disk, making them more loosely tied. The network thread will push down buffers as fast as it can, and only experience back-pressure when the disk cache is full. The disk thread will delay writing blocks to the disk until it has a full piece (obviously it will flush earlier than that if the cache is full, but it has a preference for coalescing full pieces).

This means there's some elasticity between them. It doesn't necessarily take that much of latency in the system, or to start flushing a block, for the network thread to get quite far ahead. At least it doesn't seem too unexpected.

In previous versions there was a separate limit applied to the job queue, as well as the cache. The risk with every such limit is that your overall bandwidth delay product exceeds on of the limits and you're operating sub-optimally. That's why I would be a bit worried about imposing more limits at a finer grain.

The disk cache is quite instrumented, and there is a fair amount of counters you can get out of it if you feel like it's behaving strangely, or poorly.
