### ISSUE TITLE
listen_interfaces

### ISSUE THREAD

**Issue by Col-blimp** [arvidn/libtorrent#2404]
Consider a session is running with active torrents and everything is working as expected then you do this:

```
void set_new_interfaces() {
	lt::settings_pack pack = this_session->get_settings();
	pack.set_str(settings_pack::listen_interfaces ,"{A9C7D9ED-6572-44F9-9777-BF1C13BA82B9}:55272");
	this_session->apply_settings(pack);
}
```
What happens is the DHT nodes all drop out and the trackers drop out then once the new interface takes effect DHT nodes start to appear again and trackers begin working but torrents will not connect to any peers, if you terminate the session and start afresh with:

`pack.set_str(settings_pack::listen_interfaces ,"{A9C7D9ED-6572-44F9-9777-BF1C13BA82B9}:55272");`

everything is fine so the question is is it the case that to change interface mid session you do need to abort and start afresh or is there something I'm missing?

**Comment by aldenml** [comment]
Which branch or version?

**Comment by Col-blimp** [comment]
Master, sorry.

**Comment by ssiloti** [comment]
By default libtorrent listens on `0.0.0.0` so when you specify an interface to listen on that's going to cause the existing socket to be closed, along with the DHT node and tracker announces associated with it. That's all expected behavior.

Being unable to connect to peers after the change is a bug. Can you capture a log of the failure with `session_log_notification`, `torrent_log_notification`, `tracker_notification` and `peer_log_notification` 
categories enabled?

**Comment by aldenml** [comment]
@Col-blimp is this in Windows? in macOS I can't replicate the issue, but it takes like 20 seconds to start connecting peers successful.

**Comment by Col-blimp** [comment]
Yes it's Windows and there was indeed a delay but the issue itself was an error on my part with `outgoing_interface`, thanks for your time though.
