### ISSUE TITLE
peer list memory consumption

### ISSUE THREAD

**Issue by MassaRoddel** [arvidn/libtorrent#2413]
libtorrent version (or branch): master branch

in torrent_peer_allocator::allocate_peer_entry()
is see values like:
		m_live_allocations	556890
		m_live_bytes	31187672	
		m_total_allocations	556896

which seem much to high for me.
And it looks like torrent_peer_allocator::free_peer_entry() never get called.
In ~torrent(), m_peer_list has still entries, maybe peer_list needs a destructor now to free its entries?

**Comment by arvidn** [comment]
do you have reason to believe that this is a new issue in master, not present in RC_1_1?

**Comment by MassaRoddel** [comment]
I don't know. I did not test with 1.1.

**Comment by arvidn** [comment]
please test this patch. https://github.com/arvidn/libtorrent/pull/2416

**Comment by arvidn** [comment]
I suppose this may not apply cleanly onto master. I tested it locally and it seems to fix the problem. I will merge this into RC_1_1 and then into master.

**Comment by MassaRoddel** [comment]
No problem, I changed the code accordingly.
Currently I am looking to all the memory consumption in my client.
some places fixed - some more to investigate (more my code than libtorrents)

ie: STL has that bad behavior of automatically growing but not shrinking - so I am going to add .reserve() in some place to shrink.
 I had a std::string variable which stores metadata with a reserved space of 7.5MB. Like 7MB wasted in almost any case.
Does libtorrents pool concept include shrinking over time or is it also ever growing?

**Comment by arvidn** [comment]
this issue has been fixed in RC_1_1 and merged into master now.

the pool allocators in libtorrent never shrink. The problem with shrinking is that allocations or frees no longer become as efficient, since they need to be orders, to coalesce in one end of the pool.

However, using pools for the disk cache is on its way out. I believe @ssiloti removed it from master, and I think we may have disabled it by default in RC_1_1.
