### ISSUE TITLE
get_ssl_category()

### ISSUE THREAD

**Issue by Col-blimp** [arvidn/libtorrent#2431]
https://github.com/arvidn/libtorrent/pull/1570

Is it the case that `get_ssl_category()` is no more and errors are from the generic `system_category()` instead?

**Comment by aldenml** [comment]
only for `random`, for torrent over ssl, still `get_ssl_category()` is used

**Comment by Col-blimp** [comment]
Ahh, you know I was doing this before to get the category:

```
int get_allert_category(boost::system::error_code const& ec) {
	if ( ec.category() == lt::libtorrent_category() ) {
		return 0;
	}
	if ( ec.category() == lt::http_category() ) {
		return 1;
	}
	if ( ec.category() == lt::bdecode_category() ) {
		return 2;
	}
	if ( ec.category() == lt::i2p_category() ) {
		return 3;
	}
	if ( ec.category() == lt::socks_category() ) {
		return 4;
	}
	if ( ec.category() == lt::upnp_category() ) {
		return 5;
	}
	if ( ec.category() == lt::system_category() ) { // boost::asio::error::get_ssl_category()
		return 6;
	}
	return -1;
};

`boost::asio::error` has no member `get_ssl_category() `after this patch though.
```

**Comment by aldenml** [comment]
That should be due to the missing `#include <boost/asio/ssl/error.hpp>`, make sure you have it included in your files. Btw, `get_allert_category`, is that a typo in `allert`?

**Comment by Col-blimp** [comment]
Thanks, yes that was a typo 👍

**Comment by arvidn** [comment]
something I discovered in RC_1_1 recently was that *clients* would have to link against openssl libraries (libcrypto and libssl) just because libtorrent headers included "boost/asio/ssl/*" headers. Since boost.asio is header only by default, the global initialization functions of openssl is done from within a header, causing anyone including it refer to openssl symbols requiring linking against those libraries.

In an attempt to isolate clients, I made sure that (public) libtorrent headers no longer would include any boost/asio/ssl headers. This was discovered when I cleaned up the openssl dependencies in the Jamfiles to *not* add the openssl libraries as usage-requirements.
