### ISSUE TITLE
Speed Control problem

### ISSUE THREAD

**Issue by chaoaero** [arvidn/libtorrent#2457]
**Please provide the following information**

libtorrent version (or branch): RC_1_1

platform/architecture: Linux n10-048-160 4.4.0-33.bm.1-amd64 #1 SMP Fri, 01 Sep 2017 18:36:21 +0800 x86_64 GNU/Linux with 10Gbps internal network

compiler and compiler version:  python

How can I let each node reach the maximum download limit all the time ? I found that the download speed will grow and then slow down。The download rate limit I set is 800MB, While It only reached 200MB at most for 4 12GB files at the same time.  How can I let make the download speed be kept on 800MB or even 200MB all the time from the beginning to the end? Thanks!

Yours sincerely

**Comment by arvidn** [comment]
is the download rate higher if you don't set a limit?
it's possible that at high rates the current rate limit implementation has sufficient latencies to introduce a bottleneck internally.
The way the rate limit works is that peers issue requests for additional bandwidth quota and regularly (every tick) those requests are gathered up and bandwidth is distributed among them.
You could try increasing the tick rate (or lower the tick interval) to see if that helps. But using a rate limit will always mean some latency since bandwidth is requested up-front, not in parallel with actually sending.

**Comment by chaoaero** [comment]
I haven't found the tick related API for python wrapper. 

What's more, I implemented a python p2p downloading thread which inherited from threading.Thread.  If I ran the thread for long enough time, maybe 6 hours. the download and upload speed will drop slowly and finally stalilize at 50MB/s in LAN. the local_download_rate_limit and local_upload_rate_limit is -1. 

The thread I implemented above can be add or remove torrent dynamically. If I get the signal that each 10GB file has been received by all the peers, I will remove it from the thread and add a new one in time.

What should I do? Any parameters can be set to let the speed stabilize at 100MB or even 200MB?  Thanks

**Comment by ssawe** [comment]
I am using bittorrent on a 10Gbps internal network , the idea was to distribute the download among a group of worker machines rather than relying on a single fileserver. However, i am not getting nowhere above 200MB/s. Is there a hardcoded limit on the max available bandwidth ? how do i change it?

**Comment by Seeker2** [comment]
Maybe this can help:
High performance transfers on 10 Gbit/s interfaces  https://github.com/arvidn/libtorrent/issues/2215

Also raw speed tests done with pretty much no bandwidth limitations shows speed limits much lower than expected:
EXTREME Speed Tests of various BitTorrent Apps (over loopback/ Windows)  https://qbforums.shiki.hu/index.php/topic,3956.0.html
Example of similar "hidden" speed limitations:  https://qbforums.shiki.hu/index.php/topic,4237.msg22062.html#msg22062

**Comment by arvidn** [comment]
@ssawe If the download rate is low when setting the rate limits to anything but unlimited, then you're most likely hitting an inherent issue in the way the rate limiter is implemented. It's a function of the internal tick-rate. I would recommend setting all rate limits to unlimited.

If you're still experiencing download rate issues, the first question you have to answer is: "is the bottleneck the downloader or the uploader?".

how can you know? well, you can look for performance warnings alert, you can try tweaking the number of outstanding piece requests (increasing them), you can increase the number of allowed outstanding incoming piece requests on the uploader. you want to look at the send buffer max size (on the uploader) and the receive buffer size (on the downloader).

The download buffer size is set dynamically based on the download rate multiplied by a factor (which is another setting you may want to try to increase).

the best way to have visibility on what's going on, is to call ``post_session_stats()`` periodically on the session, and log the ``session_stats_alert``. there's a python script under tools that can parse the resulting log and (using gnuplot) render graphs of a number of interesting metrics.

For more information, see the [session statistics](http://libtorrent.org/manual-ref.html#session-statistics) section.

**Comment by arvidn** [comment]
@Seeker2 regarding those benchmarks, it's quite easy to get libtorrent (client_test specifically) to transfer at around 1GiB/s over loopback using the benchmark tool that comes with it (``connection_tester``). At least if you disable the actual disk I/O, as that can easily become the limiting factor otherwise. You may need to tweak some of the default settings though, to allow for larger buffers.

**Comment by Seeker2** [comment]
I used a fast ramdrive for source and destination and my i5 650 3.2 Ghz CPU wasn't fast enough.
Doesn't help it had to do lots of work to manage the ramdrive, but qBitTorrent could spike to >70% cpu usage in some of my latest tests at ~200 MB/sec.

**Comment by arvidn** [comment]
yeah, the thing with ``connection_tester`` is that it simulates multiple peers and it generates data rather than reading it off of a disk. It's cheap, so instead of running two clients on the machine, you only have to run the one you benchmark.
Also, if you disable the disk I/O in libtorrent (or set its cache size to fit the whole torrent you're testing), it will use more than 100% CPU. There's no longer anything to wait on, it will spend a lot of time shoveling data between the kernel and user space.

**Comment by chaoaero** [comment]
@Seeker2  I met the same problem.  I found that using prefer_tcp mode by setting **settings.bandwidth_mixed_algo_t = False** and**settings.mixed_mode_algorithm = False** could solve the issue. If you still want to limit the speed, decrease the watermark by setting 

```
settings.send_buffer_low_watermark = 1024 * 10 / 10
settings.send_buffer_watermark = 1024 * 10  * 50 / 50
settings.send_buffer_watermark_factor = 20
```
 It works well with speed 200MB/sec.

**Comment by Seeker2** [comment]
I was only using TCP -- I already had uTP disabled.

**Comment by chaoaero** [comment]
@Seeker2  would do mind pasting the setting parameters?

**Comment by Seeker2** [comment]
My settings probably wouldn't be very useful for you because I was using an extremely fast ramdrive capable of 1-6 GB/sec speeds -- depending on how tiny each R/W is. SSDs tied to SATA-3 (6 gbit/sec) are limited to about 0.5 GB/sec (500 MB/sec) at best and for tiny reads/writes (like qBT's 16 KB reads/writes) often falls below 0.1 GB/sec (100 MB/sec).

I was also using only a very tiny number of torrents loaded into qBitTorrent, with even fewer of those active at once -- sometimes only 1 torrent active. These torrents were also typically single files due to multi-file misalignment issues which can cripple the drives they're on. And of the active torrents, usually there was only 1 seed (qBitTorrent) and 1 peer (another BT client).

Almost every specialty setting in qBitTorrent was disabled -- uTP, DHT, PEX, LPD, anonymous mode, UPnP (although due to a bug it was often active anyway), Automatic Torrent Management, Download in Sequential Order, Download first and last pieces first, Super Seed Mode, RSS feeds, Wed UI, Listen on IPv6 address, resolve peer host names, Resolve Peer Countries (GeoIP), Download tracker's favicon, Send upload piece suggestions (because it seems bugged), Max number of half-open connections = 1, Prefer TCP, Allow multiple connections from same IP address, Embedded Tracker, Always announce on all trackers.

I also hide the left-side column that normally shows STATUS, CATEGORIES, TAGS, TRACKERS.
