### ISSUE TITLE
Question about checking_resume_data status

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#2535]
libtorrent: `master`

Hi @arvidn, it was pointed out that for new torrents without resume data, the status is `checking_resume_data` for a brief period of time (https://github.com/frostwire/frostwire-jlibtorrent/issues/185), I can see that in line 
https://github.com/arvidn/libtorrent/blob/master/src/torrent.cpp#L1799 that it's indeed the status regardless `m_add_torrent_params` is null or not.

Does it makes sense to put this:
```cpp
set_state(m_add_torrent_params ? torrent_status::checking_resume_data : torrent_status::checking_files);
```

**Comment by arvidn** [comment]
I believe checking the resume data is an asynchronous disk job that's run regardless of whether the user provided any resume data or not. this is the job that checks to see if any files exists at all for instance. whether the torrent goes into the "checking files" state or not is decided by the first "check resumedata" job.

Since there is a disk job I think it makes sense to have the torrent's state reflect this as well.

**Comment by aldenml** [comment]
agree, and thanks for the clarification
