### ISSUE TITLE
readv be executed before initialize in flag_seed_mode with custom_storage

### ISSUE THREAD

**Issue by tjjh89017** [arvidn/libtorrent#2558]
**Please provide the following information**

libtorrent version (or branch): 1.1.1-1 (ubuntu 17.04)

platform/architecture: Ubuntu 17.04 x86_64

compiler and compiler version: gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2)

When using `flag_seed_mode` with custom_storage, `readv` will always be executed before `initialize `.
That makes `readv` failed. Because storage isn't ready for reading.

**Comment by arvidn** [comment]
I looked closer at this and there are some legitimate reasons for ``readv()`` to be called before ``initialize()``. Specifically if the torrent needs full checking, every piece will be hashed and checked. This happens before the torrent starts and initializes the storage. ``initialize()`` isn't meant as a substitute for the constructor, it's really just meant to initialize the files on disk, it's called approximately when the torrent first starts (but may also be called on a force recheck).

I will improve the documentation for this.

It also turns out there are some irregularities with regards to the resume data though. It's essentially ignored in seed-mode right now, which isn't quite right. stats counters and peers should still be loaded. I'm working on a patch for this.

**Comment by arvidn** [comment]
not entirely relevant, but related: https://github.com/arvidn/libtorrent/pull/2568
