### ISSUE TITLE
Torrents stopped downloading

### ISSUE THREAD

**Issue by WhiteTrashLord** [arvidn/libtorrent#2563]
I had the problem that a lot of my torrents were no longer downloading. After a restart a lot of the torrents were downloading again. Libtorrent was running for several days. During that time I ran out of free space on the HDD. I deleted several files to have free space again. Is it possible that Libtorrent will stop a torrent if there is no more free space and won't check if there is free space again after some time later? So it will never download again?

**Comment by arvidn** [comment]
yes, libtorrent will stop torrents if they encounter any kind of disk error. they will remain stopped for as long as the error is still set, and it can be cleared with ``torrent_handle::clear_error()``.

there is logic in there to attempt to have a special case for ``ENOSPC``, and instead of stopping the torrent, turn it into ``upload-only`` mode. If the torrent is *auto managed*, it will leave upload only every now and then to try resuming the download.

this logic has turned out to be difficult to write a reliable test for, so it's possible it's not working correctly.
