### ISSUE TITLE
build libtorrent IOS for device (armv7, armv7s, arm64)

### ISSUE THREAD

**Issue by letiennam29** [arvidn/libtorrent#26]
I am newbie in IOS deverlop. I want to build libtorrent for IOS.

I find and build lib dependence of libtorrent are boost and openssl.
   + this is link build boost:
       https://github.com/danoli3/ofxiOSBoost
   + this is link build opensll
       https://github.com/x2on/OpenSSL-for-iPhone

I have had build sucess libs boost and openssl that a Fat lib of all architectures.
But with libtorrent I don't know option for configure Host and Architectures

Please, Any one can help solve for my problem.

Thanks everyone!

**Comment by mlt** [comment]
Don't use prebuilt boost. Use bjam to build libtorrent. [This](http://stackoverflow.com/questions/17714635/how-can-i-compile-boost-1-54-0-1-54-for-the-ios-simulator-6-1-on-os-x-10-8-4) might help. If you can build boost, you should be able to proceed with libtorrent the same way.

**Comment by arvidn** [comment]
in fact, you probably want to just build libtorrent and have it build boost (otherwise you'll end up building the boost dependencies twice).

basically this comes down to configuring boost build to have a toolset for building against iOS. Here's an example I use. depending on your version of xcode, clang and the SDK, the specific paths may be different for you:

using darwin : iphone
   : /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
   -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk
	-fcolor-diagnostics
   :
   <cxxflags>-std=c++11
   <compileflags>-stdlib=libc++
   <compileflags>-miphoneos-version-min=7.0
   <define>IPHONEOS_DEPLOYMENT_TARGET=7.0
   <linkflags>-stdlib=libc++
   <compileflags>"-arch armv7"
   <compileflags>"-arch armv7s"
   <compileflags>"-arch arm64"
   <linkflags>"-arch armv7"
   <linkflags>"-arch armv7s"
   <linkflags>"-arch arm64"
   <target-os>iphone
   <macosx-version>iphone-7.0
   ;

using darwin : iphonesim
   : /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
   -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk
	-fcolor-diagnostics
   :
   <cxxflags>-std=c++11
   <compileflags>-stdlib=libc++
   <compileflags>-miphoneos-version-min=7.0
   <define>IPHONEOS_DEPLOYMENT_TARGET=7.0
   <linkflags>-stdlib=libc++
   <compileflags>"-arch i386"
   <compileflags>"-arch x86_64"
   <linkflags>"-arch i386"
   <linkflags>"-arch x86_64"
   <architecture>x86
   <target-os>iphone
   <macosx-version>iphonesim-7.0
   ;

with this in ~/user-config.jam you can build with: "b2 darwin-iphone" and "b2 darwin-iphonesim".

**Comment by aldenml** [comment]
If you don't want to create a file in your home, create the file ios-config.jam with the text above and use bjam --user-config=ios-config.jam toolset=iphone

**Comment by dpxcc** [comment]
Thanks! But how can I install boost build on Mac?

**Comment by arvidn** [comment]
I think ``brew install boost-build`` would do it. But I always use the version from the corresponding boost distribution.

**Comment by alexandrumatei36** [comment]
I want to build libtorrent for iOS but I got this output. Any hints about it? RC_1_1 branch

```CXXFLAGS =
LDFLAGS =
OS = MACOSX
...patience...
...patience...
...found 4022 targets...
...updating 162 targets...
darwin.compile.c++ bin/darwin-iphone/debug/link-static/threading-multi/client_test.o
clang: warning: using sysroot for 'iPhoneOS' but targeting 'MacOSX' [-Wincompatible-sysroot]
In file included from client_test.cpp:33:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iterator:416:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iosfwd:90:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/wchar.h:119:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/wchar.h:70:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/_types.h:27:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/sys/_types.h:32:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/sys/cdefs.h:784:2: error: Unsupported architecture
#error Unsupported architecture
 ^
In file included from client_test.cpp:33:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iterator:416:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iosfwd:90:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/wchar.h:119:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/wchar.h:70:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/_types.h:27:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/sys/_types.h:33:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/machine/_types.h:34:2: error: architecture not supported
#error architecture not supported
 ^
In file included from client_test.cpp:33:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iterator:416:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iosfwd:90:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/wchar.h:119:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/wchar.h:70:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/_types.h:27:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/sys/_types.h:55:9: error: unknown type name '__int64_t'; did you mean '__int128_t'?
typedef __int64_t       __darwin_blkcnt_t;      /* total blocks */
        ^
note: '__int128_t' declared here```

**Comment by arvidn** [comment]
I think this is the message you should consider: "clang: warning: using sysroot for 'iPhoneOS' but targeting 'MacOSX'"
