### ISSUE TITLE
Improve CMake support as a primary build tool

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#2629]
libtorrent version: `1.X (X >=3)`

I was reading more about `CMake` and I just found this http://boost.2283326.n4.nabble.com/CMake-Announcement-from-Boost-Steering-Committee-tt4696934.html

My main motivation is that `CMake` seems like more widespread used, and I don't think technically it's inferior to `b2`.

**Comment by arvidn** [comment]
my experience of using cmake is that it is quite inferior. The first few things that come to mind are:

1. you can only build a single build configuration at a time.
2. you have to manually create and cd into build-configuration directories before invoking cmake in order to have multiple build configurations
3. (afaik) you can not run tests as part of the build (which means you can't run tests and build in parallel)
4. the build model is fundamentally based on the assumption that all dependencies have a single build configuration and there are no options that may affect their ABIs (with the traditional ``CXXFLAGS`` and ``LDFLAGS`` style of linking against dependencies). Modern cmake is trying to get away from this, and adapt a model closer to boost-build (but a lot of libraries are either not modern yet or not disciplined enough to work well together).
5. cmake does not provide any compiler abstractions. Most cmake scripts I've seen assume a GCC-compatible compiler, or worse yet, linux specific dependencies, adding things like ``-pthread`` to the compiler flags. Again, modern cmake is trying to move in this direction (I believe), but only provides a handful of compiler independent options.
6. to ensure reliable ABI compatibility, you need discipline to not alter build flags, and as a dependency you need to ensure any build options you require are set, you're not allowed to set them since arbitrary properties cannot propagate up the build hierarchy. This is error prone and I don't think many libraries do this right.
7. the language to declare your build is extremely verbose, especially compared to bjam. You repeat your target names in multiple declarations/statements.

That said, I would very much like to retire the autotools build files. The only thing that's needed for is to build the package/source tar-ball. If cmake could be made to do that, it would be great.

**Comment by aldenml** [comment]
hehe, no love for cmake here :)

Well, maybe the first step is replace autotools with cmake and use it in the CI, then improve the script to have a real alternative to bjam

(and thanks for the informative comments)

**Comment by aldenml** [comment]
After playing a little more with cmake, I need to say that it _feels_ to me more easy to handle than boost.build, and all the documentation out there is outstanding. I'm changing the title here and reopening the issue.

**Comment by aldenml** [comment]
Hi @arvidn, I was taking a look at `cpack`, with the idea of removing autotools, but I see some users use the common`./configure && make && make install`. Are you thinking about removing that feature too?

**Comment by arvidn** [comment]
I would imagine it would be pretty easy to support that. The configure script just call make, and make install calls cpack, Ior whatever you do for installing
