### ISSUE TITLE
libtorrent thread exit very slow

### ISSUE THREAD

**Issue by wangjingpei01** [arvidn/libtorrent#2706]
**Please provide the following information**

libtorrent version (or branch):
1.1.2
platform/architecture:
x86/
compiler and compiler version:
vs 2015
please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
we use the libtorrent to build a project, the session thread needs more than 20 seconds to exit when add 2 torrent to the session, and more than 60 seconds to exit when add 4 torrents to the session, I really want to know how to solve this problem,  I'll be very grateful if you can provide help;

**Comment by arvidn** [comment]
in my experience, there are primarily 2 or 3 causes of slow shutdowns.

1. The trackers are really slow or down and they all have to time-out before libtorrent gives up on them. This can be mitigated by lowering the [stop_tracker_timeout](https://libtorrent.org/reference-Settings.html#stop_tracker_timeout) setting. A more aggressive approach would be to remove the trackers from the torrents before shutting down or removing them.

2. DNS lookups are synchronous (although done on a separate thread). If you have connectivity issues to your DNS server, or have lots of names that are not in any close DNS caches, it may take a long time to perform the lookups. Later versions of libtorrent tries to mitigate this to some degree by caching DNS lookups and, when shutting down, using the cached responses rather than risking the OS cache has expired requiring a new online lookup. This is most commonly a problem if you start up and then shut down shortly after, while the initial DNS lookups still haven't completed yet.

3. flushing files to disk. This is primarily a problem on macOS (prior to MacFS). Since HFS+ does not support sparse files, opening a very large file, writing a little bit a few gigabytes in and then closing the file will stall the ``close()`` call while the kernel fills in zeros in the rest of the file. There's nothing that can be done about this other than upgrading filesystem or operating system.

**Comment by LiMinggang** [comment]
Did your code wait for alerts from torrents while exiting?

lt::alert const* a = m_libbtsession->wait_for_alert(lt::seconds( 10 ) );

**Comment by Seeker2** [comment]
Would having a BT app set to announce to all trackers serve to make the shutdown longer? (than set to only announce to one tracker per torrent)

**Comment by arvidn** [comment]
it sounds like it might, even with a shorter timeout, if you have enough (broken) trackers that could still take a while

**Comment by MassaRoddel** [comment]
Does that mean that a session shutdown does not cancel pending tracker announces?
Libtorrent will still wait for all announces even if the torrent was removed before the session destructor gets called?

**Comment by arvidn** [comment]
removing a torrent will trigger tracker ``event=stopped`` announces. those will be queued up/made immediately after the torrent is removed.

If one such event gets stuck in a DNS lookup, and the session is destructed; yes, it will delay shutdown.

**Comment by MassaRoddel** [comment]
What about trying the next tracker if the current one fails, will libtorrent still go through the list until it finds a working one?

**Comment by arvidn** [comment]
it looks like it will not do that. https://github.com/arvidn/libtorrent/blob/master/src/torrent.cpp#L10992
