### ISSUE TITLE
How can I get a library like this? "libtorrent-0.15.5WMTd.lib"

### ISSUE THREAD

**Issue by colcrt** [arvidn/libtorrent#2750]
**Please provide the following information**

libtorrent version (or branch): 0.15.5

platform/architecture: windows 86/64

compiler and compiler version: (visual basic 2013)

I want to compile so that I have a .lib file but I really do not know how they can help me?

**Comment by arvidn** [comment]
who's "they"?

to get a .lib file, run ``b2 link=static``

as for the name you mention in the topic, there's a tradition on windows where ``MT`` means multi threaded (that's the runtime library version) and ``d`` means debug. I don't know ``W``, but I would guess it's something that's happened since I last developed on windows, maybe ``WinRT`` or "Appstore-App" (or whatever the term is these days).

There's nothing in the stock libtorrent distro that creates these names, so you probably need to look for a packager.
