### ISSUE TITLE
Questions about separating DHT code as a separated project

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#2754]
Hello, I know @arvidn mentioned this idea a long long time ago. At that time I personally didn't see the advantage, but now, I see that more open source P2P projects are using some kind of kademlia based DHT to perform peer discovering. But once you start looking into them, you start to see the lack of maturity, handling of special cases, and tests.

My question is: What it's necessary to create _THE_ C++ kademlia based DHT implementation as a component, that everybody can use without reinventing the wheel?

As a reference for Java: https://github.com/the8472/mldht

**Comment by MassaRoddel** [comment]
documentation, examples and error messages (local/peer), which tell you what the real problem is (not just "202 Server Error" that everybody copied from the bittorrent page)
I guess that the abi c++ level should be low. Many people I know which claim to program c++ actually program only c.

**Comment by arvidn** [comment]
I am in favour of separating out the DHT as a separate repo/project and pulled into libtorrent as a submodule. There's some glue code/types that would need cleaning up a bit to complete the separation. Specifically the ``node_id`` type, is currently the same as ``sha1_hash`` and lives in libtorrent core. If libtorrent depends on the DHT, that type would have to live in the DHT, but that may be a bit odd as well, because a ``sha1_hash`` is a core type in bittorrent, unrelated to the DHT.

Other than that, the actual network I/O is somewhat abstracted already, primarily to allow unit testing, but also to separate the DHT code from the core.

**Comment by aldenml** [comment]
Putting on the hat of software architect, then I can see that some sort of _common_ project is necessary. One when you can throw all the digest32/hasher's code, some network utility functions to handle local network status/state and work with addresses, and some primitives to write/read bytes in buffers. Maybe this "common" is a better starting point, what do you think?

**Comment by arvidn** [comment]
yes, I agree. that's what we did when we split the DHT out of uTorrent

**Comment by arvidn** [comment]
you mean have a separate, small, headers-only library with shared types?
you mean reproducing a lite version of sha1_hash for instance? and possibly duplicate some other shared code too.

**Comment by aldenml** [comment]
I was thinking more about a "minimal wrapper" classic library, with simple symbol pulling via `using...`, but now that you mention a different approach, I think it's an alternative worth looking at, but I'm worried about the code repetition. Which one do you prefer?

**Comment by arvidn** [comment]
by "minimal wrapper", do you mean simplifying the types in the interface (and maybe internally) to use, say `std::array<>` instead of `sha1_hash`?

**Comment by aldenml** [comment]
I was thinking more about `session` and his `dht_*` methods for the "minimal wrapper". For `sha1_hash` specifically, I was thinking about just pulling the symbol in a new namespace, since it's just an instance of `digest32`
