### ISSUE TITLE
Non desctructive force recheck?

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#2759]
Is there a way to do a force recheck on a torrent and stop it before it does anything destructive to the files (eg truncate or download missing pieces)?

I tried doing various incantations of set_upload_mode and stop_when_ready but without any success. The file always gets truncated to the correct size.

Some usages/complains to see why it is important: https://github.com/qbittorrent/qBittorrent/issues/6277#issuecomment-361034774

**Comment by arvidn** [comment]
yes, I believe files are truncated when the storage is initialized. This could be changed to happen on-demand when a file is opened for writing.

**Comment by sledgehammer999** [comment]
Thanks.
Just to make sure: Apart from truncating, does libtorrent anything else with the bytes when the hash check fails? For example, does it delete the bytes that fail the hash check or just waits to overwrite them if the data ever get downloaded?

**Comment by arvidn** [comment]
it does not delete anything that fails the check. I don't believe it does any other write operations

**Comment by arvidn** [comment]
empty files is an edge case, i.e. files with size 0. Since they don't store any bytes, they will never be created or written to during normal downloading. This was the main motivation for creating files on startup (before downloading starts). All empty files are created and have their size set to 0.

If torrent initialization is not supposed to be destructive, an existing file that's supposed to be empty cannot be truncated. When would it be truncated then?

should empty files that already exist in the save path just be ignored? That seems a bit risky too.

**Comment by arvidn** [comment]
the solution I went with (for this patch) was to only create empty files if they don't already exist. If they exist, leave them and never truncate them to 0. The risks is that an application may rely on the filesystem exactly reflecting what's in the torrent file once it's seeding. that invariant may be violated now.

**Comment by arvidn** [comment]
since that patch has been merged, I consider this completed.
