### ISSUE TITLE
Feature to match torrent contents to particular files on HDD

### ISSUE THREAD

**Issue by slrslr** [arvidn/libtorrent#2838]
Hello, the issue is described here: https://github.com/qbittorrent/qBittorrent/issues/6520

**Comment by arvidn** [comment]
Do you have any idea what an api to do this would look like?
It seems either very wide (and complex) or very specialize to do exactly one thing.
Do you have buy-in from any other clients that would want a feature like this?

**Comment by slrslr** [comment]
Hi, i know nothing about the coding or seen no demand from client developers.

I posted this feature because it seemed to me that it may allow much easier and thorough file sharing via torrent if the torrent client programmers will use this libtorrent feature (i have no idea how/if it can be implemented) to automatically connect payload files on the HDD to the torrent without user having to manually finding file paths and reorganizing files to match torrent structure of the files. (as described under link i posted)

**Comment by slrslr** [comment]
I am still missing it. Nowadays it is so ineffective managing large collection of torrents and keeping it in sinc with the files on HDD.

**Comment by slrslr** [comment]
File sharing apps like eMule assign hash to every shared file. Can be possible for libtorrent to assign hash to every "file" in the torrent payload so the torrent clients can add functionality where it create hash database of HDD available files and easily pair these with torrent payload files? This would solve things described in this ticket and shift torrenting to next level.

**Comment by arvidn** [comment]
a local indexer could definitely hash files and index them like that. However, you cannot compute such file hash from the .torrent file alone. Having file hashes is something people have been wanting in bittorrent for well over 10 years, but the fundamental challenge is that bittorrent doesn't validate content on a per file basis, only per piece (which may span files).

A mechanism to calculate and record (locally) the hashes of files mapping them to .torrent files would be totally doable, the main difficulty comes in when *someone else* provides this mapping for you, because you must trust them (since there's no cryptographic proof that they are telling the truth). Such local functionality seems perfectly reasonable, I just don't think it belongs in libtorrent. As far as I can tell, it can be done independently from libtorrent, possibly with some aid from classes like `file_storage` and `torrent_info`.

However, in BitTorrent V2 (currently implemented in libtorrent master) the hashing is done per file (more specifically in a merkle hash tree, rooted in each file). This enables functionality to match files to torrents.

**Comment by slrslr** [comment]
> in BitTorrent V2 (currently implemented in libtorrent master) the hashing is done per file (more specifically in a merkle hash tree, rooted in each file). This enables functionality to match files to torrents.

Not knowing if this is right place to ask this feature or which place would be better, i write this comment to prevent stale bot close this.

**Comment by slrslr** [comment]
Can this be left opened here?

**Comment by Patty-OFurniture** [comment]
Working on a proof of concept to find files, copy them to the correct path, and after a force recheck the files are available for seeding. It is a work in progress. It is based on file size and does compare piece hashes.  I don't believe this belongs in libtorrent, but an external tool is appropriate and if a client wants to implement the same, it might be helpful.

C# Developers only recommended for now, but PRs are welcome. I'll finish it soon one way or another.  I've found about 5MB of files to seed otherwise unavailable torrents, so it is functional.

The .torrent file is required, just an infohash or magnet link won't help.

https://github.com/Patty-OFurniture/TorrentFiller/tree/main
