### ISSUE TITLE
Global bandwidth limitation is ignored

### ISSUE THREAD

**Issue by Infinisil** [arvidn/libtorrent#2857]
libtorrent version (or branch): 1.1.6

platform/architecture: NixOS Linux 4.14.24 x86_64

compiler and compiler version: gcc 7.3.0

See https://dev.deluge-torrent.org/ticket/3153 and https://forum.deluge-torrent.org/viewtopic.php?p=227823

Apparently 1.1.5 didn't have that problem.

**Comment by ssiloti** [comment]
By default libtorrent does not rate limit UTP connections. Previously this was not implemented correctly but it was fixed in 1.1.6 by #2596. The proper way to apply rate limits to UTP connections in 1.1.x is to use `set_peer_class_type_filter` to assign UTP connections to the global peer class. As a stop-gap in Deluge you can use the ltConfig plugin to enable the deprecated `rate_limit_utp` setting.

**Comment by Col-blimp** [comment]
Rate limiting does not work properly in master even with the peer filter added, looks like that patch was eventually merged into master though.

**Comment by arvidn** [comment]
@Col-blimp which patch? did it break or fix the issue?

**Comment by ssiloti** [comment]
I just checked with client_test and rate limiting works for me on master. The default for `rate_limit_utp` was changed to `true` on master so you don't even need to change the class filters to get rate limiting of UTP connections.

**Comment by Col-blimp** [comment]
`rate_limit_utp` is depreciated, if you try with a build without depreciated functions you'll see what I mean.

**Comment by ssiloti** [comment]
I built client_test with deprecated functions disabled, still works-for-me.

**Comment by asavah** [comment]
Can confirm this, if you build libtorrent from branch RC_1_1 with --enable-deprecated-functions deluge does not limit the bandwidth. The workaround form me was simple change false to true in https://github.com/arvidn/libtorrent/blob/RC_1_1/src/settings_pack.cpp#L198 and rebuild.
Now everything works as it should.

Thanks for the pointers 😁 .

**Comment by cas--** [comment]
@arvid this is still an issue in latest releases

**Comment by arvidn** [comment]
@cas-- what specifically is the issue? that uTP connections aren't subject to the rate limit by default? making them subject to the rate limit doesn't work? or is it that no connections (TCP and uTP) are subject to the rate limits?

**Comment by cas--** [comment]
I have not investigated whether it is uTP or TCP but with the default settings for Deluge the global bandwidth settings are being ignored (as mentioned broken since 1.1.6). Whatever the reason this is breaking backwards compatibility, is not what the user expects and should not require any libtorrent config changes.

**Comment by arvidn** [comment]
did it work as expected in 1.1.5? (or did you mean it's been broken since *at least* 1.1.6?)

**Comment by cas--** [comment]
According to users, 1.1.5 works as expected and releases since then are
broken

**Comment by arvidn** [comment]
@cas I'm interested in your opinion, I don't think there's a clear-cut solution.

My understanding and recollection is that libtorrent, ever since uTP was introduced, exempted it from the global rate limit. It could be made subject to the rate limit by setting the `rate_limit_utp` option.

On the other hand, the bug where the uTP became subject to the rate limit was introduced in July 2014, and fixed in December 2017. So that's a pretty long time, perhaps long enough to develop the expectation that this is the intended behaviour.

Another aspect is the question of what users intend when they set a rate limit. The traditional assumption (from the days where buffer bloat hadn't even been coined) was to not overwhelm ones DSL modem's send buffer. With that assumption it makes sense to not have uTP subject to the rate limit, as it's much more efficient at utilising bandwidth without contributing to the buffer bloat. In fact, it's also much better for the echo-system as it will make use of left-over bandwidth (remember, unused bandwidth is lost).

However, if users set rate limits in order to stay within some ISP-imposed quota, it does not make sense to exempt uTP from the rate limits. So I think there is an argument to change the default as well.

So, I get the impression would prefer to have uTP subject to the rate limit by default. Would you mind elaborating a bit on your thinking and weighing the different aspects?

**Comment by arvidn** [comment]
another aspect is that perhaps uTP should be subject to the *download rate* limit by default, as its main advantage is in the upload direction. Also, eventually I'm hoping that the download rate limit can be implemented by throttling `REQUEST` messages (as it's a lot more efficient). Doing that would naturally make all connections subject to the download rate limit.

**Comment by Col-blimp** [comment]
I think what end users are expecting is that say you set a global download rate of 8 Mbps on you're 10 Mbps limited service then libtorrent won't ever go above the 8 Mbps and mess with you're Netflix streaming that needs the 2 Mbps.

At the moment in master if you say set 5 Mbps download rate then libtorrent will go up to 20 Mbps on my test system.

Personally I think that all the various protocols should be included in the global and per torrent rates otherwise it's not really global or per torrent.

**Comment by cas--** [comment]
> On the other hand, the bug where the uTP became subject to the rate limit was introduced in July 2014, and fixed in December 2017. So that's a pretty long time, perhaps long enough to develop the expectation that this is the intended behaviour.

That is only 6 months and users have been complaining since that change and trying to revert to older releases so it is a big issue. Most end-users are in the dark that it's libtorrent-related and blame Deluge. I assumed this had been resolved until I realised it wasn't rate limiting when installing the latest release.

As col-blimp says this is to do with limiting down (and up) so that it leaves known network capacity. I understand that uTP is more efficient but users definitely want it rate-limited.

**Comment by arvidn** [comment]
from libtorrent's point of view, the defaults should ideally make the most sense for *most users*. That's users of libtorrent. Deluge should make sure to have its default settings make sense for most of its users. I don't think it's obvious the defaults in libtorrent necessarily should be the same as what should be default in Deluge, but I would expect there to be a significant overlap.

Perhaps most users of libtorrent would like rate limits to apply to uTP, or perhaps the users where the current defaults make sense, using rate limits at all isn't a useful feature at all.

Other aspects of this worth taking into consideration are how local peers are treated specially as well (i.e. peers from IP addresses reserved for local networks). Local peers are not subject to unchoke slot limits by default, they are also not subject (to the same degree) to the connection limit, nor the download/upload rate limits.

Perhaps the most reasonable default for libtorrent would be to not have any special cases like this for anything, but just document how to set them.

**Comment by cas--** [comment]
A stable libtorrent library should have sane and backward compatible defaults, users don't expect a global rate limit to be suddenly ignored. Had I known about the uTP issue earlier I would have raised a red flag.

I am not sure why there is so much discussion when 1.2 sets it to `true`:  https://github.com/arvidn/libtorrent/blob/6efff919cda667d272e48b9bc31cdb8ac3708b1e/docs/upgrade_to_1.2.rst#rate-limit-utp-changed-defaults

Local peer limiting is not an issue as Deluge has had that setting since it was available.

> Perhaps the most reasonable default for libtorrent would be to not have any special cases like this for anything, but just document how to set them.

That is how it should be and what has been missed is that the special case is to _not_ rate limit uTP. So you document turning off that specific rate_limit as per 1.2 dcos

**Comment by arvidn** [comment]
@d-komarov @ssiloti @ajax16384 @aldenml (sorry for the massive ping).

Do any of you have any preferences/insights here? I kind of like the idea of removing all special cases (except the TCP class, in order to support the TCP/uTP mixed mode rate limiting).

Basically, no special handling of local peers (by default) and no special handling of uTP peers by default. I would then deprecate the built-in local peers peer class, and make the global peer class apply to all peers by default.

Is it reasonable to do this in the next 1.1.x release?

**Comment by arvidn** [comment]
something like this perhaps: https://github.com/arvidn/libtorrent/pull/3170

**Comment by aldenml** [comment]
I think that having uTP restricted by the global limit by default (if it's set) is a more natural expected behavior. Same for local peers. I'm not familiar with that part of the code to comment about the best way to achieve that.

**Comment by ssiloti** [comment]
I agree with limiting uTP by default. I'm a little wary of changing the handling of local peers in RC_1_1. It probably only affects a small number of users, but for those it does affect it will be an unpleasant surprise.

I think throttling in general is becoming less important as anti-bufferbloat measures become more common in modems and routers. I've had all speed limits disabled in my client ever since I enabled traffic shaping with CODEL in my router. In my experience CODEL works much better than uTP at limiting the impact of torrent traffic on other flows. Unfortunately I suspect setting limits will persist as a cargo cult practice long after it ceases to be necessary.

**Comment by d-komarov** [comment]
IMO by default any peer traffic should be limited by default. Since there's a documented way to change that behavior, any end user will be able to customize it.

**Comment by Seeker2** [comment]
It's even possible for connections to be mistaken as "local" when they're not and allowed at unlimited speeds.
I've heard it happening with peers/seeds using the same VPN/proxy farm (similar ips), there might be other examples.

In short, by default traffic should be limited unless uTP becomes a LOT better at smoothing bandwidth usage.
uTorrent's uTP seems much better than libtorrent's, going by bandwidth graphs. Poorly-documented rules they're following to do so?
