### ISSUE TITLE
Please implement reliable alerts

### ISSUE THREAD

**Issue by fdev1** [arvidn/libtorrent#2885]
**Please provide the following information**

libtorrent version (or branch): 1.1.6

platform/architecture: Linux/ARM and x86

compiler and compiler version: GCC 5.4.0 and 6.4.0

Currently any thread that calls wait_for_alert() or pop_alerts() has to contend with libtorrent for the mutex and there is no bound to how long it will have to wait for it. The default scheduler on Linux makes sure that the thread will get to run soon but when using a realtime policy (SCHED_RR) which uses a simple round-robin algorithm I'm seeing latencies of seconds. Even if the thread popping alerts is higher priority. So I need a very large queue to ensure I don't miss any alerts. And still there is no guarantee!

Some possible solutions:

1. Add an option for blocking alert queues that will make should_post() always return true and emplace_alert() block when the queue is full. This would be the best IMO as it will make it fully deterministic.

2. Use a triple mutex as detailed by acatmur's answer [this stack overflow question](https://stackoverflow.com/questions/11666610/how-to-give-priority-to-privileged-thread-in-mutex-locking) or similar to give the popping thread higher priority.

3. Set the underlying pthread_mutex_t's protocol attribute to PTHREAD_PRIO_INHERIT. This will boost the priority of libtorrent threads while it owns the mutex.

**Comment by aldenml** [comment]
This is an interesting case, questions:
1- Do you have enable all bits in the mask of alerts to receive?
2- Can you use `master`? there is an optimization in `should_post()` that should help if the mask is not all set

**Comment by arvidn** [comment]
Option (1) doesn't seem very practical. (I assume you still mean ``should_post()`` would still take the mask into account, just not the queue size). But a blocking ``emplace_alert()`` would just stall the network thread entirely. Have you experimented with this? In normal use of libtorrent, I would expect a GUI thread to be quite likely to stall and lock up, and not have time to pop alerts sometimes. To stop the libtorrent network thread when this happens would be quite harsh. It may also introduce deadlocks, if the GUI thread is waiting for a specific alert, but it can't be posted because the queue is full.

Note that there is a mechanism already to give certain alerts a higher priority, to still be posted even after the first queue size limit is reached.

Do you understand why it would take seconds to acquire this mutex? It should be a un-contended. Is it possible that when you use ``SCHED_RR`` mutexes are not longer fair? The amount of work libtorrent performs while holding the mutex in the alert manager (I assume that's the mutex we're talking about) is quite minimal. It may extend the heterogeneous queue to fit another alert, it will construct an alert object and possibly allocate some space on a stack allocator (which may require extending that allocation as well, but not under steady state). Are you seeing that taking seconds? Does that mean the scheduler just switches away from the libtorrent network thread for that long?

If so, it sounds like you may be running with a bit too much load. what's your typical load average?

(2) sounds pretty complex an probably unwarranted for the common case.

(3) sounds reasonable, maybe a little bit messy and linux (and likely libstdc++) specific.

If there was an easy way to make some aspect of this lock-free, I think that would be ideal. But I think that's hard without turning it into a linked list.

I also have this feeling that solving this problem is really sweeping a deeper, more fundamental problem under the carpet. If libtorrent's network thread gets off-CPU for that long at a time, will it really be effective, or will it have odd behaviors in other places too?

**Comment by fernando-rodriguez** [comment]
On 03/27/2018 03:32 PM, Arvid Norberg wrote:
> Option (1) doesn't seem very practical. (I assume you still mean 
> |should_post()| would still take the mask into account, just not the 
> queue size). But a blocking |emplace_alert()| would just stall the 
> network thread entirely. Have you experimented with this? In normal use 
> of libtorrent, I would expect a GUI thread to be quite likely to stall 
> and lock up, and not have time to pop alerts sometimes.

Yes, I meant still take the mask into account, sorry. The feature would have to be used with care but as long as the alerts thread pops ALL the alerts and services them quickly as soon as it wakes there should be no problems. So perhaps it should be marked as "use with care". I will experiment with it tonight, just wanted to get the conversation started.

Also a deadlock is exactly the problem I'm trying to solve. As long as there is a code path that allows for an alert to be missed it can be taken. So right now any program that waits on a specific alert is already broken!

> 
> Note that there is a mechanism already to give certain alerts a higher 
> priority, to still be posted even after the first queue size limit is 
> reached.
> 
> Do you understand why it would take seconds to acquire this mutex? It 
> should be a un-contended. Is it possible that when you use |SCHED_RR| 
> mutexes are not longer fair?

As far as I understand (I may be wrong) normal mutexes are never fair on Linux. As long as as the mutex is not already locked, locking and unlocking is done in userspace (by an atomic swap I suppose). Only when the mutex is already locked it makes a syscall that waits for the mutex to be unlocked by monitoring the page where it is stored.

So if libtorrent's thread is preempted while holding the lock and the thread that pops the alerts gets to run it will miss it's turn because the mutex is still locked. Theoretically this can happen forever. However, under the default policy, everytime the popping thread can't run because the mutex is locked it gets it's priority boosted, so it will be considered for wake up more and more often until it can acquire the mutex. See the SCHED_OTHER section on `man sched` for details:

> The thread to run is chosen from the static priority 0 list based on a dynamic priority that is determined only inside this list.   The  dynamic  priority  is based  on the nice value (see below) and is increased for each time quantum the thread is ready to run, but denied to run by the scheduler.  This ensures fair progress among all SCHED_OTHER threads.

So it's still possible to miss alerts with the default scheduler (I have), just much harder.


> extending that allocation as well, but not under steady state). Are you 
> seeing that taking seconds? Does that mean the scheduler just switches 
> away from the libtorrent network thread for that long?

As far as I understand the problem so far, it means that the libtorrent network thread is going at it and doesn't let the alerts thread acquire the mutex.

> If so, it sounds like you may be running with a bit too much load. 
> what's your typical load average?

Actually it's harder to reproduce under heavy load. On my smallest test system, a raspberry pi zero w, playing 1080p video and decoding audio in software with the CPU constantly at 100% I have not been able to reproduce it once. Simply because libtorrent threads are running at the lowest priority and are severely CPU starved and the CPU intensive sections are not protected by this mutex, so the chances of getting preempted while holding this mutex are slim.

On an `Intel(R) Pentium(R) Dual  CPU  E2180  @ 2.00GHz` with average CPU load of under 50%, connected via ethernet, and using SCHED_RR policy for libtorrent threads, it is very easy to reproduce, even with huge queues and the popping thread at a higher priority (because there is a priority inversion when the popping thread is higher priority).

On similar systems to the one above but using the default scheduler policy it is hard to reproduce but I've been able. Setting aio_threads to 1 seems to make it more likely as in my case it seems to give better throughput.

> (2) sounds pretty complex an probably unwarranted for the common case.

Agreed. And it still leaves a code path open for missing alerts.

> (3) sounds reasonable, maybe a little bit messy and linux (and likely 
> libstdc++) specific.

That would greatly improve things as it will ensure that my thread gets the mutex as soon as it's unlocked (as long as it's already waiting for it). But after some thought, it still leaves some indeterminism because the code path for missing alerts is still open. If the network thread can fill the queue in one time quantum alerts will still be missed. Also I'm not sure it can be done yet. I thought with std::mutex you can destroy and re-initialize the native handle but I haven't tried yet and the only source I found says it can't be done. Also not sure about boost.

 
> I also have this feeling that solving this problem is really sweeping a 
> deeper, more fundamental problem under the carpet. If libtorrent's 
> network thread gets off-CPU for that long at a time, will it really be 
> effective, or will it have odd behaviors in other places too?

On a single core it will result in the network thread being put off CPU for shorter periods because while the alerts thread has a lot of alerts to service it will use it's whole timeslice once it gets the mutex. Even after releasing it it would still be putting it off cpu.

On an SMP system it would only block the network thread for long enough to pop the alerts, after that another core can process them while the network thread runs.

In either case, when the network thread does gets put off CPU, it will be because otherwise alerts would be lost. In the case where the current implementation doesn't miss any alerts a blocking implementation would not block.

I can think of a few use cases that would break if it was enabled by default. But those are really already broken such as a program that unmasks and doesn't pop alerts, or one that waits on a specific alert. A program that only cares about throughput and not about alert reliability could simply leave it turned off and not be affected. I may have something to test tonight or in the next few days.

**Comment by fernando-rodriguez** [comment]
> 1- Do you have enable all bits in the mask of alerts to receive?

I have `lt::alert::progress_notification | lt::alert::error_notification | lt::alert::storage_notification | lt::alert::status_notification`. I think the most frequest is block_finished_alert which I don't use but need others in the same category.

> 2- Can you use master? there is an optimization in should_post() that should help if the mask is not all set

I can't use master atm.

**Comment by fernando-rodriguez** [comment]
[This](https://github.com/fernando-rodriguez/libtorrent/commit/9c99e33fe1b21c37e7c98ad6ba6e9f062aebf18c) is what I'm testing so far. It will deadlock the tests because I have it enabled by default. But if the program is carefully designed to handle alerts quickly like interrupts and doesn't make any synchronous calls to libtorrent's thread from the alerts thread, then it seems to work so far. I'm mostly using alerts to keep track of pieces so servicing them only involves setting a flag and signaling a condition variable, only `received_metadata_alert` needed to be dispatched to another thread because it made some round-trip calls. After that I tested my program with `settings_pack::alert_queue_size` set to 1 and I don't see any noticeable difference in throughput or CPU usage. It is still deadlocking in the session destructor but it's still work in progress...

**Comment by arvidn** [comment]
I understand where you're coming from. Where I'm coming from is to model this problem after things like inotify and syslog. delivery is not guaranteed, just unlikely.

What I've done to mitigate problems is to make certain alerts (that are low volume) to have higher queue size limits. This is the priority field in the alert types. most alerts are dropped once the queue reaches its max size, but alerts with priority 2 will keep being posted until the queue is twice the size of the limit, priority 3 will keep being posted until the queue is 3 times the limit, etc. The alerts that have high priority are the ones that are posted as a direct response to a user call, and that the user is likely to wait for.

So in this model, some ways to mitigate the problem you experience are:

1. put your alert in a different category than ``progress_notification``, as there are a lot of alerts posted when you enable that.
2. increase the priority of your alert, to drop other alerts first, to leave more room for the ones you care about
3. and obviously raise the queue size limit.

I recognise that from a correctness point of view, it's still useful to know that some alerts will never be dropped. Perhaps a feature like that could apply to alerts with high priority only. The obvious concern (which also is a matter of correctness in a way) is that the queue can grow unbounded. I think especially by default that's a risky behaviour.

So, even with a mechanism to never drop certain alerts, I think it's still important to make sure the queue size is kept within reason (with measures like the ones I mentioned above).

I think it may make sense to review some of the high-volume alerts right now, and make sure they still make sense to have at all. For instance, the block_finished alert would normally be very high volume. Perhaps it should just be removed, or split off into a separate category.

> Also a deadlock is exactly the problem I'm trying to solve. As long as there is a code path that allows for an alert to be missed it can be taken. So right now any program that waits on a specific alert is already broken!

I believe that in practice, as long as you only wait on one of the high priority alerts, this is not a problem. Which I'm pretty confident is by far the most common.

> As far as I understand (I may be wrong) normal mutexes are never fair on Linux. As long as as the mutex is not already locked, locking and unlocking is done in userspace (by an atomic swap I suppose). Only when the mutex is already locked it makes a syscall that waits for the mutex to be unlocked by monitoring the page where it is stored.

I think you're right there are not fairness guarantees. I would expect though that if the user-space compare-and-swap operation fails and you need to go to the kernel, your thread would (normally) be put on a queue and woken up in the order you got in line.

> So if libtorrent's thread is preempted while holding the lock and the thread that pops the alerts gets to run it will miss it's turn because the mutex is still locked. Theoretically this can happen forever.

It seems extraordinary that this would happen by chance though. As I think the amount of work libtorrent does while holding the mutex is quite small. But I suppose with ``progress_notification``, there may be a very large number of calls.

> Also I'm not sure it can be done yet. I thought with std::mutex you can destroy and re-initialize the native handle but I haven't tried yet and the only source I found says it can't be done. Also not sure about boost.

Oh, I see. I thought you could change this property on an existing ``pthread_mutex``, but you can only set it on construction?

**Comment by fernando-rodriguez** [comment]
I think there is a way to make the alerts reliable without any changes to libtorrent. The way my alerts thread is designed I think I could just use the callback function to pop and process the alerts from libtorrent's thread before the queue fills up and do away with the alerts thread. I will try it soon. If I'm thinking this right it will have the same effect of having a blocking implementation minus the context switches and thread synchronization.

**Comment by fernando-rodriguez** [comment]
It almost feels like the notify callback was designed just for this use case. I need to process the alerts one at the time since the notification is only called the first time but it's working great so far and I don't think there's much to gain by queueing them. A nice optimization now would be to be able to completely disable the alert queue since it's just overhead for my use case.

> I think you're right there are not fairness guarantees. I would expect though that if the user-space compare-and-swap operation fails and you need to go to the kernel, your thread would (normally) be put on a queue and woken up in the order you got in line.

Yes. That is what I understand. But the thread won't be eligible for wake up until the mutex is unlocked so the thread that owns it (and perhaps others) needs to run again. I'm no longer affected by this but another simple thing you can do to minimize contention is to call `sched_yield()` while the mutex is unlocked some time before the queue fills up to give any thread waiting a chance to run. I don't know why I didn't thought of this before.

> It seems extraordinary that this would happen by chance though. As I think the amount of work libtorrent does while holding the mutex is quite small. But I suppose with progress_notification, there may be a very large number of calls.

Some of the worst cases (at one point I missed an alert with a 100000 sized queue) happened early on and I now realize they could be explained by the metadata_received_alert that I was handling in the alerts thread but with a 1000 size queue I was missing alerts at times when the alerts thread was just waiting. I think if it happens at the wrong time when the libtorrent thread is just pumping alerts (when it's most likely to happen) that the alerts thread only needs to be blocked a few cycles before the queue is filled.

**Comment by fernando-rodriguez** [comment]
The documentation of `set_alert_notify()` states:

> The actual retrieval of alerts should not be done in the callback. In fact, the callback should not block. It should not perform any expensive work. It really should just notify the main application thread.

Unless I'm missing something, this should be reviewed because popping the alerts in the callback function should never block, except in the case where it's called from `set_alert_notify()` itself and that won't have any effect on libtorrent's thread. Do you see any other issues with popping the alerts and doing the work in the handler if it's cheap and dispatching it to another thread otherwise?

**Comment by arvidn** [comment]
It used to be the case that calling any public libtorrent API function from within libtorrent itself would dead-lock. either because the one mutex was held, as in the original implementation, or that the call was posted onto the message queue and then blocking that same message queue by waiting for the response. These days it's a bit safer because the calls into the API use ``dispatch()`` rather than ``post()``, which means the message is allowed to be executed immediately in case it's made from the thread running the message queue.

i.e. with the current implementation it's OK to pop the alerts and do some cheap handling of them. I'm hesitant to make this guarantee in the API though, as there may be future implementations that would benefit greatly from not supporting it. It's also not ideal to handle a single alert at a time (in the general case).

**Comment by fernando-rodriguez** [comment]
> It used to be the case that calling any public libtorrent API function from within libtorrent itself would dead-lock.

That is still the case, at least some calls still may cause deadlock. But I'm not arguing for that, just popping the alerts.

> i.e. with the current implementation it's OK to pop the alerts and do some cheap handling of them. I'm hesitant to make this guarantee in the API though, as there may be future implementations that would benefit greatly from not supporting it. It's also not ideal to handle a single alert at a time (in the general case).

I don't think you gain anything performance-wise out of queing alerts. It just de-couples the user from libtorrent allowing the library to keep working regardless of what the user does. But it actually has a performance cost.

Consider that most use cases receive alerts that they don't care about. Everytime you post an alert if there's a thread waiting for it becomes runnable and there is a context switch to it. On linux it needs to lock the mutex before `pthread_cond_wait()` returns. If there is contention there will be another context to your thread and back plus whatever cost is associated with the contention. Then it needs to lock the mutex again to pop the alerts, there may be contention again and two more context switches. Then there's another context switch back to libtorrent's thread. All this is for nothing because the user just threw away the alerts!

Likewise all the most frequent alerts are usually very quick to handle, so there's no need for all those context switches and mutex contention. Most use cases for these frequent alerts will benefit from less context switches and better cache usage, etc by inlining then.

When there's an alert that cannot be inlined under this model it would be the user responsibility to enqueue it for another thread to process. Some alerts may have cheap and expensive parts so the user may inline the top half and dispatch the bottom half to another thread, etc. It would add a lot of flexibility.

Does that makes sense? Maybe there could an option just for that. Perhaps a callback that bypasses all queuing and passes the alert to the handler as an argument.

**Comment by fernando-rodriguez** [comment]
I was looking at the plugin API and I think I came up with a small change that will make the  notifications sent to the session plugin's on_alert() callback reliable. Something along the lines of [this](https://github.com/fernando-rodriguez/libtorrent/commit/616e9ab612935a7bd70e9d4f91fd3d4db41e71e4). I just did that now so it's completely untested. I need to write the extension to test it.

First I removed the queue size check from `should_post`. It should be optimized out anyways if `emplace_alert` is called right after it so it has no effect. Then on `emplace_alert` when the queue is full I still call maybe_notify(). I'm using a new `aux::stack_allocator` for the alert in this case so it gets freed right away. If there is no session plugin this change has no effect except for a wasted allocation after the queue is full but that can be solved by modifying `stack_allocator` to support using the stack instead of a buffer. What do you think? When relying exclusively on this method to get alerts `alert_queue_size` could be set to 0 to completely disable queueing.

**Comment by fernando-rodriguez** [comment]
Updated [link](https://github.com/fernando-rodriguez/libtorrent/commit/1eb48e48de59a86c140b7283333636756018a14f) with fixed compile error.

**Comment by fernando-rodriguez** [comment]
Perhaps the check on `should_post()` should be removed regardless of whether you want to make this change because it's an optimization (a tiny one I think) that only kicks in when the queue is overrun. If we remove that check `should_post()` can be made lockless so it will alleviate the contention issue.

It may also be the source of bugs, for example in torrent.cpp on RC_1_1 near line 3366 if the comment is correct the intention there is to check that the alert is not masked but it's actually also checking that the queue is not full. I don't know enough about what's going on to say it's a bug, I'm just going by the comment.

**Comment by arvidn** [comment]
it's true that the check at torrent.cpp:3366 is intended to just check the mask, and I appreciate `should_post` being lockless. Perhaps I've been overly concerned about the case where the queue is overrun. It does seem reasonable to optimise for the case where it isn't
