### ISSUE TITLE
File prioritization error handling

### ISSUE THREAD

**Issue by d-komarov** [arvidn/libtorrent#2945]
libtorrent branch: RC_1_1
platform/architecture: Any
compiler and compiler version: Any

In case of error in `default_storage::set_file_priority`, torrent and storage file priorities will go out of sync.
Difference in storage/torrent file priorities will cause new piece blocks to be written to the part file.

I suggest that torrent should handle `set_file_priority` errors to avoid part file writes. At least torrent could notify user about file prioritization errors, if it's a problem to handle that kind of errors internally.

**Comment by arvidn** [comment]
Only two solutions come to my mind.

1. make the ``set_file_priorities`` disk job be all or nothing. If anything fails, roll back and don't apply the new priority to any files.

2. make the callback to ``set_file_priorites`` return back the file priorities it ended up with, allowing it to fail half-way through without rolling back.

Neither seem particularly appealing, but (2) is probably simpler.

**Comment by arvidn** [comment]
@d-komarov Do you have any opinion about which approach you think is better, of (1) and (2)?

implementing (2) requires a slight change in the ABI of the `storage_interface`, which probably isn't a big deal. I don't think that many implement a custom storage, but it feels a bit bad for a point-release.
(this is required so that the `storage_interface::set_file_priority` has a non-const reference to the priorities, so it can output the actual priorities it managed to establish)

Approach (1) seems complicated and not really be desirable behavior either.

**Comment by arvidn** [comment]
@d-komarov does this look reasonable? https://github.com/arvidn/libtorrent/pull/3056
