### ISSUE TITLE
[feature reqest] BEP22 in libtorrent

### ISSUE THREAD

**Issue by xcme** [arvidn/libtorrent#30]
Hello!

I opened the [issue](https://github.com/qbittorrent/qBittorrent/issues/3404) for qBittorrent about [BEP22](http://bittorrent.org/beps/bep_0022.html) and received the answer that BEP22 must first be implemented libtorrent.

Any chance that the [extension](http://bittorrent.org/beps/bep_0022.html) will be implemented in new versions libtorrent?

An [older issue](https://code.google.com/p/libtorrent/issues/detail?id=220) is still open...

**Comment by arvidn** [comment]
hi. Do you know if BEP22 is still enabled by default in uTorrent? At BitTorrent Inc. I don't recall we ever heard from anyone relying on this feature. We added it for a specific client, and as far as I know it was never picked up. my point is that BEP22 has not been receiving any attention in uTorrent either (because it didn't seem anyone relied on it). It's good to hear that it's useful.

It is quite a bit of work to implement bep22 cross platform though. Specifically performing reverse DNS lookups and reading SRV records require platform specific APIs.

**Comment by xcme** [comment]
Yes, I know that uTorrent uses BEP22. But it would be convenient that other programs could use it.

For the sake of objectivity I did some research on my network. I turned off BEP22 and waited for a few days. Average number torrents in retracker-database decreased on average by 13 percent. At this time in my database not been programs such as MediaGet, Zona, etc. Thus, it seems that mostly BEP22 used them. However, 13% is a good result. That's the number torrents without a built-in 'retracker.local' downloaded on my network via uTorrent.

**Comment by xcme** [comment]
![bep22stat](https://cloud.githubusercontent.com/assets/10675508/8913419/af12bcf6-34a1-11e5-9519-6fd4c3516c10.png)

After 5 days of testing, I turned on BEP22. As seen in the screenshot, the number of torrents are increased again. Blue lines - Min and Max when BEP22 was turned off. Red lines - Min and Max when BEP22 was turned on.


Thus, the use of BEP22 useful for my network. :)

**Comment by arhue** [comment]
Would like to see this implemented as well. This is very important for me and is the only way to cache torrent traffic without having to rely on commercial solutions+policy based routing.

**Comment by xcme** [comment]
More than 6 years have passed since the [original ticket](https://code.google.com/p/libtorrent/issues/detail?id=220). We are still waiting and hoping. :)

**Comment by arvidn** [comment]
patches are welcome
