### ISSUE TITLE
Spurious transition to downloading state when adding a completed torrent

### ISSUE THREAD

**Issue by ssiloti** [arvidn/libtorrent#3042]
libtorrent version (or branch): RC_1_1

platform/architecture: windows x86

compiler and compiler version: msvc 14.14

1c867a50263cf2243442bfc01a2b731e87c7be81 introduced an extra transition to `torrent_status::downloading` in-between `checking_resume_data` and `finished` when adding a torrent which is already complete. This means it is no longer possible to tell if a `state_changed_alert` to the `finished` state is for a torrent which just finished downloading or for one which was already complete when it was added.

Specifically [this](https://github.com/arvidn/libtorrent/blob/5f74b6e35328a07e2b2544a24c802c7cea02dd32/src/torrent.cpp#L4423) check prevents the torrent from transitioning to `finished` before `torrent::files_checked` is called which then sets to state to `downloading`.

**Comment by Seeker2** [comment]
Sounds related to this:  https://github.com/qbittorrent/qBittorrent/issues/6137
"Since the torrent is technically active while being force checked, it can even connect to peers/seeds and download/upload parts of the torrent."

**Comment by arvidn** [comment]
@ssiloti I don't recall all the details around that patch off-hand. I'll have to dig a little bit. But I think that was an attempt to simplify the state flow. I think it was in response to finding an error caused by some subtle unexpected state or transition.

I think it's right that the torrent shouldn't be set to finished until `files_checked` is called. But maybe there's a way to defer changing the state to downloading until we know we're not finished. I imagine the state remains in checking_resume_data instead.
