### ISSUE TITLE
[Feature Request] upload / seed priority

### ISSUE THREAD

**Issue by LGY90** [arvidn/libtorrent#307]
Hello, I am not sure if this is the right place for feature request, but I would like to suggest having priority for upload/seed just like for download. This would be very useful for automatically ensuring rare file can spread faster, private tracker seeding goal can be met, etc.

**Comment by arvidn** [comment]
can you describe in more detail the behavior you're looking for?

**Comment by LGY90** [comment]
For download, you can assign priority number to torrents to guide bandwidth allocation. It would be nice to have this (or something similar, like categorizing into high/medium/low priorities) for upload as well, so that one can have automated optimization of upload bandwidth.

**Comment by arvidn** [comment]
I think you may be under-estimating the problem of balancing bandwidth. despite it appearing so from a user's point of view, there's no such this as a connection's "capacity" to be divided up across torrents and peers.

The true capacity is constantly fluctuating and defined by the average rate of packets you can push given a certain congestion control algorithm. This becomes more clear with uTP in the presence of variable cross traffic (say, web browsing).

Let's say you determine your capacity as the number of bytes you've sent in the last 5 seconds divided by 5. You have two torrents you're seeding and one has twice the weight as the other. So you split the capacity in 1/3:rd and 2/3:rds respectively.

Now imagine that the torrent getting 2/3:rds of the capacity has a shortage of peers, there are only 2 other peers on that swarm, and they have really shitty connections. Those 2/3:rds capacity you allocated to this torrent can't actually be used by them, together they can only receive 1/3:rd of your capacity.

Problem 1: what do you do with that remaining 1/3:rd of upload capacity? You want to re-allocate it to some other torrent, how long do you wait until you determine that you have accurately measured the rates?

Problem 2: If you react too quickly, you will have multiple layers of control loops interacting in unpredictable ways (the transport protocol's congestion control and the 5 second timer to determine capacity). In order to layer control loops, they need to be operating at significantly different time scales, so the answer must be much more than 5 seconds.

Problem 3: If you don't react fast enough, the next cycle, your "capacity" will drop significantly (because you only used 2/3:rds of your capacity, and the sampling of your capacity will now be much lower). How do you determine that the lower capacity was caused by inadequate bandwidth allocation versus you actually having less capacity now? (your capacity may be lower if there's bad weather and you use radio or old cabling or your DSLAM ring being congested or you just having cross traffic causing congestion on your modem).

This last one really is the killer. There is no way to tell the difference between your upload capacity causing congestion and your peers' download capacity causing it. You can have various heuristics, and you have to be very careful about the lengths of your control loops and you're likely to cause more harm than good, unless you have very good testing facilities or very accurate simulations.

If you have any specific ideas of exactly how you would like priorities to be used, I'd be interested to hear. The closest I can think of would be to scale the target delay in uTP (which would not work over TCP clearly).

The assumption is that the bandwidth division between sockets is linearly proportional to their target delay, but that's probably a paper's worth of work in itself. (which also could lead to neat things like proportional bandwidth sharing instead of choke-slots)

**Comment by bostrr** [comment]
Hi I came here looking more or less for the same thing. I have many torrents for which I'm the only seeder or close to.
Whenever I monitor the client I find myself pausing many strong torrents to allow the weak ones some bandwith because very often they just stay stuck for quite a while with 1 seed and a couple of peers.

What you say arvidn makes sense, but if the problem is not knowing the amount of bandwith to allocate to each high/low priority torrent why not just order the "torrent seeds list" by seed/peer number and give priority to the with less, let it soak the bandwith or up to a per individual torrent limit, then the next, and so on. Maybe one could also choose at several points down the list.

This could be a mode to be set by the user.

Then again I could be completely misinterpreting how the whole thing is managed.

**Comment by arvidn** [comment]
for auto managed torrents that are seeding, there is prioritization based on the number of peers and seeds on the swarm, prioritizing torrents with a high peer:seed ratio. In libtorrent this is called *seed rank*. A higher rank means more likely to be seeded. The specific logic is [here](https://github.com/arvidn/libtorrent/blob/RC_1_2/src/torrent.cpp#L8370).

It essentially doesn't kick in until the configured seed ratio is met though.Similarly, if there are no seeds at all on a swarm, that takes precedence. Also, torrents that were just started also take precedence, to avoid flapping.

**Comment by bostrr** [comment]
Oh but if it's already giving priority to the higher peer/seed ratio torrents then there is a problem because I have several torrents which I am the only seeder, there are peers, I'm connectable, and I have bandwith to spare. Maybe it's the peers that are not initializing the transfers?

**Comment by arvidn** [comment]
> I have several torrents which I am the only seeder, there are peers, I'm connectable, and I have bandwith to spare. Maybe it's the peers that are not initializing the transfers?

Are you sure there are other peers, that are interested in downloading anything?
If they aren't connecting to you, it would suggest there aren't any. Is this based on the scrape data?

**Comment by bostrr** [comment]
Mainly based on the scrape, is it prone to being incorrect?

**Comment by arvidn** [comment]
I think the reliability depends a bit. if you have a single tracker, that's reliable (i.e. doesn't go down regularly) and maybe is a private tracker; it's probably pretty reliable. Otherwise it may not be.

However, if there are peers that have "paused" the download - for example by only selecting certain files for download - they may count as "peers" but not "seeds" even though they are not interested in downloading anything more. At BitTorrent Inc. we came up with an [extension](http://bittorrent.org/beps/bep_0021.html) for this case, but we did not propose a change to the scrape data to reflect it. It was primarily geared towards making the tracker able to return better peers.
