### ISSUE TITLE
Unable to force recheck or resume | Reopen --> https://github.com/arvidn/libtorrent/issues/169 ?

### ISSUE THREAD

**Issue by lev777** [arvidn/libtorrent#3134]
**Please provide the following information**

libtorrent version (or branch):
1.1.7.0 (qBittorrent 4.1.0)

platform/architecture:
Windows x64 (32bit qbittorrent)

compiler and compiler version:
Qt: 5.6.3
Boost: 1.67.0

please describe what symptom you see:
Unable to force recheck or resume several torrents
- Force recheck gives constantly restarting hash check (pausing during check gives randomly completed percentage)
- Resume causes status to switch rapidly between "Checking" & "Checking resume data".  Done percentage flashes increasing progress momentarily before returning to zero and then repeating over and over

what you would expect to see instead:
force recheck should be able to ignore resume data and successfully complete a hash check which would identify any missing pieces based on what is on the disk

and how to reproduce it:
I lost my download location drive after a reboot and torrents which where completed resumed and started updating.  I paused most of the torrents to attempt to prevent the updates.  Most were fine after returning the drive to a healthy status, but several got updated and are now stuck in an unusable state.  In some cases the same torrent is seeded to multiple trackers - one is in unusable status but the same data is fine on the others.

other info:
I see this in the log for one of the problem torrents:  

_Couldn't save resume data in C:/Users/Me/AppData/Local/qBittorrent/BT_backup/(torrenthash).fastresume. Error: Access is denied._  

I deleted the .torrent and the .fastresume, & redownloaded the .torrent but it still cannot resume.  I tried moving the files to another disk location and it still cannot resume.

To make it even stranger - a new torrent I just created and attempted to seed is also doing this --> status switching rapidly between "Checking" & "Checking resume data".  Done percentage flashes increasing progress momentarily before returning to zero and then repeating over and over :( 

Partial Workaround for old torrents: **If** there is another seed - delete a file from the torrent data and force recheck.  Recheck will be able to succeed & then Resume can download missing data and also succeed.

**Comment by lev777** [comment]
Reverting back to qBittorrent v3.3.16 allows hash checks to report proper status of files on disk

**Comment by arvidn** [comment]
what alerts do you get exactly. can you provide a log with a single torrent exhibiting this?

**Comment by lev777** [comment]
There are no alerts - only the symptoms I described.  There is nothing logged during the hashing Force recheck nor during the Resume attempts.  Is there a way to enable logging of those processes?

**Comment by lev777** [comment]
I posted [here](https://qbforums.shiki.hu/index.php/topic,6108.msg28657.html#msg28657) as well.  Not heard a whisper back so far.

**Comment by lev777** [comment]
The issue was confirmed by someone else in the thread on the qbittorrent forums, but still no word from devs yet on how to troubleshoot further.

**Comment by erasmux** [comment]
This has nothing to do with my [wishlist] request (on the qbittorrent forums).

I have not seen any such behavior with recent qbittorrent versions (I can't be sure about 4.1.0 because that one is not recent enough for my decaying memory). I do remember that around version 4.1.0, each time qbittorrent was not properly shutdown it would starts rechecking many or even all of the torrents and with recent libtorrent/qbittorrent versions this has been fixed (at least for me).

To me this sounds like a problem with multiple torrents with slightly different data referencing the same data on the disk. Try the following:
1. Pause all torrents (or at least all torrents referencing a specific set of files on the disk).
2. Recheck a single torrent and verify the recheck completes to 100%. If it does all is good (do NOT start the torrent yet, leave it paused).
3. If the recheck fails, resume only this torrent and let it complete to 100% and then pause it again. Now recheck again *all* other torrents referencing the same files on the disk (one by one and with all torrents paused).

Notice that if you're not very careful, it is quite easy to reach the point where multiple torrents reference the same files on the disk even if some of the torrents have slightly different data. As long as the pieces which have a mismatch are not requested (and your HD doesn't disappear...), qbittorrent/libtorrent will not notice this and everything will seem fine. A common case for such an example is a mismatch on the .nfo file (which can easily be actively seeded without receiving a request for the nfo file since it is so small).

In such a case you, when the problem finally does surface (i.e. because of a recheck), it could cause behavior similar to what you are describing. At least from my experience, recent libtorrent/qbittorrent versions behave as well as can be expected in such extreme cases.

**Comment by lev777** [comment]
@erasmux my current cases are single seeded torrents, so no, your assumption about seeding multiple torrents differently is incorrect for my cases.  The recheck does not recognize what is on the disk. Re-running it does not change the progress indication.  If it starts at 1% or 5%, it stays there after recheck.  Even though the data passes is as complete as it was when it was fully downloaded.  If the data is not cross-seeded the only way I have found to recover is redownloading or recreating the torrent.

**Comment by Shadowhwk** [comment]
I'm not able to delete any files to try the workaround as items are usually single file downloads. That would defeat the purpose of re-adding/re-creating the torrents as I only want to continue seeding the completed files. As you mentioned in my issue #10640, I will try to look at the logs to see if I can find anything helpful. I still find it interesting that thalieht closed issue #8917 on Mar. 24, 2019 and said the issue will be fixed in 4.1.6. Prior to build 4.1.6 I was able to use force-recheck successfully on other files that had their status corrupted. Is it safe to downgrade to 4.1.5 which had been working fine? I'll also look into the fastresume and parts files as I mentioned in my issue.
