### ISSUE TITLE
Does not close completely in Windows 8.1 Pro

### ISSUE THREAD

**Issue by jpBenfica** [arvidn/libtorrent#316]
After closing is running in the background on the task manager, for a few minutes.

**Comment by arvidn** [comment]
I assume you mean the session destructor doesn't return, is that right?
Do you know what the main thread and disk thread are doing?
Could you build with asio-debugging=true and reproduce it? That should print out the shut-down state to the terminal, while shutting down. It should pin-point what's blocking.

**Comment by jpBenfica** [comment]
After close qBittorrent, utorrent or Bittorrent,all programs running in the background for a few minutes.

**Comment by c0ff** [comment]
Hi!
I've got the same behavior (Win 8.1Pro as well) but cant reproduce it consistently - no luck today at all.
I had a process under the debugger when it freezed, unfortunately don't have a stack trace but still:
when entering the session destructor in my app:
- all torrents have beed removed (i've got  torrent_removed_alert for all the torrents)
-  session::pause() have been just called

then the destructor appears to never exit, if I break it in the debugger it always stops at the same place:
boost::asio::detail::thread_info_base::allocate(thread_info_base* this_thread, std::size_t size):
   ...
      ::operator delete(pointer);   <-- here. always (like 10 times in a row)
    }
But the ::delete is not freezed it returns and all the code seems to work. but either too slow (fragmented heap?) or too many times (too many alloc/dealloc cycles?).

**Comment by arvidn** [comment]
I would expect the main thread to be blocked in delete (or whichever way the session destructor is invoked). It's the other threads that are interesting. Or really, it's the asio outstanding handler state, which is printed when built with asio-debugging=on

**Comment by c0ff** [comment]
Typical stderr output seems to be like this:
uTP sockets left: 4
uTP sockets left: 1
uTP sockets left: 1
uTP sockets left: 1
uTP sockets left: 1
uTP sockets left: 1
uTP sockets left: 1
uTP sockets left: 1
uTP sockets left: 1

EXPECTS NO MORE ASYNC OPS

**Comment by c0ff** [comment]
One of the clients got the issue, here's the async.log. The stack trace part seems to be useless, because of it's from an optimized release build.

libtorrent log_async:
broadcast_socket::on_receive: (27)
1: <unknown>
2: <unknown>
3: <unknown>
4: <unknown>
5: <unknown>
6: <unknown>
7: <unknown>
8:yŠ4M†
session_impl::on_accept_connection: (2)
1: <unknown>
2: <unknown>
3: <unknown>
4: <unknown>
5: <unknown>
6: <unknown>
7: <unknowyŠ4M†
udp_socket::on_read: (2)
1: <unknown>
2: <unknown>
3: <unknown>
4: <unknown>
5: <unknown>
6: <unknown>
7: <unknown>
8: <unknown>yŠ4M†
log_async total_refs: 31
