### ISSUE TITLE
SSL torrents won't work when binding to normal port fails

### ISSUE THREAD

**Issue by waikontse** [arvidn/libtorrent#3262]
**Please provide the following information**

libtorrent version (or branch):
1.1.6
platform/architecture:
FreeBSD 11/AMD64
compiler and compiler version:
LLVM 6.0
please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

**What I see:**
binding to normal port e.g. 600 fails, and binding to ssl port 610 succeeds but no alert is given.
```
0.0.0.0:600 failed: [open] [TCP] Operation not permitted
0.0.0.0:600 failed: [bind] [UDP] Operation not permitted
```
When I try to see if there is a listening process on port 610 with 'sockstat -4 -l', I see both TCP and UDP.
So when I try to connect to the peer, I get "connection closed by peer" thrown via libtorrent alert and via netstat -Aan I see *connections* with "CLOSE_WAIT" and "FIN_WAIT_2".

**What I expect to see:**
Even when binding to the normal listen port fails, binding to the ssl port should succeed.
```
0.0.0.0:600 failed: [open] [TCP] Operation not permitted
0.0.0.0:600 failed: [bind] [UDP] Operation not permitted
successfully listening on [SSL/TCP] 0.0.0.0:610
successfully listening on [SSL/uTP] 0.0.0.0:610
```

**How to reproduce:**
On FreeBSD I use mac_portacl to control access to  ports, but on Linux, I think the fastest way to reproduce would be to use a privileged port as the normal port to listen on, and some random port number outside the priviliged port range for ssl_listen.

**Comment by arvidn** [comment]
in libtorrent 1.1.x, the logic for opening listen sockets is fundamentally based on the assumption that there will be a single listen socket. All support for multi-home and multiple listen sockets is hacked in (and I'm not surprised it has issues like this). in `master` it has been significantly cleaned up (by @ssiloti) to have more native support for multi-homed machines (as well as just having multiple listen sockets).

If this turns out to be too complex to fix, I may defer it for the next major release.
