### ISSUE TITLE
Any benefit to upgrading libtorrent past 1.0.11?

### ISSUE THREAD

**Issue by restalfep** [arvidn/libtorrent#3293]
I've seen a lot of posts online about how libtorrent above 1.0.11.0 seems to introduce new problems, use more CPU resources, etc. I'm currently on Pi 3 and using deluge 1.3.15, is there any benefit to updating the libtorrent or deluge clients or if everything seems to be working alright would it be advised to leaving it as-is? 

Currently I followed a tutorial online to put  a "hold" on libtorrent so it won't update unless I remove the hold. Just curious if upgrading could improve efficiency, load, speeds, etc.

**Comment by arvidn** [comment]
you should probably compare the number (and severity) of comments to the ones about upgrading from 0.16 -> 1.0 and probably from 0.15 -> 0.16 as well, to get a benchmark.

Most significant changes are mentioned in the [changelog](https://github.com/arvidn/libtorrent/blob/RC_1_1/ChangeLog).

for example:

* added support for hashing pieces in multiple threads
* added support for asynchronous disk I/O
* added support for adding torrents asynchronously (for improved startup performance)
* optimized piece picker
* optimized disk cache
* optimized .torrent file parsing
* optimize peer connection distribution logic across torrents to scale better with many torrents
* replaced std::map with boost::unordered_map for torrent list, to scale better with many torrents
* improved disk cache complexity O(1) instead of O(log(n))
* support for partfiles, where partial pieces belonging to skipped files are put
* pre-emptively unchoke peers to save one round-trip at connection start-up.
* support specifying listen interfaces and outgoing interfaces as device names (eth0, en2, tun0 etc.)
* optimize UDP tracker packet handling
* support SSL over uTP connections
* support web seeds that resolve to multiple IPs
* cancel non-critical DNS lookups when shutting down, to cut down on shutdown delay.
* improve support for HTTP where one direction of the socket is shut down.
* improve piece picker to better support torrents with very large pieces and web seeds. (request large contiguous ranges, but not necessarily a whole piece).
* improve piece picker support for reverse picking (used for snubbed peers) to not cause priority inversion for regular peers
* replaced lazy_bdecode with a new bdecoder that's a lot more efficient
* experimental support for BEP 38, "mutable torrents"
* add option to not proxy tracker connections through proxy
* improve DHT performance when changing external IP (primarily affects bootstrapping).
* fix duplicate ACK issue in uTP
* improved Socks5 support and test coverage
* added limited support for new x.pe parameter from BEP 9
* fixed crash on invalid input in http_parser
* fix issue where FAST extension messages were not used during handshake
* optimize allow-fast logic
* fixed inverted priority of incoming piece suggestions
* move files one-by-one when moving storage for a torrent
* fix filename escaping when repairing torrents with broken web seeds
* fix piece picker bug that could result in division by zero
* fix bug in last-seen-complete
* fix socks5 support for UDP
* fix move_storage() to its own directory (would delete the files)
* fix file rename issue with name prefix matching torrent name
* add feature to periodically close files (to make windows clear disk cache)
* add support for IPv6 peers from udp trackers

there are a bunch of other bug fixes too.

**Comment by cas--** [comment]
I am the Deluge dev and the main problems were with early 1.1.x releases that were not backwards compatible with Deluge but the very latest 1.1 releases are more stable so you can see how you go if you wish. 

The reason for caution with upgrading libtorrent is that Deluge 1.3 old code now and based on libtorrent releases going back to lt 0.15 and with each new major libtorrent release is it less likely to be compatible. So we knew it works well with 1.0 and advised that major version so you don't run into issues.

**Comment by mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls** [comment]
Don't upgrade> 1.0.11, this version is the most perfect I have ever used!

**Comment by arvidn** [comment]
@mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls would you care to elaborate?

both compared to 1.1.x and 1.2.x

**Comment by mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls** [comment]
> @mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls would you care to elaborate?
> 
> both compared to 1.1.x and 1.2.x

I have used both 1.1.X and 1.2.X, and the download speed is not as fast as 1.0.X, but it takes longer to accelerate. In addition, the performance requirements of 1.1.X and 1.2.X are stronger, and they are not suitable for my arm platform. Work, there are more bugs. After 1.1, if the seed exceeds 500+, there will be a high probability that the client cannot be connected!
