### ISSUE TITLE
`dht_direct_request` not python binding ?

### ISSUE THREAD

**Issue by joriscarrier** [arvidn/libtorrent#3307]
libtorrent version (or branch): 1.1.9

platform/architecture: python bindings

Hello, i have a simple question:
why `dht_direct_request` have not python bindings ?

thank you in advance.

**Comment by ssiloti** [comment]
It's missing because nobody has cared enough to add it. A regular bittorrent client has no use for manually sending DHT messages. The function was added for use by plugins, specifically [libtorrent-reputation](https://github.com/ssiloti/libtorrent-reputation).

If you have an application which needs it you can submit a pull request to add a binding for it.

**Comment by devos50** [comment]
I would like to use `dht_direct_request` from Python to have our torrent application Tribler fetch torrent health information from the DHT. See also #3701 👍

**Comment by arvidn** [comment]
@devos50 at a second thought, I'm not sure exposing this to python is a very good approach to do DHT scraping. It would be a lot better to built proper support for scraping as part of querying for peers. The bloom filters should be interpreted and turned into numbers and posted as an alert too I think.
