### ISSUE TITLE
[cmake] Build both static & shared library in the same run

### ISSUE THREAD

**Issue by Chocobo1** [arvidn/libtorrent#3439]
**Please provide the following information**

libtorrent version (or branch):
RC_1_1 latest

platform/architecture:
Arch Linux

compiler and compiler version:
gcc 8.2.1
cmake 3.12.4

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

This is more like a wishlist, currently to build a static library, one need to issue `cmake ./ -DBUILD_SHARED_LIBS=OFF && make`, and to build a shared lib another `cmake ./ -DBUILD_SHARED_LIBS=ON && make`, this takes 2x time. While in autotools, both libraries are built in the same run.

A quick google shows this: https://stackoverflow.com/a/29824424

**Comment by arvidn** [comment]
I would expect you to have to compile all translation unit twice normally though. once with `-fPIC` and once without (at least on linux).

**Comment by Chocobo1** [comment]
I see, one would argue if the performance benefits of no PIC is minimal then why bother, just use PIC in both library, but I haven't able to see such benchmarks on the net, I guess it varies for different projects...

**Comment by arvidn** [comment]
I think the main cost comes from the PLT (which introduces an indirection for every function call that's not hidden) and the GOT (at least on 32 bit architectures, it's a lot cheaper on 64 bit).

I think most of that can be mitigated by building with `-fvisibility=hidden`.

Nowadays executables are built with `-fPIE` somtimes too (position independent executable) to support address space randomization. I think that has most if the same requirements as `-fPIC`.

iirc, on darwin everything builds with PIC by default (and windows relocates code instead of building position independent code).
