### ISSUE TITLE
Always create empty file

### ISSUE THREAD

**Issue by prodigalsword** [arvidn/libtorrent#3480]
```cpp
int main()
{
    add_torrent_params params;
    params.ti = boost::make_shared<torrent_info>(R"(C:\Users\Administrator\Downloads\b5d50c023c7fa8c70275cd341dbcef5a95747e52.torrent)");
    params.save_path = R"(C:\Users\Administrator\Downloads)";

    session session;
    auto handle = session.add_torrent(params);
    session.pause();

    ::system("pause");
}
```

As you see, I haven't started downloading it yet, but it always create empty file within this torrent in my local dist. Why?

**Comment by arvidn** [comment]
you add the torrent to the session, that means you started downloading.
If you want to add the torrent without starting to download, you have to set the `paused` flag and clear the `auto_managed` flag

**Comment by prodigalsword** [comment]
@arvidn Thank you for your reply. I've done as you say, but empty file is still be created. I think that's a bug, can you test this torrent file?

**Comment by arvidn** [comment]
I'm sorry, my first response was done a bit hastily. The way libtorrent works right now is that, regardless of whether downloading starts or not, when a torrent is added, its internal storage object is initialized. It will check for existing files and load resume data for example. One of the things it does during initialization is to create empty files. Since empty files don't participate in any other disk activity, there's no obvious other time to trigger their creation.

I take it you would expect the empty files to be created when the torrent is taken out of the *paused* state. From the storage object's point of view though, it's created, resume data is checked and then blocks are being read and written. It doesn't know (or mostly care) about the state of the torrent.

Triggering file creation on resuming would also possibly cause the file creation to run multiple times, each time the torrent is paused and resumed.

**Comment by prodigalsword** [comment]
```cpp
int main()
{
    add_torrent_params params;
    params.flags = add_torrent_params::flag_paused;
    params.ti = boost::make_shared<torrent_info>(R"(C:\Users\Administrator\Downloads\b5d50c023c7fa8c70275cd341dbcef5a95747e52.torrent)");
    params.save_path = R"(C:\Users\Administrator\Downloads)";

    session session;
    auto handle = session.add_torrent(params);
    for (auto i = 0; i < handle.torrent_file()->num_files(); ++i)
    {
        if (i != 57)
        {
            handle.file_priority(i, 0);
        }
    }
    handle.resume();

    ::system("pause");
}
```

As you see,  file with index 57 is which I want to download, but the empty file which in the torrent is still be created, it's not my expection.

**Comment by arvidn** [comment]
you're setting the file priority *after* adding the torrent. In theory, it's possible for all files to have been downloaded by the time you change the priority.

Try to set the file priority directly in `add_torrent_params` instead, to avoid the race.

**Comment by prodigalsword** [comment]
I can't find the priority setting interface within add_torrent_params struct.

**Comment by arvidn** [comment]
https://libtorrent.org/reference-Core.html#file_priorities

**Comment by prodigalsword** [comment]
@airium It's OK. Thank you very much.
