### ISSUE TITLE
torrent recheck does not truncate files

### ISSUE THREAD

**Issue by ajax16384** [arvidn/libtorrent#3489]
libtorrent version : master
platform/architecture: windows

repro sequence:
- download some torrent
- stop torrent and delete resume
- append some garbage to one of torrent content files (e.g. append 1 byte to the end of file)
- add torrent using folder with modified content
- torrent starts to check hash
- hash check finishes without error
observe: modified content with extra garbage data
expected: file truncated to torrent description size

it seems hash check opens file in readonly mode (so default_storage::open_file skips truncate routine) and does not check file size.

**Comment by arvidn** [comment]
This is by design. The main rationale (iirc):

1. it lets you check torrents on read-only volumes/user access
2. user's don't expect just checking a torrent to discard data

There's been some discussion of this topic here: https://github.com/qbittorrent/qBittorrent/issues/9782

So far I haven't heard terribly strong reasons for truncating by default, and only other solutions that are complex.

**Comment by ajax16384** [comment]
may be some theoretical security concern:
 - content can be maliciously modified (e.g append runme.sh with "rm -rf $HOME")
 - "verified" with .torrent hashes by libtorrent without error
 - executed runme.sh will do unexpected things

and i agree with https://github.com/qbittorrent/qBittorrent/issues/9782#issuecomment-437194657 statement that rechecking result should expose "correctness" of local data.

**Comment by arvidn** [comment]
can you think of a way to accommodate the, apparently common, expectation that you can "test" whether files you have match a torrent or not, but without deleting anything in case they don't match?
