### ISSUE TITLE
Cannot access the file

### ISSUE THREAD

**Issue by kotbrain** [arvidn/libtorrent#3532]
libtorrent version (or branch): 1.1.10
platform/architecture: Windows
compiler and compiler version: VS 2017

Sometimes users report about an error:
```
files open (...) error: The process cannot access the file
```

The file can be absolutely anything and it is not actually blocked, even restarting the computer does not solve the problem. User can edit and delete the file manually. After deleting the file, the error no longer occurs with this file, but may appear on others.

Program runs as administrator.

**Comment by arvidn** [comment]
Where does the error come from? Who prints it?

**Comment by kotbrain** [comment]
This error from ```file_error_alert``` -> ```message()```

**Comment by arvidn** [comment]
Is that the full message? or does it also say: "because it is being used by another process"?

It would be useful to know what the `code()` of the `error_code` value is too (i.e. the actual error code). Perhaps it's `ERROR_SHARING_VIOLATION` or `ERROR_LOCK_VIOLATION`.

The `op` field would also be helpful probably, as it tells you what libtorrent tried to do when it got the error.
