### ISSUE TITLE
Need advice with custom storage

### ISSUE THREAD

**Issue by elgatito** [arvidn/libtorrent#3570]
Hello.

I'm playing with this library and trying to customize it a little bit with adding own storage, which will store only part of torrent (piece storage, to store N pieces).

So have few questions:
1) If I have to delete not-needed piece from the storage - how do I change piece status in the library, so it's not thinking I still have it? If I won't change the status and I will need same piece - library won't re-download it in advance, so I need to set piece status somehow on deletion.

Is this issue about same feature? https://github.com/arvidn/libtorrent/issues/3516

~~2) I will need to setup size of temporary storage. I have seen your example of `storage_interface` implementation and I see there are like `default_storage_constructor`, which is set to `add_params`. Is there any good way to set storage size to storage instance?  Don't like the idea to extend `storage_interface` to call it directly from the app...~~

3) `master` branch is a _feature_ branch or ready to use? I'm updating Swig bindings, so I can stick to master if there are no plans to change naming in the near future. Or it's better to stay with RC_1_1?

Thanks

**Comment by arvidn** [comment]
1. there is an extension message that libtorrent supports (and I think uTorrent might support it as well) called `lt_donthave` which tells the peer that we don't have a piece that was previously advertised as "we have". This extension is not exposed to clients of libtorrent though, it's just used internally when using an experimental feature "predictive-have", which is kind of a cut-through forwarding of pieces.
I would be open to a patch that exposes this to clients to say a piece is no longer available.

Note that if an entire file need to be advertised as no longer available, sending an `lt_donthave` message for each of its pieces may not be that great.

3. the master branch is stable. I've been meaning to cut the 1.2 release from it for a while now.

**Comment by elgatito** [comment]
1. I was talking about situation when, for example, I want to download first 100 pieces, I set priorities to them, after some time I want to remove first N pieces, and set priority to the next N pieces, libtorrents does the download. But still thinking I have those first N pieces downloaded and if I want later to re-download those pieces, what should I do in that case?

**Comment by arvidn** [comment]
I don't think I understand what you mean. If you still have the first N pieces, why would you re-download them? They can't change from the first time you downloaded them.

Do you mean you would delete them when downloading pieces [N, N+N)?

If you delete the pieces, you would ideally tell your peers about it via this extension message (which you can't without patching libtorrent). Otherwise peers may request the pieces from you and at that point the best thing you can do is to trigger a disk I/O error which shuts down the torrent.

**Comment by arvidn** [comment]
> what will happen? Physically I don't have them, libtorrent thinks they are completed.

your custom storage implementation will get a call to read that piece, and if you don't have it you will have to respond with an error, which will cause the torrent to stop and disconnect all peers.

You could prevent this by writing a plugin which catches any peer requesting pieces you no longer have and just disconnect them instead. That way the torrent will stay alive at least.

**Comment by arvidn** [comment]
actually, if you write a plugin, you could send a `lt_donthave` message if the peer supports it, instead of disconnecting. you could also send rejects for pieces you don't have, but you shouldn't *just* send rejections, as the peers will just keep requesting them over and over again unless you say you don't have it anymore

**Comment by elgatito** [comment]
The problem here is not with sharing deleted pieces (at least, currently), but with redownloading piece its needed for reading, which is not redownloaded at the moment.
