### ISSUE TITLE
O_DIRECT gone in libtorrent 1.1+?

### ISSUE THREAD

**Issue by mkatsevVR** [arvidn/libtorrent#3614]
Has the direct I/O mode been removed somewhere between 1.0 and 1.1? Any reason why? How much work would it be to put it back?

**Comment by david-y-lam** [comment]
Removed in https://github.com/arvidn/libtorrent/commit/139fb29647ad8f2a8146285c753c165e5364b02b

**Comment by arvidn** [comment]
yes, it was removed. It would be a lot of work to put back. The main reason to remove it was that it was so complex (and error prone) that it ended up being half of all the code in the disk I/O subsystem (or something significant like that).

The original reason to put it in was also fixed by not using the `FILE_FLAG_RANDOM_ACCESS` on windows (which caused the disk cache to grow indefinitely, [blog post](https://blog.libtorrent.org/2012/05/windows-disk-cache/)) as well as periodically closing files on windows (to mitigate the file cache affinity to growing indefinitely anyway, [PR](https://github.com/arvidn/libtorrent/pull/1768) and [issue](https://github.com/qbittorrent/qBittorrent/issues/5804)).

Another reason to have `O_DIRECT` (historically) was to support the kernel AIO, which turned out to not be such a great idea anyway ([blog post](https://blog.libtorrent.org/2012/10/asynchronous-disk-io/)).

The commit david-y-lam referenced was just cleaning up some of the last remains of the `O_DIRECT` feature.

what is your use case or interest in `O_DIRECT`?

**Comment by mkatsevVR** [comment]
> what is your use case or interest in `O_DIRECT`?

alleviating memory pressure from the page cache (on linux)
libtorrent own cache is sufficient since I can tune its size according to the system requirements

I see that libtorrent 1.2 has a setting called disable_os_cache, which on [Linux controls O_SYNC](https://github.com/arvidn/libtorrent/blob/04993a51207f41b9bf9de7913dd34127ebb9b1ab/src/file.cpp#L372) and not O_DIRECT ([unlike](https://github.com/arvidn/libtorrent/blob/04993a51207f41b9bf9de7913dd34127ebb9b1ab/src/file.cpp#L407) other [platforms](https://github.com/arvidn/libtorrent/blob/04993a51207f41b9bf9de7913dd34127ebb9b1ab/src/file.cpp#L416)). Is this intentional? This is not the same thing and O_SYNC doesn't affect page cache. Looks like it's the same story for Windows (FILE_FLAG_WRITE_THROUGH vs FILE_FLAG_NO_BUFFERING)

**Comment by ssiloti** [comment]
I assume by "memory pressure from the page cache" you mean an excess of dirty pages hindering system performance. This is really an OS level issue best fixed in the kernel. Is your kernel version 4.10 or newer? There were changes in 4.10 which were supposed to improve writeback behavior. Check that your kernel has `CONFIG_BLK_WBT`,  `CONFIG_BLK_WBT_SQ', and `CONFIG_BLK_WBT_MQ` enabled.

**Comment by arvidn** [comment]
@mkatsevVR is it specifically the *read* cache (i.e. non-dirty pages) you're concerned about?
I would expect `O_SYNC` to mitigate having a growing number of dirty pages.

When the (non-dirty) page count gets too high, what's the symptom you see? I was under the impression that such pages could be reclaimed by the kernel immediately, and hence be fairly cheap.

**Comment by mkatsevVR** [comment]
yes, read cache (does `settings_pack::disk_io_read_mode` not do anything at all, btw?)
the problem is that I have other performance critical applications running that require all the memory available in the system
if libtorrent is doing buffered reads, even if the pages are discarded immediately, it would evict other (more important) files from cache and affect performance of the whole system

I'm now thinking that it should be possible to implement a custom storage interface with O_DIRECT file accesses - do you see any reason why this wouldn't work? I don't quite understand [this comment](https://github.com/arvidn/libtorrent/blob/libtorrent_1_2_0/include/libtorrent/storage.hpp#L204), can you elaborate on the differences between "aligned" and "fit a fully page aligned number of bytes"?

**Comment by ssiloti** [comment]
On Linux it looks like you can use control groups to limit the memory consumption of a process, including page cache usage.

**Comment by arvidn** [comment]
> I'm now thinking that it should be possible to implement a custom storage interface with O_DIRECT file accesses - do you see any reason why this wouldn't work?

That should work. The bulk of the former `O_DIRECT` support used to live in the storage. However, keep in mind that writes to the storage are *not* aligned to disk clusters, which means you may need to reproduce some of the page cache logic. Specifically for writing "edges", you may need to perform a "read-modify-write" of a disk cluster.

Here are some references: [1](https://github.com/arvidn/libtorrent/blob/RC_1_0/src/storage.cpp#L1261), [2](https://github.com/arvidn/libtorrent/blob/RC_1_0/src/storage.cpp#L1353), [3](https://github.com/arvidn/libtorrent/blob/RC_1_0/src/storage.cpp#L1316)

> I don't quite understand [this comment](https://github.com/arvidn/libtorrent/blob/libtorrent_1_2_0/include/libtorrent/storage.hpp#L204), can you elaborate on the differences between "aligned" and "fit a fully page aligned number of bytes"?

Oh, that comment is out-of-date. It specifically refers to a requirement on Windows for using Scatter/Gather I/O operations (windows' counterpart to `readv()`/`writev()`). Every *vec* in the iovec must be a whole page on windows. However, I've since moved away from using that API on windows and instead emulate it.

**Comment by mkatsevVR** [comment]
> keep in mind that writes to the storage are _not_ aligned to disk clusters

If the torrent is guaranteed to be padded such that the starting offset of every file is a multiple of the disk block size, this should not be a problem, right?

> Every _vec_ in the iovec must be a whole page on windows

what about Linux?

**Comment by arvidn** [comment]
> If the torrent is guaranteed to be padded such that the starting offset of every file is a multiple of the disk block size, this should not be a problem, right?

As long as the piece size is a multiple of the disk block size, I believe that's correct, for writes. For reads, it's up to the peers, so they may still be unaligned.

> what about Linux?

Linux doesn't have such restriction

**Comment by mkatsevVR** [comment]
> For reads, it's up to the peers, so they may still be unaligned.

If all peers are using libtorrent 1.2, will the requests sent be aligned?

> Linux doesn't have such restriction

I meant to ask whether the buffers that libtorrent allocates on Linux are guaranteed to be aligned or not. I believe this is a requirement of O_DIRECT (both file offset and memory buffer offset must be aligned).

**Comment by arvidn** [comment]
> If all peers are using libtorrent 1.2, will the requests sent be aligned?

I'm pretty sure that's the case, yes.

> I meant to ask whether the buffers that libtorrent allocates on Linux are guaranteed to be aligned or not. I believe this is a requirement of O_DIRECT (both file offset and memory buffer offset must be aligned).

They used to be, but not anymore (starting in RC_1_2 iirc). Take a look at `disk_buffer_pool::allocate_buffer_impl()`.

I think it's sufficient with a 512 byte alignment. libtorrent used to use `valloc()` in the past. However, the windows counterpart(s) were very inefficient, and since it's not used anymore, it was simplified.

For your use case, do you think it would suffice to, after each `read()`, call `posix_fadvise(POSIX_FADV_DONTNEED)`?

**Comment by chrcoluk** [comment]
Don't know enough about madvise to give a proper opinion on it.  I had a quick look at the manpage, and it seems to be more about memory allocation rather than actual disk caching behaviour.

**Comment by andreygursky** [comment]
In the LKML link you can find also the properly function for files: ```posix_fadvise()``` and the flag ```POSIX_FADV_DONTNEED```.

**Comment by arvidn** [comment]
right, libtorrent uses memory mapped files though, since 2.0. So it would use the `madvice()` counterpart (`MADV_DONTNEED`)
