### ISSUE TITLE
Limit file cache on Windows

### ISSUE THREAD

**Issue by airium** [arvidn/libtorrent#3687]
Sorry if this topic has been extensively discussed but I didn't find any.

It is known that libtorrent-based clients, typ. qbittorrent, suffer from the unlimitedly growing file cache on Windows. On a high-speed or long-term seedbox, this may at the end occupies the whole RAM and break the client. libtorrent 1.1 removed the `FILE_FLAG_NO_BUFFERING`-based IO and introduced the periodical file closing mechanism. However, this still doesn't efficiently solve the problem. A latest qbittorrent on one my 1Gbps dedicated server still crash after taking up the whole RAM from time to time.

I found that except closing files we could actually have another way to deal with the problem. There are some articles also tools:
https://docs.microsoft.com/en-us/sysinternals/downloads/cacheset
https://www.uwe-sieber.de/ntcacheset_e.html
https://support.microsoft.com/kb/976618

They mentioned that there are multiple ~win32 APIs e.g. [`SetSystemFileCacheSize()`](https://docs.microsoft.com/en-gb/windows/desktop/api/memoryapi/nf-memoryapi-setsystemfilecachesize)~ or tools like `CacheSet` and [window dynamic caching service plus registry](https://support.microsoft.com/kb/976618) providing the utility to tweak the global file cache setting, so as to prevent it from indefinitely growing. ~And one my friend further mentioned that there is a win32 API [`SetProcessWorkingSetSizeEx()`](https://docs.microsoft.com/en-us/windows/desktop/api/memoryapi/nf-memoryapi-setprocessworkingsetsizeex) + [`QUOTA_LIMITS_HARDWS_MAX_ENABLE`](https://docs.microsoft.com/en-gb/windows/desktop/api/memoryapi/nf-memoryapi-setprocessworkingsetsizeex)  able to set per process cache limit.~

~I am therefore wondering if this will also help libtorrent to solve the file cache problem if an implementation is interesting. Unluckily, using this system call requires `PROCESS_SET_QUOTA` privilege, which means the clients have to be run as admin or users are included in `Adjust memory quotas for a process` in Local Security Policy. So, it would behave like the pre-allocation on Windows.~

Sorry, it seems I previously understood it wrongly. What actually takes effect is limiting the working set of the system file caching service, while limiting libtorrent's working set does not have any benefit and is silly. But since I didn't see anyone else mentioned this solution before, it may be still helpful for those who struggling with the over-sized file cache.

**Comment by arvidn** [comment]
there is an old (and long ) thread on this over on the qbittorrent page: https://github.com/qbittorrent/qBittorrent/issues/5804

My recollection of the research I did back then (which resulted in the periodic closing of files-feature) is that this is a complex problem to solve. Primarily because it's really an issue in the windows cache manager and all you can do as a user-space process is to nudge the kernel in the direction you'd like.

Getting rid of `FILE_FLAG_NO_BUFFERING` was critical in order to support multi-threaded disk I/O.

Here's a related issue, which I thought (and still suspect) was the main contributor to these kinds of problems: https://blog.libtorrent.org/2012/05/windows-disk-cache/

When I learned about the various functions to limit working sets, I thought that was a good "solution" too. But the fact that you need extra privileges makes it impractical and it's not a general solution, because, what do you limit the working set to? whatever you pick, there will be situations where it's too big. And certainly situations where it will be too small.

Does anyone know if this is still a problem in new versions of windows? Say, windows 10.

**Comment by airium** [comment]
Actually as I said the closing file mechanism does not efficiently prevent the system cache from indefinitely growing with a latest qbittorrent and windows 10. Seeding many torrents or in a high speed will still let the cache fill up the whole RAM. Upsetted by this problem, I just happen to find this knowledge about limiting the working set size of windows caching service. I am then here curious to ask if libtorrent has considered it. Now it seems you have ever thought about it. That's it, thanks for your explanation.

**Comment by arvidn** [comment]
it's possible that the frequency with which files are closed isn't high enough. iirc, the default is to close the least recently used file every 2 minutes. Perhaps the least recently used file will tend to be the smallest file as well, so perhaps it should be changed to round-robin. Or perhaps most recently used.
