### ISSUE TITLE
Missing create_torrent constructor

### ISSUE THREAD

**Issue by glassez** [arvidn/libtorrent#3700]
There is `create_torrent(torrent_info const& ti, bool use_preformatted);` constructor in RC_1_1 branch that is missing in both master and RC_1_2 (as far as I remember it was there some time ago).

**Comment by arvidn** [comment]
that was only there as a hold over until the ABI could be changed in 1.2. The problem was that `entry` (the decoded form of bencoding) did not preserve dictionary order (for invalid encodings). This is especially relevant for invalidly encoded torrent files where the verbatim order affects the info-hash. Since introducing a new kind of `entry` type would break the ABI, it's only introduced if the client is in fact new enough to handle it, which must be determined at run-time.

**Comment by arvidn** [comment]
i.e. in 1.2 and later, `use_preformatted` is implied true
