### ISSUE TITLE
Failure on upnp port forwarding will reset the listening port to 0

### ISSUE THREAD

**Issue by airium** [arvidn/libtorrent#3785]
**Please provide the following information**

**libtorrent version (or branch):**
latest master or 1.2 branch, tested with qbittorrent latest master
**platform/architecture:**
linux, ubuntu 18.04 LTS
**compiler and compiler version:**
GCC 7.3, C++14
**please describe what symptom you see, what you would expect to see instead and
how to reproduce it:**
Conventionally, end-users just leave the upnp function in enabled status to adapt arbitrary scenarios. However, since 1.2, the failure on upnp port forwarding (may result from no router, router upnp off, etc.) will reset the listening port to 0. This is done by:
https://github.com/arvidn/libtorrent/blob/8506f9350710db6276e7a28b90b960a6f466d722/src/upnp.cpp#L1103-L1104
where the positional argument `0` in calling `on_port_mapping` will inevitably reset the value of the listening port to 0:
https://github.com/arvidn/libtorrent/blob/8506f9350710db6276e7a28b90b960a6f466d722/src/session_impl.cpp#L5575-L5576
Since then, all announces to trackers will include `port=0`, which triggers the `invalid port` error message from trackers.

It should not reset the port to 0. If port reset, the end user has to manually turn on or off the upnp port forwarding function to avoid invalid port issue, which brings a certain inconvenience.

**Comment by ssiloti** [comment]
There's no clean way of handling this now because `*_external_port` members are shared between uPnP and NAT-PMP. When a mapping fails we don't know if the current value in `*_external_port` came from uPnP or NAT-PMP so we don't know if the port should be modified. Ideally there would be separate sets of `*_external_port` members for each mapping protocol. I still need to work through the details of that to see if it would cause problems elsewhere.
