### ISSUE TITLE
failed to compile master and last release on armhf

### ISSUE THREAD

**Issue by Askmewho** [arvidn/libtorrent#3854]
GCC: 8.1

```

  CXX      libtorrent_rasterbar_la-create_torrent.lo
In file included from crc32c.cpp:46:
/usr/local/lib/gcc/arm-linux-gnueabihf/8.1.0/include/arm_acle.h: En la función ‘void __arm_ldc(unsigned int, unsigned int, const void*)’:
/usr/local/lib/gcc/arm-linux-gnueabihf/8.1.0/include/arm_acle.h:48:46: error: invalid conversion from ‘const void*’ to ‘const int*’ [-fpermissive]
   return __builtin_arm_ldc (__coproc, __CRd, __p);
```

**Comment by arvidn** [comment]
@aldenml does this ring a bell for you? Is this some other (newer) version of that API?
I don't have an ARM SDK handy right now, so it's not easy to know which function boils down to the call to `__arm_ldc`, but there seem to be some parameter type incompatibility. afaict, libtorrent code does not use a `void const*` anywhere.

It almost looks like it could be caused by some issue with incompatible GCC and arm SDK.

**Comment by arvidn** [comment]
this version of `arm_acle.h` uses a `void const*`.

It looks like a GCC bug. I found this: https://github.com/nzbget/nzbget/issues/550

and the GCC bug report here: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81497

**Comment by arvidn** [comment]
I would be open to a patch that adds `-fpermissive` for ARM builds, ideally *just* for `crc32c.cpp`

**Comment by aldenml** [comment]
@arvidn never heard, and I'm just learning about it
