### ISSUE TITLE
peer_info.client UnicodeDecodeError on Python 3

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#3858]
This is a big vague but there is an issue with encoded peer client strings where calling `peer_info.client` raises a `UnicodeDecodeError`:

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 0: invalid start byte`

I assume that the encoding for these client strings is not `utf8` and boost.python is failing to convert from bytes to str under Python 3. I am not sure how this can be tested as it only occurs randomly for a few clients.

libtorrent version (or branch): 1.1 or 1.2

**Comment by arvidn** [comment]
would it make sense to make the `client` field a byte array instead of string? technically the peer is under no (real) obligation to encode it correctly. I think the alternative is to have a more lenient UTF-8 parser that replaces invalid encoding with a replacement character. In some way that's probably simpler for users of the library, but also slightly less flexible.

**Comment by cas--** [comment]
Yes I think a byte array makes sense. In Deluge we are expecting it to be bytes (was always under Python 2) and have a decode function to handle unexpected encodings.

**Comment by arvidn** [comment]
does this work? https://github.com/arvidn/libtorrent/pull/3865
