### ISSUE TITLE
Different name for incomplete files

### ISSUE THREAD

**Issue by WhiteTrashLord** [arvidn/libtorrent#388]
Would it be possible to save all incomplete files of a torrent under a different name?

For example: debian-8.2.0-amd64-CD-1.iso.part
Another torrent client does it like that.

An option to only check files which end with a '.part' during the start would be nice.

**Comment by arvidn** [comment]
I think that would be a relatively easy thing to do without any additional support in libtorrent. there's an alert when a file completes.

Are there any benefits of only checking .part-files on start over using resume data? (i.e. not check the files at all)

**Comment by WhiteTrashLord** [comment]
I am not sure if you fully understood my idea. I want that libtorrent gets an option which adds a '.part' at the end of the filename of every file a torrent contains when a new torrent is added.
Once the file is complete, libtorrent should give it the original name.

Renaming every file manually would be very annoying. The new file names are stored in the resume data? I am not sure if it would work well when I have to restart a session because libtorrent might have lost the information of my renamed files?

Developers who don't want to manage resume data would get a very easy faster file checking.

In my case I would like to know which files are completed without looking up the libtorrent session.

**Comment by arvidn** [comment]
I would imagine your computer program would issue the renaming of files (ideally the same program that links against libtorrent), i.e. not manually.

Yes, new names for renamed files are stored in the resume data.

Whether the checking would be faster depends entirely on how common certain operations are (for instance, if you only download single-file torrents, it wouldn't make any difference). However, you could also generate a resume data file on the fly, based on the filenames. However, you should probably consider what happens when you download a torrent where one of the files in there ends with ".part", and there's another file in the torrent with the same name except without the .part extension.

**Comment by WhiteTrashLord** [comment]
This is not very important for me. But it would make only sense when libtorrent supports it nativley.

Several other programs like Firefox and Transmission also save incomplete files like that.

And the filecheck would be also faster for single file torrents:

Content of the save directory:

Case 1:
debian-8.2.0-amd64-CD-1.iso.part -> libtorrent would know that the file is incomplete and do a file check

Case 2:

debian-8.2.0-amd64-CD-1.iso -> libtorrent would know that the file is complete and no more file check is necessary

**Comment by arvidn** [comment]
does libtransmission support it, or is it implemented in transmission?
part of my point here is that whether it's important to support the edge case I brought up or not isn't all that relevant. If it is unimportant to _all_ users of libtorrent, it would be. libtorrent is a library and must consider a wide range of use cases. In this case, I'm fairly certain, this feature does not need to live in libtorrent itself, and I'm not convinced that the majority of libtorrent users would find a use for it. (I realize there are plenty of very specialized features in libtorrent already, and I regret some of them).

Why do you say it would only make sense to implement this in libtorrent? Why would it not make sense to implement it on top of libtorrent?

For instance, let's assume firefox uses libcurl for downloading over http (I don't think it does, but for argument's sake, let's say it does). It would not make sense for the firefox developers to ask for this ".part" file extension feature to be implemented by libcurl, right? It's a higher level feature, that sits on top of the library doing the actual downloading.

**Comment by WhiteTrashLord** [comment]
It seems that libtransmission itself supports it:

transmission.h

´/** @brief return true if files will end in ".part" until they're complete */
bool tr_sessionIsIncompleteFileNamingEnabled (const tr_session * session);

Basically I only want that you consider to add these 2 options to libtorrent:

Giving all incomplete files a '.part' suffix, yes or no
Faster file check during startup based on filename, yes or no ( first option must be set to yes)

If I am the only one who thinks that this would be useful, it's totally fine when you simple ignore it.

**Comment by igor-rif-shevchenko** [comment]
@arvidn maybe you can revisit this question? I think it can be very usefull. It seems like other projects have issues implementing this on top of libtorrent, e.g.:

https://github.com/qbittorrent/qBittorrent/issues/3890#issuecomment-155138761
https://github.com/qbittorrent/qBittorrent/issues/5460
https://github.com/qbittorrent/qBittorrent/issues/10404
https://github.com/qbittorrent/qBittorrent/issues/8379

**Comment by arvidn** [comment]
@igor-rif-shevchenko would you mind summarising the issues with implementing this on top of libtorrent?

**Comment by igor-rif-shevchenko** [comment]
> @igor-rif-shevchenko would you mind summarising the issues with implementing this on top of libtorrent?

@arvidn  I've checked qbittorrent sources and realized that issue happens because renaming is done when torrent is already started, they use file progress to decide wich files should be renamed. So when there are already some partially downloaded files - they don't get checked on torrent start and everything is messed up.

Better solution is to rename files before adding torrent, no problems in that case.
But now I'm struggling with magnet links. You can't rename files before adding a torrent.
So you have to start torrent, wait for metadata and then rename files.
Can you advice how to do that right? I'm thinking to use separate session just to fetch metadata, save torrent file and then pass it to main session. But that seems too complicated.
What do you think is the right way?

**Comment by arvidn** [comment]
You can use the stop_when_ready flag on the torrent

**Comment by igor-rif-shevchenko** [comment]
@arvidn but here you said that it's a bad idea, am I missing something?
https://github.com/arvidn/libtorrent/issues/2239

**Comment by igor-rif-shevchenko** [comment]
@arvidn Maybe it's better add magnet with upload_mode and unset flag_auto_managed, wait for metadata, rename files and then set auto_managed and unset upload mode?
Can I use torrent_info.rename_file in this case? Instead of torrent_handle.rename_file - since I don't need to rename files that are on disk.

**Comment by arvidn** [comment]
@igor-rif-shevchenko ah, yes, you're right. `upload mode` and clearing `auto_managed` should do it.
