### ISSUE TITLE
Incorrect loading of url_seeds

### ISSUE THREAD

**Issue by Chocobo1** [arvidn/libtorrent#3946]
**Please provide the following information**

libtorrent version (or branch):
RC_1_2

platform/architecture:
linux

compiler and compiler version:
gcc-9.1.0

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

```c++
{
    // load torrent and remove url_seeds
    lt::add_torrent_params p;
    p.save_path = "./";
    p.ti = // from .torrent file
    lt::session s;
    lt::torrent_handle h = s.add_torrent(p);
    h.remove_url_seed(*h.url_seeds().begin());  // only has 1 url seed
    assert(h.url_seeds().empty());  // url_seeds is empty now
    // ...
    // save resume data to `buffer`
    bencode(std::back_inserter(buffer), ...);
}

{
    // restoring
    lt::add_torrent_params p;
    p = read_resume_data(buffer);
    p.ti = // from .torrent file
    lt::session s;
    lt::torrent_handle h = s.add_torrent(p);
    assert(h.url_seeds().empty());  // this fails
}
```
My problem occurs at the second `assert()`: The `url_seeds` is always non-empty. I noticed the fastresume/buffer doesn't have `url-list` entry so the fastresume is generated correctly.

One can workaround it by clearing the entries in `p.ti` and then use torrent_info::add_url_seed() to repopulate them, however that is quite dirty IMO.

Related: https://github.com/qbittorrent/qBittorrent/issues/11023

**Comment by arvidn** [comment]
I believe that if you just don't set `p.ti // from .torrent file` it would work. I believe `save_resume_data()` saves the info-dict from the torrent and `read_resume_data()` will restore it.

However, this behavior you're seeing; is it a regression from 1.x?

**Comment by Chocobo1** [comment]
>I believe that if you just don't set p.ti // from .torrent file it would work. 

Yes that worked! I tired it before and was seeing some anomaly in the UI, I thought it wasn't the right way. After closer inspection, it turns out to be a bug in my code.

>I believe save_resume_data() saves the info-dict from the torrent and read_resume_data() will restore it.

I looked into the fastresume and it has the `info-hash` string but no `info` dict as in .torrent file.
Does that means libtorrent will download the `info` dict from elsewhere? If so then maybe it's not optimal as I already have .torrent file but shouldn't use it, however I'm not familiar with the spec and I could be wrong.

>However, this behavior you're seeing; is it a regression from 1.x?

I'm not sure, `read_resume_data()` is used only recently.

**Comment by arvidn** [comment]
the "info" dict is saved here: https://github.com/arvidn/libtorrent/blob/RC_1_2/src/write_resume_data.cpp#L90

it's included in the `add_torrent_params` here:

https://github.com/arvidn/libtorrent/blob/RC_1_2/src/torrent.cpp#L6156

I notice that there's a few conditions there. It only reliably kicks in if the torrent was added from a magnet link. Otherwise you have to specify a flag to save it. Perhaps it should always be included, unconditionally. I'm not sure, it is associated with some cost.

**Comment by arvidn** [comment]
I'm considering simplifying this further in the next major version. Where `torrent_info` is immutable and essentially only represents the info-dict. instead of loading a torrent with the `torrent_info` constructor, a separate function would load a torrent and return an `add_torrent_params` object.

That way, all the things in the torrent file that aren't immutable (trackers, url seeds, etc) would be part of the `add_torrent_params` and easily modified and saved off separately.

**Comment by Chocobo1** [comment]
I think now I have all the pieces to make it work, thanks for your help!
