### ISSUE TITLE
Updating Torrents Via DHT Mutable Items (BEP-46)

### ISSUE THREAD

**Issue by tallero** [arvidn/libtorrent#4012]
#### Abstract
This extension enables torrents to update based on data stored in the BitTorrent DHT [[1](http://www.bittorrent.org/beps/bep_0044.html)], rather than an HTTP server. The publisher has control over when the torrent is updated, and which content it contains, via mutable DHT items. It is similar to BEP 39 [[2](http://www.bittorrent.org/beps/bep_0044.html)], with the difference being that it uses the DHT to notify and be notified about updates of a torrent, hence should provide more decentralized capabilities to both publishers and consumers.

The intention is to allow publishers to serve content that might change over time in a more decentralized fashion. Consumers interested in the publisher's content only need to know their public key + optional salt. For instance, entities like Archive.org could publish their database dumps, and benefit from not having to maintain a central HTTP feed server to notify consumers about updates.

#### Rationale
BEP 39 [[2](http://www.bittorrent.org/beps/bep_0044.html)] allows to automatically update torrents based on HTTP URLs. With DHT storing capabilities [[1](http://www.bittorrent.org/beps/bep_0044.html)], we can implement similar functionality in a more decentralized fashion without resorting to central HTTP servers, and using features already present in the BitTorrent network (mainly DHT store).

[...]

## Questions

Is this [documentation page](https://github.com/mveytsman/libtorrent/blob/master/docs/dht_store.rst) related?

**Comment by arvidn** [comment]
libtorrent never implemented automatically updating torrents via HTTP (nor DHT). I'm a bit hesitant to do the former, as it could be abused to DDoS a web site. Updating via DHT seems reasonable, but I would prefer it be implemented as a layer on top of a libtorrent session.

**Comment by arvidn** [comment]
is this a feature request to do the latter btw?

**Comment by tallero** [comment]
>is this a feature request to do the latter btw?

In part; I read a comment on Stack Exchange stating that libtorrent already implemented this BEP, referencing the above linked page and I didn't actually understand if that proposal had been translated into code or not. 
If not, I think it could be considered a feature request in any case.

**Comment by geiseri** [comment]
I have a use-case for being able to update torrents.  I think DHT updates would be the best since a tracker would never keep up. In my case, I have a slowly growing file set that updates once a day.  Currently, I make a new torrent every day and I am concatenating magnet links in the DHT since I control both sides so I don't have to deal with 1k rejects.  I'm assuming that this solution would not scale given a long enough timeline.

**Comment by arvidn** [comment]
This also sounds like a use case for "mutable torrents". you can include hints in your torrent file of other info-hashes the torrent share files with. If the piece size and alignment match, libtorrent will be able to "upgrade" one torrent to the other and only download the difference.

**Comment by arvidn** [comment]
https://www.bittorrent.org/beps/bep_0038.html

**Comment by geiseri** [comment]
I was under the impression that the prior torrents must still be around.  Or do I just keep adding the info hashes as the hint?  If so this would be just fine because I am relying on the DHT for hosting information.

**Comment by arvidn** [comment]
> I was under the impression that the prior torrents must still be around.

If nobody has any of the prior torrents anymore, there's really no point in using this feature. The point is that if any peers have a torrent on the "similar" list (or a torrent in the same "collection"), it will try to reuse files from there. So, yes, the torrents still have to be around, somewhere.

> Or do I just keep adding the info hashes as the hint?

Yes, you just add the previous info-hash to the list, letting it grow.

> If so this would be just fine because I am relying on the DHT for hosting information.

For it to work over the DHT, you have to put the "similar" and/or "collection" key inside the info-dict.

**Comment by Piotrmejor** [comment]
Great to stay with Git hoob

**Comment by Goddard** [comment]
I spoke with the people at qbittorrent and they said this feature isn't supported.

It would be really cool if something like this was possible.

For example, if I was working with my friends on a game and we have 400 gigs of game assets we wanted to share and keep up to date between us and one person was the "point" person for the data and would add these new files to the directory where the torrent program is watch it could automatically update the torrent.  

Would save a lot of time having to re-build the torrent file every time.  Especially since my torrent file creation took like 20 minutes.

**Comment by arvidn** [comment]
mutable torrents are supported by default in libtorrent. I don't think qbt can or attempts to disable that. The only thing missing then is the tool to (cheaply) create a new torrent for the updated files.

It's not obvious to me that such tool would be in-scope for qBittorrent.

**Comment by master255** [comment]
@Goddard You need to use the [Media Library](https://play.google.com/store/apps/details?id=com.media.library). My app has long contained editable torrents, fast torrent file updates, and even torrents over the https protocol.

**Comment by master255** [comment]
Okay. Since [Media Library](https://drive.google.com/drive/folders/1rKPerLeAwUva8orlfzQhapWusVji6r6e) is currently the only program in the world that can do what tallero is writing about, as a developer, I need to set the data format (stored in DHT):
74:731a08c33055558f548fd191f96dd64b1adb77b9

Where 74 is the change number, which increases every time Sha1 changes. The number is necessary not only for programs to understand that the information has been updated, but also for people. Therefore, even if technically the number seems useless, as information for the people who will use it, it is very necessary. Of course, programs must also check this number.
I wanted to abandon this number for a long time, but in practice I couldn't.

And 731a08c33055558f548fd191f96dd64b1adb77b9 is the Sha1 of a torrent, which can be of any format (Sha256 and other).
