### ISSUE TITLE
UPnP not adding IPv6 firewall pinhole

### ISSUE THREAD

**Issue by treysis** [arvidn/libtorrent#4111]
**Please provide the following information**

### qBittorrent version and Operating System
qBittorrent 4.1.9.1
Libtorrent 1.1.13.0 (but all versions affected)
Windows 10 1909

### What is the problem
UPnP doen't open firewall ports in the IPv6 firewall of the router.

### What is the expected behavior
The UPnP option should also send IGD2 AddPinhole requests (WANIPv6FirewallControl) to the IPv6-enabled router/firewall to open the desired ports. This is important if you want to use IPv6-Privacy-Extensions, because the IPv6 changes quite often and it is not good practice to always adjust the firewall rules on the router by hand.

### Steps to reproduce
Connect to IPv6 enabled peers with IPv6 firewall and UPnP option enabled (or just look at the source code: there is no mention of WANIPv6FirewallControl).

**Comment by ssiloti** [comment]
I started working on this a while ago but abandoned it because my router doesn't support IGD2. You can find the WIP code at https://github.com/ssiloti/libtorrent/commits/upnpv6

Libtorrent supports using Port Control Protocol (PCP) to open IPv6 pinholes. I suggest using that if your router supports it.
