### ISSUE TITLE
rb_libtorrent crashes vlc-bittorrent

### ISSUE THREAD

**Issue by musuruan** [arvidn/libtorrent#4126]
libtorrent version (or branch):
$ rpm -qa vlc* rb_l* |sort
rb_libtorrent-1.1.13-4.fc31.x86_64
vlc-3.0.9-21.fc31.x86_64
vlc-bittorrent-2.7-1.fc31.x86_64
vlc-core-3.0.9-21.fc31.x86_64

platform/architecture:
Fedora 31/x86_64

compiler and compiler version:
gcc-9.2.1

Trying to play any video via bittorrent (using vlc-bittorrent) crashes VLC.

I opened two bugs. The first against vlc-bittorrent in RPM Fusion:
https://bugzilla.rpmfusion.org/show_bug.cgi?id=5433

The maintainer thinks the problem is in rb_libtorrent 1.1.13 (it seems v1.2.2 is fine) and he proposes a patch:
https://bugzilla.rpmfusion.org/show_bug.cgi?id=5433#c4

Therefore I opened an issue against it in Fedora:
https://bugzilla.redhat.com/show_bug.cgi?id=1774414

But rb_libtorrent's maintainer is not certain the proposed patch would fix this issue and he asked me to open an issue upstream and see if the 1.1.x branch could receive an update:
https://bugzilla.redhat.com/show_bug.cgi?id=1774414#c1

**Comment by arvidn** [comment]
looking at the backtrace in the RPM-fusion report, the demangled top of stack looks like this:

```
Stack trace of thread 27719:
                #0  0x00007f6ab1c0fe35 raise (libc.so.6)
                #1  0x00007f6ab1bfa895 abort (libc.so.6)
                #2  0x00007f6aaa34b288 std::__replacement_assert(char const*, int, char const*, char const*) (libtorrent-rasterbar.so.9)
                #3  0x00007f6aaa455dbb libtorrent::piece_picker::have_piece(int) const (libtorrent-rasterbar.so.9)
                #4  0x00007f6aaa49c6ed void libtorrent::aux::fun_ret<bool>(bool&, bool&, libtorrent::condition_variable&, boost::asio::detail::posix_mutex&, boost::function<bool ()>) (libtorrent-rasterbar.so.9)
                #5  0x00007f6aaa49f9e5 boost::asio::detail::completion_handler<boost::_bi::bind_t<void, void (*)(bool&, bool&, libtorrent::condition_variable&, boost::asio::detail::posix_mutex&, boost::function<bool ()>), boost::_bi::list5<boost::reference_wrapper<bool>, boost::reference_wrapper<bool>, boost::reference_wrapper<libtorrent::condition_variable>, boost::reference_wrapper<boost::asio::detail::posix_mutex>, boost::_bi::value<boost::function<bool ()> > > > >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) (libtorrent-rasterbar.so.9)
                #6  0x00007f6aaa3811ad boost::asio::detail::scheduler::run(boost::system::error_code&) (libtorrent-rasterbar.so.9)
``` 

The `fun_ret` template is used to communicate back with the client, making a blocking call to the libtorrent API. In other words, this call is in turn caused by a client call to some blocking function on `session` or `torrent_handle`.

There are two other threads that are blocked by synchronous calls into libtorrent:
```
Stack trace of thread 27726:
                #0  0x00007f6ab1db23c5 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007f6aaa48284c libtorrent::aux::torrent_wait(bool&, libtorrent::aux::session_impl&) (libtorrent-rasterbar.so.9)
                #2  0x00007f6aaa58ad89 void libtorrent::aux::sync_call_ret_handle<boost::shared_ptr<libtorrent::torrent>, boost::shared_ptr<libtorrent::torrent_info const> >(boost::shared_ptr<libtorrent::torrent>&, boost::shared_ptr<libtorrent::torrent_info const>&, boost::function<boost::shared_ptr<libtorrent::torrent_info const> ()>) (libtorrent-rasterbar.so.9)
                #3  0x00007f6aaa579883 libtorrent::torrent_handle::torrent_file() const (libtorrent-rasterbar.so.9)
                #4  0x00007f6aaa76a06e Download::read(int, unsigned long, char*, unsigned long) (libaccess_bittorrent_plugin.so)
```

and
```
Stack trace of thread 27720:
#0  0x00007f6ab1db23c5 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007f6aaa48284c libtorrent::aux::torrent_wait(bool&, libtorrent::aux::session_impl&) (libtorrent-rasterbar.so.9)
                #2  0x00007f6aaa588b29 void libtorrent::aux::sync_call_ret_handle<boost::shared_ptr<libtorrent::torrent>, bool>(boost::shared_ptr<libtorrent::torrent>&, bool&, boost::function<bool ()>) (libtorrent-rasterbar.so.9)
                #3  0x00007f6aaa577f5b libtorrent::torrent_handle::have_piece(int) const (libtorrent-rasterbar.so.9)
                #4  0x00007f6aaa769eb1 Download::move_window(int) (libaccess_bittorrent_plugin.so)
```

Since the underlying call is made to `piece_picker::have_piece()`, it seems safe to assume it's originating from the latter, [torrent_handle::have_piece](http://libtorrent.org/reference-Core.html#have_piece()).

looking at `torrent::have_piece()`, there is a precondition on that function. the piece `index` must be in range. i.e. [0, num-piece-in-torrent). It's possible  that this precondition is violated, causing the assert.

Here's the code in 1.1.3: https://github.com/arvidn/libtorrent/blob/RC_1_1/include/libtorrent/torrent.hpp#L776

And here's the code in 1.2.x: https://github.com/arvidn/libtorrent/blob/RC_1_2/include/libtorrent/torrent.hpp#L794

As you can see, there's a check for invalid idices in 1.2. To confirm this, do you have access to the program's `stderr` when it crashes? I suspect it will contain some helpful message.

My conclusion (so far) is that technically it is the client's fault, but I could also back-port the range check to 1.1.3 (and release it as 1.1.4). However, the client is still doing suspicious things, that may be a bug.

**Comment by arvidn** [comment]
I intend to back-port the input validation check here: https://github.com/arvidn/libtorrent/pull/4128

**Comment by arvidn** [comment]
The patch referenced in the RPMfusion ticket is not related to this issue, I'm quite certain of that.
This is the patch that makes the difference: https://github.com/arvidn/libtorrent/commit/a1f299571667057e793392249691ac4d3b5f3aeb

It introduced range checking on the `torrent_handle::have_piece()` call, to return false if the piece index is out of range, rather than asserting/crashing.

However, I still maintain that the underlying bug is in the client. It is miscalculating the piece index somehow.

**Comment by arvidn** [comment]
In fact, I believe that [this](https://github.com/johang/vlc-bittorrent/blob/d6d53761e9d4a4c8c7519a20c84d07d8afa27f62/src/download.cpp#L321) line should change from:

```
for (; m_torrent_handle.have_piece(piece) && piece < np; piece++);
```

to:

```
for (; piece < np && m_torrent_handle.have_piece(piece) ; piece++);
```

Otherwise `piece` will be one-past-end and still be passed into `have_piece()`

**Comment by musuruan** [comment]
> In fact, I believe that [this](https://github.com/johang/vlc-bittorrent/blob/d6d53761e9d4a4c8c7519a20c84d07d8afa27f62/src/download.cpp#L321) line should change from:
> 
> ```
> for (; m_torrent_handle.have_piece(piece) && piece < np; piece++);
> ```
> 
> to:
> 
> ```
> for (; piece < np && m_torrent_handle.have_piece(piece) ; piece++);
> ```
> 
> Otherwise `piece` will be one-past-end and still be passed into `have_piece()`

I locally rebuilt vlc-bittorent with this fix and I no longer have crashes. I'll report this to RPM Fusion. Thanks for your time.
