### ISSUE TITLE
Skip hash check loophole

### ISSUE THREAD

**Issue by an0n666** [arvidn/libtorrent#4176]
**Please provide the following information**

libtorrent version (or branch):
1.2
platform/architecture:

compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
If a torrent is added with skip hash check then libtorrent probably doesn’t check if the file exists and goes into seeding mode directly. So it reports to tracker left=0 meaning it’s a seeder. This remains in seeding mode until probably some peer connects and tries to download/client is restarted. Anyone taking advantage of it can add thousands of torrent without downloading a single byte and get seed points or other incentive of seeding on a tracker.
The fix would be to check if the file exists on disk/ atleast check a few percentage of the file before announcing to tracker and going to seeding mode.

**Comment by arvidn** [comment]
yes, I'm pretty sure your assumptions are correct. In seed mode, all pieces are assumed to exist and be correct on disk, until a peer requests the piece for the first time. At that point it is read from disk and hash-checked. Note that every piece is still hash checked the first time it's sent to a peer, to ensure no corrupt data is transmitted. And if the file doesn't exist, or the hash check fails, all peers are disconnected and the torrent transitions into a full check of all files/pieces.

This behavior has been the same for a very long time (afaik), and I'm under the impression that there is some convention among bittorrent clients to behave like this, but I'm not sure. Do you know of any clients with a seed-mode feature that verifies some files up-front?

I imagine the best way to fix this issue is to, on startup, read a random piece and check its hash. If that succeeds, chances are that the torrent is in fact seeding.

However, I'm not convinced that this is the responsibility of libtorrent. There may be users of libtorrent that absolutely do not want any redundant disk I/O when adding torrents in seed-mode. After all, from libtorrent's point of view, it's not humans that are being trusted to not lie about seed-mode, it's the client program making the call. So, one could argue the client of libtorrent, if they want to validate seed-mode torrents, could read one piece to check. I'm pretty sure it would be sufficient to call [read_piece](http://libtorrent.org/reference-Core.html#read_piece()).

I can also see an argument that it's not really the client's responsibility either. If a tracker cares about clients not lying about this, they could also try to download a random piece from anywone that announces with `left=0&uploaded=0`.

**Comment by an0n666** [comment]
You are correct. This issue is not limited to libtorrent but almost every client has this issue. I also believe it's the responsibility of the tracker to verify the seeder. Thanks! Closing this.
