### ISSUE TITLE
Support Tron's BTT cryptocurrency

### ISSUE THREAD

**Issue by ghbplayer** [arvidn/libtorrent#4243]
Tron's BTT cryptocurrency has the potential to reduce leeching and cheating, improve fairness, and help some make extra money. Is it a good standard or good for LT? Will it benefit some or most users? Will it be hard to add to LT?

[Whitepaper](https://www.bittorrent.com/btt/btt-docs/BitTorrent_(BTT)_White_Paper_v0.8.7_Feb_2019.pdf).

**Comment by FranciscoPombal** [comment]
Isn't Tron just another classic shitcoin IPO scam? Certainly seems to be:
https://torrentfreak.com/magnificent-bittorrent-speed-or-half-baked-magic-beans-190714/

**Comment by ghbplayer** [comment]
Almost all cryptocurrencies are useless and most are horrible ideas. Using some form of token currency does make sense for bittorrent though. I despise cryptocurrencies but there are still good uses for them.

**Comment by FranciscoPombal** [comment]
> Almost all cryptocurrencies are useless and most are horrible ideas. Using some form of token currency does make sense for bittorrent though. I despise cryptocurrencies but there are still good uses for them.

Like my link in the previous post shows, it doesn't even seem to bring tangible benefits to the swarms.

**Comment by ghbplayer** [comment]
Did you expect much benefit in an already well-seeded swarm? The primary benefits from BTT are getting people to seed longer and kick-starting your download when you have nothing to share.

**Comment by ghbplayer** [comment]
@arvidn, I assume from your lack of comment you're not interested in supporting this. That's fine, I'm not willing to put in the work either. For the record though, could you add your thoughts? I'm sure other people will ask in the future.

**Comment by arvidn** [comment]
Right, there are are a few reasons I’m not jumping at this.

* the general problem of creating incentives across swarms is big, and I have more pressing issues in libtorrent 
* I’m not convinced that BTT solves the problem well, but it’s partially caused by the next point
* I don’t believe the protocol is documented in sufficient detail that it *could* be implemented by a 3:rd party

In general I have more faith in the approach taken by the Tribler team at delft.

**Comment by ghbplayer** [comment]
You're right, I can't find implementation documents. I wonder why. From reading the whitepaper I have concerns about scale and efficiency. I also suspect the entire problem could be solved a better way.

**Comment by Knocks** [comment]
Setting aside the macroeconomics of token/crypto incentives, the biggest reason not to implement this is that Tron holds a vast number of BTT tokens and promoting a specific token by integrating it in the torrenting ecosystem is in their direct financial interest.  There is a major conflict of interest here.

**Comment by mozo78** [comment]
It would be great to add support. I don't wan't to use crap like uTorrent. And it's unavailable on Linux.

**Comment by ValeZAA** [comment]
>Tron holds a vast number of BTT tokens and promoting a specific token by integrating it in the torrenting ecosystem 

They need to hold a vast amount to burn it. Just like they burn Tron, that causes deflation and increases the price. They burned Tron just a week ago. BTT not yet.

>don't wan't to use crap like uTorrent

You do realise uTorrent is the least crap app for uTP protocol? Though all recent Nagle fixes maybe made this app better.

**Comment by ShrirajHegde** [comment]
This is a great idea, but something existing and controlled by someone else like BTT is a bad idea. 

Cryptocurrency as a reward for seeding makes a lot of sense, but it is better to stay away from any currency associated and regarded as "investment".

However, a crypto as a medal for seeding might be a great idea to incentivize seeding, which might gain actual transactional value than an "investment" like the rest. This can totally create phenomenon like "seeding farms" where rare torrents are seeded for bounty and the possibilities are endless. This is one of the few places where a blockchain actually makes sense, as BitTorrent protocol is already a distributed protocol.

Again, it needs a careful consideration, with emphasis on not treating it as an investment or trading or any other shady stuff regular cryptocurrencies involve themselves with.

Hopefully this is reconsidered when the irrational crypto craze dies down.

@arvidn What is your opinion on this topic in July 2024?

**Comment by ValeZAA** [comment]
>This can totally create phenomenon like "seeding farms" where rare torrents are seeded for bounty and the possibilities are endless.

This is very much the case for the last 4 years. That is point. People were earning 1000$ from this... wow

**Comment by ShrirajHegde** [comment]
The problem is, with tokens line BTT which are valued outside BitTorrent ecosystem, it is risky and unstable. Ideally, nothing outside the BitTorrent ecosystem should affect the value of it. It should at least start, valueless outside the ecosystem until it gains widespread adaption. Any real cryptocurrency should avoid the "investment" angle. There is a real chance it becomes a Ponzi scheme without any single person orchestrating it (basically a bubble). This currency should not fluctuate randomly due to speculation as the "value" of seeding/leeching traffic are pretty much constant, due to the ubiquitousness of unlimited internet connections.

As @arvidn mentioned, I checked out Tribler. It is doing new things, but alternative approaches might be able to improve the ecosystem with different approaches. Anonymity is not the highest priority for everyone. If I understand correctly, Tribler is an academic project with strict goals than a practical project at this point of time and has a strong focus on anonymity and decentralization

But other things people are concerned with are:
 - Detection of BitTorrent traffic
 - Lack of public IP address/port forwarding/opening a port
 - Both peers behind CGNAT
 - People on Mobile data/Metered connection
 
 If a currency can provide incentives for seed box/VPS users to help out these users, it would be incredibly great. Like behaving as TURN servers relaying traffic between two devices or a Debrid service relaying BitTorrent through TCP/HTTPS. Again, the possibilities are countless, as public torrents currently do not have a real incentive for seeding.

**Comment by ValeZAA** [comment]
>Again, the possibilities are countless, as public torrents currently do not have a real incentive for seeding.

That is not true. Rutracker and many ithers have people that are paid to preserve content.

>This currency should not fluctuate randomly due to speculation as the "value" of seeding/leeching traffic are pretty much constant, due to the ubiquitousness of unlimited internet connections.

It should. This is how free market and stock/spot trading works.

>People on Mobile data/Metered connection

Not an issue at all. Most people are and most prople are not even using a pc anymore.
