### ISSUE TITLE
file related api error on windows

### ISSUE THREAD

**Issue by MassaRoddel** [arvidn/libtorrent#428]
Using the recent master I get file access related errors (87 - wrong parameter). These errors seem to be caused by calling WaitForMultipleObjects() in pwritev() with more than MAXIMUM_WAIT_OBJECTS (64 on Win7 64bit). While debugging it I saw values up to 123.

**Comment by arvidn** [comment]
the fix for this was merged into RC_1_1 yesterday, which in turn was merged into master last night (less than 24 hours ago). Could you make sure you have that change? (specifically, in file.cpp there's now a wrapper function around WaitForMultipleObjects()).

If you have that patch and there was a place I missed, please re-open this ticket.
