### ISSUE TITLE
Periodic `Try again` (code 11) error during downloading

### ISSUE THREAD

**Issue by proninyaroslav** [arvidn/libtorrent#4281]
**Please provide the following information**

libtorrent version (or branch): 1.2.x

platform/architecture: Android arm/x86

Hi. I noticed that on `1.2.x` version I often get the `asio::error::try_again` error (by alerts), especially for large torrents that download for more than 5 minutes. This error pauses the download. This is not critical, but the download speed drops if I resume it again. As far as I know, this is a socket error that says that resource is temporarily unavailable. On `1.1.x` version, I almost didn't see this error. Is this normal?

**Comment by arvidn** [comment]
which kind pf alert, specifically, do you get this error code in? Is it `torrent_error_alert`?
Do you have any more information from the alert? like other fields.
If it is a `torrent_error_alert`, what is the `filename()`?

**Comment by proninyaroslav** [comment]
Yes, `torrent_error_alert`. `filename()` gives me the name of the file that is currently downloading. I don't have much information, I looked at the log and didn't find any prerequisites for the error appearance. `torrent_handle::resume()` after handling error solves the problem, but usually the error appears several times in a row and only then the torrent downloads normally without any errors.

**Comment by arvidn** [comment]
ok, so it is most likely a disk I/O operation that's failing with `EAGAIN` then. That's unusual, I'm not using any asynchronous I/O. Do you also get a `file_error_alert`? if not, make sure you have `alert::status_notification` enabled in the `alert_mask`.

It has an `operation_t` field in it, which tells a bit more about what happened.

**Comment by proninyaroslav** [comment]
`file_error_alert`: `disk error: (11) Try again [write : file_open]`. I was probably mistaken that this is `asio` error, sorry.

**Comment by arvidn** [comment]
errno 11 on android is `EAGAIN` ([here](https://android.googlesource.com/kernel/lk/+/dima/for-travis/include/errno.h)). the `file_open` operation in that error code means it was the error returned by `open()`. Which is odd, because the [man page](http://man7.org/linux/man-pages/man2/open.2.html) says it cannot fail with that error code. (that's the linux man page, I couldn't find one specific for android).

Without any documentation on how to interpret `EAGAIN` from `open()`, it's hard to implement handling of it. Just blindly retrying in a loop is most likely a bad idea.

**Comment by ssiloti** [comment]
While `EAGAIN` is not listed in the man page for `open()`, `EWOULDBLOCK` is and that is a synonym for `EAGAIN`. That being said, the man page says `EWOULDBLOCK` is only returned when the `O_NONBLOCK` flag is specified, which libtorrenet does not do. There's another catch though, the error documentation in the man pages has always been woefully incomplete. The list of error codes for a syscall and their causes should not be taken as exhaustive.

**Comment by arvidn** [comment]
@proninyaroslav are you using an NFS drive? https://access.redhat.com/solutions/4392111

**Comment by proninyaroslav** [comment]
@arvidn 
I think I understood the reason. I'm using a Java wrapper over `libtorrent` (by JNI) https://github.com/aldenml/libtorrent4j. It implements POSIX interface, this helps me download torrents both to the classical file system and to the Android [Storage Access Framework](https://developer.android.com/guide/topics/providers/document-provider). In the case of the `EAGAIN` error, I used standard POSIX calls to the file system, which are wrapped with C++ code ([here](https://github.com/aldenml/libtorrent4j/blob/f24cefee92755ec2decf0020fb6497f8545ae186/swig/libtorrent.h#L315)). 

Without using this POSIX wraper, I don't see `EAGAIN`.

**Comment by arvidn** [comment]
I see. So there's some Java implementation of `open()` that returns `EAGAIN`. I have three questions:

1. Is this an official Java posix wrapper? What I see in the code you link to only seems like an interface that could be implemented by Java.

2. If this is an official implementation, do you know under what conditions it return `EAGAIN`? and what would be reasonable to do when it happens?

3. How is the call to `open` in libtorrent intercepted, to be replaced by this wrapper? is it using function interpositioning to replace the libc functions?

**Comment by arvidn** [comment]
aha, found [it](https://github.com/aldenml/libtorrent4j/blob/f966d9e81be4aa73dea1e8d284505eee844e77d7/.travis.yml
) :) 

In fact, @aldenml may know more about this `EAGAIN` business

**Comment by aldenml** [comment]
well, yes :) I know a little bit about it (the mentioned posix wrapper).

I remember receiving this error, causing a lot of bad behavior (not only slowing down transfers). Now, what could be happening (and it is my theory from the days I was actively working on that hack), is that since the actual "open" happens in Java, which in turns eventually triggers all sort of native calls (not only `::open`), the last `errno` simply does not correspond to something `::open` should finish with.

I remember adding `void set_posix_errno(int val)` to able to perform some corrections.

Now, I don't think this should be troubleshot here (in `libtorrent`) unless a case can be reproduced in android without all that java layering.

**Comment by proninyaroslav** [comment]
@aldenml 
At first, I didn't expect this to be a POSIX wrapper problem. But unfortunately, this turned out to be a POSIX wrapper problem. And this is already the 6th problem that I noticed (and the 2nd problem with the `open()` call https://github.com/aldenml/libtorrent4j/issues/52), you should be remember that I have opened issues in your repo.

**Comment by aldenml** [comment]
@proninyaroslav yes, I remember, and I wish I could have the necessary time to spend on fixing them.

**Comment by proninyaroslav** [comment]
@aldenml thank you. I think I can close this issue and open it in `libtorrent4j`.

**Comment by arvidn** [comment]
it sounds like this ticket can be closed then
