### ISSUE TITLE
'Moving' files should behave the same way as 'checking' files wrt to IO.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [arvidn/libtorrent#4309]
Continuing from conversation here: https://github.com/qbittorrent/qBittorrent/issues/9407

Currently, any client using libtorrent that also supports moving must figure out a way to queue moves to prevent disk subsystem thrashing (as libtorrent will copy them all simultaneously).  This has pretty bad performance on most IO systems (as most apps are not going to run on systems where the copies could happen in parallel without perf impact).  

Libtorrent already is able to do very heavy IO ops in a way that best makes use of hte underlying storage system.  i.e. it can already check files in serialized fashion to ensure that checking happens much more quickly than if it were done in parallel.  It would be great if it could do the same for moving files.

Note: if it does this, it means all clients get this functionality instead of all of them having to figure out a way to schedule this.  Note that this is not an argument to push all client functionality into libtorrent, merely one heavy-io OP that libtorrent already exposes teh functionality for.

**Comment by CyrusNajmabadi** [comment]
--

> "Good behavior" for one user may be bad behavior for another. For instance, someone might expect to be able to move files located on separate drives in parallel. 

Someone might expect to be able to check multiple files in parallel.  Such expectations are reasonable, and i would have no problem with the software making it possible for people to specify that thsi is what they want.

However, this seems like the *abnormal* case.  i.e. which is more likely across all your users: that they have torrents being moved simultaneously to *multiple different drives*?  Or that they're moving to the same drive?

The software should work well for the more common case, and optionally provide ways to work well for the less common cases.

> The original behavior for checking files in libtorrent was to only check one at a time. This was extended to allow checking files in parallel (but the default was still one at a time).

Sounds *great*.  Having the same for *moving* would be awesome.  Looks like there's good precedent for it in the library :)

>  I won't repeat my response.

As i said, your response rings hollow to me.  All the reasons you've given for 'checking' to be done in the manner it is done, also seem to apply just as well to 'moving'.

> copyfile() copies the file, it doesn't queue it up and do it later. It's reasonable because it's a low level API.

That's a choice of the API currently.  There's no reason that you only have to supply a low-level copy op, just like there would be no need to just have a low-level 'check' API that the app layer would have to coordinate to prevent thrashing.  

> If you want to respond, PLEASE file a ticket in the libtorrent repo.

Sure.

**Comment by ghbplayer** [comment]
That conversation was painful to read, but it came to an agreeable resolution. Is there any reason to keep this issue open over here?

**Comment by arvidn** [comment]
(I missed this, I didn't get an email notification of it).

> However, this seems like the abnormal case. i.e. which is more likely across all your users: that they have torrents being moved simultaneously to multiple different drives? Or that they're moving to the same drive?

I think part of the core of this issue is who are users. You may be considering humans using qBT or Deluge as users. They are users of qBT and Deluge, but not users of libtorrent. qBT is *one* user of libtorrent, Deluge is *one* user, facebook is *one* user, Blizzard is *one*, BitTorrent Inc. (or I suppose, tron foundation) is *one*.

I argue that it's libtorrent's responsibility to cater to its users, and qBT's responsibility to cater to its users.

However, even if it turns out the majority of libtorrent users would like to have the functionality of serializing moves, it's still not very close to the core of bittorrent functionality (I would argue). There are much more pressing issues and important optimizations that are core to the bittorrent functionality, that essentially *have* to go into libtorrent. (examples are the recent fixes to announcing behaviors, support for multi-homed systems and IPv6, and SOCKS5 proxy support).

> 
> However, this seems like the abnormal case. i.e. which is more likely across all your users: that they have torrents being moved simultaneously to multiple different drives? Or that they're moving to the same drive?
> 
> The software should work well for the more common case, and optionally provide ways to work well for the less common cases.

My stance is that the library should not paint anyone into a corner of not being able to achieve optimum performance. Which means only implementing higher level logic as long as it doesn't perform worse under certain conditions. That might leave a low level API as well as a high level API. Or just have a high level API that has a high quality implementation (which is a lot more work to create and maintain).

> > The original behavior for checking files in libtorrent was to only check one at a time. This was extended to allow checking files in parallel (but the default was still one at a time).
> 
> Sounds great. Having the same for moving would be awesome. Looks like there's good precedent for it in the library :)

Your mental model does not match how libtorrent actually works. Checking files is a state that mutually exclusive other states such as allocating files on disk, downloading, seeding, checking fast-resume-file. A torrent can only be in one of those states at a time, and they are all subject to certain queuing rules (except checking fast-resume, which is a short state while starting up).

Moving the storage of a torrent is orthogonal to those states. It doesn't matter whether you categorize states as "heavy I/O" and suggest they are similar, they aren't. 

> As i said, your response rings hollow to me. All the reasons you've given for 'checking' to be done in the manner it is done, also seem to apply just as well to 'moving'.

The only way I can see it also apply to moving is by re-defining the states to make moving also mutually exclusive to all other state (which it isn't). You can move a torrent regardless of which state it's in.

One significant difference between moving and checking is that checking is a fundamental part of bittorrent. That functionality cannot be removed. It's also a fundamental part of a *progression* of states all torrents have to go through. After checking, the torrent always transition into the "downloading" state. The fast-resume state is an optimization to skip the checking state, but as an optimization, it is really just a substitute for the checking state, so I think it's fair to argue that all torrents have to go through the checking state. They all do at least once, when they're first added.

> Note: if it does this, it means all clients get this functionality instead of all of them having to figure out a way to schedule this. Note that this is not an argument to push all client functionality into libtorrent, merely one heavy-io OP that libtorrent already exposes teh functionality for.

Serializing moving files of can easily be shared among libtorrent users as a separate library (as long as someone implements it).



> > copyfile() copies the file, it doesn't queue it up and do it later. It's reasonable because it's a low level API.
> 
> That's a choice of the API currently. There's no reason that you only have to supply a low-level copy op, just like there would be no need to just have a low-level 'check' API that the app layer would have to coordinate to prevent thrashing.

The reason is to not paint anyone into a corner where they cannot get optimal performance. This is generally something operating systems try to avoid as well, hence lower level APIs first, and maybe higher level APIs later. The choice of the `copyfile()` API isn't arbitrary (and it's pretty much locked in, since it's provided by the operating system. it can't easily change).
