### ISSUE TITLE
anonymous_mode sends local 10.x.x.x and 192.168.x.x ips to udp trackers

### ISSUE THREAD

**Issue by Safari77** [arvidn/libtorrent#4340]
libtorrent version (or branch):
1.2.4 + https://github.com/arvidn/libtorrent/pull/4339
platform/architecture:
Fedora 30 Linux x86_64

compiler and compiler version:
gcc 9.2.1

When using qbittorrent with anonymous mode enabled, it sends local 10.x.x.x and 192.168.x.x ips to udp trackers (instead of 0.0.0.0 as it should in anonymous mode).

>Specifically, if you listen to a single IP address, a socket bound to that address will be used to connect to the tracker.

Yes, but the public IP address is often different when using NAT or VPN.

>It sounds like you see two announces to the tracker, is that right? Are both of those networks (192.168.x.x and 10.x.x.x) connected to the internet?

wireguard device has 10.x.x.x address, and the public IP address is something else after VPN provider does its thing. It does not help to send 10.x.x.x etc to public trackers (e.g. tracker's address not 192.168.x.x or 10.x.x.x or 127.x.x.x or 172.16-31.x.x etc).

**Comment by arvidn** [comment]
I would like to understand what you mean by "it sends local 10.x.x.x and 192.168.x.x ips to udp trackers".

Are you talking about the source IP field of the IP header? That field cannot be set to 0.0.0.0, it has to contain a return address for you to be able to receive responses. In fact, the kernel will fill this field in.

On a local network the source address has to be the local address, it will be replaced with your external address by the NAT.

You say libtorrent sends *both* of those local IPs. Are you saying you see two announces to the tracker?

That's probably because libtorrent believe those two networks are both, independently, connected to the internet, having two separate external IPs. Is that not the case?

If you listen to *only* a single IP address, i.e. only set a single IP in the `listen_interfaces` setting, libtorrent should *only* announce from that IP. However, if you listen to multiple IPs, or every IP associated with a device, libtorrent may announce each of those to the tracker (if it has reason to believe they have different external IPs).

What do you set your `listen_interfaces` to?

I take it you have at least those two local networks configured.
What does your routing table look like? Do you have two default routes, with gateways?

**Comment by Safari77** [comment]
Not the IP field, but UDP packet contents have the 10.x.x.x or 192.168.x.x address in the announce:
```udp_tracker_connection::send_udp_announce()```
I didn't say it sends both of these local IPs.  But it can send 10.x.x.x or 192.168.x.x, depending of interface configuration.  

qbittorrent has settings Connection\Interface=wg Connection\InterfaceName=wg Connection\InterfaceAddress=0.0.0.0 (made by setting "Listen on all IPv4 addresses.".

192.168.x.x is used for local networking and also, the router gives me 192.168.x.x address via dhcp. Then the wireguard device is configured so that libtorrent doesn't figure it out correctly (we have discussed about this earlier).

**Comment by arvidn** [comment]
I see. So we're talking about the IP field in the UDP announce message. Similar to the `&ip=` parameter one can send to an HTTP tracker.

The relevant code can be found [here](https://github.com/arvidn/libtorrent/blob/RC_1_2/src/udp_tracker_connection.cpp#L715).

As you can see, this field is entirely based on the configuration option `settings_pack::announce_ip`. The option is documented [here](http://libtorrent.org/reference-Settings.html#announce_ip). By default it's an empty string, which will leave this field blank.

The documentation should probably explain how this field is not really meant to be set under normal circumstances though.

**Comment by Safari77** [comment]
I made a stupid error with tcpdump options. I remembered -X shows packet without IP headers but that was not the case.  I verified with wireshark and libtorrent does not send my local IP addresses in anonymous mode.  Sorry for the trouble. And fortunately qbittorrent does not set ```announce_ip```.
