### ISSUE TITLE
Report error if a torrent has no working tracker. 

### ISSUE THREAD

**Issue by an0n666** [arvidn/libtorrent#4371]
libtorrent version (or branch):
1.2.4

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

What I find in libtorrent based clients (deluge, qBt) is that they don’t list torrents with tracker errors in the Errored torrents list. This is problematic for PT users. Sometimes torrents get deleted/banned from the tracker but there’s no indication that something is wrong with the torrent. I’m suspecting it’s a limitation in the underlying layer(libtorrent). If that’s the case, then please treat torrents as errored if none of the trackers are working.

**Comment by arvidn** [comment]
I don't see why the [error code](https://libtorrent.org/reference-Core.html#last_error) in `announce_entry` would not be sufficient for this.

**Comment by an0n666** [comment]
That helps to find out which tracker isn’t working. But can it be used to find out which torrent has no working tracker and list it as error? If yes, then idk why these clients behave this way.

**Comment by arvidn** [comment]
oh, you mean no working tracker should be "promoted" to an error on the *torrent*?
Typically, errors on torrents are fatal, in that they pause the torrent as well. It seems a bit harsh that a, possibly transient, tracker failure would do that.

**Comment by an0n666** [comment]
> oh, you mean no working tracker should be "promoted" to an error on the _torrent_?
> Typically, errors on torrents are fatal, in that they pause the torrent as well. It seems a bit harsh that a, possibly transient, tracker failure would do that.

Not saying it should be paused. If an error is posted then it'd be easy to detect a torrent with no working trackers just by looking at the Errored torrents counter. For a private torrent a non working tracker is considered fatal..or you'd say otherwise?

**Comment by an0n666** [comment]
Arvidn I believe it’s logical to post an error for private torrents when all the trackers return an error. Private torrents rely on trackers so those torrents could be counted as non working.

**Comment by arvidn** [comment]
I'm not convinced that such special case logic belongs in libtorrent.

**Comment by arvidn** [comment]
a client could just as easily detect that all trackers have failed and alert the user of it.

**Comment by FranciscoPombal** [comment]
@an0n666 
If libtorrent promotes "no trackers working" to a torrent-level error, then a torrent with no working trackers will get paused until the user finds out and resumes it manually.

In particular, this would lead to the following situation with private torrents:
1. Suppose that in a private torrent announcing to only one private tracker, a single announce to the tracker fails due to whatever reason (temporary connectivity problems on the user's side, temporary tracker downtime...).
2. Then, the torrent will get paused indefinitely on the client, until the user manually intervenes.

You could work around this by:
1.Implementing client-side logic to auto-retry resuming private torrents that were auto-paused due to tracker errors.
2. Implement client-side or in libtorrent some sort of logic to parse private torrent tracker error messages (to look for "torrent not registered", "torrent removed", etc) and pause the private torrents accordingly.

Both of these options are sub-optimal for obvious reasons:
- Option 1 seems very complex state logic that needs to be integrated with the existing logic.
- Option 2 is brittle since tracker error messages are not standardized (especially in private trackers)

IMO, both of these options are worse than the client-side implementation @arvidn mentioned:
- For each torrent, if it is private _or_ if it is public but the DHT is turned off/not working: if it's trackers are not working, list as "Errored".

It seems fairly simple to implement this client-side. Just receive the alert, iterate through the tracker announce results and execute the appropriate action accordingly (e.g. display in the "Errored" column).

A clearer description of the algorithm I have in mind, in pseudo-python (only the part relevant to private torrents, and public ones when DHT is off/down):

```python
for torrent in torrents:
    if torrent.isPrivate() or not dht:
        state = working
        bool oneWorking = false
        for tracker in torrent.trackers():
            if tracker.isWorking():
                oneWorking = true
            if tracker.isErrored():
                state = warn
        if not oneWorking:
            state = errored
        torrent.setState(state)
```

I decided to include the corner case of the DHT being off or not working as well as an extra "Warned" category, for the corner case where one private torrent has more than one tracker, for completeness. In practice, torrents from private trackers have only one tracker entry per torrent, but not much is lost from having this additional flexibility. In addition, the same code would have to be somewhat repeated for some sort of DHT on/off alert.

**Comment by arvidn** [comment]
my understanding is that most people would want to interpret a failing private tracker as they have added the torrent before the tracker has white-listed it, and want to retry as soon as possible, to race starting it, i.e. a failing tracker is *not* an error, but an expected state early on in the torrent's life.

**Comment by FranciscoPombal** [comment]
@arvidn 

The racing stuff is another matter entirely, but 100% compatible with my suggestion above. As long as the private torrent does not receive a successful response from the private tracker, it stays in the "Errored" column.

Come to think of it, qBittorrent should probably have a finer grain filtering of states - we could possibly distinguish between fatal errors (corresponding to fatal libtorrent events, torrent gets paused) and "connectivity errors" (an indication that something is wrong, such as non-working trackers, but the torrent is still resumed and retrying). A racing torrent would start out in the "connectivity errors" column as the client would detect the tracker error alerts and put it there.

**Comment by an0n666** [comment]
My main concern here in deleted/banned torrents. Transient tracker errors can be overlooked. But if a tracker is returning unregistered torrent or banned torrent msgs then those should come into users attention. As there’s no point in keeping such a torrent active anymore. I think this would require parsing the msgs sent by tracker and list such torrents in red/errored state.

**Comment by FranciscoPombal** [comment]
@an0n666 

> My main concern here in deleted/banned torrents. Transient tracker errors can be overlooked. But if a tracker is returning unregistered torrent or banned torrent msgs then those should come into users attention. As there’s no point in keeping such a torrent active anymore. I think this would require parsing the msgs sent by tracker and list such torrents in red/errored state.

I disagree with the parsing. The messages are not standardized at all. I still think the approach in my comment above is best. Torrents (private) that get tracker erros go into a "Connectivity errors" (or even the existing "Errored" category). Then the user manually inspects the tracker message and decides whether to stop and remove those torrents or not.

**Comment by an0n666** [comment]
> I disagree with the parsing. The messages are not standardized at all. I still think the approach in my comment above is best. Torrents (private) that get tracker erros go into a "Connectivity errors" (or even the existing "Errored" category). Then the user manually inspects the tracker message and decides whether to stop and remove those torrents or not.

That would help, specially for private torrents.

Closing this since looks like this can be addressed easily by the client itself.

**Comment by an0n666** [comment]
@arvidn 
May I know why is_working() was marked deprecated in libtorrent 1.2 in `announce_entry`?
I'm trying to use it to find out if a torrent has at least one working tracker.
And since qBt is no longer using deprecated functions I'm not seeing any easy way of finding out if a torrent has at least one working tracker. I could check though the endpoints but it's not available in the torrent_handle.

**Comment by arvidn** [comment]
the main reason is that it is really an internal function, and having it exposed to clients makes it more difficult to refactor internals in libtorrent. In libtorrent `master` the `announce_entry` family of types have been separated between internal and public versions now, to not provide any functions, but just the information.

You can trivially implement your own `is_working()` function, since it just uses the public fields from the `announce_entry`.

**Comment by arvidn** [comment]
As you can see [here](https://github.com/arvidn/libtorrent/blob/RC_1_2/include/libtorrent/announce_entry.hpp#L144), it's just an alias for `fails == 0`

**Comment by arvidn** [comment]
right, so it depends a bit on what you want `is_working()` to mean. Say you listen on an IPv4 and an IPv6 address. announcing IPv4 worked (`fails == 0`) but IPv6 failed (`fails == 1`). Should the tracker be considered working?

**Comment by an0n666** [comment]
I want is_working to return true if at least one of the endpoints were working. But seems like keeping count of failures is not the correct way.

**Comment by arvidn** [comment]
so, if at least one of the endpoints has a fail counter of 0, is that not the condition you're looking for? or do you want to treat trackers that haven't been tried yet as not working?, if so, you could also look at `start_sent`, if it's true the initial announce has been made

**Comment by an0n666** [comment]
Sorry my main issue wasn’t about checking if a tracker is working or not. qBt already does that by going through all the endpoints. 

I just wanted an easy way to check through all the trackers in a torrent to find out if at least one was working. So there’s no other way other than going through all endpoints for each tracker right?

**Comment by arvidn** [comment]
right
