### ISSUE TITLE
some ssl symbols are missing from self compiled libtorrent static library

### ISSUE THREAD

**Issue by grzs** [arvidn/libtorrent#4418]
libtorrent version (or branch): 
1.2.5 RC_1_2

platform/architecture:
MacOSX10.15

compiler and compiler version: 
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin19.3.0
Thread model: posix

I compiled libtorrent with CMake and it had failed until I set Boost_NO_BOOST_CMAKE:BOOL=ON
When it has succeeded it still complained that sha1.cpp.o and sha512.cpp.o has no symbols...

When I tried to compile my project using libtorrent static lib it failed, because couldn't find some ssl related symbols in the static lib.
Undefined symbols for architecture x86_64:
  "_SHA512_Final", referenced from:
      libtorrent::hasher512::final() in libtorrent.a(hasher512.cpp.o)
  "_SHA512_Update", referenced from:
      libtorrent::hasher512::update(libtorrent::span<char const>) in libtorrent.a(hasher512.cpp.o)
  "_SHA512_Init", referenced from:
      libtorrent::hasher512::hasher512() in libtorrent.a(hasher512.cpp.o)
  "_SSL_set_bio", referenced from:
      boost::asio::ssl::detail::engine::engine(ssl_ctx_st*) in libtorrent.a(socket_type.cpp.o)
  "_SSL_shutdown", referenced from:
      boost::asio::ssl::detail::engine::do_shutdown(void*, unsigned long) in libtorrent.a(socket_type.cpp.o)
  "_GENERAL_NAMES_free", referenced from:
      boost::asio::ssl::rfc2818_verification::operator()(bool, boost::asio::ssl::verify_context&) const in libtorrent.a(socket_type.cpp.o)
...

I attached CMakeCache.txt and the whole compile error log.

Thanks in advance!
[CMakeCache.txt](https://github.com/arvidn/libtorrent/files/4332416/CMakeCache.txt)
[compile_error.log](https://github.com/arvidn/libtorrent/files/4332417/compile_error.log)

**Comment by arvidn** [comment]
libtorrent can be built both with and without OpenSSL support. so `sha1.cpp` and `sha512.cpp` are internal implementations of those has functions, for when not linking against OpenSSL. However, it sounds like when you built libtorrent, it was configured to use OpenSSL, but when you linked against it, you did not include openssl in the link. So, that's most likely the problem.

Either build libtorrent without openssl support, and it will use its built-in hash functions instead of looking for them in openssl or build libtorrent with openssl support and make sure to include openssl when linking. that's `libcrypto` and `libssl`.

**Comment by grzs** [comment]
Thank you for the answer. Is there a variable in CMake I could turn ssl
off? I found encryption:BOOL but it didn't work when I turned it off.
Sorry, I am not familiar to CMake and I don't know how can I list build
variables.

Arvid Norberg <notifications@github.com> ezt írta (időpont: 2020. márc.
14., Szo 12:13):

**Comment by arvidn** [comment]
You can use `ccmake`

**Comment by grzs** [comment]
ok, many thanks!

Arvid Norberg <notifications@github.com> ezt írta (időpont: 2020. márc.
14., Szo, 13:13):
