### ISSUE TITLE
UPNP doesn't work with wireguard VPN

### ISSUE THREAD

**Issue by leigh123linux** [arvidn/libtorrent#4471]
libtorrent version: rb_libtorrent-1.2.5-1.fc33.x86_64

platform/architecture: Linux fedora 33 x86_64

compiler and compiler version: gcc (GCC) 10.0.1 20200311 (Red Hat 10.0.1-0.9)

I am using a wireguard vpn, after updating from libtorrent-1.1.13 UPNP no longer works.
Qbittorrent reports the router can't be found, it appears to be using the wrong IP address

```
http://239.255.255.250:1900*
```

The router is on  192.168.0.1

```
Frame 120: 128 bytes on wire (1024 bits), 128 bytes captured (1024 bits) on interface azirevpn-uk1, id 0
    Interface id: 0 (azirevpn-uk1)
        Interface name: azirevpn-uk1
    Encapsulation type: Raw IP (7)
    Arrival Time: Mar 27, 2020 08:59:50.029601164 GMT
    [Time shift for this packet: 0.000000000 seconds]
    Epoch Time: 1585299590.029601164 seconds
    [Time delta from previous captured frame: 0.000057332 seconds]
    [Time delta from previous displayed frame: 0.000057332 seconds]
    [Time since reference or first frame: 25.660413340 seconds]
    Frame Number: 120
    Frame Length: 128 bytes (1024 bits)
    Capture Length: 128 bytes (1024 bits)
    [Frame is marked: False]
    [Frame is ignored: False]
    [Protocols in frame: raw:ip:udp:ssdp]
    [Coloring Rule Name: UDP]
    [Coloring Rule String: udp]
Raw packet data
Internet Protocol Version 4, Src: 10.20.13.156, Dst: 239.255.255.250
    0100 .... = Version: 4
    .... 0101 = Header Length: 20 bytes (5)
    Differentiated Services Field: 0x00 (DSCP: CS0, ECN: Not-ECT)
        0000 00.. = Differentiated Services Codepoint: Default (0)
        .... ..00 = Explicit Congestion Notification: Not ECN-Capable Transport (0)
    Total Length: 128
    Identification: 0x8dfc (36348)
    Flags: 0x4000, Don't fragment
        0... .... .... .... = Reserved bit: Not set
        .1.. .... .... .... = Don't fragment: Set
        ..0. .... .... .... = More fragments: Not set
    ...0 0000 0000 0000 = Fragment offset: 0
    Time to live: 1
    Protocol: UDP (17)
    Header checksum: 0xe3c6 [validation disabled]
    [Header checksum status: Unverified]
    Source: 10.20.13.156
    Destination: 239.255.255.250
User Datagram Protocol, Src Port: 40409, Dst Port: 1900
    Source Port: 40409
    Destination Port: 1900
    Length: 108
    Checksum: 0x0828 [unverified]
    [Checksum Status: Unverified]
    [Stream index: 11]
    [Timestamps]
        [Time since first frame: 0.000000000 seconds]
        [Time since previous frame: 0.000000000 seconds]
Simple Service Discovery Protocol
    M-SEARCH * HTTP/1.1\r\n
        [Expert Info (Chat/Sequence): M-SEARCH * HTTP/1.1\r\n]
            [M-SEARCH * HTTP/1.1\r\n]
            [Severity level: Chat]
            [Group: Sequence]
        Request Method: M-SEARCH
        Request URI: *
        Request Version: HTTP/1.1
    HOST: 239.255.255.250:1900\r\n
    ST:upnp:rootdevice\r\n
    MAN:"ssdp:discover"\r\n
    MX:3\r\n
    \r\n
    [Full request URI: http://239.255.255.250:1900*]
    [HTTP request 1/4]
    [Next request in frame: 124]
```

**Comment by FranciscoPombal** [comment]
Probably related to https://github.com/qbittorrent/qBittorrent/issues/12253

**Comment by arvidn** [comment]
what is the expected behavior? If you're using a VPN, do you still want to accept incoming connections from your regular connection? Otherwise, why would you want to map ports that aren't used?

The intended behavior (which I think makes sense) is that an SSDP search is performed on the VPN network. If there is a InternetGatewayDevice there, an attempt will be made to map a port. For example, I would expect a lot of VPNs will still be private networks with a gateway to the internet, where it might make sense to allow port mappings.

**Comment by FranciscoPombal** [comment]
@arvidn 
I would expect a lot of VPNs will still be private networks with a gateway to the internet, where it might make sense to allow port mappings.

yes, most popular commercial VPN providers allow port mapping IIRC.

>If you're using a VPN, do you still want to accept incoming connections from your regular connection?

In case @leigh123linux wants to do this, does libtorrent support it?

@leigh123linux please clarify if that's what you want or if the port mapping is failing in the VPN connection itself.

**Comment by arvidn** [comment]
the details about what UPnP is doing will mostly be logged only when the `port_mapping_log_notification`  flag is set in the `alert_mask`. But there should be some other hints under the normal `port_mapping_notification` flag as well. But I don't get the impression qBT prints these to its log.

**Comment by FranciscoPombal** [comment]
@arvidn There has been talk of reworking qBittorrent's logging subsystem to properly support toggle-able logging levels. In that rework, we could probably also switch to a blacklist policy rather than a whitelist policy w.r.t libtorrent alerts, as I believe you have previously suggested.

A balance needs to be struck between performance during general usage and producing logs detailed enough to be useful to you in most cases.
With this in mind, can you give some pointers as to what alerts you would expect a client application to log at different logging levels? E.g. something like a "tier list" of alerts:

- "During normal operation, I would expect every alert to be blacklisted except x y and z"
- "With a verbose flag, maybe unblock all alerts of type w and those related to..."
- "With even more verbose..."

**Comment by arvidn** [comment]
I don't think logging levels is the right approach. I think, similar to how uTorrent does it, having checkboxes to enable different kinds of logging, depending on what one is looking for, makes the most sense.

That said, probably the *least* useful alert category to enable is `block_progress_notification`, `upload_notification`, and probably also `piece_progress_notification`. Those will be extremely verbose and expensive (especially at high download rates).

`picker_log_notification` is probably also quite fringe, and really only useful for debugging the piece picker.

All of the alert categories with the word "log" in it are low level and can also be pretty verbose, but they can be really helpful when understanding what's going on.

`stats_notification` are not meant for trouble shooting, and in fact aren't very useful for anything anymore (those alerts don't scale well).

**Comment by FranciscoPombal** [comment]
> I don't think logging levels is the right approach. I think, similar to how uTorrent does it, having checkboxes to enable different kinds of logging, depending on what one is looking for, makes the most sense.

I see.

> That said, probably the _least_ useful alert category to enable is `block_progress_notification`, `upload_notification`, and probably also `piece_progress_notification`. Those will be extremely verbose and expensive (especially at high download rates).
> 
> `picker_log_notification` is probably also quite fringe, and really only useful for debugging the piece picker.
> 
> All of the alert categories with the word "log" in it are low level and can also be pretty verbose, but they can be really helpful when understanding what's going on.
> 
> `stats_notification` are not meant for trouble shooting, and in fact aren't very useful for anything anymore (those alerts don't scale well).

Thanks, this is exactly what I wanted to know. I assume it would be useful to have everything else available through checkboxes (not always 1 checkbox per alert, of course)?

**Comment by an0n666** [comment]
I get the same router not found error on latest qbt when using a VPN. (Lib 1.2.5).

**Comment by arvidn** [comment]
@an0n666 one change (I would call it "fix") in recent libtorrent versions was to *only* attempt to discover UPnP InternetGatewayDevices on the networks libtorrent is listening on. In other wors, if you set your VPN network interface as the one to listen for incoming connections from, that's the network to look for a an internet gateway device to forward ports on.

I think that's reasonable behavior, I would like to know if there are any problems with that. In fact, I would think it's *undesirable* to look for Internet Gateway Devices on any other network, and forward ports for no reason. (since we're not listening for incoming connections on any other network anyway).

So, what isn't clear to me in this thread is; do VPN providers actually run UPnP Internet Gateway Devices on their network, to allow people to forward ports via the UPnP protocol?

If they do, did that used to work in earlier versions of libtorrent?

If they don't, it would seem this ticket is documenting correct behavior, not a sign of a regression.

**Comment by FranciscoPombal** [comment]
> one change (I would call it "fix") in recent libtorrent versions was to _only_ attempt to discover UPnP InternetGatewayDevices on the networks libtorrent is listening on. In other wors, if you set your VPN network interface as the one to listen for incoming connections from, that's the network to look for a an internet gateway device to forward ports on.
> 
> I think that's reasonable behavior, I would like to know if there are any problems with that. In fact, I would think it's _undesirable_ to look for Internet Gateway Devices on any other network, and forward ports for no reason. (since we're not listening for incoming connections on any other network anyway).

:+1: 

I think popular commercial VPNs allow forwarding specific ports only, chosen beforehand in the client software, but feel free to correct me. If they allow forwarding arbitrary ports automatically, maybe they are using something other than UPnP?

**Comment by an0n666** [comment]
Nope. VPNs don't use UPnP. I haven't seen it in any of them. 
I got confused by the error message which wasn't present in older versions.
 
Now I understand that it's a correct behaviour.

**Comment by iz8mbw** [comment]
There are VPN "providers" that supports UPnP.

**Comment by arvidn** [comment]
could someone give this patch a try? https://github.com/arvidn/libtorrent/pull/4595
