### ISSUE TITLE
Can queue order be stored?

### ISSUE THREAD

**Issue by zbooa** [arvidn/libtorrent#4605]
Like this:
Add a.torrent
Add b.torrent
Add c.torrent
...
I know that each torrent has a queue location
I think that after the restart
the order of the download queue still remains the same as that of the last closed download queue. But no similar function was found.
Libtorrent have this function?

**Comment by arvidn** [comment]
I'm curious if you have any specific kind of API in mind. The short answer is no, or probably no.
Since you can only add torrents one at a time in libtorrent, it would violate the invariant to be able to add a torrent to a queue position greater than the total number of torrents. So, you have to add the torrents in the order you want them in the queue, or sort them once they've all been added.

**Comment by zbooa** [comment]
> I'm curious if you have any specific kind of API in mind. The short answer is no, or probably no.
> Since you can only add torrents one at a time in libtorrent, it would violate the invariant to be able to add a torrent to a queue position greater than the total number of torrents. So, you have to add the torrents in the order you want them in the queue, or sort them once they've all been added.

specific kind of API ？No.
I am learning the examples provided in the source code, Here
https://github.com/arvidn/libtorrent/blob/48627d7dfe47fb50a99fbd429de25bebec129dfc/examples/client_test.cpp#L714

This is the recovery files in the loading folder. I just want to load them in the original queue order, so I have this idea.

**Comment by arvidn** [comment]
I'm open to suggestions of how this can be done. Ideally some way that doesn't introduce a lot of complexity, in either implementation or API

**Comment by zbooa** [comment]
> I'm open to suggestions of how this can be done. Ideally some way that doesn't introduce a lot of complexity, in either implementation or API

Ok, I get it. Thank you.
