### ISSUE TITLE
Possible to implement intermediate cache?

### ISSUE THREAD

**Issue by mleczan** [arvidn/libtorrent#4613]
Would it be possible to implement additional cache in between RAM disk cache and destination disk?
Rationale is to use SSD as cache for HDD, for instance having 128-256 GB SDD acting as cache for 8-16 TB HDD, downloading and storing pieces directly into SSD, evict (or just copy) finished pieces into HDD in sequential order.
Finished pieces could be left on SSD cache until there is demand for it (if not kept in RAM cache)
To achieve the same with only RAM disk cache it would need huge amount of RAM which is not available on most machines while free space on SSD is common case.

Currently I'm trying to download to SSD and move torrents to HDD however this solution is far from ideal for at least two reasons:
1) Torrents larger than free disk space on SSD have to be downloaded directly on HDD and can't benefit from SSD performance
2) Moving torrent from SSD to HDD will pause upload

**Comment by Ryrynz** [comment]
Good idea. Also being able to move torrents with pausing anything would be good too.

**Comment by arvidn** [comment]
There was a feature like this called `mmap_cache`, but it was removed for various reasons.
I think it's more reasonable to solve this kind of problem at the block layer, with something like lvmcache

**Comment by mleczan** [comment]
What about ability to seed while torrent is being moved? Would it be possible?
From what I've seen when torrent is moved from one drive to another it's copied and when all data on dest is available then it's deleted from source, which should allow to continue seeding while move is in progress. Whould this be possible?

**Comment by arvidn** [comment]
yes, it would be possible, but complicated. Currently the whole move operation is mutually exclusive all other disk jobs for that torrent. You can only discover that the files need to be copied (instead of renamed) *after* you have made actual OS calls to touch the files on disk (so, that definitely need to happen while no other disk operations are happening).

Once you've learned that you need to copy the files, the disk job no longer needs to be mutually exclusive other jobs. However, the way that's implemented is at the granularity of complete disk jobs.

I suppose one approach could be to break down the existing disk job into several. the first one to attempt a rename (which needs to be mutually exclusive). If it succeeds we're done. If it fails and need to copy + delete the files, it could issue a *new* disk job that is not mutually exclusive, that copies the files. When the copy job is complete, it can then post a new job, that *is* mutually exclusive, which deletes the files and redirect all subsequent disk operations to the new location.

That would probably be the most reasonable way of implementing this. Still a lot of work for a (somewhat) fringe use case. I would be happy to help anyone wanting to give that a stab. I would highly recommend doing that in `master` though, as the disk subsystem has changed a fair amount.

**Comment by mleczan** [comment]
Ok, thank you for detailed and informative explanation.
In that case possible gain is not worth the effort.
