### ISSUE TITLE
Rename the base name

### ISSUE THREAD

**Issue by lunatichai** [arvidn/libtorrent#4617]
libtorrent version (or branch): 1.2.5, 1.2.6

platform/architecture: win10 x64

compiler and compiler version: msvc2017 x64

Rename the base folder name not working. In API documentation says "If you want to rename the base name of the torrent (for a multi file torrent), you can copy the file_storage (see files() and orig_files() ), change the name, and then use remap_files()." But folder on HDD not renaming.

Pseudo code:
lt::file_storage fs= handle.torrent_file()->files();
fileStorage.set_name(newName);
std::shared_ptr<const lt::torrent_info> ptr;
ptr = std::const_pointer_cast<lt::torrent_info>(handle.torrent_file());
lt::torrent_info ti = *ptr.get();
ti.remap_files(fileStorage);

**Comment by arvidn** [comment]
doing that will not rename any files *on disk*. It will rename the files the torrent_info *will write* to disk once you add it to the session.

After that snipped of code you post, do you add `ti` to a session, and it downloads under the old name?

**Comment by lunatichai** [comment]
After add to a session `ti` downloads to new name. But how can i rename folder? When i renamed all files with `handle.rename_file` some files and old base folder was not removed. Should I delete them manually?

**Comment by arvidn** [comment]
did you get any errors?
did the files with the new name appear on disk? i.e. did it just leave behind the old, unused, file?

**Comment by lunatichai** [comment]
once i got assert: 

version: 1.2.6.0-ac4dd411c
file: 'src\torrent_info.cpp'
line: 1708
function: check_invariant
expression: m_files.file_name_ptr(i) < m_info_section.get() + m_info_section_size

stack:
 0: 00007FF679824748 libtorrent::print_backtrace +232  e:\projects\utorr\3rdparty\libtorrent-rasterbar-1.2.6\src\assert.cpp:185
 1: 0000001439AF20A0
 2: 0000000000000001
 3: 0000012500000003
 4: 0000001439AF2038
 5: 0000001439AF2370
New folder is creatied and files are moved to it, but: 

everytime all folders copied but not removed
sometimes some files not replaced
sometimes some files copied

**Comment by arvidn** [comment]
@lunatichai would you mind helping me fix this by providing a small examples that reproduce it?

**Comment by lunatichai** [comment]
ok

**Comment by arvidn** [comment]
I'm eagerly waiting an example to reproduce that assert. Also, while re-reading your initial post, I noticed:

```
lt::file_storage fs= handle.torrent_file()->files();
fileStorage.set_name(newName);
std::shared_ptr ptr;
ptr = std::const_pointer_castlt::torrent_info(handle.torrent_file());
lt::torrent_info ti = *ptr.get();
ti.remap_files(fileStorage);
```

(I imagine there were some brackets that got filtered there). You get the shared pointer to a `const` torrent_info from the torrent handle. The reason this is `const` is because it's the internal object, and it's accessed from multiple threads (including yours). So it cannot be mutable, as that would introduce a data race.

You `const_pointer_cast` that to a pointer to a *mutable* `torrent_info` object and then you mutate it with `remap_files()`. That is not expected to work. It introduces a data race and is undefined behavior. You really shouldn't `const_cast` anything (except when interacting with C APIs that have incorrect `const` qualifiers).

**Comment by arvidn** [comment]
I could not reproduce a problem in the example you sent me
