### ISSUE TITLE
Download rate after pause

### ISSUE THREAD

**Issue by smirok** [arvidn/libtorrent#4664]
What can be the reasons that after a pause of a single torrent, its speed(torrent_status::download_rate) gradually tends to 0, instead of momentally becoming 0

Thank you in advance

**Comment by arvidn** [comment]
the download rate is computed as a rolling average. If you want complete control how rates are reported, look at the download counters with whatever window size you're interested in, and report the delta.

**Comment by vktr** [comment]
@arvidn Are these download counters available per torrent? All I can find are the `session_metric` ones which I would assume are per session.

**Comment by arvidn** [comment]
right. if you want per-torrent stats you have to look at `torrent_status`

**Comment by vktr** [comment]
Sure, but those are rolling average ones. Currently in PicoTorrent, when I display the download rate and you pause the torrent, I have to check if the torrent is paused and if so, I don't display the download rate. It works, but it would be nice to have non-averaged values, perhaps the download rate since the last `state_update_alert`.

**Comment by arvidn** [comment]
`total_payload_download` and `total_payload_upload` are not rolling averages. sample them with whatever frequency you like to compute the rate

**Comment by vktr** [comment]
Hey, that's pretty cool!
