### ISSUE TITLE
Not announcing with port 1 when configured with proxy

### ISSUE THREAD

**Issue by an0n666** [arvidn/libtorrent#4711]
**Please provide the following information**

libtorrent version (or branch):
RC_1_2
platform/architecture:

compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

When qBittorrent is configured with Socks5 or Http proxy, the port in the announce request to tracker is not set to 1 even though there’s no listen socket.
However when built with RC_1_1 port is set to 0 in the announce request.

**Comment by arvidn** [comment]
I think people were having problems with port 0, where trackers would reject the announce. It should be set to 1 though, or at least it should *not* be set to whatever actual port the client is listening on for incoming traffic from the proxy.

Is it the case that the port is random?

**Comment by an0n666** [comment]
It’s announcing with the actual client port.

**Comment by arvidn** [comment]
ok. looking at the code; when a proxy is set the UDP listen socket is sent to the tracker. the UDP port is very likely to be the same as the TCP port, there are always attempts to make that happen.

The rationale is that when you configure a SOCKS5 proxy, you can still accept incoming connections over uTP, so that port needs to be announced.

Now that I think of it, maybe we don't actually know what external UDP port we were assigned by the socks proxy, so maybe this logic doesn't make sense.

Can you tell whether your *external port*, i.e. the one you're reachable via on the proxy, is that one that was announced?

**Comment by an0n666** [comment]
I don’t think my UDP port is reachable via proxy because when I use socks5 I don’t get any incoming connections. Also I couldn’t find a external service to check udp ports. Can you link one?

**Comment by arvidn** [comment]
hm. yeah, it might not be that simple. If we don't know our external port on the proxy, the only way for other peers to learn about it is via DHT (where the UDP port is implied) or possibly via a UDP tracker. I can't remember of UDP trackers can imply the port or not.

In those cases, what port is announced doesn't matter anyway.

When using an HTTP tracker, there is no way to accept incoming connections, but for the purpose of the logic I just described, a proxy is a proxy and it will still announce the port.

**Comment by an0n666** [comment]
If I understand correctly then we’re sending port 1 in announce request to tracker for privacy reasons? If that’s the case then it should be consistently maintained across all types of proxies.

**Comment by arvidn** [comment]
could you give this a try? https://github.com/arvidn/libtorrent/pull/4712

**Comment by an0n666** [comment]
Tested. It's working now.
