### ISSUE TITLE
No libgeoip build support (--with-libgeoip) on RC_1_1?

### ISSUE THREAD

**Issue by lethanhviet** [arvidn/libtorrent#474]
ltv@viethd ~/source/libtorrent-RC_1_1 $ ./configure --enable-python-binding --with-libgeoip --with-libiconv --disable-debug
configure: WARNING: unrecognized options: --with-libgeoip

**Comment by arvidn** [comment]
built-in support for libgeoip was deprecated in 1.0 and has been removed in 1.1. The reason is that resolving IP addresses really is outside of the scope of libtorrent, and there's no real benefit of doing it inside libtorrent. the client has all it needs (the IP) to call into libgeoip to perform the lookup.
