### ISSUE TITLE
Add a torrent with "null" disk output?

### ISSUE THREAD

**Issue by ichorid** [arvidn/libtorrent#4780]
To check for metainfo (e.g. to show the list of torrent contents) the Tribler client creates a dummy Libtorrent download pointing to a temporary directory and stop downloading as soon as we receive the metainfo. This leaves *a lot* of empty directories afterwards.

Is there a better way to do it in Libtorrent? Could we, say, output *all* the disk output to some "null" disk driver, so Libtorrent does not even bother to create a temporary dir?

**Comment by arvidn** [comment]
I would recommend setting `upload_only` mode as a flag in the `add_torrent_params` object, when adding the torrent. This will make the torrent download the metadata, but nothing else. To prevent it from creating *any* directories, you could point the download directory to an invalid path, so any attempt just fails. The torrent will probably be stopped and have an error set when this happens, but by then you'll have the metadata already.

If you then want to resume the download, you have to set a new download directory (`move_storage()`) and clear the error, to allow resumption (`clear_error()`), and `resume()`.

A simpler way, but not as reliable, is to set all the file priorities to 0 in the `add_torrent_params` object. You can set file priorities for more files than exist in the torrent, since you don't know that up-front. However, if there are more files than you set zeros, those last files may cause empty directories to be created.

**Comment by arvidn** [comment]
this was recently clarified in the documentation: https://github.com/arvidn/libtorrent/pull/4778

**Comment by MassaRoddel** [comment]
Wasn't there the idea to expand the file priority vector to the actual number of files by libtorrent after the metadata was received? That way a single file priority would be enough in add_torrent_params.

**Comment by arvidn** [comment]
yeah, I was thinking about that, but that would actually not be fully backwards compatible. At least not the way I was imagining it. I think a better way would be to add a separate `download_priority_t` field to `add_torrent_params` to set the default file priority, for any file that's not specified by the file priority vector.

**Comment by MassaRoddel** [comment]
It would be good a have an implementation that would download metadata only. Maybe enabled by a field in add_torrent_params.

**Comment by arvidn** [comment]
that's a good point, the only good use case is to set all file priorities to 0. However, adding such flag would be *really* close to identical to `upload_only` that it feels hard to justify

**Comment by MassaRoddel** [comment]
Maybe upload_only should be read_only and really does not create any files or directories.

**Comment by arvidn** [comment]
that would be a more complicated change than it sounds. Right now, the creation of zero-size files and their directories is "edge triggered" when running the initial check resume-data job. If they aren't created then, they would have to be created at some other time if the torrent is resumed.
