### ISSUE TITLE
Issue with allowing multiple connection from same IP

### ISSUE THREAD

**Issue by an0n666** [arvidn/libtorrent#4781]
**Please provide the following information**

libtorrent version (or branch):
RC_1_1
platform/architecture:

compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

When I enable that option, I see same peer connected with me through multiple ports and stuck at 0%. The real port displayed for that peer in the tracker website is 8999 which is the default port for that version of qBt. And there's only one peer with that IP:Port in websites' peer list. So I'm not obtaining them from the tracker but getting incoming connections from random ports.
These peers don't disconnect, don't download anything, and they do not keep increasing indefinitely. They just remain stuck at 0%. I have seen this multiple times with multiple qBt peers. So I think something must be wrong in the libtorrent side that it's attempting connections from so many random ports.

![172e7532d555398c59c57389caef5585](https://user-images.githubusercontent.com/47396879/85189979-ba347680-b2d5-11ea-8e3c-ebe591ce35c6.png)

**Comment by an0n666** [comment]
More:
![Capture](https://user-images.githubusercontent.com/47396879/85190124-046a2780-b2d7-11ea-962e-40fd447d7b08.JPG)

**Comment by an0n666** [comment]
After some more digging I found that these peers were making outgoing connection with me from random ports which seem to be the default for QBittorrent. It uses random ports for outgoing connections. Probably these peers were failing in some part of the handshake and were getting stuck indefinitely. The fact that there were hundreds of stalled connections from same peer, they were trying to reconnect each time using a different port.

**Comment by arvidn** [comment]
This option has not received a lot of attention, partly because it doesn't seem particularly useful. I added it a long time ago mostly for testing swarms over loopback. There's some difficulty in determining whether a connection is coming from oneself or not. Previously this used to be done by identifying the peer_id, but peer_ids are random now, and aren't stored so can't easily be looked-up.

I would be inclined to remove the option rather than trying to fix it. Are there important or useful use cases for it?

**Comment by arvidn** [comment]
as you may have figured out, TCP connections are identified by the (source-IP, source-port, target-IP, target-port)-quadruple, and it *must* be unique. So, outgoing connections can't really be bound to the local *listen* port by default.

If they are, and you are attempting to make a connection to a peer behind NAT (and you're failing by timing out). That peer will not be able to connect to you, because it would have the same (IP,port)-quadruple.

So, you *can* affect outgoing ports by specifying a range that are used round-robin, but it's not on by default. It's meant for simple traffic-shaping tools that only can filter by local ports.

**Comment by an0n666** [comment]
What if a peer failed to make an outgoing connection but on my side that peer hasn’t timed out for some reason? Then I can’t establish a connection with that peer till it times out. This delay seems unreasonable and people may want to use this feature. Also sometimes seedboxes are on shared servers with one dedicated IP. If I don’t accept connections from all then only one of them will get connected. And if one of the gets stuck for some reason then everyone gets blocked from connecting.

**Comment by arvidn** [comment]
> What if a peer failed to make an outgoing connection but on my side that peer hasn’t timed out for some reason? Then I can’t establish a connection with that peer till it times out.

Right, the scenario I described is true in the reverse direction as well. All assuming all outgoing connections would bind their local port to the listen port (which they aren't). I was explaining why they aren't.

> This delay seems unreasonable and people may want to use this feature.

I don't know what delay you mean, but the feature of allowing multiple connections per IP never relied on detecting source ports. It sounded like you expected it to, so I explained why that wouldn't work very well.

> Also sometimes seedboxes are on shared servers with one dedicated IP. If I don’t accept connections from all then only one of them will get connected.

Right, that's the default behavior.

> And if one of those boxes gets stuck for some reason then everyone gets blocked from connecting till it times out.

I don't follow this. You mean if one of the seed boxes does something to cause its peers to ban the IP? say, send corrupt data. Then all other peers on that IP also get banned, is that what you mean?

Anyone who wasn't connected to the first seed, wouldn't have banned the IP though, so I don't see how it would affect "everyone".

Or, you mean if you try to connect to one of them, and it won't accept connections, then you can't connect to any of the other ones, since you don't allow multiple connections per IP, yeah?

That's true, however, when multiple connections per IP is disabled (which it is by default) your local peer list is keyed by IP, so you won't even *store* the other peers.
