### ISSUE TITLE
soversion goes backwards in 2.0.0RC2

### ISSUE THREAD

**Issue by lgbaldoni** [arvidn/libtorrent#4927]
**Please provide the following information**

> libtorrent version (or branch):

2.0.0RC2

> platform/architecture:

openSUSE Tumbleweed x86_64

> compiler and compiler version:

gcc 10.1.1, cmake 3.18.0

> please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Build with cmake creating shared libs.
libtorrent-rasterbar.so.2.0.0 will be produced, with a softlink to libtorrent-rasterbar.so.10: that's going to look like a downgrade on most linux distributions, are you sure it's the intended outcome?

Is there an API change with respect to the 1.2.x branch btw?

**Comment by arvidn** [comment]
yes, not only API changes, there are ABI changes since 1.2.x. SO version need to be incremented for 2.0

**Comment by arvidn** [comment]
As far as I understand, the main reason to use SOVERSION is to avoid subtle bugs because of ABI incompatibility.
It doesn't *really* matter whether it counts up or down, as long as each distinct ABI version is unique.

Would it not be possible to "start over" and just use the normal library version as the SOVERSION?

Also, the SOVERSION is really just a convention of the filename of the .so file, right? as far as I can tell, it's not encoded inside the library file itself. Is that right?

**Comment by lgbaldoni** [comment]
> As far as I understand, the main reason to use SOVERSION is to avoid subtle bugs because of ABI incompatibility.
It doesn't really matter whether it counts up or down, as long as each distinct ABI version is unique.

It's true for the major version, but for minor and patch there is the assumption of non breaking changes.

> Would it not be possible to "start over" and just use the normal library version as the SOVERSION?

Since it's quite distant (2 vs. 10) there should be no version clash. Still, it's a break with tradition.

> Also, the SOVERSION is really just a convention of the filename of the .so file, right? as far as I can tell, it's not encoded inside the library file itself. Is that right?

Nope, see `objdump -p libname.so.<sover>|grep SONAME`.

**Comment by arvidn** [comment]
this addresses the SONAME issue https://github.com/arvidn/libtorrent/pull/4930
