### ISSUE TITLE
In 1.2.8, add_piece() is a no-op if called while checking

### ISSUE THREAD

**Issue by AllSeeingEyeTolledEweSew** [arvidn/libtorrent#4980]
libtorrent version (or branch): 1.2.8

platform/architecture: alpine linux testing branch, x86_64

I have a lot of unit tests which use `add_piece()` to simulate downloading data. They all started failing in 1.2.8. The calls to `add_piece()` had no effect.

Seems I'd been calling `add_piece()` before the torrent was done checking. If I wait until the torrent's status is no longer checking, `add_piece()` does work.

I attached some example code:
 - Under 1.2.8, `./bug.py` shows the torrent never receives data.
 - Under 1.2.8, `./bug.py --wait` shows the torrent will receive data if we wait until it's done checking.
 - Under 1.2.7, `./bug.py` or `./bug.py --wait` both show the torrent receives data.

[bug.py.gz](https://github.com/arvidn/libtorrent/files/5065782/bug.py.gz)

**Comment by arvidn** [comment]
this was a deliberate change. It's mentioned in the `Changelog`. [Here's](https://github.com/arvidn/libtorrent/commit/5e40926ec4f6aedd9b11b98f63a2bcdc71fb5f4a) the commit.

There used to be an issue where calling `add_piece()` *before* the piece had been checked, the `we_have()` function could end up being called twice for the same piece, violating invariants. Rather than building extra logic to support this case, I just disallowed it instead, ensuring the internal invariants are maintained correctly.
I believe it mostly affects tests. As you can see in that commit, I had to update a few tests as well, that use `add_piece()` to emulate downloading data.

Previously, those tests were flaky, and would fail with mysterious errors every now and then (because of this race condition).

**Comment by AllSeeingEyeTolledEweSew** [comment]
I even read the changelog, but apparently glanced over this.

Could we add some feedback for this case? Even having fixed my tests, I assume I'll write more later that hit this case, and get confused again. Could `add_piece()` throw an exception if called during checking? Could it be changed to return an `error_code` without ABI breakage? Or maybe just a `torrent_log_alert`?

**Comment by arvidn** [comment]
I think an assert would be reasonable probably

**Comment by arvidn** [comment]
does this look reasonable? https://github.com/arvidn/libtorrent/pull/4982

**Comment by AllSeeingEyeTolledEweSew** [comment]
:+1:
