### ISSUE TITLE
[New Feature] Support removable devices

### ISSUE THREAD

**Issue by latot** [arvidn/libtorrent#5008]
Hi hi :3

Actually, some files when we share torrents are stored in other devices, like external hdds, but some times happen's that we unplug the device, so we need start checking all the torrents and pause it, if we accidentally unplug the device, libtorrent start sending the IO Errors everywhere, because it doesn't detect if where the files are is actually available.

In other way.., change the IO Error, first, if the IO Error is because the device was unpluged disable the torrent and test the files until the files are available again and send an alert, if is not the case and the hdd is just failing keep the actual IO Error.

Thx.

**Comment by arvidn** [comment]
If I understand you correctly, you would like to have a special case to distinguish I/O errors that are caused by their drive being unmounted and other kinds of I/O errors. If the drive was unmounted, periodically check if the drive comes back and when that happens, start the torrents again.

Do you know if there is a way that (reliably) can tell whether an I/O error happened because the drive disappeared?

It's not clear to me that logic like this belongs in libtorrent either. A client could do this polling an call `resume()` on the affected torrents too.

**Comment by latot** [comment]
mmm, i think is possible to detect it, actually would be retrieve the actual drives and their mount locations, then check what files belong to the drives, so, if there is a I/O errors we can check if the device is actually mounted, if is mounted for example, and then still have IO/Error would for example because there is a problem in the hdd or the files was moved, anyway there is that way to do that.

And Yes, the client would be able to do this, but i was thinking, this would be very useful for any client, so i think would be useful have it here.

Maybe, add an option to the torrents, to can say the files are stored in a external device (?

Thx.

**Comment by Dobatymo** [comment]
I encountered this issue a few times as well. On Windows for example, there are [Device Events](https://docs.microsoft.com/en-us/windows/win32/devio/device-events). They could be used to mark source HDDs and all torrent files stored on them as temporarily unavailable and resume when available.

**Comment by latot** [comment]
Hi hi @arvidn is like @stale is closings a lot of things.... D: (bot bot bot)
