### ISSUE TITLE
Port 1 Announcement When Using Proxy Getting Blocked

### ISSUE THREAD

**Issue by webheaded** [arvidn/libtorrent#5105]
**libtorrent version (or branch)**: libtorrent-rasterbar 1:1.2.8-1
**platform/architecture**: Arch Linux / x86_64
**compiler and compiler version**: N/A

**Issue**:
So I see the behavior was changed previously to account for trackers blocking port 0 when using a proxy, but lo and behold, now one of my trackers is blocking port 1 as well.  Is there any work around for this?  I basically can't use any of these clients with a proxy and a particular tracker (currently on Deluge 2.0.3).

**Comment by arvidn** [comment]
Do you understand what the rationale is for the tracker to block it?
If they deliberately want to prevent you from using a proxy, do you think it's a good idea to start a cat-and-mouse game with them by announcing a random port?

**Comment by an0n666** [comment]
I think some trackers block it because there’s a cheat tool which uses proxy to modify the download upload amounts.

**Comment by arvidn** [comment]
a cheat tool that re-writes the port, to give itself away? :p

**Comment by an0n666** [comment]
> a cheat tool that re-writes the port, to give itself away? :p

Haha. Nope. 
The tool is just a local proxy.  When you add that proxy to client, it changes the parameters sent to tracker.

**Comment by arvidn** [comment]
oh, I get it.

**Comment by webheaded** [comment]
>cat-and-**mouse**

Funny you mention that lol.  This tracker actually does support proxies and such but the block port 0 and 1 because as they state:

> As to the port 1 (or now 0): we block things running on privileged or invalid port numbers.  Why your client has picked to report port 1 I am unsure. qBittorrent with socks set up won't change the port number from my tests.  Some setting must be causing this.

Basically it looks like BS so they block it.  Maybe if there were at some point a way for the various programs to offer an option to pass through the real port you're using or something that doesn't look like it's invalid, that would be better?  Not sure.  Right now it just kind of sucks because I can't use my proxy anymore with that tracker (I might need to setup a client specifically for the tracker for now).

From what I read in past topics, you guys had been reporting port 0 previously then swapped over to port 1.  I saw that it seemed to have been done for specific reasons (though I don't remember now why you didn't pass the real port through).

I'm using Deluge 2.0.3 btw.

**Comment by an0n666** [comment]
qBt latest version doesn’t report port 1 because of a libtorrent bug that was fixed recently. Once qBt receives an update it’ll also start reporting port 1.

**Comment by arvidn** [comment]
fundamentally, the issue is: what port do you announce when you don't have a port that can accept incoming connections?
Ideally, the `&port=` parameter should just be omitted entirely. But I don't think any tracker would be happy with that. Although, it would give the tracker an opportunity to immediately know the peer cannot be connected to, and never hand it out to anyone else.

By passing any port that "looks normal", the performance of the system degrades (by some small amount), since there will be a number of peers sacrificing peer-slots (temporarily) and bandwidth to attempt a connection that is known to fail.

@webheaded if you're in touch with the operators, perhaps you can ask them what they think you should send as `&port=` when you know you cannot accept incoming connections. (and not sending `&port=` at all would probably be the best answer).

**Comment by webheaded** [comment]
Update here.  I was actually quoting a previous thread where someone in the staff posted that.  I posted my own new thread (it was closed) and I am still waiting for a follow up if any.  I'll let you know.  In the interim...I have no idea what to say other than maybe just allow us to set the port manually if we like?  Set the default to whatever you guys think is proper and otherwise...let us override maybe?
