### ISSUE TITLE
libtorrent IPv6 tracker connections & errors despite IPv4 addresses

### ISSUE THREAD

**Issue by slrslr** [arvidn/libtorrent#5113]
Hello,
i had problem with trackers marked as Not working in torrent client qbittorrent 4.2.5 and i was referred to your client_test.exe tool linked in [this post](https://github.com/arvidn/libtorrent/issues/3542#issuecomment-683726838). So i have downloaded it and ran and it [returned errors](https://bin.disroot.org/?19989e2de3c86757#Hshb5YVp9oyoeZH6KisY62yxL9YGcrE97VnaznHLTGNM) (password: a ) which was [commented by a qbittorrent developer](https://github.com/qbittorrent/qBittorrent/issues/7762#issuecomment-687611097). I am not aware on how to solve this on my Windows 10 computer.

When i connected to same VPN server not via WireGuard (which i am using) but via OpenVPN and defined the interfaces in the client_test.exe like this:
client_test.exe --alert_mask=error,tracker -f log.txt --upnp_ignore_nonrouters=true --outgoing_interfaces="10.8.0.2" listen_interfaces="10.8.0.2:6881" "C:\path\to\torrent.torrent"
(10.8.0.2 is vpn client TUN network interface)
then [the log](https://bin.disroot.org/?d2249f14ba098ce4#8rtBfTfhyLnZYSDWtDdK7jCYJ88aKXHsd2JSjeVGG1ci) (password: a ), still contained numerous error lines that are worrisome for a layman like me:
[127.0.0.1:6881] host unreachable "" (1)
[::1]:6881] Systém nemuže otevrít zadaný soubor nebo zarízení "" (1) _(free english translation: System is unable to open definer file or device)_

I also tried to connect different VPN server, though results appeared similar. I am not using IPv6, so for simplicity i would prefer if it is not used in torrenting. So i tried to remove it from all Windows interfaces, from VPN config files and from server networking too (/etc/sysctl.conf) but you see the errors that suggesting there are IPv6 like attempts.

Windows computer network interfaces and IPs (when Wireguard tunnel is established) are pasted [here](https://bin.disroot.org/?91b05f61e3570d5f#EqZs1dpqB9HYbMrrzWFB1718s4iB84S8FQdLk2p5E99t) (password: a )
I will be happy to provide any other details if needed, note i know minimum about networking and libtorrent area. Thank You

**Comment by arvidn** [comment]
libtorrent will attempt to connect to trackers from all local interfaces. That means 127.0.0.1 (loopback) will fail with `host unreachable` as well as an IPv6 address may fail if you don't have internet connectivity over IPv6. However, the relevant part is whether the IPv4 address *succeeds*. I the source interfaces you *expect* to succeed do so, there are no problems.

I suppose errors like that could be suppressed somehow, or maybe posted with a different category, to make them not visible by default.

It sounds like all the failures you see are from loopback and IPv6. Loopback I would expect to fail, would you expect IPv6 to fail, or is there a genuine problem somewhere here?

**Comment by FranciscoPombal** [comment]
@arvidn

The content of the previous posts in the qBittorrent issue trackers boils down to this: it seems the only/majority of attempts to contact IPv4 trackers are done through IPv6(-only?) addresses/interfaces. Or at least the logs led me to believe that.

**Comment by an0n666** [comment]
I think useless alerts should be suppressed if at least one endpoint succeeds. This will reduce the client performance impact as well.

**Comment by an0n666** [comment]
> @arvidn
> 
> The content of the previous posts in the qBittorrent issue trackers boils down to this: it seems the only/majority of attempts to contact IPv4 trackers are done through IPv6(-only?) addresses/interfaces. Or at least the logs led me to believe that.

If a tracker has a DNS entry pointing to a IPv6 address I think it'll be tried first anyway before falling back to IPv4 endpoint.

**Comment by slrslr** [comment]
[That torrent](https://ufile.io/qi6xmihq) i have tried contains around 160 trackers (mix of ip, hostname, udp, http). If necessary i can test some particular.

**Comment by an0n666** [comment]
Most trackers these days use Cloudflare. The thing is CF enforces IPv6 on all their protected domains. So even if the tracker doesn’t support IPv6 it’ll still be requested over v6 due to the endpoint advertised by DNS.



> [That torrent](https://ufile.io/qi6xmihq) i have tried contains around 160 trackers (mix of ip, hostname, udp, http). If necessary i can test some particular.

The thing is some of them definitely have IPv6 in their DNS but they don’t support IPv6. Even if you disable IPv6 on all interfaces I think some loopback v6 addresses will be used to try to connect to the tracker via v6. Posting your qBt logs will help determine if you’re listening on any V6.

**Comment by arvidn** [comment]
@slrslr in `client_test`, if you press `t` it will show you the trackers it's using and their status. `client_test` attributes errors (and successes) to the correct source interface, meaning for any given tracker, you can see which interface is failing and which is succeeding.

I couldn't find anything in the logs you posted on the qbt ticket suggesting that a tracker that resolved to an IPv6 address was contacted over IPv4 (I would expect an IPv4 interface would fail such announce with "no route to host" *before* attempting to connect to it). Though, it would probably be better if there was a special error code to mean "I'm skipping this announce because it doesn't make sense", rather than reusing the system error code for "no route to host".

**Comment by FranciscoPombal** [comment]
@arvidn 

> I couldn't find anything in the logs you posted on the qbt ticket suggesting that a tracker that resolved to an IPv6 address was contacted over IPv4

There are several instances of trackers resolved to an IPv4 address being contacted over IPv6 in those logs, though.

**Comment by arvidn** [comment]
> There are several instances of trackers resolved to an IPv4 address being contacted over IPv6 in those logs, though.

can you help me find them? which log are they in?

**Comment by arvidn** [comment]
There's nothing obviously wrong in that log as far as I can tell. All the IPv6 -> IPv4 announces fail with "host unreachable", which is the error code used when an announce is skipped. It's not great to use that error code though, since it implies that a connection was actually attempted on the real network.

**Comment by arvidn** [comment]
would something like this make sense? https://github.com/arvidn/libtorrent/pull/5123

**Comment by an0n666** [comment]
Can such alerts be dropped altogether? I mean when a announce is skipped.

**Comment by arvidn** [comment]
well, I'm a bit worried about consistency. If one expects to learn what happened to an announce for all interfaces, there would be gaps. there wouldn't be a complete status update so to speak.

I was thinking if they could be moved into their own alert category perhaps, but the infrastructure for that isn't great right now, as categories are assigned to alert types, not the situation they are posted in. I'm open to suggestions.
