### ISSUE TITLE
PEX For WebRTC

### ISSUE THREAD

**Issue by zero77** [arvidn/libtorrent#5115]
According to the following, webtorrent does not support DHT, and solely relies on trackers for peer discovery.
https://github.com/webtorrent/webtorrent/issues/1684

As an alternative option for finding WebRTC peers could PEX for WebRTC be considered.
https://github.com/webtorrent/ut_pex

**Comment by paullouisageneau** [comment]
Indeed, this actually goes beyond discovery and is a big limitation of WebTorrent since it is based on WebRTC: you can't open a connection directly, you have to exchange signaling messages via a relay to establish a connection. For now the only way to do so is via the tracker.

The existing PEX won't work as you can't simply use an address to connect another peer. Unless I'm mistaken, the `ut_pex` implementation you link is still limited to exchanging traditional BitTorrent peers, even if it can be run by WebTorrent nodes.

A solution would be to define a specific kind of PEX for WebTorrent using the already-connected peers to forward signaling messages. There is a good suggestion here from @KayleePop https://github.com/webtorrent/webtorrent/issues/1191 but I don't think it has been implemented.
