### ISSUE TITLE
[Feature request] Swarm Discovery

### ISSUE THREAD

**Issue by JonasNo** [arvidn/libtorrent#5168]

**Comment by arvidn** [comment]
would you mind adding a description?

**Comment by zero77** [comment]
Do you mean:
https://wiki.vuze.com/w/Swarm_Discoveries

**Comment by arvidn** [comment]
that's a good start. The next step would be to describe specifically, what feature you asking for and ideally how it should do it. That document does not specify a protocol or an algorithm

**Comment by arvidn** [comment]
it seems, generally, that you would like to be able to discover related content. How should related content be discovered? where should relationships be stored? And is there a good reason for such feature to be part of libtorrent? (it seems out of scope to me)

**Comment by zero77** [comment]
Some other documentation i have found on this topic:
https://github.com/BiglySoftware/BiglyBT/wiki/Swarm-Discoveries
https://wiki.vuze.com/w/Swarm_Merging

Having a quick look at this, it looks similar to the functionality in BitTorrent v2 with Mutable Torrents and Merging Swarms.

**Comment by arvidn** [comment]
there's no global database of related torrents in BitTorrent V2 though

**Comment by YfheA3r** [comment]
If every file hash is added to the DHT whouldn't be possibile to discover all peer with the same file even in different torrents?

**Comment by arvidn** [comment]
I see two problems with that:

1. truncated file-root hashes could be used as keys in the DHT, but the *value* behind keys are peer-lists, not info-hashes, so the mapping from a file-hash to multiple info-hashes would still not be obvious
2. There are a lot of files and there's a risk it would overwhelm (i.e. degrade performance) of the DHT

**Comment by arvidn** [comment]
Also, the "related content" feature in Vuze is different from that, right? If find *related* content, not the exact same content.

**Comment by YfheA3r** [comment]
> Also, the "related content" feature in Vuze is different from that, right? If find _related_ content, not the exact same content.

It's not the same thing but in BiglyBT (Vuze new name) it is also used to find file with the same size to attempt a Swarm Merge, the problem is that only the relationship between one torrent and another (i think it means that all torrent downloaded by the same peer have a relationship) are stored on BiglyBT DHT (not the same as the Mainline DHT) and that is not really good for finding the exact same file in multiple torrent since they may not be considered "related".

>     1. truncated file-root hashes could be used as keys in the DHT, but the _value_ behind keys are peer-lists, not info-hashes, so the mapping from a file-hash to multiple info-hashes would still not be obvious

If we want to help downloading a file by searching other peer that have it in a different torrent do we need to know its info-hash?
Or it is possible to ask the peer for the specific file without knowing the torrent info-hash?

If instead we want to find all torrents that have a specific file can we store the file/info-hash relation in the DHT using BEP44?

**Comment by arvidn** [comment]
> If we want to help downloading a file by searching other peer that have it in a different torrent do we need to know its info-hash?
> Or it is possible to ask the peer for the specific file without knowing the torrent info-hash?

That's actually an interesting idea. Files that satisfies some criteria (say, they're large enough) could be announced as-if they were swarms themselves. If the client ever receives an incoming connection asking to join a swarm with one of those hashes, there could be an extension message that basically responds with the info-hash the file belongs to.

> If instead we want to find all torrents that have a specific file can we store the file/info-hash relation in the DHT using BEP44?

That feature requires that *either* the location is not fixed, but determined by the content *or* that there is some authority that decides what content should be stored at that location. An authority that can sign.
