### ISSUE TITLE
Mapping a Custom DNS

### ISSUE THREAD

**Issue by Starsnatcher** [arvidn/libtorrent#5233]
Good afternoon,

I am wondering if there is any support for mapping a custom DNS to the resolver, if not I would like to request this feature.

Thank you!

**Comment by master255** [comment]
@Starsnatcher The idea is not bad, but there are dark moments. Where should the DNS records be stored? 
This is a library. Wouldn't it be easier to do it in a program rather than in a library? You have full control over the data coming into the library.

**Comment by arvidn** [comment]
@Starsnatcher It sounds like you want to specify the server to use to perform hostname lookups.

libtorrent uses boost.asio for performing name lookups, which, as far as I can tell, does not let you configure this. It will use the system-configured DNS.

https://www.boost.org/doc/libs/1_74_0/doc/html/boost_asio/reference/ip__tcp/resolver.html

Unless, by "DNS" you mean hostname, and you want to *override* a hostname to an IP of your chosing. If that's what you mean, wouldn't the best solution be to use the `/etc/hosts` file? (it also seems like quite a fringe feature)

**Comment by themacguffinman** [comment]
Let me describe a use case that's important to me, even though it might be niche: plugging the DNS leak on Windows.

On Windows, it's quite hard to isolate torrent networking properly (on Linux you have network namespaces, which are the ultimate level of isolation), but it's quite common to want a setup where your torrent client is using one network (eg. VPN), while the rest of your work uses the normal network.

libtorrent and its GUIs (like qBittorrent) already support binding torrent traffic to a specific network interface, which is one of very few simple ways on Windows to isolate your torrent client. However, binding to a specific network interface still doesn't stop libtorrent from leaking DNS requests because IIUC Windows handles DNS requests by round-robining them to every DNS server it can find on every available network interface, and this behavior is very difficult to change. Allowing libtorrent clients like qBittorrent to explicitly specify DNS servers would allow average Windows users to plug DNS leaks in an environment where they don't have a lot of powerful isolation tools to begin with.
