### ISSUE TITLE
preformat bencoding, while no decoding method

### ISSUE THREAD

**Issue by Morpheusai** [arvidn/libtorrent#5250]
Hello, everyone.

We test the bencoding test file and review the codes in bencode.hpp, found that it has preformat encoding method, but no decoding method supported.

And also no TEST_CHECK(bdecode(encode(e)) == e) in test_becoding.cpp of TORRENT_TEST(preformatted) function.

What's the purpose of this ？

Thanks for reply.

**Comment by arvidn** [comment]
I may be misunderstanding the question; but the `preformatted` node type in the `entry` (or the hierarchy used for *encoding*) is, essentially, to support reproducing invalid encodings.

dictionary keys must be sorted. If they are not, it;s invalid encoding and won't round-trip through a decoder-encoder step. Similarly overlong integer encodings (with leading zeroes for example) will also not round-trip.

Since the info-hash is the SHA-1 hash of the info dictionary, and the info-dictionary may use invalid encodings that don't round-trip, there needs to be a way to talk about it, and produce an output with it that has the same info-hash.

That's really the only reason for `preformatted` node type to exist.

**Comment by wuzhengy** [comment]
Thanks Arvidn. We `reformatted` an array of `RLP` encoded ethereum block into v. The encoder does add the RLP binary, but the decoder case switch does not recognize `RLP` binary since it is "invalid", therefore the v value will miss entire RLP binary. Of course, we could use `string byte` to represent RLP binary, it does work as tested. But, can we add `preformatted` into the decoder case switch to add the binary back to v value?  Thanks.

**Comment by arvidn** [comment]
the decoder can only decode bencoded data, not any arbitrary data. If you need to include an arbitrary blob of binary data, it has to be as a string. Anything else would require extending the bencoded format with some other kind of string (which would still have the exact same behavior as string, except it would turn into a `preformatted` node in the decoder). It still wouldn't round-trip, so it would still have awkward behavior.

I don't think there's any benefit of trying to shoehorn non-bencoded data into `preformatted`. Perhaps the name should have been `preencoded`. It's expected to be bencoded formatting.

Putting binary data in a string is fine and has precedence. a bencoded "string" isn't just text, it's meant for binary data as well.
