### ISSUE TITLE
Delete pieces

### ISSUE THREAD

**Issue by oxygencraft** [arvidn/libtorrent#5260]
I would like a function where you can delete a piece from storage and prevent it from being redownloaded.

**Comment by arvidn** [comment]
related issue: https://github.com/arvidn/libtorrent/issues/5086

**Comment by YenForYang** [comment]
I've been looking for this feature as well, namely for RC_2_0. I would assume that this feature would be pretty important when it comes to streaming large files that can't be kept on disk. 

Ideally, I would like this functionality paired with some sort of [file reader interface (#5278)](https://github.com/arvidn/libtorrent/issues/5278); such an interface would be particularly useful in RC_2_0, as I find the custom storage kinda difficult to use. It seems like the only way to access the pieces is via `read_piece()`; this makes in-memory custom storage(s) rather difficult to manage for large torrents/files due to the inability of using something like `remove_piece()`. If there are any workarounds to this limitation, let me know -- I'm currently using [anacrolix/torrent](https://github.com/anacrolix/torrent) as it provides a more useful custom storage API, but it also lacks a function to "formally" announce that a previously read piece has been removed (i.e. in anacrolix/torrent's case, I can remove the piece but I come to the issue described [here in #5086](https://github.com/arvidn/libtorrent/issues/5086#issuecomment-688537497).)

As a side note, `async_clear_piece()` doesn't look like it's used for anything besides `torrent::piece_failed()`. I was hoping that it could be used for removing pieces, but I've had no luck in that regard.

An issue that needs to be resolved in order to add this functionality: 
[[Feature] A way to invalidate pieces? #3516](https://github.com/arvidn/libtorrent/issues/3516)
