### ISSUE TITLE
Is there a file reader interface?

### ISSUE THREAD

**Issue by boramalper** [arvidn/libtorrent#5278]
Hi,

Does libtorrent have a file reader interface like [anacrolix/torrent](https://godoc.org/github.com/anacrolix/torrent#Reader) to allow reads at random offsets while downloading the corresponding pieces itself transparently?

I see that [streaming is already supported](https://libtorrent.org/streaming.html) so I think libtorrent should be capable of such functionality, though I could not find if it has been already implemented or not.

Thanks!

**Comment by arvidn** [comment]
there's [read_piece()](http://libtorrent.org/reference-Torrent_Handle.html#read-piece) which, asynchronously, reads a piece from a torrent and delivers it in an alert.

**Comment by master255** [comment]
This uses a different, more efficient algorithm, which we already discussed [here](https://github.com/arvidn/libtorrent/issues/4408), but Arvin doesn't have time to add it to the main branch.

**Comment by boramalper** [comment]
I see, thanks!

**Comment by arvidn** [comment]
I just realized that you may be talking about accessing pieces *before* they are downloaded. In that case, you'd want to use [set_piece_deadline()](http://libtorrent.org/reference-Torrent_Handle.html#clear-piece-deadlines-reset-piece-deadline-set-piece-deadline) and pass in the `alert_when_available` flag, to receive the `read_piece_alert` with the data.

**Comment by i96751414** [comment]
Hello @arvidn!

Out of curiosity, is this the only way possible to do this?
I used to do `get_storage_impl()` and then `readv` to achieve this on libtorrent-1.2. Is there anything similar in libtorrent-2.0?

The fact it is async makes things a bit harder.

**Comment by arvidn** [comment]
accessing the internal storage object from a user thread is not safe in all circumstances. If there are any outstanding "fence" jobs outstanding for example. A fence job is one that needs exclusive access to the files of a torrent. Operations like:

* renaming a file
* moving files
* deleting files
* force checking
* setting file priority
* releasing file handles (which happens when completing the download, to re-open the files in read-only mode)
* resetting a piece (happens if a piece hash fails). This is a fence synchronizing with write jobs for the corrupt data, to ensure they aren't intermingled with write jobs of the new, re-downloaded, piece

The other things `read_piece()` does is making sure that the piece actually has been downloaded and written to disk. If it hasn't been written to disk, you'll still get the data out of the disk cache.

The cache would be an issue in libtorrent-2.0 as well, if you read directly from the disk. However, only on windows I believe. On windows the updating of the file on disk is deferred, and may only be visible through the file handle used by libtorrent. On linux though, file writes should be visible to all other processes immediately.

**Comment by i96751414** [comment]
I see... But read piece by piece seems somehow odd to me, specially in the particular case of streaming. In some cases we may need more than one piece, in others less. Do you think it would be possible to have a `readv` method with the same protection as `read_piece`? I am not asking you to implement that :) I just want to understand if would be possible

**Comment by master255** [comment]
@i96751414 In any case, it will work slower than [this](https://github.com/arvidn/libtorrent/issues/4408) method, which does not slow down the overall process of data downloading and runs at full speed.

**Comment by arvidn** [comment]
@master255 sequential mode doesn't solve the same problem as a random-access file interface. that's why think it's off-topic

**Comment by master255** [comment]
@arvidn But, as you can see, it solves. Rewinding in the player works fine. This is RandomAccess, right?

**Comment by arvidn** [comment]
@i96751414 the main reason the API for reading data is per piece is that the disk I/O subsystem is all piece-oriented, and this API was really just the simplest possible way for a client to get data out of there.

I can think of a number of improvements to this API:

* the the read function could take a `user_data_t` that's returned in the `read_piece_alert`. This would make it much simpler to build a synchronous API on top if the asynchronous one.
* the read function could take an arbitrary offset and size (but probably still constrained by the piece boundaries) to read less than a full piece. This would be especially useful for torrents with large pieces and small read requests.
* the read function could take a buffer that is filled in, rather than heap-allocating the buffer to be returned in the `read_piece` alert
