### ISSUE TITLE
Question on multi-torrent DTLS state

### ISSUE THREAD

**Issue by burdges** [arvidn/libtorrent#5300]
Are there any issues worth considering if I have nodes participate in a rapid-ish succession of distinct torrents?  

Imagine we've 1k to 10k nodes that each create a fresh torrent every 10ish seconds.  Are these going to all require fresh key exchanges in DTLS or does libtorrent keep the DTLS state among nodes across multiple torrents?

**Comment by arvidn** [comment]
typically the terminology in bittorrent is:

node = a participant on the DHT network
peer = a participant in a bittorrent swarm (either uploading or downloading)

My interpretation is that you have many machines that create a torrent each every 10 seconds. That in itself doesn't cause any network traffic.

Do all machines then join all swarms, via bittorrent?

What libtorrent does is that it will keep a connection to each peer for each torrent. i.e. if all 10k torrents have 10k peers. A client joining all 10k swarms would (attempt) 10k times 10k = 100M peer connections. Now, it won't actually try that unless you set the connection limit that high (or unlimited). But it won't recognize that one socket could in theory be used to refer to multiple torrents.

The BitTorrent protocol includes the info-hash of the swarm in the handshake and doesn't support "multiplexing" multiple torrents over a single connection.

There is no DTLS state. But if you are using the extension to run these swarms over TLS, there is the regular TLS state for each peer.

**Comment by burdges** [comment]
> it won't recognize that one socket could in theory be used to refer to multiple torrents.

Ok this is what I wanted to know.  Thank you!

**Comment by arvidn** [comment]
it would be an interesting extension though. probably not very likely to make a difference for most uses, but specialized ones.

**Comment by burdges** [comment]
It'd be directly useful mostly for commercial applications with large stable peer sets, like distributed databases aka blockchains.  

We're primarily looking towards QUIC for our particular p2p data transport needs, but a couple parts really look more like uTP with careful priorities for the picker, than like QUIC so I'm curious.  

I suppose an obvious question is:  Does it make sense to run roughly uTP over QUIC datagrams?  And are QUIC datagrams acceptable performance?  This is more a question for the QUIC implementation though I guess.  If yes, then maybe QUIC's existing use cases could broaden the use cases for something like this, not really my area though.  

It'd be incredible if some judiciously designed QUIC extension for file transport somehow reduced CloudFlare's importance/power, maybe just a pipe dream there though.  ;)

**Comment by arvidn** [comment]
both QUIC and uTP are transport protocols, I don't think it would make sense to *stack* them. But QUIC would be a great fit to run bittorrent peer connections over. One issue with the current "single channel" bittorrent protocol is that payload (piece messages) are intermingled with control messages (request, choke, unchoke, interested, cancel, etc.). This may delay the control messages and makes them slightly less effective.

The bittorrent peer protocol is designed to run on top of a "stream" transport, i.e. not unreliable datagrams. uTP uses UDP since that's the only option for a user-space transport protocol. and the main purpose of uTP is to employ the LEDBAT congestion control. I seem to recall that QUIC uses [CoDel](https://en.wikipedia.org/wiki/CoDel), which has similar properties as LEDBAT.

With QUIC, control messages could be sent on a different channel from payload. QUIC also improves a few other performance issues in TCP, like slow-start. But I think HTTP suffers from that a lot more than bittorrent, since bittorrent typically has long lived connections and can have deep request pipelines to the pipe full.

**Comment by burdges** [comment]
Interesting, thank you!  

As an aside, we've one distinction that makes bittorrent slightly suboptimal for our particular use case:  In bittorrent, it makes sense to fetch the entire torrent file because typical users eventually download the whole file.  In our case, if we've n peers then the jth peer only wants the jth chunk, but then 10-20 peers eventually want any 1/3rd of the chunks (from which they reconstruct the whole file using the file's erasure coding).  It's therefore more efficient for us to use merkle proofs for each chunk, while in bittorrent it's more efficient to download the whole torrent file separately.  This kind of thing is obviously more for reliable short-term storage, not transferring per se.  And it's also the reason for the large swarm size.
