### ISSUE TITLE
Did libtorrent 2.0 switched to mmap storage by default?

### ISSUE THREAD

**Issue by mayli** [arvidn/libtorrent#5305]
**Please provide the following information**

libtorrent version (or branch): 2.0

platform/architecture: Linu/x86_64

compiler and compiler version: doesn't matter

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I am trying qbittorent + libtorrent 2.0 over my mergerfs storage, and all io operation ends up with "no such device". I've configured the mergerfs to not support mmap for performance reasons, but it seems the new behavior is broken for my setup, and there isn't any workaround other than recompile libtorrent 2.0 with mmap disabled.

**Comment by arvidn** [comment]
it *is* possible to disable mmap disk I/O at runtime, by setting the disk interface constructor to `lt::posix_disk_io_constructor` when constructing the session. qBittorrent probably doesn't have this option though. Note that the posix disk io is the simplest possible implementation, which means file handles are not cached and it's single threaded.

I'm curious, is it not possible to run executables or load shared libraries off of this volume as well then?

**Comment by mayli** [comment]
Yeah, but qBittorrent isn't exposed that functionally to user. Executables or shared libraries seems just working fine to me.

**Comment by markmdscott** [comment]
@mayli if you're doing this for performance, then you'll have to reconfigure your mergefs storage to support mmap. Because [@arvidn correct me if I'm wrong] it doesn't seem like you can recompile libtorrent 2.0 to get the 1.x behavior back, and without mmap it will really suck.

https://www.libtorrent.org/reference-Storage.html

**Comment by arvidn** [comment]
I read up a bit on mergerFS. I assume it predates logical volume management, and is an attempt at implementing it. I understand the problems it runs into, from the page cache's point of view, mergerfs and the other volumes are separate and are cached independently. In reality, mergerfs is a mirror of the other volumes so half of the cache is redundant, which is wasteful.

The solution I see being suggested is to disable caching (or enable `direct_io`) on the mergerfs volume, to rely entirely on the underlying filesystem's caches. This is problematic when memory mapping a file on mergerfs, since it heavily relies on the page cache being there. The fact that the underlying file is cached on the original filesystem doesn't really help. In a (theoretical) world where you *could* mmap a file in `direct_io` mode, every page access would still be a page fault, a round-trip through the mergerfs FUSE process and then back to the filesystem and be a cache hit. By then, you've lost so much time, it doesn't really matter that it's a cache hit (I would imagine).

How about the converse approach; enable caching on the mergerfs volume, but disable it on the underlying filesystems. At least you would greatly improve performance of processes accessing the files via mergerfs.

**Comment by mayli** [comment]
That would cause mergerfs to eat all my ram. Currently I am mounting the mergerfs in two flavors with mmap and without. Most ordinary application can live without mmap, such as lt1.x bt clients or plex media directory. And use another mount point mergerfs-mmap for applications that does require mmap feature, (including lt2.x bt client, plex's sqlite3 db).
Which seems to be fine so far, but I could try the "converse approach" and get some numbers on CPU/RAM impact of different caching modes.

**Comment by arvidn** [comment]
> That would cause mergerfs to eat all my ram.

It sounds like you say that as something bad. Which it could be, if it's also not the first pages to be evicted by the kernel when it needs memory for more important uses.

But generally, if you're incurring heavy I/O on a drive, I would think you *want* the page cache for that drive to use as much RAM as possible. Especially if you have a slow drive (which I imagine is unavoidable with FUSE).
