### ISSUE TITLE
announcing undesired IPv6 in ipv6= parameter sent to tracker

### ISSUE THREAD

**Issue by ghost** [arvidn/libtorrent#5318]
**Please provide the following information**

libtorrent version (or branch):
1.2.11
platform/architecture:

compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I have two IPv6 addresses. One is bound to my main interface and another pseudo IPv6(teredo) adapter(these start as `2001:0:......`)

The problem is that when I select to listen on all interfaces(default), qBt is including my teredo address in the `&ipv6=` parameter sent to the tracker(v4 tracker which collects v6 through a parameter) instead of the IPv6 of my main ethernet interface. The tracker doesn't accept teredo addresses and only returns v4 peers.
But if I specify my Ethernet adapter in the network interface my main v6 gets included in the  `&ipv6=` parameter.

I think libtorrent should be able to figure out the main active interface and fetch that IPv6 instead. Or just ignore any IPv6 starting with 2001:0: and fe80: etc.

**Comment by arvidn** [comment]
as far as I can tell from the code, *all* of your IPv6 addresses (that aren't local or loopback) will be reported to the tracker. So, it should be announcing your main IPv6 address in addition to the teredo address.

So, presumably the tracker is expecting only one `&ipv6=` parameter, and it picks the teredo address. Is there anything inherently wrong with posting the teredo address? It seems like it could be reasonable, it's just that this tracker filters it.

**Comment by an0n666** [comment]
If there are multiple `&ipv6=` parameters reporting all IPv6 then I guess it's an issue with the tracker. I mean it could choose to discard the teredo but accept the main one.

**Comment by arvidn** [comment]
is there perhaps libtorrent can do here by ordering the HTTP parameters by some metric?

**Comment by an0n666** [comment]
The issue was resolved by the tracker operators. 

However, I think most of the trackers expects only one &ipv4 and &ipv6 parameter.
So whenever libtorrent is including more than one, they're either getting overwritten or ignored. This is because 99% of the trackers store one IPv4+v6 per peer. 
Again this is an issue with the tracker software itself and not libtorrent. 
Accepting multiple IP addresses from one announce possesses a great risk as anyone could append tons of fake ipv4 parameters to fillup a swarm with fake IP. So traditionally most trackers like to store one address against each peer id.
