### ISSUE TITLE
Very low download performance using USB3 disk with Ubuntu 20.04.1 LTS, Python binding

### ISSUE THREAD

**Issue by lopezvg** [arvidn/libtorrent#5323]
libtorrent version (or branch): 2.0.1 Python 2.7/3.8 binding

platform/architecture: Ubuntu 20.04.1 LTS, Kodi 18/19, USB3 disk

compiler and compiler version: gcc++9

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Downloading a torrent file on a USB3 1 TB disk under Windows 10, Kodi 18 Libtorrent Python 2.7 binding, it obtains the max. network performance.  However, with the same PC & disk, booting fom Ubuntu 20.04.1 LTS, Kodi 18 Libtorrent Python 2.7 binding, the downloading stars very slowing and soon stalls.  Testing the same configuration with Libtorrent 1.2.11 Python 2.7 binding works perfectly in all environments.

**Comment by arvidn** [comment]
same computer and same disk you say, is it formatted as NTFS? if so, how are you mounting it on linux? via a FUSE driver by chance?

I take it downloads work fine to other drives, that are not USB. Is that correct? If so, have you had a look at what the operating system is doing with the disk? Say, the number of dirty pages it has on the drive, and at what rate it's flushing them.

**Comment by lopezvg** [comment]
Sorry fo the delay on my answer.  Let me give you more information so you can get a better picture.

I'm using latest generation technology (2020) in both the PC and the external disk:
- PC i7-1065G7 - 16 GB mem. - 1TB SSD - Dual boot W10 2020 (October) and Ubuntu 20.04.1 LTS
- Seagate 5TB USB3 NTFS formatted
- Ubuntu Mount: /dev/sda2 on /media/lopezvg/BUNKER type fuseblk (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096,uhelper=udisks2)

I've been doing some testing so I believe I have found the root cause of the problem: lt.storage_mode_t

The way I use Libtorrent in Kodi is starting the download and as soon as there is enough pieces downloaded I start the reproduction of the video.  For that reason I use lt.storage_mode_t.storage_mode_allocate.

Until LT version 2 there has been no problem with it, but starting with version 2 I've seen strange behaviors in Ubuntu (no in W10): it looks like the storage_mode_allocate mode has taken the storage_mode_sparse behavior and viceversa.

- storage_mode_sparse: works perfectly with both internal SSD and extenal USB3 NTFS.  However I can't reproduce while downloading with version 1.2.11 (error form Kodi)

- storage_mode_allocate - using USB3 disk to download:
   - It stars the download but stall after few second.  The USB3 disk light keeps blinking for nearly 4 minutes and then resumes the download at full speed and it starts the reproduction totally normal.  I don't know what is doing in these 4 minutes, but I tried with a couple of videos with different size and the wait time seems to be constant.

- storage_mode_allocate - using internal SSD disk to download:
   - it stars the download at full speed and right after loading the first (20) pieces it stars the reproduction.  The problem is that the reproduction freezes

Hope you get a better feeling with this info.  Regards

**Comment by arvidn** [comment]
I don't know what you mean by "reproduction of the video", but it doesn't seem central to the issue. Do you mean "start playback"?

I would expect that the FUSE driver is a lot slower than a native driver (which could explain difference between linux and windows). Since this seems related to storage allocation, that's system specific and also different between linux and windows anyway.

I don't understand what your motivation for using `lt.storage_mode_t.storage_mode_allocate` is. If I understand correctly, you can play back video from sparse files as well. The video player will see the same bytes.

Anyway, what this storage allocation mode will do is to try its best to ensure all the space on disk is allocated and committed and cleared with zeroes up-front. This used to be its own step before starting the download, but now it's done "lazily", when a file is written to for the first time. If the file is large and the storage is slow, I would expect it to take a while. It's more surprising that it's quick with libtorrent 1.2.11. That might suggest that there's something broken in the allocate storage logic there.

You can see the ways libtorrent attempts to allocate storage for a file [here](https://github.com/arvidn/libtorrent/blob/RC_2_0/src/mmap.cpp#L350), on linux.

* posix_fallocate()
* fcntl(.., F_ALLOCSP64, ..)
* fcntl(..., F_PREALLOCATE, ...)

**Comment by lopezvg** [comment]
Yes, by "reproduction of the video" I meant "start playback".

"I don't understand what your motivation for using lt.storage_mode_t.storage_mode_allocate".  In W10 it works either allocate o sparse, but on Ubuntu 1.2.11 requires "allocate", otherwise I get a Kodi error on start playback.

The file I was using is 2GB size and the USB3 disk is the fastest you can buy now, so it can'n take 4 minutes to 0's

**Comment by arvidn** [comment]
> the USB3 disk is the fastest mechanical you can buy now, so it can't take 4 minutes to 0's

But mounting it via a FUSE driver is (probably) the *slowest* possible way of accessing it. I'm not saying that necessarily explains the 4 minutes, but it *could*. `iostat` might shed some light.

**Comment by lopezvg** [comment]
Attached you'll find logs running for 6 minutes while performing the latest test:

Ubuntu 20.04.1 LT, 16GB mem, 1TB internal SSD, 5TB USB3 mechanical disk
Kodi 19 Beta, Libtorrent 2.0.1 Python Bindindg 3.8, lt.storage_mode_t.storage_mode_allocate, 2GB download

Please, let me should you more information.

[sar_cpu_file.txt](https://github.com/arvidn/libtorrent/files/5653997/sar_cpu_file.txt)
[sar_mem_file.txt](https://github.com/arvidn/libtorrent/files/5653998/sar_mem_file.txt)
[iostat_file.txt](https://github.com/arvidn/libtorrent/files/5653999/iostat_file.txt)

**Comment by arvidn** [comment]
> is it normal that the free main memory decreases by 4 GB during the process?

Yes, I would expect so. as you're writing to disk, more of the free memory will be used as page cache by the kernel.

My guess would be that the main cause of this delay is that you're allocating the file up-front, over a very slow device (a FUSE-mount). Perhaps the allocation of the file is even done from user space in that setup.
