### ISSUE TITLE
move_storage() into the torrent's subfolder fails

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#543]
1. Multifile torrent
2. Path `G:\a`. Multifile torrent creates its root, so files are actually saved in `G:\a\root`.
3. Let it write something to disk first
4. Set location to a folder inside root. eg `G:\a\root\b`.

The move fails with:
>Could not move torrent: 'torrent name'. Reason: <torrent name> storage move failed: The filename or extension is too long

And on disk I get this path created:
```
G:\a\root\b\root\b\root\b\
```

**Comment by arvidn** [comment]
I would imagine this to fail with "mv" and "rename" too, no? This is just a single rename of a directory to be a subdirectory of itself. I suppose one thing to do would be to first rename the root directory into some random name, and then apply the renaming, but I'm not sure that would be any more intuitive, and there would be the risk of error paths not restoring the name.

I suppose the expected behavior is to detect the longest common subdirectory between the target path and the paths part of the torrent, and essentially:

1. rename the root to a random name
2. create all directories in the destination path
3. perform the move

**Comment by sledgehammer999** [comment]
Shouldn't this be transparent to the end application? We tell libtorrent to move the torrent to path X and libtorrent handles all the intricate details.

**Comment by arvidn** [comment]
well.. I don't think "mv" would for instance, so I don't think it's obvious. Anyway, the reason you get a surprising error message is because the first move/rename call fails, and libtorrent assumes that any failure in move means that copying may work, so it tries to copy, recursively. this obviously fails with infinite recursion.

I think the most obvious fix would be to specifically handle the error you get when moving a directory into itself, and simply report that error back.

**Comment by glassez** [comment]
The root of this problem (and #435 too) is too simplified storage moving implementation.

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/546

**Comment by arvidn** [comment]
it just occurred to me that that patch may actually break the case where storage is moved across volumes. it's possible that results in an invalid argument too

**Comment by arvidn** [comment]
my patch and test should pass on windows now. If anyone would want to give it a try I'd appreciate it. specifically, make sure moving a torrent across volumes/drives still work.

In order to make the case of moving a folder into itself work, even if files were moved individually you could run into the case where you get file collisions. As far as I can tell, the only reliable way of doing it would be to first rename the whole directory to a temporary name, then create the destination path, and then move it again in there.

That wouldn't solve the problem raised by #435 though. To support both the temporary location could be built from scratch, moving every file belonging to the torrent in there individually, then make sure the destination path exists and then move the files individually into the final path. in fact, the temporary storage does not need to map the actual torrent directory structure, files could really just be called 1,2,3 etc. as long as the (randomly named) root directory is unique.

**Comment by arvidn** [comment]
here's the patch btw: https://github.com/arvidn/libtorrent/pull/546
