### ISSUE TITLE
python binding - install module - does not install shared libs

### ISSUE THREAD

**Issue by userdocs** [arvidn/libtorrent#5766]
**Please provide the following information**

libtorrent version (or branch): tested on RC_1_2

platform/architecture: any

compiler and compiler version: b2 / boost 1.75

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

If I used b2 like this with the python binding:

```bash
libtorrent-link=shared boost-link=shared stage_dependencies install_module python-install-scope=user
```

**1:** The main python library will be installed but the `stage_dependencies` files are not installed.

**2:** If i skip `stage_dependencies` the shared items are never created meaning `install_module` will install a broken object (maybe a test to prevent this?)

Tbh, i don't have this issue with a static install, i just noticed it when trying to install the shared binding and getting a runtime error.

So i was wondering if you could help me understand.

**1:** Is this the expected behaviour and i should manually copy/install the libs from `/bindings/python/dependencies`

or

**2:** It should be part of the `install_module` command?

Currently i would need to use `stage_dependencies` regardless. If it was part if the `install_module` i'd like to skip that.

If you let me know your thoughts i will attempt a working example.

**Comment by arvidn** [comment]
did this get resolved?
what happens if you add `install-dependencies=on` to the command line?

**Comment by userdocs** [comment]
It's not solved.

Using this appears to do nothing `stage_dependencies install-dependencies=on` as the outcome is this.

```bash
root@localhost:~# python3 -c "import libtorrent; print(libtorrent.version)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: libboost_python37.so.1.75.0: cannot open shared object file: No such file or directory
```

If I manually copy the dependencies it works.

```bash
root@localhost:~# cp -fRT qbit/libtorrent/bindings/python/dependencies/ /usr/local/lib/
root@localhost:~# python3 -c "import libtorrent; print(libtorrent.version)"
1.2.12.0
```

So it appears the dependencies are never copied to a system library path and the `install-dependencies=on` option is broken or doing something wrong.

Here is the build script, it works in a docker. 

https://gist.github.com/userdocs/fbe89dcb59d3e7177504be4da213bd6d

**Comment by arvidn** [comment]
Right, that's deliberate. I think it would be controversial for an install rule to also install dependencies. That's the kind of things package managers do.

There are a few options.

**link against system packages**

Link against system-installed boost and libtorrent-rasterbar libraries (this is the default on non-windows when using `setup.py`). This happens when specifying `libtorrent-link=prebuilt`. linking against system-installed boost is typically the default. If the environment variable `BOOST_ROOT` is set, boost is built from source from that location, so to be extra sure to link against system boost, prefix the command by `BOOST_ROOT= `, like this:

```
BOOST_ROOT= b2 install_module libtorrent-link=prebuilt
```

**link statically**

like this:

```
b2 boost-link=static libtorrent-link=static install_module
```

This requires `BOOST_ROOT` to be set though. You can also mix-and-match, if you have boost installed but not libtorrent, just specify `libtorrent-link=static`

The `setup.py` is supposed to pick the most reasonable default. I'm open to suggestions on how to improve this situation.

**Comment by userdocs** [comment]
Well, the reason I closed this was because I use static and this was not really an issue for me personally, so that part we agree on.

But, it raises the question. If I am building and installing the python binding myself, with no reliance on packet managers or pre built libraries, how do I build and install a functional python binding using this method.

Currently it appears the only real option when using `libtorrent-link=shared boost-link=shared` is to copy the the shared libs manually , like this.

```
cp -fRT libtorrent/bindings/python/dependencies/ /usr/local/lib/
```

I would argue that in this particular example, having a option to install dependencies to `/usr/local/lib` as part of the build process would make sense and is perfectly valid as I can build, manage and use the binding this way. Though I would suggest it is a very deliberate choice and not default or automated.
