### ISSUE TITLE
Add for libtorrent a direct server function for full download speed

### ISSUE THREAD

**Issue by ghost** [arvidn/libtorrent#5780]
**Is your feature request related to a problem? Please describe.**
I am very frustrated there is no easy way in torrent client to provide files and give full download speed only for some users, so similar to Usenet.

But without account and any provider dependence. Directly from my high-end smartphone with 5G unlimited data plans.

**Describe the solution you'd like**
Sorry, I'm just a user.

I will try to offer a solution. Currently when I want to share my files for a short time for someone or for random users can not reach the maximum download speed, because sometimes is dependent on Seeds etc.. 

**For which platform is this feature request?**
- Platform: [Linux, Android]

**Do you have an idea of how we would add it?**
The libtorrent developers integrate such a direct server function so that the users for certain users e.g the first random 10 users can load the file and the download speed e.g my 5G data plans creates a maximum of 1 Gbits and each "peer" can load a maximum of 100 Mbits and if automatically there are less random users then the maximum download speed increases.

Can you create a similar server function with torrent technology? This is only supposed to be an additional function.

I think this idea is that each user has its own torrent server directly on his device.

**Comment by NotTsunami** [comment]
-1. You would be extending the BitTorrent protocol to implement this. This is a library implementation of the BitTorrent protocol. I don't feel it's necessary to break this down bit by bit, but even if you wanted to share full speed with a random user, they are still capped by your upload or their download, and I highly doubt you would ever see the speeds that you are desiring.

**Comment by arvidn** [comment]
I don't understand the proposed solution. I get the impression that the problem is "my download is slow". If your download is slow, it means there aren't enough people willing to give their upload capacity to you. If *you* want to give *your* upload capacity to other users, that's totally possible today. Just uncap your bittorrent client and keep seeding. If you want to rent a server to run your bittorrent client on to give that bandwidth away to other users, that's also fine. libtorrent runs on servers too.

Every bittorrent peer connection is a "direct download server". The "full download speed" part obviously depends on the uploader and downloader capacity. Is the proposal to be able to add a server that for sure has greater upload capacity than all its peers? (because that could also just be a bittorrent client).

Please elaborate.

**Comment by Chavahtem** [comment]
I think I meant rather a torrent cloud software or app on the notebook or smartphone where the user e.g for friends, few random users or privately share or stream his files and folders. It should also be possible to edit the files or folders in a small team. In addition, the data transfer is encrypted and it is not account dependent.

So a torrent P2P central or hybrid solution. Is there such a thing?
If there is such a thing then I don't need more cloud app like Dropbox, Google Drive etc. because they are account dependent.

The idea is that then each user can create his own torrent cloud server directly from his device. I think in the future with 5G connections and very fast mobile devices it will be possible.

**Comment by arvidn** [comment]
you're describing a product that could be built using libtorrent, not a feature that should be added to libtorrent. A few examples: https://en.wikipedia.org/wiki/Comparison_of_file_synchronization_software

**Comment by Chavahtem** [comment]
> you're describing a product that could be built using libtorrent, not a feature that should be added to libtorrent. A few examples: https://en.wikipedia.org/wiki/Comparison_of_file_synchronization_software

I know this software, but they are not designed to be user friendly, and have some random problems and do not use torrent technology. I am looking for exactly the same user feeling as on Google Drive, Dropbox etc. but without account and other external dependencies.

You say it is possible to create something like this with libtorrent, do you know any software or app that can do this?

If not I should probably send a feature request to one of the torrent client developers to see if they can create something like this. Do you know a torrent client where I should send the request? Which people could create something like this?

**Comment by arvidn** [comment]
Resilio Sync (formerly known as BitTorrent Sync) uses bittorrent to transfer files. It doesn't require accounts, but it requires *identities* (i.e. key pairs). And it will be less user-friendly since there's not central coordination of users. So sharing requires sending keys, or access codes to acquire keys securely.

It's not open source though.
