### ISSUE TITLE
assert(false) in piece_picker::pick_pieces

### ISSUE THREAD

**Issue by ssiloti** [arvidn/libtorrent#587]
I've seen this several times running 2e6685c (from RC_1_0). I believe it has to do with setting files to do not download. In this case the torrent I was downloading has three files of lengths 2246385239, 2767239777, 1551335979 bytes respectively. The first and last files were both set to Do Not Download in deluge. The piece size was 8MB. The failing piece here was 597 which, if you do the math, is the last piece with data from the middle file. I haven't seen any actual problems arise so I suspect this is a bug in the assertion itself.

I'm still trying to wrap my head around the piece picker code.

[stderr.txt](https://github.com/arvidn/libtorrent/files/203446/stderr.txt)
[ppbacktrace.txt](https://github.com/arvidn/libtorrent/files/203447/ppbacktrace.txt)

**Comment by arvidn** [comment]
the picker is a bit more complicated than I would like. I tried to make up for it with very high test coverage though. One reason that makes it a bit more complicated is performance. You don't really have the luxury to scan pieces in multiple passes, but you still want prioritization and affinities of which pieces are better to pick from (apart from rarity).

The assert that trips runs because num_blocks > 0, meaning that the upper layer was really asking to pick more pieces. In your case, at the end of the picker function it was short 40 blocks. Returning fewer blocks than was requested is only acceptable if there literally are no more blocks to pick (and at least one busy block may be picked as well).

What your debug output shows is that there are two "partial" or downloading pieces that are outside the range of the middle file. i.e. their piece priority should be 0. (the reason they exist is because some blocks were picked before the file priority was set to 0).

However, the last piece of the middle file, 597, still appears to have unpicked blocks in it. The pieces that are printed are the partial/downloading ones, with at least one block that is in a state other than state_none. Each digit that's printed corresponds to a block and the digit is the state it's in. 0 means state_none, and all those zeroes in 597 indicates that those blocks are free, and they should have been picked (or at least 40 of them).

**Comment by arvidn** [comment]
I believe this fixes it. would you mind giving it a try?
https://github.com/arvidn/libtorrent/pull/588
