### ISSUE TITLE
Question : Required port range for trackerless

### ISSUE THREAD

**Issue by bemaru** [arvidn/libtorrent#5883]
libtorrent version (or branch): 1.2.3

platform/architecture: windows10 x64

compiler and compiler version: vs2015(v140)

I'm testing with client_test.exe.
I want to run trackerless, but peer discovery seems to fail.
(When I use the tracker it works fine.)

The port allowed between seeder and peer is TCP 6881~6889, UDP 6881.
Also, UDP 1900 and 6771 ports are allowed for each multicast group address.
(Except for a few ports, all ports are blocked, and only necessary ports are allowed.)

As I know, Various udp ports are required for peer discovery.
Should I allow all UDP ports?

**Comment by arvidn** [comment]
If your peers can talk to each other without forwarding any ports, there's no need to forward anything else.

there are a few things "peer discovery" can refer to. I would think the most likely one is the DHT. Make sure you can bootstrap the DHT. There is a DHT bootstrap server configured by default that should be reachable via both IPv4 and IPv6.

If you really mean local service discovery, that relies on multicast working on the local network. There shouldn't be any need for port forwarding here, since (presumably) the firewall wouldn't filter packets on the local network.

That said, forwarding the peer ports you bind your client to will always be a benefit, as you can talk to more peers. Just the TCP and UDP port, whichever you pick. It defaults to 6881.

**Comment by bemaru** [comment]
The tcp udp for 6881 is allowed in the firewall, but it still doesn't work with DHT.

In more detail,
I am working on a private network that is not accessible via the internet (like google.com). However, connection between A and B peers is possible.
And there is a firewall and L3 switch between peer A(ip 10.x.x.x) and B(ip 11.x.x.x).

The dht count shown in the capture below (red circle) increases when using tracker, but continues to be 0 when configured as trackerless.
![image](https://user-images.githubusercontent.com/22659938/105130499-83079b80-5b2a-11eb-9457-a1467f606bcf.png)

Do I need to have a bootstrap server for trackerless DHT?

**Comment by arvidn** [comment]
I see. It sounds like your private network may be large enough to not have multi-cast enabled across all of it then. Is that right?

If so, the "local service discovery" (which us based on SSDP) won't work, at least not across segments that don't do multicast.

If *outgoing* traffic is also blocked by your firewall, the reason you can't bootstrap the DHT may be because the default DHT bootstrap router that I run is running on an odd port: `dht.libtorrent.org:25401`. However, if that's the case, being able to reach the bootstrap node may not help you very much since other DHT nodes in the wild tend to run on random ports too.

You *could* run your own, internal, DHT. By spinning up a DHT bootstrap node within your network. [This](https://github.com/arvidn/bootstrap-dht) is the node that I run. You would have to configure your clients to use your DHT bootstrap node, in the `dht_bootstrap_nodes` libtorrent setting.

**Comment by bemaru** [comment]
I'm trying to build bootstrap-dht, but it doesn't seem to compile with msvc. Does bootstrap-dht support windows platform?

**Comment by bemaru** [comment]
I converted posix api like open() and mmap() of dht bootstrap and compiled it in msvc.

On server A, run seeding and bootstrap node with client_test.exe and dht-bootstrap.exe.

B is waiting for file download by executing only client_test.exe.

Both A and B's client_test specify the dht_bootstrap_nodes option.

However, DHT is still not working. What should I check to solve the problem?


![image](https://user-images.githubusercontent.com/22659938/105332631-2da9b800-5c18-11eb-8f19-d1cc3e0d529f.png)


![image](https://user-images.githubusercontent.com/22659938/105332786-55008500-5c18-11eb-81a1-9b7ff18d325f.png)

**Comment by arvidn** [comment]
you can enable [dht logging](http://libtorrent.org/reference-Alerts.html#alert_category_t) in the `alert_mask` [setting](http://libtorrent.org/reference-Settings.html#alert_mask). That will give you every DHT packet sent and received

**Comment by arvidn** [comment]
the counters you have in the bootstrap node are in "invalid source". You probably need to remove some restrictions in there, to accept IP addresses on local networks. It's made for being run on the internet out-of-the-box.

**Comment by bemaru** [comment]
Are you saying to modify the client_test?
Should I modify the ip filter like below?

```cpp
    lt::session s(std::move(params));

    std::uint32_t const mask = 1 << lt::session::global_peer_class_id;
    lt::ip_filter f;

    // for every IPv4 address, assign the global peer class
    f.add_rule(address_v4::from_string("0.0.0.0")
        , address_v4::from_string("255.255.255.255")
        , mask);

    // for every IPv6 address, assign the global peer class
    f.add_rule(address_v6::from_string("::")
        , address_v6::from_string("ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff")
        , mask);
    s.set_peer_class_filter(f);
```

**Comment by arvidn** [comment]
> Are you saying to modify the client_test?

No.

The DHT bootstrap rejects incoming packets from local network addresses, because those would just be noise on the internet. You would need to remove this restriction to *accept* local network addresses.

**Comment by bemaru** [comment]
I see. I'll check the dht bootstrap source.

**Comment by bemaru** [comment]
I modified the is_valid_ep() function to always return true, but it doesn't work.
