### ISSUE TITLE
Python bindings (Windows) - Downloading/writing .exe files issue

### ISSUE THREAD

**Issue by Gallardo994** [arvidn/libtorrent#5907]
libtorrent version (or branch): 2.0.2

platform/architecture: Windows 10 x64, Python 3.7.8 x32

compiler and compiler version: boost 1.73, Python 3.7.8 x32, the rest is from the documentation

The issue comes with downloading an executable from peers, rendering libtorrent unable to connect to virtually any tracker and/or peer including DHT peers.

Steps:
1. Download entire torrent in the attachment
2. Delete .exe files in the root directory
3. Completely restart download of the torrent (with clean session, without resume_params and etc - as if it's new)
4. Most of the time, you will get a quick spike in download, then it will reset to 0 peers and never actually download the file (or sometimes it goes up to 200 peers slowly, but never does anything). The download will get stuck in 99.99<whatever> progress and alerts will show that all the connections get timed out. Destroying the session and adding back the same torrent a time or two fixes the issue, and the files actually get downloaded as intended.

(!) Libtorrent 1.2.4 does not have this issue and all the files are downloaded properly each time. I can confirm the issue reproduces in libtorrent 2.0.0, 2.0.1 and 2.0.2.

It could also be related to files having a digital signature, but that is not confirmed.

What I tried:
* Completely removed any antivirus software. The issue reproduces in a clean virtual machine, in all versions of Windows starting from 7SP1
* Added python and everything to Windows Defender exceptions
* Added python and everything to Windows Firewall exceptions, allowed all connections to any port
* Completely disabled Windows Defender
None of the attempts made any difference.

Attaching the torrent file which can reproduce the issue (you can skip huge files but keep the root folder):
[v15.0.v2.torrent.zip](https://github.com/arvidn/libtorrent/files/5863317/v15.0.v2.torrent.zip)

**Comment by arvidn** [comment]
I've been looking into this some. Are you confident it has anything to do with the torrent containing a .exe?

I can reproduce the issue only when the download directory is a network share (i.e. the host system of my windows VM). If I download to the virtual machine's own drive, `c:\`, it works fine (I've tried a few times).

What makes this an odd issue is that when I try to inspect the process, after reproducing the issue downloading to a network drive, anything that touches the process or the network share hangs.

* Explorer hangs trying to list the save directory
* Visual studio hangs trying to pause the process
* task manager hangs trying to kill the process.

(and once in this state, all I can do is to reset the virtual machine and reboot).

This makes it tricky to understand what's going on. One thing I managed to do was to download to the network share, but log to a local drive. This at least gave me a log of what was going on.

I do see a lot of `PIECE_REQUEST_TIMED_OUT` in the log. As if all peers stalled somehow.

One hint I see is that libtorrent stops reading from sockets, with messages like this:
```
<<< CANNOT_READ [ quota: 93904  can-write-to-disk: no queue-limit: 1048576 disconnecting: no  connecting: no ]
```

That `can-write-to-disk: no` means that this peer has too many bytes waiting to be written to disk, that it can't receive any more over the network. i.e. this is back-pressure from the disk. It suggests that the libtorrent disk threads are stalled.

When the network thread downloads faster than the disk can write, and it has to hold back to let the disk catch up, this message is logged:

```
*** DISK [ exceeded disk buffer watermark ]
```

Which shows up a lot in the log. When the disk catches up again, this is printed:

```
*** DISK [ dropped below disk buffer watermark ]
```

Which also shows up a fair amount. The last time this happens (in my latest test run) is 1478.220 seconds in. There are several logs after that indicating we hit the upper limit again, at 1487.847 seconds.

I also captured the performance counters for this test run, which I've made some plots from. Something definitely happened about 1500 seconds into my run:

![disk_write_queue_0000](https://user-images.githubusercontent.com/661450/106059064-6e12a580-60f2-11eb-8035-8f1ab4b7116c.png)

Here's a plot of the number of disk threads that are running, and what they're doing. They all get stuck writing to disk.

![disk threads_0000](https://user-images.githubusercontent.com/661450/106059389-f09b6500-60f2-11eb-8382-e08704d92628.png)

Since other processes also stalled accessing the disk, it seems that something deeper than just a bug in the disk thread, making it hang. I wonder if there's an issue with too many file mappings at the same time, on a network drive. It defaults to 40, which doesn't seem like that many.

**Comment by Gallardo994** [comment]
I can personally reproduce this in 2 virtual machines, my local machine, and several different PCs running different versions of Windows, virtually on any drive, including system one. The problem is, as soon as i rename .exe files to smth like .wtf extension before the torrent starts, the problem fixes itself.

**Comment by arvidn** [comment]
I'm not entirely convinced that the problem I'm experiencing is the same as yours. One interesting experiment would be to run without using memory mapped files.

That's done by creating the session with a `session_params` object where `disk_io_constructor` is set to `posix_disk_io_constructor`. That's not possible to do via the python bindings though, so you could either rebuild as a 32 bit executable (`address-model=32`) or with memory mapped files disabled (`mmap-disk-io=off`).

**Comment by Gallardo994** [comment]
I do build it x32 for Python bindigs. Will it work or do I exactly have to have a separate executable?

**Comment by arvidn** [comment]
I'm not sure whether a 64 bit python binary will be able to load a 32 bit module. It's possible. Windows has some pretty impressive glue in its WOW64.

**Comment by Gallardo994** [comment]
I actually use x32 Python too, so that should work

**Comment by arvidn** [comment]
so, was it the memory mapped files on a network share that caused the issue?
