### ISSUE TITLE
1.2.12 breaks cross compiling for python binding

### ISSUE THREAD

**Issue by xuefer** [arvidn/libtorrent#5932]
**Please provide the following information**

libtorrent version (or branch):
1.2.12 (RC_1_2)

platform/architecture:
openwrt/x86_64

compiler and compiler version:
gcc 10.2.0

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

```
In file included from src/magnet_uri.cpp:5:
src/boost_python.hpp:10:10: fatal error: boost/python.hpp: No such file or directory
```

unexpectedly: host compiler/linker and flags are used to compile target
```
warning: No toolsets are configured.
warning: Configuring default toolset "gcc".
warning: If the default is wrong, your build may not work correctly.
warning: Use the "toolset=xxxxx" option to override our guess.
warning: For more configuration options, please consult
warning: http://boost.org/boost-build2/doc/html/bbv2/advanced/configuration.html
.....
    "g++"   -fPIC -O3 -finline-functions -Wno-inline -Wall -Wno-deprecated-declarations -fvisibility-inlines-hidden -fvisibility=hidden -DNDEBUG -DTORRENT_USE_I2P=1 -D_WIN3
2_WINNT=0x0600  -I"../../include" -I"/openwrt/source/staging_dir/hostpkg/include/python3.9" -I"/opt/local/include" -I"/usr/local/include" -I"/usr/sfw/includ
e" -I"src"  -c -o "bin/gcc-9.3.0/release/address-model-64/lt-visibility-hidden/python-3.9/src/module.o" "src/module.cpp"
```

"g++" is host compiler which is unexpected, expecting target compiler "ccache_cxx" (providing CXX=ccache_cc by openwrt)
cflags like "-I" flags missing quite a lot for target include dirs, unexpected "/openwrt/source/staging_dir/hostpkg/include/python3.9"  which is from host python sysconfig, expecting target include directory "/openwrt/source/staging_dir/target-x86_64_glibc/usr/include/python3.9”

reason: bindings/python/setup.py does not pass all necessary flags decided by configure like openwrt or gentoo do
see:
https://github.com/openwrt/packages/blob/master/libs/boost/Makefile#L405
```
echo "using gcc : $(GCC_VERSION) : $(GNU_TARGET_NAME)-gcc : <compileflags>\"$(TARGET_CFLAGS)\" <cxxflags>\"$(TARGET_CXXFLAGS) $(EXTRA_CXXFLAGS)\" <linkflags>\"$(TARGET_LDFLAGS)\" ;" > \
tools/build/src/user-config.jam ; 
```

https://github.com/gentoo-mirror/gentoo/blob/stable/dev-libs/boost/boost-1.75.0.ebuild#L94
```
using ${compiler} : ${compiler_version} : ${compiler_executable} : <cflags>"${CFLAGS}" <cxxflags>"${CXXFLAGS}" <linkflags>"${LDFLAGS}"
```

previous setup.py may not be perfect but was better than this. changing build system in minor release is bad IMHO

**Comment by xuefer** [comment]
[0003-fix-python-bjam-build.diff.txt](https://github.com/arvidn/libtorrent/files/5900996/0003-fix-python-bjam-build.diff.txt)
I haven't figure out how to deal with python paths but this patch works for me fixing most of the problem. I see no reason to filter out most of cxxflags and ldflags assuming they're correct

**Comment by AllSeeingEyeTolledEweSew** [comment]
I did the refactoring of `setup.py` to be invoke `b2`, but I don't have that much familiarity with `b2`.

Based on your links, looks like it's normal for distributions to modify `user-config.jam` to configure `b2`-based packages. Could you walk me through the normal way that those configurations should be picked up, when building such packages? Do we need to pass `b2 toolset=gcc` or `b2 toolset=$CXX` or something?

I feel pretty hopeless trying to read `b2` documentation to understand such things.

You modified the code path that picks up configuration from `libtool`, but this is a deprecated path now. libtorrent 2.0+ doesn't have any `libtool` build system at all. It's probably best to get `setup.py` to invoke `b2` such that it picks up the right stuff from the distro `user-config.jam`, rather than via libtool. We can port that to the newer branches.

**Comment by AllSeeingEyeTolledEweSew** [comment]
Also, the motivations for refactoring `setup.py` were
1. libtorrent is going to continue to use `b2` as its primary build system, but
2. we need to take advantage of python-specific packaging (building wheels for pypi; sdist-install for `tox`; etc)

`b2` is really not meant to be used this way and it's always going to be brittle, it's just the *least* brittle approach I could see.

So, I recommend that if distro build scripts like openwrt and gentoo can just use `b2` to build the python bindings directly instead of going through `libtool` and `setup.py`, they should probably do that.

**Comment by xuefer** [comment]
You're right to go for b2 on 2.0 branch, not so for 1.2 branch, but I feel the same hopeless.  Let's hope this ticket (and this project) attract more b2 experts.

I'm not sure if boost on openwrt is well maintained since big packages like this isn't commonly used by small devices. 
Beside cooking homebrew build script from scratch, we can always lean from other packages build script on heavily used distro like debian/ubuntu/gentoo

**Comment by AllSeeingEyeTolledEweSew** [comment]
Are you a distro maintainer? I assumed you were, as you mentioned cross compiling and cited some distro scripts. Otherwise what's your context for cross-compiling? What are you trying to do?

I searched all build scripts for alpine linux, gentoo and openwrt. I can't find ANY packages that build using `b2`, except for boost itself. @arvidn I know I've been salty about `b2` over the last few weeks, but I think this is a really significant data point

I don't have as much experience with debian/ubuntu's build system; I don't know how to search the whole build script corpus there

**Comment by xuefer** [comment]
> Are you a distro maintainer? I assumed you were, as you mentioned cross compiling and cited some distro scripts. Otherwise what's your context for cross-compiling? What are you trying to do?
I don't think myself as a distro maintainer but I'm running my ported deluge+libtorrent-rasterbar on one of my openwrt device
cross compiling is the only way to run on openwrt device since most if not all device compile anything on target device. They're a lot of other users run torrent p2p on wrt-alike platforms for 24h/7days running
> 
> I searched all build scripts for alpine linux, gentoo and openwrt. I can't find ANY packages that build using `b2`, except for boost itself. @arvidn I know I've been salty about `b2` over the last few weeks, but I think this is a really significant data point
> 
gentoo maintainer @mgorny updated to [https://github.com/gentoo-mirror/gentoo/tree/stable/net-libs/libtorrent-rasterbar libtorrent-rasterbar-1.2.11] just 4 days ago, not yet for 1.2.12.

**Comment by arvidn** [comment]
I realize it was probably a mistake to land the `setup.py` overhaul in the 1.2.x branch, sorry about that.

As for this issue, my understanding is that this really is limited to the python bindings, right? From the openwrt package file it looks like the main library's cross compilation is configured (as it's meant to be) via `user-config.jam`. It seems to me it boils down to:

1. How do you specify which toolset (compiler) to use when building the python bindings. The toolset configures the compiler binary, compile- and link flags, include paths etc.
2. How do you specify which python version to link against. When cross compiling, auto-detecting based on which python version is running `setup.py` won't work, since that's the host python.

The previous `setup.py` kind of separated the two steps. `b2` was invoked, relying on the default toolset configured, and relying on the python configuration in `user-config.jam`. This allowed full control over both target platform and target python version. However, it was tedious to manually configure python.

The current `setup.py` assumes that the python bindings are to be built for whatever python version is executing `setup.py`, which seems like a reasonable default.

As far as I can tell, it would be sufficient to have an option to `setup.py` to disable all auto-detection, and defer entirely to `user-config.jam`. Both for toolset and python config.

As for picking up environment variables to affect these things, I'm a bit hesitant. I will take a closer look at the openwrt and gentoo build scripts to see what they rely on, to better understand how I can help solve this.

**Comment by arvidn** [comment]
Looking over the proposed setup.py patch:

It proposes restoring the use of "compile_cmd", "compile_flags" and "link_flags" files. These files were a work-around to forward the build configuration from ./configure to setuptools when building the bindings. I would like to phase these out. As far as I can tell from going over the openwrt [build script](https://github.com/openwrt/packages/blob/master/libs/boost/Makefile), it does not touch these files. I don't get the impression they are necessary for its build script to work.

However, the gentoo [build script](https://github.com/gentoo-mirror/gentoo/blob/stable/net-libs/libtorrent-rasterbar/libtorrent-rasterbar-1.2.11.ebuild) *does* touch these files. The only thing it does is to strip "-std=c++11" from "compile_cmd". It also updates library path in "link_flags" and header include paths in "compile_flags".

With the recent changes to setup.py, I suspect those changes may not be necessary, I think the ebuild currently benefits from the python auto-detection. The removal of std=c++11 is a bit suspicious, if it should be removed from the binding, it most likely should be removed from the main library too, which is controlled by the configure script.

The other part of the patch adds this to the b2 configuration (site-config, which is written to a temporary file by `setup.py`):

```
write("using gcc")
write(" : ")
write(f" : {self.cxx}")
write(f" : <cxxflags>\"{self.cxxflags}\" <linkflags>\"{self.linkflags}\" ;\n")
```

This essentially is a way for a build script to configure a toolset via environment variables, and have `setup.py` include it in the configuration it writes.

It would seem simpler if they could be separated. The build script should configure the toolset (independent of `setup.py`) and `setup.py` auto-configures python. Additionally, there would need to be an escape-hatch where the build script opt-out of auto detecting python, to support cross compilation.

The build script *could* write this directly to `Jamroot.jam` instead, in the root of the libtorrent repository. I think that would be a cleaner separation of toolset and python configs. It would be similar to how the openwrt script writes the toolset configuration to `~/user-config.jam`, but more localized.

@mgorny I'd be happy to help make the ebuild file work for 1.2.12 (which I also would expect would make it work for 2.0.x as well).

**Comment by xuefer** [comment]
Thanks arvidn, you have a better global view on this than I do.

regarding to your point 2:

it seems 3 ways to do this, both previous and current method used by libtorrent isn't the most compatible way. previously it use m4/ax*python.m4 which is too old, current using sysconfig from host python.

modern configure script tends to use python-config and later better pkg-config script, pkg-config is a better upgrade of anylib-config since since all *.pc is just metadata, the build system (like openwrt) can hack pkg-config by providing wrapper once for all
setup.py(setuptools)/cmake/scons all are doing good job for host build, but when it comes to cross compiling the write custom script ask pkg-config for help on auto detection

see https://github.com/openwrt/openwrt/blob/master/tools/pkgconf/files/pkg-config
```
~/src/openwrt/source/staging_dir
$ cat ./host/bin/pkg-config
#!/bin/sh

if [ -z "${STAGING_PREFIX}" ]; then
        exec /usr/bin/pkg-config "$@"
fi

pkg-config.real \
--keep-system-cflags \
--keep-system-libs \
--define-variable=prefix="${STAGING_PREFIX}" \
--define-variable=exec_prefix="${STAGING_PREFIX}" \
--define-variable=bindir="${STAGING_PREFIX}/bin" "$@"
```

```
~/src/openwrt/source/staging_dir
$ PKG_CONFIG_PATH=$PWD/target-x86_64_glibc/usr/lib/pkgconfig PATH=./host/bin:$PATH STAGING_PREFIX=$PWD/target-x86_64_glibc ./host/bin/pkg-config python-3.9 --cflags
-I/home/xuefer/src/openwrt/source/staging_dir/target-x86_64_glibc/include/python3.9
```

**Comment by mgorny** [comment]
> > Are you a distro maintainer? I assumed you were, as you mentioned cross compiling and cited some distro scripts. Otherwise what's your context for cross-compiling? What are you trying to do?
> gentoo maintainer @mgorny updated https://github.com/gentoo-mirror/gentoo/tree/stable/net-libs/libtorrent-rasterbar to 1.2.11, not yet for 1.2.12.

Nope, not me. You're looking for @Zlogene.

**Comment by xuefer** [comment]
> Looking over the proposed setup.py patch:
> 
> It proposes restoring the use of "compile_cmd", "compile_flags" and "link_flags" files. These files were a work-around to forward the build configuration from ./configure to setuptools when building the bindings. I would like to phase these out. As far as I can tell from going over the openwrt [build script](https://github.com/openwrt/packages/blob/master/libs/boost/Makefile), it does not touch these files. I don't get the impression they are necessary for its build script to work.
> 
> However, the gentoo [build script](https://github.com/gentoo-mirror/gentoo/blob/stable/net-libs/libtorrent-rasterbar/libtorrent-rasterbar-1.2.11.ebuild) _does_ touch these files. The only thing it does is to strip "-std=c++11" from "compile_cmd". It also updates library path in "link_flags" and header include paths in "compile_flags".
> 
> With the recent changes to setup.py, I suspect those changes may not be necessary, I think the ebuild currently benefits from the python auto-detection. The removal of std=c++11 is a bit suspicious, if it should be removed from the binding, it most likely should be removed from the main library too, which is controlled by the configure script.
it maybe the same reason as my proposes patch. my patch move any args in compile_cmd to compile flags, since I doubt if jam file accept space for compiler binary, and -std=c++11 is different compiler(in language version) in conception, it's a compile flag, not a part of binary path
some packages can't even handle space like ```ccache g++```, which is exactly why openwrt use a "ccache_cc" wrapper shell script which simply call ```ccache $(CC)```

**Comment by arvidn** [comment]
@xuefer If you do something like this (untested, copy-pasted from the openwrt build script):

```
echo "using gcc : $(GCC_VERSION) : $(GNU_TARGET_NAME)-gcc : <compileflags>\"$(TARGET_CFLAGS)\" <cxxflags>\"$(TARGET_CXXFLAGS) $(EXTRA_CXXFLAGS)\" <linkflags>\"$(TARGET_LDFLAGS)\" ;" >Jamroot.jam
```

After setting up your environment variables. You can then pass in `--toolset=gcc-$(GCC_VERSION)` to `setup.py` to ask it to use it. That will cause it to cross-compile.

You would still have the issue of the system python to be used, rather than the target python headers and libraries. You configure that with:

```
using python : **version** : **python-exe** : **include-paths** : **library-paths** : **b2-build-features** : **python-extension-suffix** ;
```

This would need to go in `user-config.jam` or `Jamroot.jam` (or `project-config.jam`). And there would need to be a way to ask `setup.py` to not auto-detect python, but to rely on what's configured in one of the b2 configuration files (`Jamroot.jam` or `~/user-config.jam`)

**Comment by arvidn** [comment]
You can configure a toolset to use ccache by simply inserting it on the compiler command in the `using` configuration. This is one of the compilers I have configured for instance:

```
using gcc : 9 : ccache g++-9 : <compileflags>-fdiagnostics-color ;
```

When configuring a cross-compiler, it might make sense to make the "version" also name the target, to avoid confusion of a host compiler auto-detects the same version. e.g:

```
using gcc : aarch : ccache aarch64-linux-gnu-g++-10 : <compileflags>-fdiagnostics-color ;
```

**Comment by xuefer** [comment]
okay, good to know it support space now. last time I build boost years ago I had a hard time on this

**Comment by AllSeeingEyeTolledEweSew** [comment]
I'm relatively sure that cross-compiling here (and maybe generally) just refers to using the right compiler and flags. Do I have that right? Is there a case you need to change the python config as Arvid mentioned, to invoke `setup.py` with one version of python but building against a different version?

**Comment by arvidn** [comment]
I would expect the python library you link against has to be built for the target architecture.

**Comment by xuefer** [comment]
> I would expect the python library you link against has to be built for the target architecture.

I thinks so. more importantly the python headers file version must match target python

linking to *.a must be match both CFLAGS and compiler (and all headers) that affect arch and machine code instructions (e.g.: vary x86 instruction set), since all objects in the *.a needed is linked into target 
in case linking to *.so the linker still need the collect symbol names from .so file (so it can you undefined symbol or not). older linker were not able to recognize .so in different arch; even when if it can it refuse to accept different arch *.so file, this greatly help  identifying a misconfigured include/libpath setting, to avoid using wrong version of header files

in my case it's *.so while both host and target are x86_64 and python header file version is same since python in hostpkg is built by openwrt from the same python source code, not from my system. so I got it built successfully before paying time to fix the python include/linking path problem

**Comment by arvidn** [comment]
@xuefer are you working on fixing the openwrt build file? If so, I'd be happy to assist

**Comment by xuefer** [comment]
thanks @arvidn, I'm putting this on hold

@yangfl how are you doing on this for 2.0 version? since I see python biding is comment out https://github.com/openwrt/packages/blob/83e5e21f110db9f323291168fc227fde771793bf/libs/libtorrent-rasterbar/Makefile, and what package are you planning to depends on libtorrent-rasterbar-2.0 ? deluge support 1.2 branch of libtorrent only
