### ISSUE TITLE
Active seeds not working correctly - python

### ISSUE THREAD

**Issue by latot** [arvidn/libtorrent#5980]
Hi hi, two weeks ago I compile libtorrent from git.

I'm loading torrents in python in the next way:

```
        self.ses.active_seeds = -1
        self.ses.active_limit = -1
...
        params.flags |= lt.torrent_flags.super_seeding
        params.flags |= lt.torrent_flags.upload_mode
        params.flags |= lt.storage_mode_t.storage_mode_allocate
        params.flags |= lt.torrent_flags.auto_managed
...
        torrent["handler"] = self.ses.add_torrent(params)
        torrent["handler"].set_download_limit(-1)
        torrent["handler"].set_upload_limit(-1)
        torrent["handler"].resume()
...
```

I have a lot of torrents to load, and are loaded successful, almost 200 torrents, when I check in the server if they are active this happens, first, all shows as active torrents, all fine, but when the time pass the active torrents start to down..., now for example the server says I'm sharing 48, even if python says all the torrents are seeding....

I had a similar script before, but without auto_managed and all the torrents was seeding, checked from python and the server where I'm connecting.

Linux 64, Debian

Thx.

**Comment by arvidn** [comment]
I don't think this does what you think it does:

```
        self.ses.active_seeds = -1
        self.ses.active_limit = -1
```

To change settings you have to build a dictionary and pass it to `ses.apply_settings()`.

**Comment by latot** [comment]
Hi hi, I now test that way, sadly even using ```ses.apply_settings()``` this happens.

**Comment by arvidn** [comment]
are you confident that you successfully set the limit? (do you have any indication of that? the fact that you see auto-manage logic kick in suggests otherwise).

Are you sure all torrents are actually seeding? Seed-mode will still hash check pieces, and a failure will turn the torrent into download mode, at which point a different auto-managed limit applies.

Please collect more information from libtorrent to indicate what's actually happening. Alerts for torrents changing state would be good for instance.

**Comment by latot** [comment]
Hi, actually, I don't know why is working, after restart the compuer, if happens again I'll open a new issue with more info.

Ty.
