### ISSUE TITLE
Question about the use of open and fopen

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#6011]
libtorrent: `master`

Hi @arvidn, chasing the issue of android and 32bits, I find that `fopen` is called inside `posix_storage` and `open` inside `file::file`. I'm only looking for opening of potentially "big" files. Should I look at another location inside the source code? Thanks.

**Comment by arvidn** [comment]
as far as I recall, those are the only places where torrent data files are opened. In fact, I believe `file::file()` is only used by the part file now, so that file probably doesn't get all that large. I've made some efforts to remove the `file` class in favor of some storage-specific class (i.e. use different objects for `mmap` and `posix` backends). I haven't completed that though, as I think I may have tried to take too big of a bite and also make the underlying file descriptors owned by the respective file pools.

It's tricky to have a part file on top of a memory mapped file, since it needs to grow.

**Comment by aldenml** [comment]
Thanks you!
