### ISSUE TITLE
Problems with build_dist and aafigure

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#6045]
I am trying to make an RC_1_2 package for my PPAs and whatnot.
I am doing this in a Debian sid(unstable) VM. A few months ago debian dropped python2 support and along with it `python-aafigure` which provides `aafigure` which is used by `docs/makefile`.
There doesn't seem to be a python3 package for aafigure.

Is there some alternative?

I also tried to do `pip install aafigure` for which the docs on PyPi suggest that it also installs an `aafigure` cmd program. But it doesn't work. I am a python noob. Maybe I missed something. Please, let me know.

**Comment by FranciscoPombal** [comment]
> `pip install aafigure`

All mainstream distros have stopped shipping Python 2 installed by default, now they only have Python 3. You won't be able to install `aafigure` on a system that does not have Python 2, as it is only compatible with this version (and you must use the Python 2 `pip` to install it). But assuming that you're already trying with Python 2 `pip`:

I suppose you are running this as a regular user (which is "right thing to do", in most cases), not as root, right? In this case, binaries are installed to `~/.local/bin`, so you must ensure this is in your `$PATH`.

At least on Ubuntu, the default `.profile` ensures this:

```bash
# ...
# set PATH so it includes user's private bin if it 
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi
# ...
```

Anyway, the real problem here is depending on something that depends on Python 2 - that is definitely a bug. I did find a supposed python3 fork, but it's not on PyPi and it's abandoned anyway: https://github.com/aquavitae/aafigure

**Comment by sledgehammer999** [comment]
>In this case, binaries are installed to ~/.local/bin, so you must ensure this is in your $PATH

That's what I was missing. Thank you.

Also on Debian pip is a now aliased for pip3. I also checked the `~/.local/bin/affigure` and it has a python3 shebang. So I guess it is compatible with python3 with no official debian package.

arvidn, you can close this if you don't want to provide an alternative resolution.

**Comment by FranciscoPombal** [comment]
> That's what I was missing. Thank you.

:+1:
 
> Also on Debian pip is now aliased for pip3. I also checked the `~/.local/bin/affigure` and it has a python3 shebang. So I guess it is compatible with python3 with no official debian package.

That's weird. Not even PyPi mentions Python3 compatibility. I would expect that maybe Debian had a downstream patch but it appears that's not the case either.

@arvidn I don't know what the alternatives are, but based on these findings you might consider migrating away from `aafigure`.

**Comment by arvidn** [comment]
> I don't know what the alternatives are, but based on these findings you might consider migrating away from aafigure.

yeah, I've been meaning to do that for a while. I don't know of a good alternative though. I would like something that is universal and can be edited on any platform with free tools, hence text based diagrams. Perhaps I'll have to go back to Dia.

**Comment by FranciscoPombal** [comment]
@glassez 

>Perhaps I'll have to go back to Dia.

Since you are open to using tools other than Python stuff, and these are your requirements:

> I would like something that is universal and can be edited on any platform with free tools

LaTeX + PGF/TikZ technically fulfill these requirements, but it might be overkill. There's also graphviz, but it might not have the flexibility you need. Other than that, yeah, you'll have to resort to some graphical tool like Dia, GIMP, etc.
