### ISSUE TITLE
python binding: read_resume_data() bad return type

### ISSUE THREAD

**Issue by lawnmowerwcd** [arvidn/libtorrent#606]
Using the latest code from master. In the python binding `read_resume_data()` has return type `add_torrent_params` but this neither does have a converter to a python type nor is consistent with the `[async_]add_torrent()` methods. It should probably return an appropriate dict that can be passed to those methods.

```
TypeError: No to_python (by-value) converter found for C++ type: libtorrent::add_torrent_params
```

**Comment by arvidn** [comment]
ah, yes, that's a good point

**Comment by arvidn** [comment]
looking into this a bit, I think it would make sense to promote add_torrent_params to a properly exported type. Primarily because it's now passing essential resume-data information via python, and with the current design that would require two conversion steps, which seems unnecessarily error prone.

Does that make sense?

Basically, if some information is inaccessible from python, or poorly bound, at least it will be preserved for the add_torrent() call.

**Comment by arvidn** [comment]
does this solve the problem for you? https://github.com/arvidn/libtorrent/pull/609

**Comment by lawnmowerwcd** [comment]
Thank, that works pretty well. Several attributes of `add_torrent_params` cannot be accessed due to missing converters but the most important attributes seem to work (for me at least).

**Comment by Falcosc** [comment]
Some of them are not allowed to use, others does already work. We take care of parameters which are left.

**Comment by arvidn** [comment]
I believe the problem with those fields is that they're exposed as ``def_readwrite`` rather than ``add_property``. like this: https://github.com/arvidn/libtorrent/blob/master/bindings/python/src/session.cpp#L634
