### ISSUE TITLE
Libtorrent Block Upload Alert

### ISSUE THREAD

**Issue by cyrillicw** [arvidn/libtorrent#6088]
I need to embed billing into the libtorrent. So I need to know when node B successfully uploads a block to node A. But according to libtorrent docs, alert block-uploaded-alert is posted when a block intended to be sent to a peer is placed in the send buffer. So in fact the block is not yet uploaded when this alert is posted. Is there a way to know whether the upload was successful?

P.S. Can I limit the number of blocks which are uploaded to the same peer at the same time?

**Comment by arvidn** [comment]
> I need to embed billing into the libtorrent. So I need to know when node B successfully uploads a block to node A. But according to libtorrent docs, alert block-uploaded-alert is posted when a block intended to be sent to a peer is placed in the send buffer. So in fact the block is not yet uploaded when this alert is posted. Is there a way to know whether the upload was successful?

This is not trivial. Even when the call libtorrent makes to send the block, it's stored in the kernel's send buffer (or the uTP send buffer). To know that it was received, one would have to wait for those bytes to be ACKed, which is complicated. But perhaps more importantly, just because those bytes were ACKed by the other end's kernel, doesn't mean the application has read them yet.

My point is, the most reliable way of knowing a block was received is to wait for the peer to send a `HAVE` message back, that covers the block. However, there are two issues with this:

1. the peer really has no obligation to tell you about pieces it downloads (that you already have). It may not.
2. Just because it completed the piece doesn't *necessarily* mean it used your block. It may have requested that from someone else as well, which arrived before yours.

> P.S. Can I limit the number of blocks which are uploaded to the same peer at the same time?

You mean how many blocks are allowed in the send buffer? You can control the send buffer, not trivially per per. Most of the controls are proportional to the current send rate.

**Comment by cyrillicw** [comment]
If node A downloads the same block from B and C, will A receive block_finished_alert for both the downloading? Or only for the first one?

**Comment by arvidn** [comment]
only the first one. The fine-print is that a `block_finished_alert` is posted when the block is done being written to disk. And technically this can happen multiple times in case the piece hash is incorrect, and the piece is re-downloaded.

**Comment by cyrillicw** [comment]
But will A download the same block from two nodes at the same time? It seems to require a lot of traffic. Or only if downloading from the first node was unsuccessful the effort to download from the second one will be made?

**Comment by arvidn** [comment]
in end game mode the same block can be requested from more than one peer at a time, yes. Whether one would consider the first request successful or not is a bit subjective. e.g. It can happen because the first request is taking too long to complete.

**Comment by cyrillicw** [comment]
Thank you very much! Let me ask one more question: is it possible to change the choking strategy? For example, if I do not want to use Tit-for-tat logic but some another?

**Comment by arvidn** [comment]
you can change it amongst a few pre-defined strategies. If you want a custom one you'd have to patch libtorrent

**Comment by Seeker2** [comment]
Might be worth examining the super seeding logic, since it has some mechanism/s to track pieces.

**Comment by cyrillicw** [comment]
@arvidn @Seeker2 Great! Thank you very much
