### ISSUE TITLE
Check for actual local address when throttling speeds

### ISSUE THREAD

**Issue by updateing** [arvidn/libtorrent#611]
**Environment:**
- Private IPv4 address on eth0 (192.168.1.100)
- Public IPv6 address on eth0 (`2001:250:abcd:1234::1/112`)
- Gigabit connection to my subnet, but only 100Mbps to the rest of Internet

**Symptom:**

When I get IPv6 peers on the same subnet, the speed limits will apply to them.
For instance, if the tracker returns a peer at `2001:250:abcd:1234::2`, `ignore_limits_on_local_network` does not work and I can only download from that peer at the same speed as peers outside of my subnet (~800KB/S for popular torrents). However, uTorrent is able to download from this peer at ~15MB/S.

I checked the implementation of `is_local`. It seems that it will only check for loopback, link-local and multicast link-local addresses. Public addresses are not checked.

**Expected Results:**

We should check the actual address and prefix length on the interface. Downloading from peers within the same subnet should not be throltted if `ignore_limits_on_local_network` is on, though the peers are coming from public addresses.

**Comment by Falcosc** [comment]
As long as this is not fixed you could use traffic control.

At least I'm not a friend of static limits anyway because that is always a waste of bandwidth if the other services are not in use.
I don't know how the other developers think about this, but if the share my opinion this ticked would be not fixed in the future.
If you would like to have a proper throttling, you should go for a solution where the unused bandwidth is shared over the services. I do it with htb http://luxik.cdi.cz/~devik/qos/htb/manual/userg.htm

**Comment by updateing** [comment]
Thanks for the explanation. I will try this.

**Comment by Falcosc** [comment]
@updateing if you have problems with htb setup, you could ask me. It's a little bit hard to understand at same details.
