### ISSUE TITLE
Messaging via Libtorrent

### ISSUE THREAD

**Issue by cyrillicw** [arvidn/libtorrent#6114]
[BEP50](https://www.bittorrent.org/beps/bep_0050.html) describes Pub/Sub protocol over BitTorrent Protocol. Nevertheless, the BEP is not implemented in the LibTorrent. Are there any options for nodes to exchange messages via LibTorrent?

**Comment by geiseri** [comment]
BEP50 is a bit different than what you are asking.  That is putting a message on the DHT that others listen for. It would not be ideal for something real-time messaging.   If you are just looking for a "mailbox" then you might as well use [dht_put_item](https://libtorrent.org/reference-Session.html#id69) and [dht_get_item](https://libtorrent.org/reference-Session.html#id67).

If you are looking for something a bit more stateful I have found the best way "at least for me" is to have a "dummy" torrent that has a [torrent_plugin](https://libtorrent.org/reference-Plugins.html#torrent-plugin) that will return a [](https://libtorrent.org/reference-Plugins.html#peer-plugin) instance from [new_connection](https://libtorrent.org/reference-Plugins.html#new-connection).  Then the peer plugin will use the [on_extended](https://libtorrent.org/reference-Plugins.html#on-extended) to process any message.  In theory, you could also use [on_dht_request](https://libtorrent.org/reference-Plugins.html#on-dht-request) without a torrent, but I found that it a bit more cumbersome since really needed to implement 99% of a torrent anyway.  

I would check out the https://github.com/arvidn/libtorrent/blob/RC_2_0/src/ut_metadata.cpp file.  The code is pretty educational for the above.

**Comment by cyrillicw** [comment]
@geiseri Thank you!! I would like to notify viewers that a new part of the video live stream is ready to download. Will your approach cope with this problem?

**Comment by geiseri** [comment]
You can probably get away with a [dht_put_item](http://libtorrent.org/reference-Session.html#id69) using a "well known" key with a value in it.  Note you only really get 1000 bytes to play with in there so I would stick with a magnet link.  See [BEP44](https://www.bittorrent.org/beps/bep_0044.html) for the rules.  You can then have the client poll that key at a "polite" interval of less than 2 hours for a change.  This is more or less what I do to distribute public keys to a swarm.

**Comment by master255** [comment]
@cyrillicw this should help you https://habr.com/ru/post/546612/
