### ISSUE TITLE
How can I bootstrap a init dht node?

### ISSUE THREAD

**Issue by Zjek** [arvidn/libtorrent#6152]
Hello!
I want to use lintorrent's DHT to build a DHT network, but I don't know how to start the first node.Which router is linked by default？How can I make it link only to my own router？
What should I do?
Thanks!

**Comment by Zjek** [comment]
>     settings.set_str(lt::settings_pack::listen_interfaces,"0.0.0.0:6881,[::]:6881");
Can it make others join my router through my IP and bound port？
How can I test it？
Thanks！

**Comment by markmdscott** [comment]
> Hello!
> I want to use lintorrent's DHT to build a DHT network, but I don't know how to start the first node.Which router is linked by default？How can I make it link only to my own router？
> What should I do?
> Thanks!

You want to start up a new DHT network that is separate from the BitTorrent Mainline DHT network?

**Comment by Zjek** [comment]
@markmdscott 
Yes, I think so.what should I do?

**Comment by markmdscott** [comment]
Ah okay. That's an interesting question, could the code in the kademlia directory be used to instantiate a new DHT network (or many!) just by say easily instantiating a new C++ object from some DHT node class? You should look at the code there for some answers. If it is structured in an object oriented way like I suspect it is (much like the rest of this codebase) then it should be easy to use it on its own, because it would not tightly coupled with the rest of the codebase. So dig through here:

github.com/arvidn/libtorrent/tree/master/include/libtorrent/kademlia
github.com/arvidn/libtorrent/tree/master/src/kademlia

**Comment by arvidn** [comment]
make the [dht_bootstrap_nodes](https://libtorrent.org/reference-Settings.html#dht_bootstrap_nodes) setting point to your bootstrap node.

The DHT networks will still likely merge. If it's important that they stay separate, you need to introduce some incompatibility in the protocol.
