### ISSUE TITLE
Missing Boost components in CMakeLists.txt

### ISSUE THREAD

**Issue by lichray** [arvidn/libtorrent#6254]
libtorrent version (or branch): 1.2

platform/architecture: Windows

compiler and compiler version: msvc 19.29.30037 for x64

Install boost-system and boost-python, cmake configuration passes but fails to build. You need vcpkg to reproduce it.

Expect a successful cmake run implies a successful build.

Please add boost-crc, boost-scope-exit, boost-asio.

**Comment by FranciscoPombal** [comment]
`vcpkg install libtorrent` works fine for me. The dependencies are correctly specified:

https://github.com/microsoft/vcpkg/blob/680b27d15f4d62bc6181fd33dc5259482b0890b1/ports/libtorrent/vcpkg.json#L9

However, if you are building libtorrent itself without vcpkg, it is indeed the case that libtorrent's CMake may successfully configure but fail to build, if you have some, but not all necessary boost components installed. This is because libtorrent's CMake doesn't ask for all the specific components it actually needs, it just tries to find the boost "core" (which I think amounts to just finding `Boost::system` or something).

I will try to submit a PR later to fix that, thanks for pointing this out.
