### ISSUE TITLE
Bittorrent v2 Merkle hash seeding

### ISSUE THREAD

**Issue by kovalensky** [arvidn/libtorrent#6289]
In Bittorrent v2, each file has its own hash.
Will it be possible to seed these files within swarms in DHT in the bright future?
It would be much easier to revive dead torrents by searching for alternative sources in swarms and make a huge step in the durability of BitTorrent protocol if it was done correctly and if it certainly wouldn't create any problems.

**Comment by arvidn** [comment]
yes, this is one of the main motivations (at least in my mind). It's on my list to experiment with ways of doing this. I have just had a lot of more urgent things to do lately (both libtorrent issues and work).

My current thinking is something like:

* any file greater than **X** MB is announced on the DHT as if it was a torrent's info-hash
* there's a small protocol extension that adds a message saying "this file belongs to the torrent with info-hash <foo>".

Any client supporting this protocol would just announce large files to the DHT. When someone connects to that "info-hash" (which is really a file root hash) the client responds with saying "you can find this file in this other info-hash".

The connection could then either be promoted to a peer connection to that hash, or it could be disconnected, and the peer reconnects using that info-hash.

Since many peers can announce to the same file root hash, but having that file in different torrents, they might each map it to a different info-hash. So, someone looking for alternative sources would want to connect to as many peers as possible, collecting as many file-hash -> info-hash mappings as possible.

The downloading client could then implement various levels of sophistication, where the piece picker and disk storage could be shared between the torrents, for this file. Or it could simply try to download the file separately from the different swarms until one succeeds.

Some care would have to be taken to not be tricked into joining a swarm one is not interested in. Once the metadata for a redirect-target swarm has been downloaded, the existence of the file root hash would need to be verified. e.g. if it turns out to be a v1 torrent, it should probably be regarded as spam and disconnected.

**Comment by AllSeeingEyeTolledEweSew** [comment]
IMO it would be interesting to implement that announcement and an alert for the dht-redirect message in a near release of libtorrent, ahead of the "sophisticated" stuff

**Comment by geiseri** [comment]
I would be worried about the amount of traffic.  I wonder if it might not be better to have these hashes exposed by "sample_infohashes" so the correlation could be done on demand.  Also, could "similar" torrents be leveraged?  I am using this with v1 torrents that play games with alignment but looking to use this with v2 torrents at a file level.

**Comment by arvidn** [comment]
the `sample_infohashes` feature would still require that nodes announce the file-hashes, for them to show up in the info-hash list in the first place.

I agree that traffic load on the DHT is a concern. I don't see how you would save traffic by using list_infohashes though. if you know the hash you're looking for, you might as well just do a normal lookup.

**Comment by geiseri** [comment]
Ah right.  I was thinking as in building a local index that if another node queried for a hash you could return it.  You still need a way to map back to the original torrent though.  Currently what I am doing is building a root torrent as an aggregate of the other torrents.  It was just a dummy file at the "root" of the structure for the others and I then set that similar to the individuals.  Then the client nodes would download those similar ones, look for the files they wanted and download just those.  It's a real quagmire because it's sensitive to alignment issues.  I was hoping to use the v2 structure to remove that constraint.   This would further simplify matters as I would no longer need the "root" torrent, which has its own structure constraints.

**Comment by the8472** [comment]
Since the root hash is not bijective to content you need length + root hash. And if you encode that into a higher level hash you may as well do something a little less hack: Instead we should specify a way to to generate a synthetic, canonical info dictionary for a single v2 file. Clients could then announce and accept incoming connections for the synthetic torrent instead of the parent torrent containing it.
How that's accounted for internally (as separate torrent or as a special peer only doing downloads of a subrange and offsetting all request/piece messages) would be an implementation detail.

Adding a "this actually belongs to larger torrent X" message/handshake extension would be supplementary.

**Comment by geiseri** [comment]
That kinda smells like BEP-36. Since you have a root hash for a file that can be used as the `guid` and the magnet uri can have the file index for the actual file.   So as a "container" that sounds like it might work.   

Ex:
```xml
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0">
    <channel>
        <title>File Index</title>
        <lastBuildDate>Sat, 18 Sep 2021 09:07:01 -0400</lastBuildDate>
        <item>
            <title>foo.dat</title>
            <guid> 5bfc91da340e79eead03118b27640f13fb9f011ad859e9bc756c9a334ad40f7c </guid>
            <enclosure url="magnet:?xt=urn:btih:e380a6c5ae0fb15f296d29964a56250780b05ad7&so=2" type="application/x-bittorrent" />
        </item>
    </channel>
</rss>
```

That being said since RSS support was removed from libtorrent (it sounds like it didn't have any use in the core at the time) this might be too much for the core library.  It also might be better served to be a bencoded dictionary since XML is huge.  

```
i1631973228ed32<root hash>65magnet:?xt=urn:btih:e380a6c5ae0fb15f296d29964a56250780b05ad7&so=2ee
```

Really just epoch time for the last build, then a dictionary of root hashes and the magnet URI.  If you stick with a single 16k block you can fix around 140 file entries.  

This doesn't account for the discovery aspect.   Something like BEP-49 might work as a "well-known" distribution point, but I am not sure that would scale well since, in the end, something would need to "index" them all.  I guess a tracker could do this, but I would rather use the DHT when possible. 

Either way, after reading the emails around the removal of RSS it seems like this should be a distinct BEP, or an external plugin for the client.

**Comment by arvidn** [comment]
> Instead we should specify a way to to generate a synthetic, canonical info dictionary for a single v2 file. Clients could then announce and accept incoming connections for the synthetic torrent instead of the parent torrent containing it.

I like that idea

**Comment by FranciscoPombal** [comment]
@arvidn 

> My current thinking is something like:
> 
> * any file greater than **X** MB is announced on the DHT as if it was a torrent's info-hash
> 
> * there's a small protocol extension that adds a message saying "this file belongs to the torrent with info-hash ".
>
> (...)

I assume the "greater than **X** MB" restriction is to prevent creating high loads on the DHT network caused by the announce of many small files (which are of course more numerous than large files on average). Anecdotally though, it seems that some of the smallest files are the first to "die" in public torrents (for example, think of .nfos and samples in "scene" releases, which many people end up deleting after the download finishes).

It would be nice if there wasn't such a restriction on file size. Is it not possible to side-step the issue of overloading the DHT with announces by doing the following?

1. Keeping a local index of files -> synthetic torrent matches (as stated at the start of https://github.com/arvidn/libtorrent/issues/6289#issuecomment-882089586) - this can be entirely in-memory, it need not be a file or whatever.
2. Instead of clients announcing that they _have files_ on the DHT, make clients that want files announce that they _want them_ (i.e., data pull instead of push). Clients that have the files can be "listening" for such requests, comparing against their local index, and can choose to service the request by connecting to the respective peer(s).

This way, it is easy to discern a malicious peer from a legitimate one.
A malicious peer will try to make a lot of requests for files, while legitimate peers will not (they will stay below some kind of sane threshold). A client can choose to ban a client exhibiting malicious behavior.

In the push model, where clients are supposed to broadcast the files that they have, a legitimate peer that is announcing a lot of small files is indistinguishable from a malicious one who is trying to perform DoS. Plus, some heavy-duty seeders can be seeding a lot of torrents each with many large files, the announcing of all of which might put them over the threshold of malicious.

**Comment by kovalensky** [comment]
[FranciscoPombal](https://github.com/FranciscoPombal)
Wouldn't second point make peers to search files for longer time?
And every peer would check every hash with search attribute that passed through them, someone have 6k+ torrents, that would make it disadvantageous by spent CPU cycles.

**Comment by kovalensky** [comment]
Hello @arvidn, what's the current status of this feature? Thank you.

**Comment by kovalensky** [comment]
@arvidn Don't want to bother, but is there any progress on that matter, I wrote a technical instruction for a well-known tracker team for implementing magnet links for hybrid torrents, they were asking if there will be benefits from new standart. That's why I'm asking for stage progress. Thanks.

**Comment by arvidn** [comment]
this feature has not been implemented
