### ISSUE TITLE
torrent_finished_alert emitted resumed torrents too

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#64]
I have discovered that I get a `torrent_finished_alert` for all my fastresumed torrents that were already finished and I just added them to the session.

I have code reacting to this alert and it assumes that the alert is for newly downloaded torrents. A simple example is popping a balloon notification in the tray to say that X torrent finished. Complex one is having the finished torrents moved to another location.
And in my case it results in long startup times if you have many torrents.

I don't know if this is intended or not. I am bringing it to your attention and I hope you'll consider it a bug.
Tested with latest RC_1_0.

**Comment by arvidn** [comment]
This has always been the case. The main rationale is consistency. All torrents are considered new from libtorrent's point of view (because libtorrent doesn't keep track of state across sessions by itself). All torrents transition through the same states. If the torrent is completely downloaded, you should also get a torrent_seeding_alert right after torrent_finished.

If you have actions to take when a torrent completes, I would recommend you store the fact that the action has been taken explicitly in the resume data.

**Comment by sledgehammer999** [comment]
>If you have actions to take when a torrent completes, I would recommend you store the fact that the action has been taken explicitly in the resume data.

Ok. This is what we do in one of our branches. I was hoping of eliminating it. Anyway thanks for the clarification.
