### ISSUE TITLE
UnicodeDecodeError in python bindings

### ISSUE THREAD

**Issue by WhateverNameItIs** [arvidn/libtorrent#6407]
libtorrent-rasterbar-1.2.12-r1
Linux-5.13.5-gentoo
deluge-2.0.3-r9
g++ (Gentoo 10.3.0-r2 p3) 10.3.0
Python 3.9.5

When i add torrent that has 0xed 0xb8 0x88 sequence in filename, deluge throws an exception.
After looking into it, seems like exception comes from libtorrent bindings.

Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/twisted/internet/defer.py", line 662, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib/python3.9/site-packages/twisted/internet/task.py", line 838, in <lambda>
    d.addCallback(lambda ignored: callable(*args, **kw))
  File "/usr/lib/python3.9/site-packages/twisted/internet/defer.py", line 1656, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/usr/lib/python3.9/site-packages/twisted/internet/defer.py", line 1571, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
--- <exception caught here> ---
  File "/usr/lib/python3.9/site-packages/twisted/internet/defer.py", line 1445, in _inlineCallbacks
    result = current_context.run(g.send, result)
  File "/usr/lib/python3.9/site-packages/deluge/core/core.py", line 507, in add_torrents
    yield self.add_torrent_file_async(
  File "/usr/lib/python3.9/site-packages/deluge/core/core.py", line 426, in add_torrent_file_async
    d = self.torrentmanager.add_async(
  File "/usr/lib/python3.9/site-packages/deluge/core/torrentmanager.py", line 601, in add_async
    torrent_id, add_torrent_params = self._build_torrent_params(
  File "/usr/lib/python3.9/site-packages/deluge/core/torrentmanager.py", line 424, in _build_torrent_params
    name = torrent_info.name()
builtins.UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 0: invalid continuation byte

Attached archived .torrent file.

[bad.zip](https://github.com/arvidn/libtorrent/files/7003763/bad.zip)

**Comment by AllSeeingEyeTolledEweSew** [comment]
I *think* it's an issue in `torrent_info.cpp`.

my expectation is that `torrent_info` should sanitize the `name` field to replace any invalid utf-8 sequence with `'_'`, in `sanitize_append_path_element`. the python bindings always try to decode `name` as utf-8, but this should always succeed.

@arvidn thoughts?

**Comment by wrtorrent** [comment]
`��.txt` work fine outside python.

**Comment by arvidn** [comment]
libtorrent doesn't sanitize filenames passed into it. The user is generally trusted, and when the user asks libtorrent to open a file it will attempt to open it.

I would think a more reasonable approach would be to treat filenames as byte strings, just like linux does.

Filenames fund in .torrent files are *not* trusted and are sanitized. This goes far beyond correcting invalid UTF-8 sequences, but also strips certain right-to-left markers and overlong character representations and characters that are invalid on windows in certain locations.

**Comment by AllSeeingEyeTolledEweSew** [comment]
@arvidn the `name` field *within the .torrent* isn't being sanitized here

```
{b'creation date': 1629209284,
 b'encoding': b'UTF-8',
 b'info': {b'length': 5,
  b'name': b'\xed\xb8\x88.txt',  <====
  b'piece length': 32768,
  b'pieces': b'N\x12C\xbd"\xc6nv\xc2\xba\x9e\xdd\xc1\xf9\x13\x94\xe5\x7f\x9f\x83',
  b'private': 0}}
```

**Comment by arvidn** [comment]
I see. this isn't the *filename*, it's the "name" of the torrent, as specified by the .torrent file itself. It is definitely sanitized, [here](https://github.com/arvidn/libtorrent/blob/RC_1_2/src/torrent_info.cpp#L1050).

I'll take a look

**Comment by arvidn** [comment]
I think the issue is that libtorrent doesn't contain a unicode database, and doesn't ensure code points actually exist in unicode. The filename is valid UTF-8 encoding of the code point `U+DE08`. However, that code point is not defined as a character in unicode.

I imagine python expects unicode strings to only contain code points that are defined by unicode, and nothing else. Hence, decoding this string fails.

I don't know what the best way to fix this is. I'm open to suggestions.

**Comment by AllSeeingEyeTolledEweSew** [comment]
`U+D800` through `U+DFFF` are surrogate halves. These should never appear in UTF-8, per [RFC 3629](https://datatracker.ietf.org/doc/html/rfc3629). They should *only* appear in UTF-16, and then only in pairs, to encode high codepoints.

This validation *should* be done, but I believe it's uncommon because of Windows. Windows doesn't validate surrogates in many contexts, including filenames: `\uDE08.txt` is an allowed filename, despite it not being a valid UCS sequence.

**Comment by arvidn** [comment]
it would be simple enough to filter this range of code points in libtorrent. It raises two questions:

1. Any existing torrent with files containing such character would have its name changed, and existing files on disk would not longer be found. Is that a serious issue?

2. Are there other code point ranges that should be filtered?

**Comment by wrtorrent** [comment]
> 1. Is that a serious issue?

Very. Such a feature worth a ban at any pvt tracker.

**Comment by arvidn** [comment]
> Very. Such a feature worth a ban at any pvt tracker.

It has the be weighed against the likelihood of a pvt tracker accepting torrents with such (invalid) filenames too

**Comment by wrtorrent** [comment]
Windows not validate multibyte filenames since they existed long before ntfs/utf16.


> validation _should_ be done

If there a file on disk why would one do extra validation?
You're trying to trick into something.
libtorrent not fsck.
Data from .torrent(magnet) link should be saved as is.

**Comment by arvidn** [comment]
> Windows not validate multibyte filenames since they existed long before ntfs/utf16.

The windows APIs dealing with filenames use UTF-16. Windows (as opposed to linux) doesn't treat filenames as arbitrary byte-strings. Neither does MacOS, as it will normalize unicode representations under the hood (but still takes UTF-8).

> Data from .torrent(magnet) link should be saved as is.

There are several issues with that approach. Apart from filenames that are just not allowed on windows (space or "." at the end of a filename or other banned characters):

* `/` or `\` characters could be a security issue since extra directories could be created
* Filenames stating with `/` or `c:\` could be a security issue since you can overwrite sensitive files
* overlong UTF-8 sequences could be a security issue as you could sneak in another character sequence that's harder to detect
* unicode codepoints for reversing writing order (right -> left) is a security issue as you can have a filename *appearing* to end in `.pdf` but really end with `.exe`, just not to the far right of the name.
* two filenames can be the same, only differing in case. This would be a problem on windows and would best be solved by renaming one of the files

So, I don't think skipping sanitation all together really is an option (but I'm open to hearing arguments against it). I wrote down some of the challenges [here](https://blog.libtorrent.org/2014/12/filenames/).

**Comment by wrtorrent** [comment]
`/` `c:\` `0x00/` are security issues with `save_path`, nothing to do with sanitizing.

User A share some file(s) for user B+C.
Assumption: every file is legal since it was legal to have it at disk initially.
No sanitizing needed due assumption.

Why would you one-way fix filesystem incompatibility in first place?
No other program doing this (zip, tar, rar, etc).

Torrent not a distributed multi-OS filesystem to interchange.

Python 'builtins.UnicodeDecodeError' error supposed to be handled.
Then we still speak about some Thai multibyte charset filename in UTF8 linux Python.
I can see virus (botnet) authors would include libtorrent as download tool and unable to get remote user files without some extra.

**Comment by arvidn** [comment]
> Assumption: every file is legal since it was legal to have it at disk initially.
> No sanitizing needed due assumption.

It's not safe to make that assumption. A file can contain *any* bytes, not just the ones allowed in filenames. One can easily create a .torrent file with a file called `../../../etc/hosts` or `../../../etx/passwd` or `../.profile`. If your bittorrent client naively just concatenates that to the save path (which is, say, `/home/user/Downloads`) you may have a security issue.

Also, I think you'll find that it's quite common to create torrents on one operating system/filesystem, seed it on another and download it on another. It's not safe to assume that won't happen.

**Comment by AllSeeingEyeTolledEweSew** [comment]
> 1. Any existing torrent with files containing such character would have its name changed, and existing files on disk would not longer be found. Is that a serious issue?

I think this case is *different* from the case of using random locale encodings in paths.

An encoder should never produce a surrogate in utf-8. Any encoder that does is either
* degenerate, or
* depending on some local meaning for isolated surrogates.

Those should be the only users affected by this change.

> 2. Are there other code point ranges that should be filtered?

I couldn't find any other filtering rules for a passthrough encoder, except to filter codepoints above `U+10FFFF`, which libtorrent already does.

**Comment by AllSeeingEyeTolledEweSew** [comment]
@wrtorrent

> Very. Such a feature worth a ban at any pvt tracker.

What? I disagree.

> Assumption: every file is legal since it was legal to have it at disk initially.

It sounds like you believe this bug is about filtering *metadata* exchanged between peers, but it is not.

When exchanging data between peers, libtorrent always forwards data as-is.

This bug is about sanitization done by libtorrent when
* writing files to local disk, and
* presenting *some* sanitized fields to the app (python in this case)

Are you aware libtorrent already does *LOTS* of sanitization in these cases? It already filters out all other cases of bad utf-8.

It filters out the filename `COM1` on Windows, because that was an illegal filename in DOS.

This bug is about adding to the *existing suite of sanitization*.
