### ISSUE TITLE
two session status statistics  problems

### ISSUE THREAD

**Issue by CowTC** [arvidn/libtorrent#6444]
1） 1st problem
In session_impl.cpp
```
		s.ip_overhead_download_rate = m_stat.transfer_rate(stat::download_ip_protocol);
		s.total_ip_overhead_download = m_stats_counters[counters::recv_ip_overhead_bytes];
		s.ip_overhead_upload_rate = m_stat.transfer_rate(stat::upload_ip_protocol);
		s.total_ip_overhead_upload = m_stats_counters[counters::sent_ip_overhead_bytes];
```
m_stat is triggered by data transfer in torrent download or upload, only in TCP protocol.

However, the m_stats_counters is triggerred by two sections: data transfer in torrents and udp packets transfer in dht,
As said in dht_tracker.cpp: 
```
		m_counters.inc_stats_counter(counters::dht_bytes_out, int(m_send_buf.size()));
		// account for IP and UDP overhead
		m_counters.inc_stats_counter(counters::sent_ip_overhead_bytes
			, aux::is_v6(addr) ? 48 : 28);
		m_counters.inc_stats_counter(counters::dht_messages_out);
```

In my understanding, the dht network data flow is independent. 

The payload data download or upload bytes can be read by dht_bytes_in or dht_bytes_out.

The protocol data is 40+8 or 20 + 8, but not counted in sent_ip_overhead_bytes.

2） 2nd problem

The statistics of network data flow considered the TCP/UDP + IP protocol, but no link layer protocol,  usually used Ethernet II or IEEE 802.3, 18 bytes or 26 bytes. 

I think the reason is that the transfer data in torrent,  may be sliced for the MTU-1500 bytes in link layer and the slice number is no need to calculate, the statistic value is just an estimated value.

But in DHT section, the link layer protocol can be added. Finally the network data = payload + protocol(udp+ip+link layer), for the reason that, MTU is considered in mutable and immutable data.  

Thanks for your time and look forward to your reply.

**Comment by arvidn** [comment]
sorry for the delay, this ticket fell through the cracks. I'm having a hard time understanding these issues. Would you mind being a bit more specific?

> m_stat is triggered by data transfer in torrent download or upload, only in TCP protocol.

What do you mean by "triggered"? You mean it's only updated by TCP transfer?
There are tests demonstrating these counters in uTP transfers too, I'm pretty sure.

> In my understanding, the dht network data flow is independent.

Right.

> The payload data download or upload bytes can be read by dht_bytes_in or dht_bytes_out.

I believe libtorrent uses the term "payload" to refer to the actual bytes that are part of the content of a torrent (i.e. the data that's hashes). As opposed to protocol messages. I would think DHT traffic is only referred to as protocol overhead in libtorrent. But maybe I'm missing your point.

> The protocol data is 40+8 or 20 + 8, but not counted in sent_ip_overhead_bytes.

Do you mean that the IP+UDP overhead caused by DHT traffic is not accounted for?

> The statistics of network data flow considered the TCP/UDP + IP protocol, but no link layer protocol, usually used Ethernet II or IEEE 802.3, 18 bytes or 26 bytes.

I made a (somewhat) arbitrary decision to not estimate the link-layer overhead. The main reason is that I think it's uncommon to consider since it's just a property of your local network. It changes at every network hop. For this reason, I would expect an ISP's accounting not taking into account (but this is pure speculation).

In either case, if you're on WiFi, and your router is connected to ethernet, the actual data transfer visible upstream is ethernet, but from your point of view it's WiFi.
