### ISSUE TITLE
Cannot connect to a tracker that uses an EEC certificate

### ISSUE THREAD

**Issue by 786259135** [arvidn/libtorrent#6456]
**Please provide the following information**

libtorrent version (or branch):
1.2.14.0
![image](https://user-images.githubusercontent.com/16495257/132783917-b1bf6e1b-889d-402f-87fd-faec2f242fd1.png)

platform/architecture:
Win10 x64 Pro

compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

with RSA certificate，Working fine
https://t.hdsky.me/announce.php

with EEC certificate， it prompts: certificate verify failed
https://www.tracker.hdsky.me/announce.php

When disabled validate_https_trackers option works normally.

------------

This is the relevant feedback in qbittorrent:
https://github.com/qbittorrent/qBittorrent/issues/15442

**Comment by arvidn** [comment]
can you verify that you have the root CA in the windows certificate store?
libtorrent relies on pulling certs from the system to validate against on windows.

serial number: 5C 8B 99 C5 5A 94 C5 D2 71 56 DE CD 89 80 CC 26

**Comment by 786259135** [comment]
> can you verify that you have the root CA in the windows certificate store? libtorrent relies on pulling certs from the system to validate against on windows.
> 
> serial number: 5C 8B 99 C5 5A 94 C5 D2 71 56 DE CD 89 80 CC 26

What do i need to do

**Comment by arvidn** [comment]
I'm not very familiar with this aspect of windows. What libtorrent is doing is that it enumerates the root certificates from windows' certificate store ([here](https://github.com/arvidn/libtorrent/blob/RC_2_0/src/session_impl.cpp#L606)) and then it populates the OpenSSL certificate store that's used to make SSL connections.

I made a dummy torrent and used that tracker. Starting that torrent in `client_test` on ubuntu works (as in, the SSL handshake works, but I get a 404. Presumably because my info-hash isn't white-listed).

This leads me to believe the issue is caused by lacking root certificates on your system.
