### ISSUE TITLE
streaming specified torrent's file

### ISSUE THREAD

**Issue by ruinalgo** [arvidn/libtorrent#6504]
libtorrent version (or branch):
version: 1.2.14.0, revision: b5bf6c3260bd726b0181671625c007be5ad49845

platform/architecture:
android (linux), x86

I had similar issue described here: 
https://github.com/arvidn/libtorrent/issues/4408 

I'm using java version **jlibtorrent** (with swig generation): https://github.com/frostwire/frostwire-jlibtorrent

The issue from my end relates to the streaming specified file from the multiple files torrent . Lets take *.mkv files, in case torrent contains one *.mkv inside then streaming and seek backward/forward operations are works fine, but if this is a multiple files torrent with specified required one by `torrent_handle::prioritize_files` and user starts to seek position while streaming then Matroska extractor fails to find the varint lenght mask and raises exception, even if lib reports `piece_finished_alert` for the piece contains required bytes prior to an attempt to read. I assume something related to I/O operations (like data is not yet flushed to fs) for the file storage. This happens only for a torrent contains multiple files.

**Comment by AllSeeingEyeTolledEweSew** [comment]
libtorrent 1.2 uses a cache for receiving data. The data isn't guaranteed to be flushed to disk by the time you receive `piece_finished_alert`. You can either
* wait for `cache_flushed_alert` before you allow the file to be read, possibly manually flushing the cache
* read data using `read_piece()` and `read_piece_alert` rather than reading the file on disk
* use libtorrent 2.0, which `mmap()`s the file on supported platforms; in theory `piece_finished_alert` should mean the data can be read from the file (I don't really know the conditions necessary for this)

**Comment by ruinalgo** [comment]
@AllSeeingEyeTolledEweSew 
I tried to force flush prior to read by `torrent_handle::flush_cache` does not help. Would note, that issue happens for the torrent with multiple files (lets say 5-12) where I specified priority for the wanted file only.
