### ISSUE TITLE
redefinition libtorrent::session_handle::add_default_plugins

### ISSUE THREAD

**Issue by k-morozov** [arvidn/libtorrent#6670]
**Please provide the following information**

libtorrent version (or branch):
libtorrent/2.0.1
platform/architecture:
OS: ubuntu 21.04
compiler and compiler version:
g++-11
please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I want to understand how the project works, so I started by reading the documentation and examples.
[https://www.libtorrent.org/tutorial-ref.html](url)
```
#include <libtorrent/session.hpp>
#include <libtorrent/session_params.hpp>
#include <libtorrent/add_torrent_params.hpp>
#include <libtorrent/torrent_handle.hpp>
#include <libtorrent/alert_types.hpp>
#include <libtorrent/magnet_uri.hpp>
int main() {
    libtorrent::settings_pack p;
    p.set_int(lt::settings_pack::alert_mask, lt::alert_category::status
                                             | lt::alert_category::error);
    libtorrent::session ses(p);

}
```

I try to build this code from the documentation and get an error:
`/usr/bin/ld: /home/focus/.conan/data/libtorrent/2.0.1/_/_/package/ba6cb48c099bc6b9c1a89a40126f5a40d092cb17/lib/libtorrent-rasterbar.a(session_handle.cpp.o):(.rodata+0x5): повторное определение(redefinition) «libtorrent::session_handle::add_default_plugins»; CMakeFiles/example.dir/main.cpp.o:(.rodata._ZN10libtorrent14session_handle19add_default_pluginsE[_ZN10libtorrent14session_handle19add_default_pluginsE]+0x0): здесь первое определение(here is the first definition)`

I use cmake and conan to build.

cmake:
```
cmake_minimum_required(VERSION 3.21)
project(example)

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
set(CONAN_DISABLE_CHECK_COMPILER True)
conan_basic_setup()

set(CMAKE_CXX_STANDARD 20)

add_executable(${PROJECT_NAME} main.cpp)
target_link_libraries(${PROJECT_NAME} ${CONAN_LIBS})
```

conan:
```
[requires]
libtorrent/2.0.1

[generators]
cmake
```

**Comment by arvidn** [comment]
`add_default_plugins` is only defined in `src/session_handle.cpp`. However, since C++17 [1]:

> A constexpr specifier used in a function or static data member (since C++17) declaration implies inline. 

[1] https://en.cppreference.com/w/cpp/language/constexpr

My suspicion is that the conan package is built with C++14, which defines the symbol without making it a weak definition. When you build with C++20, it's implicit inline and defined as a weak symbol.

I suggest you try to set `CMAKE_CXX_STANDARD` *before* setting up conan, that will give it a chance to know which version you're using and pick the right package. Alternatively, try building with C++17 or 14.

**Comment by k-morozov** [comment]
Thx.
it worked for me
`set(CMAKE_CXX_STANDARD 14)`
