### ISSUE TITLE
Python 3.10 - ImportError: DLL load failed while importing libtorrent: The specified module could not be found.

### ISSUE THREAD

**Issue by Samfun75** [arvidn/libtorrent#6689]
**Please provide the following information**

libtorrent version (or branch): 2.0.5

platform/architecture: Windows 10, Python 3.10.2

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I installed libtorrent from pip and I am getting ImportError.

![Screenshot 1](https://user-images.githubusercontent.com/38332931/150783770-59e1d58d-cd57-4276-83eb-f515f37d10a2.png)

I used [Dependencies](https://github.com/lucasg/Dependencies) to check if all dependencies are there and found that `libcrypto-1_1-x64.dll` and `libssl-1_1-x64.dll` are missing.

![Screenshot (21)](https://user-images.githubusercontent.com/38332931/150790082-832b4003-0bab-4def-9afe-78bed9fbdb22.png)

Do I have to install Openssl myself?

**Comment by arvidn** [comment]
yes, I believe so. you can use chocolatey, which is used to build the python modules on CI

**Comment by mhertz** [comment]
It needs those two dll's next to pyd, dir added to os.add_dll_directory, or in system32 e.g shinning openssl installer prompts if you additionally wants it copied there. There where some talk earlier to link statically to openssl unless I'm wrong(for the pyd on pypi) - is those plans still scheduled? - ref:  https://github.com/deluge-torrent/deluge/pull/347#issuecomment-1019977302

**Comment by arvidn** [comment]
linking statically is possible when building libtorrent and the python binding

**Comment by Samfun75** [comment]
> yes, I believe so. you can use chocolatey, which is used to build the python modules on CI

Thanks, I'll do that. Since it was on pypi I thought it came with everything it needed.

**Comment by AllSeeingEyeTolledEweSew** [comment]
I thought I intended to statically link OpenSSL on Windows. We statically link on other platforms.

We use `crypto=openssl link=static boost-link=static`. That seems to statically link openssl on Linux and Mac. If it's not doing so on Windows, maybe it's a bug/quirk. (I *think* we're statically linking via the `Jamfile`, rather than relying on `auditwheel` to vendor stuff)

I don't remember whether I noticed the lack of static linking and decided it was fine, or whether this was unintended.

I tried to comb through the discussions in #6188 and offshoots, but I don't that we reached any clear decision about this.

@arvidn any insight why the `Jamfile` wouldn't statically link openssl on Windows in this case?
