### ISSUE TITLE
Raspberry pi - python linking to latomic incorrect

### ISSUE THREAD

**Issue by kapitainsky** [arvidn/libtorrent#6692]
libtorrent version (or branch): 2.0.5

platform/architecture: raspberry pi 4, 32b raspbian

I build libtorrent 2.0.5 to use with deluge. I follow standard python way: `python setup.py build && sudo python setup.py install`

It is built and installed sucessfully but later deluge build has problem:

`Warning: libtorrent (libtorrent-rasterbar) not found: No libtorrent library found: /usr/local/lib/python3.9/dist-packages/libtorrent-2.0.5-py3.9-linux-armv7l.egg/libtorrent.cpython-39-arm-linux-gnueabihf.so: undefined symbol: __atomic_fetch_add_8`

it is related to problem with latomic linking.

I have found workaround with LD_PRELOAD trick:

`export LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1.2.0`

and then Deluge finds it and can use without any issues.

I have tried to link latomic properly in libtorrent python build but to no avail. Is there any simple way to ensure that python build on raspberry pi properly links to latomic?

**Comment by arvidn** [comment]
I believe fundamentally this is a problem with the toolchain on older Raspberry PIs.

There are some heroics in the `CMakeLists.txt` tha attempts to discover whether `libatomic` needs to be linked in or not. If you built with `b2`, there is no such detection done there, it just expects that `-std=c++14` is enough to have access to all of the standard library.

**Comment by kapitainsky** [comment]
Thank you for clarification. Hence it only affects 32bit version and LD_PRELOAD provides workaround this is not  important to fix. 
Especially that at some stage raspbian will move to 64 bits.

**Comment by kapitainsky** [comment]
and now with raspbian finally moved to 64 bits it should not be an issue anymore.

**Comment by AllSeeingEyeTolledEweSew** [comment]
> There are some heroics in the `CMakeLists.txt` tha attempts to discover whether `libatomic` needs to be linked in or not. If you built with `b2`, there is no such detection done there, it just expects that `-std=c++14` is enough to have access to all of the standard library.

`setup.py` has only used `b2` for a while now. If the OP is building libtorrent with `setup.py`, it shouldn't hit any cmake logic.

> I build libtorrent 2.0.5 to use with deluge. I follow standard python way: `python setup.py build && sudo python setup.py install`

> It is built and installed sucessfully but later deluge build has problem:

deluge has historically used some custom logic to find/build libtorrent. I think it's pretty minimalist in their current `master` branch, but I'm not sure what version of deluge you're using.

If you've built libtorrent with `setup.py`, you should be able to just `import libtorrent`. If not, that may be a build bug.

If you're building libtorrent followed by deluge as you say, and still hitting an import error, I think the problem is the libtorrent on your `PYTHONPATH` isn't the one you expect.

You should only need to build libtorrent on 32-bit raspbian though. On 64-bit, you should be able to `pip install libtorrent`.
