### ISSUE TITLE
[Question] Usage of disk_buffer_holder in custom storage

### ISSUE THREAD

**Issue by tjjh89017** [arvidn/libtorrent#6735]
**Please provide the following information**

libtorrent version (or branch): v2.0 or later

platform/architecture: linux/amd64

compiler and compiler version: gcc

after reading the example from [custom storage](https://www.libtorrent.org/reference-Custom_Storage.html)
I'm not sure how to manage the `disk_buffer_holder`.
Is there any example for buffer holder?
the only thing that i understood might be `free_disk_buffer` is for releasing the `disk_buffer_holder` data pointer before losing that pointer. (malloc and free)

my scenario:
I will use torrent to transfer a collection of used block in a partition or disk, and store the offset in the file name fields.
So when I recv/send the piece, I need to convert the file name back to offset and write/read from disk (I consider to mmap whole parttion, and convert fd offset to mem address)
disk upper bound will be at least 10TB

so if i use mmap, disk_buffer_holder shouldn't be free at all until torrent is removed?

if mmap is not good choice for whole disk, i have to fallback to read/write
How should I handle the disk_buffer_holder life?
Is there any example for this?

Note: try to upgrade my program to fit libtorrent 2.0
https://github.com/tjjh89017/ezio

thanks and appreciate

**Comment by arvidn** [comment]
the `disk_buffer_holder` is a smart pointer that the bittorrent engine will keep a copy of until it has been sent off to the peer requesting the data. It's purpose is to allow the disk subsystem (the thing you implement) to keep track of lifetimes of buffers you've passed back to the bittorrent engine. If you memory map a whole torrent, you would think that you could just pass back pointers into that mapping, and never free them.

In short, you don't need to *use* the `disk_buffer_holder`, you just return it in the job completion handler and once the bittorrent engine is done with the pointer you gave it, the `free_disk_buffer()`.

There are a few caveats:

1. You still need to keep track of how many handles you have handed out, that hasn't been returned yet, to ensure you don't unmap the memory region too early. To do this, you could just decrement a counter in `free_disk_buffer()` (which is part of an interface you need to implement to hand to the `disk_buffer_holder` constructor).
2. When libtorrent negotiates an encrypted connection, the disk buffer handed back from the disk buffer is sometimes required to be a *copy* of the data, to allow for in-place encryption of the block before sending it along to the peer. When libtorrent needs its own copy, it communicates this to `async_read()` via the flags argument. See the `force_copy` flag, here: https://github.com/arvidn/libtorrent/blob/RC_2_0/include/libtorrent/disk_interface.hpp#L160

If you want to avoid (2), you can *probably* do that by disabling all form of protocol encryption, and also disable the `smart_ban` plugin. The smart_ban plugin will read back pieces that fail the hash to record the blocks that made it up, right before those blocks are overwritten by newly downloaded blocks, that's why it needs a copy.

Actually, come to think of it, the `custom_storage.cpp` example fail to take (2) into account. It has a bug.

**Comment by tjjh89017** [comment]
thanks for advice!

Is it good idea that I refer to `struct TORRENT_EXTRA_EXPORT mmap_disk_io` directly as example? https://github.com/arvidn/libtorrent/blob/RC_2_0/src/mmap_disk_io.cpp#L165
also need to consider your advice to avoid some bug

**Comment by tjjh89017** [comment]
after some study, piece might contains two non-continuous blocks of disk.
so i still need to allocate additional mem space to store and send out in `async_read`

**Comment by tjjh89017** [comment]
Is there possible to return partial piece in async_read?
I want to make sure every `disk_buffer_holder` will be continues part but it might not be whole piece in it.

**Comment by arvidn** [comment]
> Is there possible to return partial piece in async_read?

No.

> I want to make sure every disk_buffer_holder will be continues part but it might not be whole piece in it.

You mean "contiguous", right? If you need to stitch two ends of a file together, you need to heap allocate a buffer and copy them into that buffer.

**Comment by tjjh89017** [comment]
got it thanks
that means I need to create a buffer pool, threading pool, cache pool for this topic.
but it seems every disk_buffer_holder will hold 0x4000 size buffer always in mmap_disk_io.
that is possible to pre-allocate some buffer for buffer pool and re-use it.

**Comment by arvidn** [comment]
perhaps this should be exposed to clients: https://github.com/arvidn/libtorrent/blob/RC_2_0/include/libtorrent/aux_/disk_buffer_pool.hpp#L59

**Comment by tjjh89017** [comment]
if you will consider to expose disk_buffer_pool, it will be great to consider store_buffer.
but those two components are a little bit complex to use, so maybe need more docs for this
thanks a lot

**Comment by tjjh89017** [comment]
althought i more like the old way, i only need to considert about "storage" rather than whole disk io including threading. haha

**Comment by arvidn** [comment]
the main reason I made this change is that some resources span individual torrents. Such as the disk buffer pool, the cache and the file handle pool. And those work fundamentally different for a memory mapped back-end and a `preadv()`/`pwritev()` based back-end.

**Comment by tjjh89017** [comment]
that is true.
maybe we should have some advance example for this to guide us

**Comment by tjjh89017** [comment]
If our custom async_read returns incorrect data to libtorrent, will libtorrent deal with it or set torrent to error state?
If some buffer might in write buffer pool but not disk, and we always read from disk.

Thanks a lot

**Comment by arvidn** [comment]
> If our custom async_read returns incorrect data to libtorrent, will libtorrent deal with it or set torrent to error state?

Neither actually. libtorrent will assume that data previously stored to disk can be recalled. It will assume the data is intact, without performing an extra hash check (which wouldn't be possible in most cases anyway, since the hashes are at piece-, not block granularity.

However, the other peer will most likely detect the corrupt data and disconnect and ban you.

> If some buffer might in write buffer pool but not disk, and we always read from disk.

That could cause problems. Especially given some modes where the piece you just downloaded may be the most sought-after piece in the rest of the swarm, and may be the most likely to be requested from peers.

There is a store buffer I use in `mmap_disk_io` that is checked before hitting disk, you may be able to use that, or be inspired by it.

https://github.com/arvidn/libtorrent/blob/RC_2_0/include/libtorrent/aux_/store_buffer.hpp#L91

and used here:

https://github.com/arvidn/libtorrent/blob/RC_2_0/src/mmap_disk_io.cpp#L823

And for reads not aligned to block boundaries
https://github.com/arvidn/libtorrent/blob/RC_2_0/src/mmap_disk_io.cpp#L762

**Comment by tjjh89017** [comment]
> > If our custom async_read returns incorrect data to libtorrent, will libtorrent deal with it or set torrent to error state?
> 
> Neither actually. libtorrent will assume that data previously stored to disk can be recalled. It will assume the data is intact, without performing an extra hash check (which wouldn't be possible in most cases anyway, since the hashes are at piece-, not block granularity.
> 
> However, the other peer will most likely detect the corrupt data and disconnect and ban you.
> 
> > If some buffer might in write buffer pool but not disk, and we always read from disk.
> 
> That could cause problems. Especially given some modes where the piece you just downloaded may be the most sought-after piece in the rest of the swarm, and may be the most likely to be requested from peers.
> 
> There is a store buffer I use in `mmap_disk_io` that is checked before hitting disk, you may be able to use that, or be inspired by it.
> 
> https://github.com/arvidn/libtorrent/blob/RC_2_0/include/libtorrent/aux_/store_buffer.hpp#L91
> 
> and used here:
> 
> https://github.com/arvidn/libtorrent/blob/RC_2_0/src/mmap_disk_io.cpp#L823
> 
> And for reads not aligned to block boundaries https://github.com/arvidn/libtorrent/blob/RC_2_0/src/mmap_disk_io.cpp#L762

Thanks a lot.
I read the store buffer before, that is the reason why I had this question.
Is that possible to use `buffer_pool` & `store_buffer` directly from libtorrent? (obviously, i still want to have whole mmap_disk_io, and i only need to implement mmap_storage with `mmap`)
and we could only implement `disk_interface` only with `thread_pool` and `job_queue`.

By the way, is there lots of people using `custom_storage` feature as you know?
I didn't find many discussions about this.

Still thanks a lot

**Comment by tjjh89017** [comment]
If it isn't a near plan, maybe I should pause the project and wait for some C++ experts from my friends to help me.

**Comment by tjjh89017** [comment]
To record:
for custom_storage usage, I finally got code worked.
we could refer to this repo: https://github.com/tjjh89017/ezio

Thanks Arvidn again!

**Comment by arvidn** [comment]
that's really cool!
