### ISSUE TITLE
session_status and cache_status alternatives in new API

### ISSUE THREAD

**Issue by glassez** [arvidn/libtorrent#674]
@arvidn We have already touched on this issue, but have not solved it.
Although some fields of these structures correspond to counters from new metrics API, others are calculated based on several counters, but for some I can't find a suitable replacement.

**Comment by arvidn** [comment]
it's possible that some aren't tracked anymore. which ones specifically?

**Comment by glassez** [comment]
Later I will present a list of what is the problem.

**Comment by glassez** [comment]
From session_status:
```
payload_download_rate
payload_upload_rate
download_rate
upload_rate
ip_overhead_download_rate
ip_overhead_upload_rate
total_upload
total_download
total_payload_upload
total_payload_download
dht_nodes
```

From cache_status:
```
total_used_buffers
queued_bytes
job_queue_length (removed from libtorrent-1.1 at all)
queued_jobs
```

**Comment by Falcosc** [comment]
payload_download_rate: use session_stats_metrics "net.recv_payload_bytes"
payload_upload_rate: use session_stats_metrics "net.send_payload_bytes"
download_rate: use session_stats_metrics "net.recv_bytes" it does include payload + protocol bytes but does not include ip protocol bytes
upload_rate: use session_stats_metrics "net.send_bytes" it does include payload + protocol bytes but does not include ip protocol bytes
total_upload: use session_stats_metrics "net.send_bytes" it does include payload + protocol bytes but does not include ip protocol bytes
total_download: use session_stats_metrics "net.send_bytes" it does include payload + protocol bytes but does not include ip protocol bytes
total_payload_upload: use session_stats_metrics "net.recv_payload_bytes"
total_payload_download: use session_stats_metrics "net.send_payload_bytes"
dht_nodes: use session_stats_metrics "dht.dht_nodes" and "dht.dht_nodes_cache"
total_used_buffers: use session_stats_metrics "disk.disk_blocks_in_use"
queued_bytes: if you mean the bandwidth_manager, we don't have a replacement
job_queue_length: don't know what do you expect here, maybe the queue length session setting
queued_jobs: use session_stats_metrics "disk.queued_disk_jobs"

there are no replacements for
ip_overhead_download_rate
ip_overhead_upload_rate

ip packet overhead did not get counted for metrics api
https://github.com/arvidn/libtorrent/blob/4f7b69be90b438e2657da93fcc22683f7c3e84dd/src/session_impl.cpp#L3008

@arvidn should I add ip packet overhead to metrics or did we remove it on purpose because it's an estimation?

**Comment by arvidn** [comment]
all "rate" counters were removed. the intention is that you sample the cumulative counters periodically and calculate the average rate of increase. For instance, if you query once per second, the difference could be used as the Bytes/s rate.

**Comment by Falcosc** [comment]
Arvid reminds me the we have actually have sent_ip_overhead_bytes and recv_ip_overhead_bytes

I will just modify the documentation and then we could close the ticket.

**Comment by arvidn** [comment]
thanks @Falcosc
