### ISSUE TITLE
HTTPS (http over tls) proxy support

### ISSUE THREAD

**Issue by nE0sIghT** [arvidn/libtorrent#6770]
This is follow up of https://github.com/qbittorrent/qBittorrent/issues/15860
It would be nice to support HTTPS (http over tls) proxy in addition to http and socks.

I looked to qBittorrent source code and found that it just follows libtorrent proxy feature which is missing https proxy support.
Since https proxy protocol is same as http proxy and just initial connection must be made using https instead of plain http it should be not so hard to implement.

I will try to provide proper patch, but it would be nice if someone more familiar with libtorrent source code will add this faster.

### Extra info/examples/attachments
HTTPS proxy info in Squid wiki: https://wiki.squid-cache.org/Features/HTTPS#Encrypted_browser-Squid_connection

**Comment by arvidn** [comment]
yes, this would be a reasonable feature. Currently the proxy settings only take a hostname and port, so there's no opportunity to specify SSL or plaintext via a URL schema. It would probably best be a separate proxy type.

One (possibly) confusing thing is that the HTTP proxy for peer connections require the `CONNECT` functionality, which I believe also sometimes is referred to HTTPS proxy (since the SSL connection has to be opaque to the proxy itself). But you're talking about the proxy itself authenticating.

**Comment by unbeatable-101** [comment]
Poking issue because of stale bot, I would like to see this feature (but can't help contribute).

**Comment by Neustradamus** [comment]
@Domini has done a new ticket here:
- https://github.com/arvidn/libtorrent/issues/8260
