### ISSUE TITLE
Wrong tarball uploaded for version 2.0.6?

### ISSUE THREAD

**Issue by i0ntempest** [arvidn/libtorrent#6815]
There is a tarball for 1.2.16 under 2.0.6 release.

**Comment by PriitUring** [comment]
Showing orange dot atm - bump version (2.0.6): https://github.com/arvidn/libtorrent/commits/RC_2_0

So it's not ready yet, otherwise Green Checkmark or red X would be shown.

Now opening that Pull Request and clicking on "View details" you see which 2 checks out of total 37 haven't yet passed:
![Screenshot_20220416-202610_Chrome](https://user-images.githubusercontent.com/74606403/163685240-4190b7b6-a442-444c-a762-26ddeb43a4c2.jpg)

Now if you click on "Details" button next to "continuous-integration/appveyor/pr Waiting for AppVeyor build" you will be redirected to this:
https://ci.appveyor.com/project/arvidn/libtorrent/builds/43254594 

So once build is finished there, maybe in an 1 hour or so, I assume the artifacts files will be correctly updated and you should then close this issue.

**Comment by an0n666** [comment]
Yes you’re right. @arvidn uploaded wrong file.

**Comment by arvidn** [comment]
sorry about that. Thanks for reporting!
