### ISSUE TITLE
pkg-config file is broken when CMAKE_INSTALL_{INCLUDE,LIB}DIR is absolute

### ISSUE THREAD

**Issue by alexshpilkin** [arvidn/libtorrent#6865]
libtorrent version (or branch): [v2.0.5](https://github.com/arvidn/libtorrent/releases/tag/v2.0.5) (verified by inspection on master https://github.com/arvidn/libtorrent/commit/54a5ed3bbf18439396705f279368018bc3eb581f as well)

platform/architecture: `Linux localhost 5.15.36 #1-NixOS SMP Wed Apr 27 12:39:02 UTC 2022 x86_64 GNU/Linux`

compiler and compiler version: CMake 3.22.3, GCC 11.2.0, GNU binutils 2.38

The machinery that generates pkg-config files cannot handle absolute paths in `CMAKE_INSTALL_{INCLUDE,LIB}DIR`, as it seems to insist on prepending the prefix to them (in different places: the include paths seem to be transformed by `cmake/Modules/GeneratePkgConfig.cmake`, while the library path is specified this way in the pkg-config template itself, `cmake/Modules/GeneratePkgConfig/pkg-config.cmake.in`). This leads to broken pkg-config files on NixOS in particular.

See “[Concatenating paths when building pkg-config files](https://github.com/jtojnar/cmake-snips#concatenating-paths-when-building-pkg-config-files)” for a thorough discussion of the problem and a suggested fix, or [KDE’s extra-cmake-modules](https://invent.kde.org/frameworks/extra-cmake-modules/-/blob/master/modules/ECMGeneratePkgConfigFile.cmake#L166) for a simpler approach. Unlike in other instances of this issue, I’m sorry to say that your CMake infrastructure is just too involved for me to promise to fix it if you don’t get to it earlier :(

**Comment by arvidn** [comment]
@zeule would it make sense to ignore prefix whenever the path is absolute?

**Comment by zeule** [comment]
Aside from '~' at the beginning of the path, how one can distinguish between an absolute and non-absolute UNIX path?

**Comment by arvidn** [comment]
my understanding is that it's the shell that expands `~`, and it wouldn't necessarily work anywhere else. Any path starting with `/` is absolute.

**Comment by arvidn** [comment]
on windows it's a bit trickier, but it it sounds like cmake has built-in functionality for this: https://cmake.org/cmake/help/latest/command/cmake_path.html#append

**Comment by zeule** [comment]
> Any path starting with `/` is absolute.

But it very well could meant to be relative as well.

**Comment by userdocs** [comment]
> > Any path starting with `/` is absolute.
> 
> But it very well could meant to be relative as well.

Can you expand on what you mean by this as I find it wrong at a glance but may have misunderstood the meaning.

**Comment by zeule** [comment]
> Can you expand on what you mean by this as I find it wrong at a glance but may have misunderstood the meaning.

When you install into a prefix, CMAKE_INSTALL_PATH might be equal to "/usr", but in fact it is a relative path inside the prefix.

**Comment by userdocs** [comment]
https://cmake.org/cmake/help/latest/command/if.html#file-operations

Looking at the KDE example linked in the main post I wondered what `IS_ABSOLUTE` actually does

> if(IS_ABSOLUTE path)
> True if the given path is an absolute path. Note the following special cases:
>
> An empty path evaluates to false.
>
> On Windows hosts, any path that begins with a drive letter and colon (e.g. C:), a forward slash or a backslash will evaluate to > true. This means a path like C:no\base\dir will evaluate to true, even though the non-drive part of the path is relative.
>
> On non-Windows hosts, any path that begins with a tilde (~) evaluates to true.

So it does not defined an absolute path on non windows by it starting with  `/` but uses the `~` and expands it?

**Comment by userdocs** [comment]
On second thoughts, they list special cases as examples so I assume it behaves on non Windows as it does on Windows?

**Comment by zeule** [comment]
It does. The `IS_ABSOLUTE` op in CMake simpy returns values from [std::filesystem::path::is_absolute()](https://en.cppreference.com/w/cpp/filesystem/path/is_absrel). The latter one assumes paths that begin with '/' to be absolute. But by design of the UNIX file system an absolute path can be used as relative.

We can add the `IF_ABSOLUTE` test (I guess the problem occurs [here](https://github.com/arvidn/libtorrent/blob/master/cmake/Modules/GeneratePkgConfig.cmake#L55)) and see which distributions prepend slashes to relative paths. We also could check if install path begins with `${CMAKE_INSTALL_PREFIX}` and don't prepend it if the test passes, but I can imagine that creates an even better hidden problem in cases if that is intentional. 

A similar bug was reported with another distribution, but I haven't found it yet.

**Comment by userdocs** [comment]
I think if it tests for `~` it should work as that expands to a path with no trailing slash `/`

`~` = `/home/username` so it can really be considered in terms of `~/` in most cases.

If we use `~/relative/dir` then  `/relative/dir` is relative to `~` but since we knew we were using `~` we also provided the required trailing slash to make sure we provided a correct path.

so if it starts with `~/` you could safely assume that will expand for a user.

A check to prevent `~/` being joined to `/path` avoiding `~//path`. That kind of stuff.

**Comment by alexshpilkin** [comment]
Thank you bot, it’s been an ... interesting year, but I do need to get back to this.
