### ISSUE TITLE
Unresolved External Errors - NotifyUnicastIpAddressChange and CancelMibChangeNotify2

### ISSUE THREAD

**Issue by SuperSlimey5** [arvidn/libtorrent#6943]
**Libtorrent Version:** 2.0.6

**Platform:** Windows - 64 bit

**Compiler** MSVC 19; Obtained from VCPKG

**Issue:** I've been trying to use Libtorrent statically in my project. I've been able to use it fine dynamically but wanted to change it to fit my project better.

Currently, whenever I build my project it spits out the error below:
```1>torrent-rasterbar.lib(ip_notifier.cpp.obj) : error LNK2019: unresolved external symbol __imp_NotifyUnicastIpAddressChange referenced in function "public: __cdecl libtorrent::aux::`anonymous namespace'::ip_change_notifier_impl::ip_change_notifier_impl(class boost::asio::io_context &)" (??0ip_change_notifier_impl@?A0x9582ead7@aux@libtorrent@@QEAA@AEAVio_context@asio@boost@@@Z)
1>torrent-rasterbar.lib(ip_notifier.cpp.obj) : error LNK2019: unresolved external symbol __imp_CancelMibChangeNotify2 referenced in function "public: virtual __cdecl libtorrent::aux::`anonymous namespace'::ip_change_notifier_impl::~ip_change_notifier_impl(void)" (??1ip_change_notifier_impl@?A0x9582ead7@aux@libtorrent@@UEAA@XZ)```

I didn't have this issue when using it dynamically. Can anyone help me?

**Comment by Kolcha** [comment]
don't know anything about VCPKG, but this error is very generic and easy to fix - you just need to link some library to your project.

in this particular case you should link `Iphlpapi.lib` to your project, see:
https://docs.microsoft.com/en-us/windows/win32/api/netioapi/nf-netioapi-notifyunicastipaddresschange
https://docs.microsoft.com/en-us/windows/win32/api/netioapi/nf-netioapi-cancelmibchangenotify2

this happened due to the nature of static libraries and their difference from dynamic. and this is completely fine.

**Comment by arvidn** [comment]
it (probably) indicates an issue in vcpkg. I would expect it to add the `iphlpapi.dll` dependency when you depend on the static libtorrent target.
