### ISSUE TITLE
Python binding for macOS aarch64 fails to install

### ISSUE THREAD

**Issue by robd003** [arvidn/libtorrent#7131]
Currently cannot install libtorrent on macOS running Apple Silicon (arm64)

```
$ pip install libtorrent==2.0.7
ERROR: Could not find a version that satisfies the requirement libtorrent==2.0.7 (from versions: none)
ERROR: No matching distribution found for libtorrent==2.0.7
```

**Comment by arvidn** [comment]
it looks like there's no wheel being built for macosx arm64

**Comment by robd003** [comment]
I'm curious if the [crossenv](https://github.com/benfogle/crossenv) project could be used to cross compile from the macos github runner for aarch64

Trying to find other projects successfully building with it

**Comment by AllSeeingEyeTolledEweSew** [comment]
The build system (boost.build) can actually cross-compile from x86_64 to arm64 today.

However the build can't be tested today. Github actions doesn't have mac arm64 environments (https://github.com/actions/runner-images/issues/2187).

I'd be reluctant to publish untested builds, since there are known arch-specific problems today (#6447)

Cibuildwheel recently released support for cirrus CI (https://github.com/pypa/cibuildwheel/releases/tag/v2.10.0) as a workaround. Testing this is on my to-do list

**Comment by robd003** [comment]
@AllSeeingEyeTolledEweSew I'm willing to help test macOS arm64 builds if you get either build tool working

**Comment by AllSeeingEyeTolledEweSew** [comment]
We could also publish an sdist, so pypi users could be covered on archs we haven't published/tested.

The main reason I haven't is because the sdist would still require boost, which is problematic. Boost, especially boost.build, must often must be manually installed and specially configured.

The main advantage I see to sdists, versus cloning a repo, is they reduce the mental effort to get something installed. I just run `pip install foo`, and if it fails with `command not found: bar`, I do `apt install bar` and repeat. Boost.build *may* require the user to write and maintain a `user-config.jam`, which has imperative syntax and so can't reasonably be maintained automatically. With this level of effort at baseline, which would need to be documented somewhere, it's not a lot of additional effort to just clone the repo instead of `pip install libtorrent`.

I have tried to wrangle the build process in `setup.py` such that `user-config.jam` shouldn't be required. But boost.build's design is patchwork, and its documentation is poor, and there are few examples of anyone using it in practice, and so I don't really understand the overall use case for `user-config.jam` in the first place. I only know the few extant examples of boost.build in the wild look like "put this ad-hoc content in `user-config.jam` and run this ad-hoc `b2` command". As a result, I don't think we can reach a point where we can confidently say the python bindings can be built without a `user-config.jam`, even in some known set of supported environments.

If we publish an sdist, I expect it will invite a flood of issues of people trying to figure out the build process. IMO our effort is better spent trying to get an arm64 build somehow.

**Comment by AllSeeingEyeTolledEweSew** [comment]
> @AllSeeingEyeTolledEweSew I'm willing to help test macOS arm64 builds if you get either build tool working

Sounds good. In the short term, I'll build an arm64 wheel with a patch to the github actions cibuildwheel process on 2.0.7, link you the build artifact to test, then @arvidn can publish it manually.

In the long term, I think the best option right now is to research porting our cibuildwheel process to cirrus CI.

**Comment by AllSeeingEyeTolledEweSew** [comment]
ok, I ran the build workflow with macos arm64 enabled here: https://github.com/AllSeeingEyeTolledEweSew/libtorrent/actions/runs/3192631455

link to the artifacts: https://github.com/AllSeeingEyeTolledEweSew/libtorrent/suites/8634024065/artifacts/388142312

@robd003 could you run the python test suite on the macos arm64 wheel? should be
```shell
cd bindings/python
python test.py
```

if that passes, it should be fine to publish

**Comment by robd003** [comment]
@AllSeeingEyeTolledEweSew Weirdly I'm not seeing any exported functions in the wheel

```
$ otool -TV libtorrent.cpython-310-darwin.so 
libtorrent.cpython-310-darwin.so:
Table of contents (0 entries)
module name      symbol name
```

Attempting the test:
```
$ python test.py 
Traceback (most recent call last):
  File "/Users/robd/code/libtorrent/bindings/python/test.py", line 5, in <module>
    import libtorrent as lt
ImportError: dynamic module does not define module export function (PyInit_libtorrent)
```

**Comment by AllSeeingEyeTolledEweSew** [comment]
Looks like `setup.py` is invoking `b2 address-model=64 architecture=arm`, which I think is correct for cross compiling.

But in the `b2` output I see warnings like this:
```
/Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: ../..
/bin/darwin-12.0.0/release/address-model-64/architecture-arm/cxxstd-14-iso/link-static/threading-multi/visibilit
y-hidden/src/sha1.o has no symbols
```
@arvidn, thoughts on this?

I believe the cibuildwheel / cirrus integration works by running the build in emulation, so that may use a different codepath within boost.build.

**Comment by arvidn** [comment]
> Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: ../..
/bin/darwin-12.0.0/release/address-model-64/architecture-arm/cxxstd-14-iso/link-static/threading-multi/visibilit
y-hidden/src/sha1.o has no symbols

This warning is because SHA-1 is pulled in from OpenSSL and the built-in SHA-1 implementation is `#ifdeffed`-out. so the object file will effectively be empty.

**Comment by AllSeeingEyeTolledEweSew** [comment]
> This warning is because SHA-1 is pulled in from OpenSSL and the built-in SHA-1 implementation is `#ifdeffed`-out. so the object file will effectively be empty.

Ah, makes sense.

I found another warning that looks more relevant:
```
2022-10-05T21:05:04.7732120Z   ld: warning: ignoring file bin/darwin-12.0.0/release/address-model-64/architectur
e-arm/cxxstd-14-iso/python-3.8/src/torrent_info.o, building for macOS-arm64 but attempting to link with file bui
lt for unknown-x86_64
```

I'll rebuild with verbose options and try to diagnose further.

**Comment by robd003** [comment]
@AllSeeingEyeTolledEweSew any luck on fixing the build?

**Comment by AllSeeingEyeTolledEweSew** [comment]
It looks like in https://github.com/bfgroup/b2/pull/63, they fully broke the `architecture` feature on darwin. The PR title indicates they intended to break `architecture=combined`, but they also broke cross-compilation apparently without consideration. This was merged without discussion, so I don't know what they were trying to do. This change was included in boost 1.78.0 and later.

There were complaints about the removed functionality, and I'm not impressed by the developers' response. In https://github.com/bfgroup/b2/pull/150 a user tried to restore the feature, and [the response was to use `architecture=arm+x86` in place of `architecture=combined`, pushed directly to master with no discussion](https://github.com/bfgroup/b2/pull/150#issuecomment-1109265178)

I have no hope the developers will have any reasonable response if I file a bug about cross-compilation being broken.

I don't really want to roll back the boost version we use for cibuildwheel.

Assuming they're only going to care about native compilation, it seems the only way forward is to get cibuildwheel on cirrus working. I'll work on that sometime soon.

**Comment by robd003** [comment]
@AllSeeingEyeTolledEweSew I did see this ticket about getting cross compilation to work on macOS: https://github.com/bfgroup/b2/issues/181

Could we try changing `architecture=combined` to `architecture=arm+x86` here: https://github.com/arvidn/libtorrent/blob/RC_2_0/bindings/python/setup.py#L393

Curious if that will build a universal2 module.

**Comment by AllSeeingEyeTolledEweSew** [comment]
I gave this a try since it's straightforward. Workflow run: https://github.com/AllSeeingEyeTolledEweSew/libtorrent/actions/runs/3230932097/jobs/5289916950

It looks like it's using the expected flags:
```
2022-10-11T23:31:03.5174380Z       "g++"   -std=c++14 -fPIC -O3 -Wall -dynamic -gdwarf-2 -fexceptions -Wno-inlin
e -arch arm64 -arch x86_64 -Wno-deprecated-declarations -Wno-unused-command-line-argument -fvisibility-inlines-h
idden -fvisibility=hidden -DBOOST_ALL_NO_LIB -DBOOST_ASIO_ENABLE_CANCELIO -DBOOST_ASIO_HAS_STD_CHRONO -DBOOST_AS
IO_NO_DEPRECATED -DBOOST_MULTI_INDEX_DISABLE_SERIALIZATION -DBOOST_PYTHON_STATIC_LIB -DBOOST_SYSTEM_NO_DEPRECATE
D -DBOOST_SYSTEM_STATIC_LINK=1 -DNDEBUG -DOPENSSL_NO_SSL2 -DTORRENT_SSL_PEERS -DTORRENT_USE_I2P=1 -DTORRENT_USE_
LIBCRYPTO -DTORRENT_USE_OPENSSL -D_FILE_OFFSET_BITS=64 -D_WIN32_WINNT=0x0600  -I"../../deps/try_signal" -I"../..
/include" -I"../../include/libtorrent" -I"/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8" -
I"/opt/homebrew/opt/openssl/include" -I"/tmp/boost" -I"/usr/local/opt/openssl/include" -I"src"  -c -o "bin/darwi
n-14.0.0/release/address-model-64/architecture-arm+x86/cxxstd-14-iso/python-3.8/src/module.o" "src/module.cpp"
```

But there are warnings:
```

2022-10-11T23:43:50.7222380Z   ld: warning: ignoring file /usr/local/opt/openssl/lib/libssl.dylib, building for 
macOS-arm64 but attempting to link with file built for macOS-x86_64
2022-10-11T23:43:50.7223050Z   ld: warning: ignoring file /usr/local/opt/openssl/lib/libcrypto.dylib, building 
for macOS-arm64 but attempting to link with file built for macOS-x86_64
2022-10-11T23:43:50.7241080Z   ld: warning: direct access in function 'boost::python::objects::caller_py_functio
n_impl<boost::python::detail::caller<void (*)(_object*), boost::python::default_call_policies, boost::mpl::vecto
r2<void, _object*> > >::signature() const' from file 'bin/darwin-14.0.0/release/address-model-64/architecture-ar
m+x86/cxxstd-14-iso/python-3.8/src/sha1_hash.o' to global weak symbol 'boost::python::converter::expected_pytype
_for_arg<_object*>::get_pytype()' from file '/tmp/boost/bin.v2/libs/python/build/darwin-14.0.0/release/architect
ure-arm+x86/cxxstd-14-iso/link-static/python-3.8/libboost_python38.a(iterator.o)' means the weak symbol cannot b
e overridden at runtime. This was likely caused by different translation units being compiled with different vis
ibility settings.
```

It fails with:
```
2022-10-11T23:43:54.2035090Z + delocate-listdeps /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibuildwheel2z
e7xfu4/built_wheel/libtorrent-2.0.7-cp38-cp38-macosx_10_9_universal2.whl && delocate-wheel --require-archs x86_6
4,arm64 -w /var/folders/24/
8k48jl6d249_n_qfxwsl6xvm000
0gn/T/cibuildwheel2ze7xfu4/repaired_wheel /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibuildwheel2ze7xfu4/
built_wheel/libtorrent-2.0.7-cp38-cp38-macosx_10_9_universal2.whl
2022-10-11T23:43:57.8270850Z /usr/local/Cellar/openssl@3/3.0.5/lib/libcrypto.3.dylib
2022-10-11T23:43:57.8271190Z /usr/local/Cellar/openssl@3/3.0.5/lib/libssl.3.dylib
2022-10-11T23:44:03.1815700Z Traceback (most recent call last):
2022-10-11T23:44:03.1816480Z   File "/Library/Frameworks/Python.framework/Versions/3.8/bin/delocate-wheel", line
 8, in <module>
2022-10-11T23:44:03.1816790Z     sys.exit(main())
2022-10-11T23:44:03.1817340Z   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packag
es/delocate/cmd/delocate_wheel.py", line 91, in main
2022-10-11T23:44:03.1817700Z     copied = delocate_wheel(
2022-10-11T23:44:03.1818860Z   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packag
es/delocate/delocating.py", line 616, in delocate_wheel
2022-10-11T23:44:03.1819290Z     raise DelocationError(
2022-10-11T23:44:03.1819610Z delocate.delocating.DelocationError: Some missing architectures in wheel
2022-10-11T23:44:03.1820000Z Required arch arm64 missing from /usr/local/Cellar/openssl@3/3.0.5/lib/libssl.3.dyl
ib
2022-10-11T23:44:03.1820480Z Required arch arm64 missing from libtorrent.cpython-38-darwin.so
```

So it looks like we'd at least need to figure out how to install openssl in some multiarch way. Looks like [homebrew doesn't natively support this](https://github.com/Homebrew/discussions/discussions/2843). I'm not sure if openssl is causing the libtorrent module to lack multi-arch, or if that's a separate issue.

I'm going to stop there. I don't intend to pursue `universal2` wheels as a long-term solution, since multi-arch binaries are bloated for most users. (I know some use cases do need to distribute a single multi-arch binary, but I hoped to put off making this build work until someone really needs it)

I will pursue cibuildwheel on cirrus instead. From initial research, I don't see anything too complex.

**Comment by ASmoliak** [comment]
Just wanted to update you guys that it may be possible to fix the universal now that boost has closed my issue:

https://github.com/bfgroup/b2/issues/181

**Comment by robd003** [comment]
@AllSeeingEyeTolledEweSew any luck building on b2 v4.9.3?

**Comment by robd003** [comment]
Just another gentle nudge @AllSeeingEyeTolledEweSew to see if we could get this building properly using the newly released b2 v4.9.3 that fixes the multiarch build problem

**Comment by AllSeeingEyeTolledEweSew** [comment]
This is still on my mind, but I probably won't be able to devote time to it until December.

If someone on your team has time, they could try to get an arm64 build on cirrus CI in a fork of libtorrent, then submit it as a PR.
* I was going to start with the cirrus example from https://cibuildwheel.readthedocs.io/en/stable/faq/#universal2
* The workflow should be manual-run only
* For Arvid's convenience, it should include an *optional* step to upload the artifact to pypi, like the current github workflow does

**Comment by drew2a** [comment]
I was able to build `libtorrent` on M1 yesterday.

I leave a summary of the [instruction](https://github.com/arvidn/libtorrent/blob/v1.2.18/docs/python_binding.rst) here in the hope it will be helpful to someone as long as the pip version is not available (yet):

```shell
git clone https://github.com/arvidn/libtorrent
cd libtorrent
git checkout v1.2.18

brew install python@3.11 boost boost-build boost-python3

python3.11 setup.py build
python3.11 setup.py install
```

**Comment by robd003** [comment]
@drew2a I think the problem is getting the GitHub build servers which only have macOS running on x86_64 to build the arm64 whl files using b2. Until that happens there's no binary build available on pypi

**Comment by drew2a** [comment]
@robd003 i see... https://github.com/actions/runner-images/issues/2187

**Comment by moodyjon** [comment]
> I was able to build `libtorrent` on M1 yesterday.

Thanks! I just did something similar, but got tripped up by the submodules in this project. You must use `--recurse-submodules` to get those submodule dirs populated:

`git clone --recurse-submodules https://github.com/arvidn/libtorrent.git`

After working around the missing libboost_python39 problem by creating a symlink, and running "pip install ../libtorrent/.", I found that these two libtorrent files were installed in my venv.

(lbry-venv-3.9) lbry-sdk % find lbry-venv-3.9/ -name 'libtorrent*' -ls                        
118207008    38248 -rwxr-xr-x    1 swdev1           staff            19580652 Jan 26 12:56 lbry-venv-3.9//lib/python3.9/site-packages/libtorrent.cpython-39-darwin.so
118207009        0 drwxr-xr-x    9 swdev1           staff                 288 Jan 26 12:56 lbry-venv-3.9//lib/python3.9/site-packages/libtorrent-2.0.6.dist-info

One `libtorrent-rasterbar.a` was built in one of the `libtorrent/bin/...` subdirs:

libtorrent % find bin -name 'libtorrent*' -ls                                                                                                                   
118206782   541376 -rw-r--r--    1 swdev1           staff            269963424 Jan 26 12:56 bin/darwin-14.0.0/release/address-model-64/architecture-arm/cxxstd-14-iso/link-static/threading-multi/visibility-hidden/libtorrent-rasterbar.a

**Comment by moodyjon** [comment]
I have some work-in-progress here trying to add build and test to `.cirrus.yml`:

https://github.com/arvidn/libtorrent/compare/RC_2_0...moodyjon:libtorrent:macos_arm64_ci

I am stuck debugging a missing `libtorrent::hash_value()` definition when trying to test the python bindings.

I don't know what is special about this symbol...

https://cirrus-ci.com/task/5384327534477312

```
+ /bin/sh -c 'cd /private/var/folders/76/zy5ktkns50v6gt5g8r0sf6sc0000gn/T/cirrus-ci-build/bindings/python && python test.py'
Traceback (most recent call last):
  File "/private/var/folders/76/zy5ktkns50v6gt5g8r0sf6sc0000gn/T/cirrus-ci-build/bindings/python/test.py", line 5, in <module>
    import libtorrent as lt
ImportError: dlopen(/private/var/folders/76/zy5ktkns50v6gt5g8r0sf6sc0000gn/T/cibw-run-y81cifrh/cp39-macosx_arm64/venv-test/lib/python3.9/site-packages/libtorrent/__init__.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace (__ZN10libtorrent10hash_valueERKNS_14torrent_handleE)
```

```
c++filt __ZN10libtorrent10hash_valueERKNS_14torrent_handleE
libtorrent::hash_value(libtorrent::torrent_handle const&)
```

I tried adding `extern` and also removing a type-cast to check the type. It does seem like this function might be removed while building the libtorrent-rasterbar library since I can't find callers. But marking it `extern` did not work.

**Comment by moodyjon** [comment]
After going around in circles investigating `extern`, linker flags, and this issue https://github.com/pypa/cibuildwheel/issues/816, I have stumbled upon something that works. My problem was the way cibuildwheel works with the build system (b2). As cibuildwheel works through different combinations of python version and architecture, it will reuse `libtorrent-rasterbar.a` from prior builds. 

cibuildwheel was choosing to work on `cp38-macos...` first. The `libtorrent-rasterbar.a` produced was a bad one that didn't work with `cp39-macos...`, etc. Just dropping `cp38-macos` wheels seems to fix it.
