### ISSUE TITLE
Issue with non-latin characters

### ISSUE THREAD

**Issue by th0ma7** [arvidn/libtorrent#7179]
**Please provide the following information**

libtorrent version (or branch): 2.0.7-8 (tested and all ok under 1.2.17+)

platform/architecture: any

compiler and compiler version: gcc-7.5

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Accentuated characters are not being handled for the filenaming.  This is only seen with version 2.x and cannot be reproduced on a 1.2.x version (all using the same deluge version).

Additional information can be found at:
* https://github.com/SynoCommunity/spksrc/issues/5448
* https://community.synology.com/enu/forum/1/post/156550

**Comment by arvidn** [comment]
the way filesystems handle non-ascii characters in filenames varies across platforms. The platform matters to pin-point the issue. I'm guessing this issue is happening on Linux. The locale of the system would also be relevant. libtorrent uses `std::wcrtomb()` to convert unicode codepoints to the native locale. Specifically, `LC_CTYPE`.

If the locale's name ends with `.UTF-8`, libtorrent will not convert UTF-8 strings.

Looking at the ticket you reference, it looks like the torrent file contains invalid UTF-8 sequences. These are replaced by `.`.

However, invalid UTF-8 sequences were replaced by `.` in libtorrent 1.2.x as well. Is there any chance anyone has a test torrent that exhibits this problem?

**Comment by th0ma7** [comment]
I don't have any example to run by but am asking the reporter if he can find one freely available.

Here is an example of output:  ![Capture d’écran du 2023-01-11 20-15-11](https://user-images.githubusercontent.com/17141866/211952681-390e74bd-431b-4b10-9f88-55eadf32177c.png)

And the relevant file on the filesystem:
```
# tree
.
└── Legend of the Seeker, l..p.e de v.rit. integrale 2008.WEBDL.1080p.FRx265.Antrax
    ├── Legend of the Seeker, l..p.e de v.rit. Saison 1 2008.WEBDL.1080p.FRx265
    │   ├── Legend of the Seeker ( L'.p.e de v.rit. ) S01E01 FRENCH 1080p st.r.o x265 HEVC.mkv
    │   ├── ...
```

**Comment by th0ma7** [comment]
May be related to https://github.com/qbittorrent/qBittorrent/issues/16127

**Comment by arvidn** [comment]
perhaps a missing locale should be assumed to be UTF-8 on linux. I believe, right now, I use `iconv` empty string to refer to the system locale (unless it's UTF-8, in which case there is no character conversion).

**Comment by th0ma7** [comment]
I'll give it a shot at starting the deamon while enforcing `LC_ALL="en_US.UTF-8"` and see what comes out of it.

Interestingly though, this is only hapening on libtorrent 2.x ... on the other libtorrent 2.x is only used on DSM7 (as DSM6 uses libtorrent 1.2.x).  So is it libtorrent or rather a difference of environment between Synology Linux DSM6 & DSM7?

**Comment by th0ma7** [comment]
Re-reading your post:
> right now, I use iconv empty string to refer to the system locale ...

I'm currently not packaging `iconv` with deluge using libtorrent 2.x on DSM7 ... that might be it!  (currently building)

**Comment by th0ma7** [comment]
I've ended-up solving the issue with `export LC_ALL=en_US.UTF-8` ... locale caught at startup wasn't sufficient otherwise.

**Comment by PikachuEXE** [comment]
I use 
```sh
sudo locale-gen "en_US.UTF-8"
sudo dpkg-reconfigure locales

# Maybe after reboot
sudo localectl status
```
