### ISSUE TITLE
Question about incoming packet protocol and DHT

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#723]
libtorrent: master

In the past we saw that incoming IPv6 packets in the DHT with only IPv4 support was problematic. Now the DHT can handle both protocols, but I wonder if still each DHT (per protocol) should accept incoming packets from the same protocol only.
Relevant line: https://github.com/arvidn/libtorrent/blob/master/src/kademlia/dht_tracker.cpp#L539

**Comment by ssiloti** [comment]
Routing incoming packets to both DHT nodes is necessary to support cross-protocol bootstrapping, i.e. bootstrapping a v6 node by sending a request to the v4 address of a remote dual-stack node. To do this the v6 node needs to be able to receive the v4 response to its bootstrap request.

The DHT node will discard incoming requests which use a protocol other than the one the node is configured for, so this does not pose a problem.

**Comment by aldenml** [comment]
Thank you!

**Comment by aldenml** [comment]
I want to ask one more question here. Some parts of the code (and it's hard to track all the flows) goes directly to `::to_ipv4()` without calling `::is_v4()` when not defined `TORRENT_USE_IPV6`. If I'm correct, the code is robust for the case of `TORRENT_USE_IPV6` but if not defined, shouldn't the hard filter like in RC_1_1 be there?

**Comment by ssiloti** [comment]
As far as I know, the checks made using `dht::node::native_address()` should be sufficient to prevent IPv6 addresses from ever reaching an instance of `to_v4()`. You could argue that for safety there should be a check to drop IPv6 packets early when `TORRENT_USE_IPV6` is false, but I think that if we ever see a case of an IPv6 address hitting one of those calls it would indicate a bug even when v6 support is enabled. It would be better to find out about those cases sooner rather than later.

**Comment by aldenml** [comment]
Thank you again for the explanation (and pointing out `dht::node::native_address()`). The code related to the udp_socket incoming packets changed a lot, I can't see where and how it could fail if an IPv6 packet is mishandled. I suppose a testing compilation with no `TORRENT_USE_IPV6` is necessary.

**Comment by arvidn** [comment]
I may have broken that in my udp_socket overhaul. now it's driven by session_impl.
