### ISSUE TITLE
[feature] add pypi for python 3.11

### ISSUE THREAD

**Issue by pseudo-rnd-thoughts** [arvidn/libtorrent#7265]
With python 3.11 released, could pypi have pre build libtorrent for python 3.11 

I can't find a prior issue on this topic nor does the current change logs include this 

But looking through the .GitHub folder, I see that python 3.11 is used in the python.yml

**Comment by malomehi** [comment]
Yes please. It would be great.
Some distros are now using 3.11 as the default python3 version.

**Comment by cas--** [comment]
Looks like it's being currently skipped for cibuildwheel since boost-python >= 1.81 is required so should be relatively easy to resolve...

Skipped for builds: https://github.com/arvidn/libtorrent/blob/2b6360320b1b1bf3a28b72c9866071b2b155ac21/pyproject.toml#L5

Skipped for macos too: https://github.com/arvidn/libtorrent/blob/2b6360320b1b1bf3a28b72c9866071b2b155ac21/.cirrus.yml#L48

**Comment by Solomon1732** [comment]
Is version 2.0.9 a stable release or is it, say, a release candidate (or beta or somesuch)? I'm asking here since it looks like it support python 3.11, but I'm not sure. I'm basing it on the fact `pyproject.toml` doesn't skip it anymore.

**Comment by cas--** [comment]
Anything with a release version is stable
