### ISSUE TITLE
The last activity shows irregular values for already added torrents.

### ISSUE THREAD

**Issue by stalkerok** [arvidn/libtorrent#7335]
Problem description here: https://github.com/qbittorrent/qBittorrent/issues/18637

I can suggest such a fix, if it can be implemented: after a certain value of years, let's say 5 years, show the infinity symbol.

**Comment by arvidn** [comment]
I imagine the problem is that resume data saved with the previous version and loaded by the new version will (mis)interpret those timestamps. They are probably not correct.

**Comment by stalkerok** [comment]
@arvidn, is it possible to make it so that after a certain value timestamp, which will be equal to 5 or 10 years, for example, just ∞ is shown, this would solve the problem. Maybe there are other solutions?

**Comment by arvidn** [comment]
I don't see how it would solve the problem. Assuming the problem is you get the wrong values, hiding the wrong values behind a symbol won't really improve things. You could just as well just show a blank field in case the values are out-of-whack.

Either way, I believe that would be in the scope of the client rather than libtorrent.

**Comment by stalkerok** [comment]
@arvidn, why didn't you port fixes like https://github.com/arvidn/libtorrent/pull/7328 (and much more) back to RC_1_2?
