### ISSUE TITLE
I2P: make session options configurable

### ISSUE THREAD

**Issue by Vort** [arvidn/libtorrent#7354]
Right now code contains following line:
https://github.com/arvidn/libtorrent/blob/58170282b081027aaed5ee234f8ffa0ed8208104/include/libtorrent/i2p_stream.hpp#L433

These defaults are good, however, lots of users will prefer to change them.
That's why new configuration options are needed.

This is how I think such implementation can be done: https://github.com/Vort/libtorrent/commit/08041f267ba4a05d8c153b373c836aa59d10171e.

_libtorrent version (or branch):_ 58170282b081027aaed5ee234f8ffa0ed8208104
_platform/architecture:_ Windows x64
_compiler and compiler version:_ clang 15.0.7

**Comment by Vort** [comment]
I made my change compatible with latest version: https://github.com/Vort/libtorrent/commit/d385e4c055719c063ec4d753dd2534dbd3aa8b4b.

**Comment by arvidn** [comment]
@Vort would you mind making a PR with that change?

A few notes:

1. adding settings to a `settings_pack` enum has to be at the end, otherwise some settings will change value and that's incompatible with the existing ABI.
2. I think it would be good to omit options that haven't been set explicitly, when building the `SESSION CREATE` string. I'd like libtorrent to defer default values to the i2p router as much as possible.
3. it *might* be worth exploring putting these settings in their own class, to be able to pass them as one bundle to `open()`. `m_inbound_quantity`, `m_outbound_quantity`, `m_inbound_length`, `m_outbound_length`

**Comment by Vort** [comment]
> would you mind making a PR with that change?

Done: #7419.

**Comment by Vort** [comment]
Implemented in #7422.
