### ISSUE TITLE
Deceiving clients with corrupted v2 root hash

### ISSUE THREAD

**Issue by kovalensky** [arvidn/libtorrent#7358]
libtorrent version (or branch):
2.0.8.0
platform/architecture:
win/64
compiler and compiler version:
boost/1.81.0

### Technical details
Since some trackers, DHT indexers could show root hashes of hybrid / v2 torrents in their web pages, some peers could send corrupted hashes to deceive users searching for specific swarms with files.

This gives ability to **mask corrupted files / malware** inside v1 swarm.

Changing root hash inside v2 info metadata won't affect v1 piece validation, torrents will be shown as completed and healthy:

_original.torrent:_

tmrr.exe:
`Hash: 28db8ce451a3470b90f4f6b6ded3a6cf61afb8c650adce259cf257a3469b9558 Size: 2998272`

_corrupted.torrent:_

tmrr.exe:
`Hash: 9ddfe31eb8db96041e4334fefd1634562c3071d63d01e441c9ee72ca47f4285e Size: 2998272`

### Expected behaviour
While using v1 protocol, clients should also check validity through root hash or piece layers if they persist.

**Comment by kovalensky** [comment]
Any thoughts @arvidn ?

**Comment by arvidn** [comment]
I don't understand this attack. Are you suggesting that some pieces are not validated against the piece hashes?

Have you demonstrated this attack?

> While using v1 protocol, clients should also check validity through root hash or piece layers if they persist.

I think I'm misunderstanding you. A client using (only) the v1 protocol won't know that the torrent is a hybrid and won't know about v2 torrents. It clearly can't be expected to validate any v2 properties.

**Comment by arvidn** [comment]
> Since some trackers, DHT indexers could show root hashes of hybrid / v2 torrents in their web pages, some peers could send corrupted hashes to deceive users searching for specific swarms with files.

It sounds like you're suggesting some hashes aren't validated. I don't know of any hashes that aren't validated, can you be more precise about which hashes a peer can corrupt and send other peers (without those peers failing to validate them and disconnecting)?

**Comment by kovalensky** [comment]
> It sounds like you're suggesting some hashes aren't validated. I don't know of any hashes that aren't validated, can you be more precise about which hashes a peer can corrupt and send other peers (without those peers failing to validate them and disconnecting)?


Sorry for late reply, I had to make some tests to be sure.

I checked twice now, I attached two torrents files, example.png.torrent is a legitimate file, corrupted.png.torrent is the torrent I changed "pieces root" key, they both work fine.
I seeded corrupted torrent from Transmission to qBittorrent, have no errors.
I tried to create v2 only torrent with corrupted root hash, it works the same, pieces are validated.

pieces root key is not checked for validity, like piece layers and pieces.

Torrent trackers and DHT trackers can show merkle root hashes in their web pages for users to search torrents by its hash, there are tools for extracting them, including my [own](https://github.com/kovalensky/tmrr).

Attack demonstration:

<img src="https://i2.imageban.ru/out/2023/04/04/a16539c49dd49d0300121e19e41d80e8.gif">



[attack.zip](https://github.com/arvidn/libtorrent/files/11147914/attack.zip)

**Comment by arvidn** [comment]
When downloading a torrent, the internal structure for validating pieces is initialized with the root ([here](https://github.com/arvidn/libtorrent/blob/RC_2_0/src/torrent.cpp#L7565-L7566)) and will reject the piece layer hashes if they are invalid (relative to the root hash) ([here](https://github.com/arvidn/libtorrent/blob/RC_2_0/src/torrent.cpp#L7574) and [here](https://github.com/arvidn/libtorrent/blob/RC_2_0/src/merkle_tree.cpp#L269)).

Nobody will be able to download a file whose root hash mismatches the one in the .torrent file (info-dict). The root hash is the authoritative content of the file.

In your example, you still have a "piece layers" dict, but no entry for the file. So all the piece hashes are ignored, because they don't match any file in the torrent. When will happen instead is that libtorrent will attempt to request hashes from peers (which are always validated against the root hash).

Allowing a .torrent file to not have a piece layer for files is an extension of libtorrent ([here](https://github.com/arvidn/libtorrent/blob/RC_2_0/src/torrent_info.cpp#L1452)). Perhaps this should be controllable by the client in some way.

Making your example a bit more interesting, one could make the piece layer be attributed to the file in the torrent (but the hashes are wrong). Doing will still validate the piece layer hashes ([here](https://github.com/arvidn/libtorrent/blob/RC_2_0/src/merkle_tree.cpp#L147)) and fail. It's not a fatal error however, it will just clear out the hashes and start with an empty tree.

In either case, I don't see a way for any peer sending pieces that don't validate against file root (without being detected).

When downloading hybrid torrents, pieces are checked both against the v1 and v2 hashes.

So, I'm still not sure what you have in mind when you say:

> While using v1 protocol, clients should also check validity through root hash or piece layers if they persist.

I can see 2 approaches:

1. when loading .torrent files, *require* there to be valid piece layers (it would be difficult to avoid validating the piece layer twice)
2. When checking the files of a hybrid torrent where we don't have the piece layers, fail, rather than falling back to just using the hashes we have (the v1 hashes)

These aren't mutually exclusive.

**Comment by kovalensky** [comment]
> Nobody will be able to download a file whose root hash mismatches the one in the .torrent file (info-dict). The root hash is the authoritative content of the file.

@arvidn Just to be sure, I was successful to download a corrupted hybrid torrent from another peer in qBittorrent, same applies to the magnet link.

https://user-images.githubusercontent.com/45331093/229862244-cbde4a71-c3f9-403d-af29-eb8ad4193b13.mp4

Exported .torrent file still has corrupted root hash.

**Comment by kovalensky** [comment]
> Nobody will be able to download a file whose root hash mismatches the one in the .torrent file (info-dict). The root hash is the authoritative content of the file.
> 
> In your example, you still have a "piece layers" dict, but no entry for the file. So all the piece hashes are ignored, because they don't match any file in the torrent. When will happen instead is that libtorrent will attempt to request hashes from peers (which are always validated against the root hash).

Just to clarify that we understood each other, here's the demonstration of qBittorrent successully downloading corrupted torrent from a local peer:

https://user-images.githubusercontent.com/45331093/229878691-4b75436a-ee6c-4862-a296-676f615fec22.mp4

Does it supposed to happen or those two approaches will fix this too?

**Comment by arvidn** [comment]
@kovalensky would you mind trying out these patches? https://github.com/arvidn/libtorrent/pull/7372

**Comment by kovalensky** [comment]
> @kovalensky would you mind trying out these patches? #7372

I would like to, but I'm not experienced in building Boost/C++ applications.

**Comment by arvidn** [comment]
I've landed that patch
