### ISSUE TITLE
Handle arbitrary multi-file url_seed redirects

### ISSUE THREAD

**Issue by dbnicholson** [arvidn/libtorrent#763]
libtorrent version (or branch): master
platform/architecture: linux/x86_64
compiler and compiler version: g++ 5.3.1

We have a multi-file torrent file with a url-list pointing to a single path per the spec. Something like this:
```
{'info': {'files': [{'length': 2002999058, 'path': ['foo']},
                    {'length': 3872, 'path': ['bar']}],
          'name': 'mytorrent',
          'piece length': 262144,
          'pieces': 'z\xdf;3\x96\x82\x1c...'},
 'url-list': 'http://example.com/files/'}
```
However, the files don't exist on the server in this directory structure. Instead, it responds with 301s to the actual location. This allows us to create torrents with arbitrary structure without having to disturb the actual layout of the (very large) files on disk.

Unfortunately, it appears that libtorrent throws `invalid_redirection` for this. What would it take support that? I see the TODO in the code, but I'm not familiar with what it would take to do it.

Thanks!

**Comment by arvidn** [comment]
the web_peer_connection class would need to keep a mapping of file -> redirected URL. since file index is dense, it could probably just be a vector. This vector would need to be preserved between disconnects of the connection though, so it probably would have to go into the web_seed_entry (there's one public struct and one internal one that derives from it, this would live in the internal one). Then it would need to recognize redirects and update this state, and possibly reconnect to the new host. This would be a bit complicated since a single piece may end up living on multiple hosts.

Fortunately, there is a partial "piece" member in the internal web_seed_entry already, which supports resuming a piece across disconnects.

When making requests, this map would need to be consulted, and if there is a mapping to a different host, perform the reconnect, if there isn't a mapping, go ahead and issue the request like is done today.

**Comment by raduancuta** [comment]
We tried making the required changes but the requests end in timeout eventually, This happens because for overlapping pieces we request only the part of the piece that we know is present on the current server.
After a few timeouts the web seed is banned on account of multiple failures. Our changes are pushed to github here https://github.com/endlessm/rufus/commit/3769df9d373e1814faed37383d117ef175313108
We hope you give us some pointers on what we are doing wrong (as we obviously are doing something wrong) we will continue the changes to have this supported by libtorrent.

Thank you!

**Comment by arvidn** [comment]
that's a good start. I would suggest you populate the redirection table from receiving the redirects (the portion you commented out), rather than having the user manually populate it.

Also, the web_peer_connection should remember which host it's connected to, and if it ever needs to request a file from a different host (either because the redirection table points to a different host or there is no redirection entry and it's not connected to the original host), it needs to reconnect. I believe just disconnecting should be enough, and libtorrent will reconnect within a second or so. There are ways to make it reconnect sooner I believe, with fast_reconnect.

**Comment by arvidn** [comment]
Here's a patch that intends to add support for this. There is one big caveat though. If files will be redirected to different hosts, the boundaries between those files *must* be piece aligned. This can be achieved most effectively with pad files.

There are no tests yet. I imagine tests are best written under the simulation directory, since there is an http server simulator already.

https://github.com/arvidn/libtorrent/pull/1060

**Comment by arvidn** [comment]
that PR has been merged
