### ISSUE TITLE
Python wheels for 3.12

### ISSUE THREAD

**Issue by NatanSlvdr** [arvidn/libtorrent#7650]
In the 2.0.10 release, some commits are about building for python 3.12, but there are no wheels on PyPi.

Is it normal ?

**Comment by arvidn** [comment]
The github workflow for building and publishing the wheel has not been working for a while.
I triggered a build for 2.0.10 here: https://github.com/arvidn/libtorrent/actions/runs/8579717727

**Comment by Nytro05** [comment]
Hi, it seems to have failed

Le sam. 6 avr. 2024 à 09:51, Arvid Norberg ***@***.***> a
écrit :

**Comment by DjLegolas** [comment]
It seem that there is an issue with the `cibuildwheel` action on the 2.0.10 release.
@arvidn you have pushed some changes to it only in 4ef221187f1690a126da533994afa7a5898bec57 (which still fail on windows)

**Comment by qstokkink** [comment]
I tried to reconstruct the action run failure. I think what is happening is this (matching the log output):

1. The `pypa/cibuildwheel@v2.12.3` is used (see [here](https://github.com/arvidn/libtorrent/blob/74bc93a37a5e31c78f0aa02037a68fb9ac5deb41/.github/workflows/cibuildwheel.yml#L107)). 
2. The default value of `''` is used for the `only` input of the `cibuildwheel` action (see [here](https://github.com/pypa/cibuildwheel/blob/v2.12.3/action.yml#L16-L19)).
3. Specifically for Windows, `--only '"${{ inputs.only }}"'` is used, which evaluates to `--only '""'` (see [here](https://github.com/pypa/cibuildwheel/blob/v2.12.3/action.yml#L57)).
4. The `cibuildwheel` application then parses the `only` command-line value as `""`, i.e., not empty (see [here](https://github.com/pypa/cibuildwheel/blob/v2.12.3/cibuildwheel/__main__.py#L235-L238)).
5. The `cibuildwheel` application tries to match `""` to a known platform, which fails and causes the log statement `Invalid --only='""', must be a build selector with a known platform` (see [here](https://github.com/pypa/cibuildwheel/blob/v2.12.3/cibuildwheel/__main__.py#L172-L183)).

From the linked source code of (4), it seems that the only way out of this situation is to omit the argument `only` (to the application). However, this seems impossible due to the forced double-quotes of (3) in the `pypa/cibuildwheel@v2.12.3` action. Thankfully, this seems to be [recently fixed](https://github.com/pypa/cibuildwheel/pull/1757) and it should just be a matter of switching to `pypa/cibuildwheel@v2.17.0`.

I hope that helps resolve this issue.

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/7672

**Comment by qstokkink** [comment]
@arvidn with all CI checks now passing, is this issue (and its duplicates #7536 and #7683) now resolved for the 2.0.11 release?
