### ISSUE TITLE
Problems with boost::system::error_code redefined in libtorrent

### ISSUE THREAD

**Issue by ruslanfedoseenko** [arvidn/libtorrent#774]
**Please provide the following information**

libtorrent version (or branch):
RC1_1
platform/architecture:
Win10 x64
compiler and compiler version:
MSVC 12.0 (Visual Studio 2013)

A program which use libtorrent may use some part of boost.
As you redefined boost::system::error_code as libtorrent::error_code compiler can give error that error_code is ambiguous. 
Of Course I can solve it in various ways but from a sight as a new developer working with libtorrent i expect that as it defined as it defined libtorrent::error_code it is something different than boost::system::error_code.

I have a patch to fix this. If you agree with my thoughts than I can make a pull request.

**Comment by arvidn** [comment]
I'm not sure I understand the problem. libtorrent::error_code is a typedef to boost::system::error_code. It's the same type. It also has a different (fully qualified) name, so there shouldn't be any name conflict caused by it.

It sounds like perhaps you would like to be able to do this:

```
using namespace boost::system;
using namespace libtorrent;

```
without any name conflicts. That is not a reasonable expectation, that's what namespaces are for.

**Comment by ruslanfedoseenko** [comment]
sorry it was just VS IntellISense warning no compiler errors given.
