### ISSUE TITLE
Questions on config.h

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#830]
libtorrent: master

1- Is `TORRENT_COMPLETE_TYPES_REQUIRED` required/supported/needed?
2- Is `TORRENT_NO_ATOMIC_DURATION` still necessary (since the required gcc is now > 5)?
3- Are the warnings suppression directives inside `#elif defined BOOST_MSVC` necessary?

**Comment by arvidn** [comment]
(1) technically the C++ standard library containers aren't guaranteed to support incomplete types. Most do, as a QOI, but the ones shipped by sunpro didn't last time I tried (which was many years ago now).
The reason I hesitate to remove that macro is because technically, one cannot refer to C++11 as a guarantee that the code needs to compile. I think there's only one place that breaks this, the "entry" class.

(2) This is probably correct. I imagine this can be removed.

(3) I'm pretty sure 4251 may still be necessary, not sure about 4258.

**Comment by aldenml** [comment]
Closed with https://github.com/arvidn/libtorrent/pull/834
