### ISSUE TITLE
Loading a very large (~10 MB) .torrent file

### ISSUE THREAD

**Issue by AndresGalaviz** [arvidn/libtorrent#865]
libtorrent version (or branch):
master

platform/architecture:
Windows/x64

compiler and compiler version:
msvc-14.0 address-model-64 release

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
Loading a very large torrent file(~10 MB) created with the default make_torrent tool for ~90k files (Around 4GB in total) creates the error "metadata_too_large", after further investigation I found this is because of an imposed limit of 8000000 on the load_file() method under torrent_info.cpp. Setting this higher resolved this issue however a new error appears, namely bdecode_errors::error_code_enum::limit_exceeded, to solve this problem I tried changing the depth_limit under bdecode() inside bdecode.cpp however(As expected) this creates a stack overflow. Is there a solution for this behavior?

**Comment by arvidn** [comment]
the (new) bdecoder isn't actually recursive, so I wouldn't expect it to cause a stack overflow. The old bdecoder was though, and it's still around for creating bencoded structures. There are a few limits involved when loading. The first one is just the limit on how large memory block to allocate, the file size limit. The second you found was the depth limit, the nested-level of the bencoded structure. This is only a resource used during the actual decoding. It's not using the regular runtime call stack, it has it's own heap-allocated stack, which is quite dense. However, I wouldn't expect a valid torrent to ever hit this limit (I believe the default is 1000 or so, it's there to catch malicious bencoded structures, like all 'd'). The thirst limit though, is the number of tokens. For a large torrent with lots of files in it, you'll most likely need to bump this limit up significantly.

These limits are defined in the torrent_info constructor that takes a filename. It has been on my list for a while to extend that constructor to allow those limits to be customized by the caller. I haven't done it yet because of API and ABI backward compatibility concerns. If you're up for it, I would be happy to merge a pull request that exposes those limits to be customized by the caller of that constructor. It has to be in a backwards API compatible way though. the flags argument may be a bit inconvenient.

**Comment by AndresGalaviz** [comment]
I see, I was looking at the wrong limit thanks for pointing it out, it works now. I'm definitely up to it, I'll add it during the long weekend(4th of July in the US).

**Comment by arvidn** [comment]
in master the file size limit has been removed
