### ISSUE TITLE
"file too short" error

### ISSUE THREAD

**Issue by purak** [arvidn/libtorrent#93]
Hello,

I use Deluge 1.3.11 and libtorrent 1.0.5.0 and I'm getting the following error while seeding some torrents. 

```
[DEBUG   ] 06:47:45 alertmanager:123 save_resume_data_alert: WWE RAW 2015 08 03 HDTV x264-Ebi -={SPARROW}=- resume data generated
[DEBUG   ] 06:47:45 torrentmanager:1080 on_alert_save_resume_data
[DEBUG   ] 06:47:45 torrentmanager:747 Opening torrents fastresume file for load.
[DEBUG   ] 06:47:45 torrentmanager:788 Saving fastresume file: /putio/deluge_cfg/8081/state/torrents.fastresume
.....
[DEBUG   ] 06:48:13 alertmanager:123 file_error_alert: WWE RAW 2015 08 03 HDTV x264-Ebi -={SPARROW}=- file (reading p: 5595 b: 0 s: 12000 (read: 11623)) error: file too short
[DEBUG   ] 06:48:13 alertmanager:123 torrent_error_alert: WWE RAW 2015 08 03 HDTV x264-Ebi -={SPARROW}=- ERROR: file too short
[DEBUG   ] 06:48:13 alertmanager:123 tracker_announce_alert: WWE RAW 2015 08 03 HDTV x264-Ebi -={SPARROW}=- (udp://open.demonii.com:1337) sending announce (stopped)
[DEBUG   ] 06:48:13 alertmanager:123 torrent_paused_alert: WWE RAW 2015 08 03 HDTV x264-Ebi -={SPARROW}=- paused
[DEBUG   ] 06:48:13 alertmanager:123 torrent_paused_alert: WWE RAW 2015 08 03 HDTV x264-Ebi -={SPARROW}=- paused
[DEBUG   ] 06:48:13 alertmanager:123 tracker_reply_alert: WWE RAW 2015 08 03 HDTV x264-Ebi -={SPARROW}=- (udp://open.demonii.com:1337) received peers: 0
[DEBUG   ] 06:48:13 torrentmanager:1148 on_alert_file_error: WWE RAW 2015 08 03 HDTV x264-Ebi -={SPARROW}=- file (reading p: 5595 b: 0 s: 12000 (read: 11623)) error: file too short

```

After getting this error message, the torrent is marked "paused" by deluged. The Deluge developers said that the underlying issue is related with libtorrent. Also I can provide a magnet link to try to reproduce the issue.

**Comment by arvidn** [comment]
did you add the torrents in seed-mode? This error indicates that files on disk are smaller than expected in the .torrent file. Normally this is checked when loading resume data. When adding in seed-mode though, it's assumed to be right (basically, that's the user saying: I promise these are seeding, I know what I'm doing).

Are the files shorter than the files in the .torrent file? (you can use a tool to dump the file sizes in the torrent file and compare to the sizes on disk. Or you could force-recheck the torrents to make sure you have everything).

My first guess would be that this is caused by some file corruption happening after libtorrent has started seeding them.

**Comment by arvidn** [comment]
a second look at this log, it looks like perhaps deluge saves the resume data for this torrent before the existing resume data is completely parsed. I should probably make sure you can't save resume data before the resume data that was passed in is done being checked.

**Comment by arvidn** [comment]
oh, you're seeding this torrent. This doesn't happen when you start up?

this line in the log looks suspicious, what does this mean?

    [DEBUG   ] 06:47:45 torrentmanager:747 Opening torrents fastresume file for load.

It sounds odd to do that while seeding a torrent.

**Comment by purak** [comment]
Hello,

The issue happens after downloading the torrent, in seeding phase. I really don't have idea about what happens under the hood but I cannot reproduce the issue on my computer. It only happens on our RAID 0 configured server. I can provide whatever you need to trace the issue. More logging, deluge configuration and torrents/magnets.

Cheers.

**Comment by arvidn** [comment]
knowing which calls are made into libtorrent around the time of completing the torrent would probably be helpful. also, is there a chance you could send that .torrent file to me? (arvid@cs.umu.se)

I wonder if that read length coincides with any file boundary.

**Comment by arvidn** [comment]
which operating system is this on btw? and do you disable OS file caches by any chance? Do you preallocate files? (knowing this would narrow down the search of the faulty code)

**Comment by purak** [comment]
Hello,

We run Ubuntu 12.04, deluge 1.3.11 and libtorrent 1.0.5 on that server. The torrent client uses a dedicated 1TB RAID 0 device as storage. Also there are 9 different torrent client and RAID 0 disk(per disk per client) and I can reproduce the error on every torrent client. I used a magnet link to add the torrent, so I don't have a torrent file for the case. I will send the link a little later.

Here is the core.conf for deluge:
https://gist.github.com/purak/3425ad99d7b79c744a70

**Comment by arvidn** [comment]
hm. that torrent has 5883 pieces. the error message you posted says it's trying to read piece 5595. No wonder it fails. Now, the question is why the bittorrent engine thinks such a piece exists, or why it doesn't filter the request for that piece

**Comment by arvidn** [comment]
if it would be possible for you to make a build with verbose logging enabled, that would probably be very helpful (that is, a libtorrent build with verbose logging enabled, which includes per-peer logs).

**Comment by purak** [comment]
Hello,

I built libtorrent 1.0.5 with "--enable-logging=verbose" parameter to collect debug logs but we couldn't reproduce the issue with ~250 different torrents. It works fine right now. Is there any idea?

**Comment by purak** [comment]
Hello,

I have installed libtorrent 1.0.6 with enable-logging=verbose option and everything seems to work fine. But I just removed the verbose logging option and built it again, the issue appeared instantly. I can reproduce it with an magnet link. I can send it you if you want. By the way, here is some low level info about our libtorrent installation:

ldd /putio/env/lib/libtorrent-rasterbar.so.8.0.0 
        linux-vdso.so.1 =>  (0x00007fffdc1ff000)
        libboost_system.so.1.55.0 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.55.0 (0x00007f914b1a7000)
        libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f914af49000)
        libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f914ab6d000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f914a965000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f914a748000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f914a447000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f914a088000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f914b934000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f9149e72000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9149c6d000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f9149a56000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f914975a000)

ldd /putio/env/lib/python2.7/site-packages/libtorrent.so
        linux-vdso.so.1 =>  (0x00007fff16fff000)
        libtorrent-rasterbar.so.8 => /putio/env/lib/libtorrent-rasterbar.so.8 (0x00007fe33e831000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe33e614000)
        libboost_system.so.1.55.0 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.55.0 (0x00007fe33e40f000)
        libboost_python-py27.so.1.55.0 => /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.55.0 (0x00007fe33e1c3000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fe33dec3000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fe33dcac000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe33d8ed000)
        libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007fe33d68f000)
        libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007fe33d2b3000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fe33d0ab000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fe33f25a000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fe33cdae000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe33cbaa000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fe33c993000)

**Comment by arvidn** [comment]
while trying to look for what might be causing this, I added some asserts to try to catch this issue earlier. If you're up for it, please try head of the RC_1_0 branch and see if you hit an assert. It could reveal some more information about the bug.

**Comment by purak** [comment]
I have built and installed libtorrent using that branch and I have just sent detailed debug logs you for further investigation.

**Comment by arvidn** [comment]
as far as I can tell from those logs (I looked at one of the occurrences), the issue does indeed seem to be at the disk layer (which unfortunately does not really do any logging). It also seems to be more likely to happen towards the end of the torrent (but perhaps that's just because it always happens at the end of a file). I wonder if there's anything in the driver of your disk that lazily flushes changes to disk. So lazy that the same thread coming back to read it fail to see it.

**Comment by purak** [comment]
I don't have any idea about how the disk driver works. It's too low level to investigate, I think. Also the problem appears randomly after some time the downloading is finished. Is there any ideas?

**Comment by arvidn** [comment]
one more source of data that could be collected would be the actual system calls made to open, seek, read and write files. This would be quite verbose, and not very easy to collect because of it. It might be feasible if you have a simple reliable and quick way to reproduce it. The logs can be collected with strace. care would have to be given to make sure only I/O functions are logged and that all relevant ones are included in the filter (libtorrent uses readv() and writev()).

In fact, one thing to try could be to disable use of readv() and writev(). If you build with TORRENT_USE_READV=0 the regular read() and write() will be used. Perhaps your driver has an issue with the more sophisticated variants.

**Comment by arvidn** [comment]
I recently realized that the logic in the default_storage does not take into account that read() and write() (the low level functions on file descriptors) may return fewer bytes than requested despite not having reached end-of-file. I believe it's extremely unusual for that to actually happen on disk I/O, but I imagine that there are disks or drivers that take advantage of this for performance reasons.

The code in the 1.0.x branch is complicated and the testing facilities are limited, so I've only fixed this in master. Basically, I'm worried I would introduce worse bugs by trying to fix this in 1.0.x.

If you have a chance, please try the master branch from git. If you encounter any incompatibility with deluge, please let me know. I've intended to stay (mostly) API compatible, but there may be discrepancies breaking deluge.

**Comment by YourHuckleberry** [comment]
What is the status of this currently?  I regularly have this same issue, and it only seems to happen on larger files once seeding.  It will seed for a short time, and then error out.  How can I get you the information you need to look into this?

**Comment by arvidn** [comment]
please try the latest stable, libtorrent 1.1

There's a chance it has been fixed in there (as my previous comment suggests)

**Comment by arvidn** [comment]
If that still breaks, providing the strace log for the failing disk I/O call (read/write/open/close/readv/writev etc.) with surrounding calls could be helpful. see https://github.com/arvidn/libtorrent/issues/93#issuecomment-140223188

libtorrent 1.1 should provide more details in the disk error report as well, which would be helpful.

**Comment by YourHuckleberry** [comment]
Can you provide some guidance on build parameters?  I'm working from [http://dev.deluge-torrent.org/wiki/Building/libtorrent](http://dev.deluge-torrent.org/wiki/Building/libtorrent) but I think it's a bit dated.  Also, the --enable-logging=verbose mentioned above does not work.

**Comment by arvidn** [comment]
ah, yes. verbose logging should be enabled by default now (as of 1.1), but instead of written to disk, the log is delivered as alerts (and those alert categories are disabled by default).

see the alert categories here: https://github.com/arvidn/libtorrent/blob/master/include/libtorrent/alert.hpp#L167

The ones you want to enable are session_log_notification, torrent_log_notification and peer_log_notification. That will be quite verbose. My understanding is that deluge prints alerts into its log already, so once you do enable these (which you may need to alter deluge to do, or possibly use the lt config plugin, I'm not sure) it should all be printed to the regular log file.

Also, I would expect the actual disk error to have a lot more useful information in it in 1.1 as well. would you mind posting the log line just for the disk error?

**Comment by YourHuckleberry** [comment]
[DEBUG   ] 20:35:47 alertmanager:123 file_error_alert: [OMITTED] file (reading p: 452 b: 257 s: 524288 (read: 0)) error: file too short

Working on figuring out how to enable those other alerts.

**Comment by YourHuckleberry** [comment]
Hmm.  I see Deluge is still using libtorrent 1.0.7.0 even though 1.1 is installed and verified available by importing it into python and checking libtorrent.version.

I will have to dig into getting 1.1 running and report back.

**Comment by RDgiuliom** [comment]
I'm struggling with the same issue for quite a long time now. To solve this I've tried to install LT 1.1 but deluge has problems with version newer than 1.0.x, so I've reverted back to 1.0.9 and also installed qBittorrent to understand if the problem was related to Deluge.

At the moment I have the same problem on both Deluge and qBittorrent with LT 1.0.9, I'm going to temporarly disable Deluge, install LT 1.1 and try again with qBittorrent, I would be quite sad if it solves the issue since I don't like very much qBittorrent and I rather stay on Deluge :)
