### ISSUE TITLE
Configure error: sed: can't read include/libtorrent/version.hpp

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#955]
I have seen this into the configure output over quite a few versions now:

```
checking for iconv declaration... 
         extern size_t iconv (iconv_t cd, char * *inbuf, size_t *inbytesleft, char * *outbuf, size_t *outbytesleft);
sed: can't read include/libtorrent/version.hpp: No such file or directory

Generating Makefiles:
```

I've not checked the code for the reason it is occurring but felt I should at least log it in case there is an easy fix... :)

One small detail I missed is that this is with debian package build so this an example configure line:

```
CPPFLAGS="-D_FORTIFY_SOURCE=2 -I/usr/include/python3.2dmu -I/usr/include/python3.2dmu" \
    PYTHON_LDFLAGS="-lpthread -ldl -lutil -lm -lpython3.2dmu" \
    dh_auto_configure --builddirectory build-py3.2-dbg -- \
        PYTHON=/usr/bin/python3.2-dbg PYTHON_INSTALL_PARAMS="--root=/home/ubuntu/Projects/lt-PPA-cas/lt_1.1git/libtorrent-RC_1_1/debian/tmp --install-layout=deb" \
        --enable-python-binding --with-boost-python=boost_python-py32 \
        --with-libiconv
```

Perhaps the SVN version test should be removed?

**Comment by Falcosc** [comment]
What did you take as base of your compilation? Because I can't reproduce it on 1.1, maybe it is already fixed?

On master there is a GIT revision check and on RC_1_1 an svn revision check. If the revision check does not match your checkout client, it will just return an empty string but no errors because include/libtorrent/version.hpp is always there.

**Comment by Falcosc** [comment]
@cas-- did you still able to reproduce the issue? Because I would like to have the possibility to test a change somewere where the error appears.

**Comment by cas--** [comment]
Every debian pkg build has this error:

https://launchpadlibrarian.net/301686651/buildlog_ubuntu-zesty-amd64.libtorrent-rasterbar_1.1.2dev8436+5d1fb97+201701081817~ubuntu17.04.1_BUILDING.txt.gz

**Comment by Falcosc** [comment]
Thanks

**Comment by Falcosc** [comment]
@cas-- where did you get your sources from? Because you did not build from version controll which means version have to be taken from the version file but your sources doesn't include them. I did check the gitbranches and the released sources but all have the missing file.

Could you check why your source archive is incomplete?
```
Local sources
-------------

libtorrent-rasterbar_1.1.2dev8436+5d1fb97+201701081817~ubuntu17.04.1.dsc exists in .; copying to chroot
```

Because after my fix you will still need to have include/libtorrent/version.hpp in there which you are missing in your source archive

**Comment by cas--** [comment]
From my understanding the problem isn't that the file is missing it's that that sed line is using a hardcoded path

**Comment by Falcosc** [comment]
Thanks,

I didn't test `../configure`

**Comment by Falcosc** [comment]
could be closed

**Comment by cas--** [comment]
```
   Config results:
  -=-=-=-=-=-=-=-=-

Package:
  name:                 libtorrent-rasterbar
  version:              1.1.1
  git revision:         1229491
```

Thanks!
